
class _MFG_ID(str):
    id = 0x00

    def __eq__(self, other):
        if isinstance(other, int):
            if other == self.id:
                return True
            return False

        return str.__eq__(self, other)

    def __ne__(self, other):
        return not self.__eq__(other)


MFG_ID_NOT_DEFINED = _MFG_ID('Not defined')
MFG_ID_NOT_DEFINED.id = 0xFFFF

MFG_ID_2B_ELECTRONICS = _MFG_ID('2B Electronics')
MFG_ID_2B_ELECTRONICS.id = 0x0028

MFG_ID_2GIG_TECHNOLOGIES_INC = _MFG_ID('2gig Technologies Inc.')
MFG_ID_2GIG_TECHNOLOGIES_INC.id = 0x009B

MFG_ID_3E_TECHNOLOGIES = _MFG_ID('3e Technologies')
MFG_ID_3E_TECHNOLOGIES.id = 0x002A

MFG_ID_A1_COMPONENTS = _MFG_ID('A-1 Components')
MFG_ID_A1_COMPONENTS.id = 0x0022

MFG_ID_ABILIA = _MFG_ID('Abilia')
MFG_ID_ABILIA.id = 0x0117

MFG_ID_ACROCOMM_CORP = _MFG_ID('AcroComm Corp.')
MFG_ID_ACROCOMM_CORP.id = 0x034A

MFG_ID_ACT_ADVANCED_CONTROL_TECHNOLOGIES = _MFG_ID('ACT - Advanced Control Technologies')
MFG_ID_ACT_ADVANCED_CONTROL_TECHNOLOGIES.id = 0x0001

MFG_ID_ADMOBILIZE_LLC = _MFG_ID('AdMobilize, LLC')
MFG_ID_ADMOBILIZE_LLC.id = 0x0297

MFG_ID_ADOX_INC = _MFG_ID('ADOX, Inc.')
MFG_ID_ADOX_INC.id = 0x0101

MFG_ID_ADTRUSTMEDIA_LLC_DBA_EZLO = _MFG_ID('AdTrustMedia LLC  dba: eZLO')
MFG_ID_ADTRUSTMEDIA_LLC_DBA_EZLO.id = 0x025B

MFG_ID_ADVANCED_OPTRONIC_DEVICES_CO_LTD = _MFG_ID('Advanced Optronic Devices Co.,Ltd')
MFG_ID_ADVANCED_OPTRONIC_DEVICES_CO_LTD.id = 0x016C

MFG_ID_ADVENTURE_INTERACTIVE = _MFG_ID('Adventure Interactive')
MFG_ID_ADVENTURE_INTERACTIVE.id = 0x009E

MFG_ID_AEINNOVATION_AEI = _MFG_ID('Aeinnovation (AEI)')
MFG_ID_AEINNOVATION_AEI.id = 0x035B

MFG_ID_AENSYS_INFORMATICS_LTD = _MFG_ID('AENSys Informatics Ltd.')
MFG_ID_AENSYS_INFORMATICS_LTD.id = 0x0350

MFG_ID_AEON_LABS = _MFG_ID('AEON Labs')
MFG_ID_AEON_LABS.id = 0x0086

MFG_ID_AEOTEC_LIMITED = _MFG_ID('Aeotec Limited')
MFG_ID_AEOTEC_LIMITED.id = 0x0371

MFG_ID_AIRVENT_SAM_SPA = _MFG_ID('Airvent SAM S.p.A.')
MFG_ID_AIRVENT_SAM_SPA.id = 0x0088

MFG_ID_ALARMCOM = _MFG_ID('Alarm.com')
MFG_ID_ALARMCOM.id = 0x0094

MFG_ID_ALERTME = _MFG_ID('Alertme')
MFG_ID_ALERTME.id = 0x0126

MFG_ID_ALLEATO = _MFG_ID('ALLEATO')
MFG_ID_ALLEATO.id = 0x0372

MFG_ID_ALLEGION = _MFG_ID('Allegion')
MFG_ID_ALLEGION.id = 0x003B

MFG_ID_ALPHANETWORKS = _MFG_ID('Alphanetworks')
MFG_ID_ALPHANETWORKS.id = 0x028E

MFG_ID_ALPHONSUS_TECH = _MFG_ID('Alphonsus Tech')
MFG_ID_ALPHONSUS_TECH.id = 0x0230

MFG_ID_AMADAS_CO_LTD = _MFG_ID('AMADAS Co., LTD')
MFG_ID_AMADAS_CO_LTD.id = 0x029F

MFG_ID_AMDOCS = _MFG_ID('Amdocs')
MFG_ID_AMDOCS.id = 0x019C

MFG_ID_AMERICAN_GRID_INC = _MFG_ID('American Grid, Inc.')
MFG_ID_AMERICAN_GRID_INC.id = 0x005A

MFG_ID_AMETA_INTERNATIONAL_CO_LTD = _MFG_ID('Ameta International Co. Ltd.')
MFG_ID_AMETA_INTERNATIONAL_CO_LTD.id = 0x0384

MFG_ID_ANCHOR_TECH = _MFG_ID('Anchor Tech')
MFG_ID_ANCHOR_TECH.id = 0x032B

MFG_ID_ANIMUS_HOME_AB = _MFG_ID('Animus Home AB')
MFG_ID_ANIMUS_HOME_AB.id = 0x0392

MFG_ID_ANTIK_TECHNOLOGY_LTD = _MFG_ID('Antik Technology Ltd.')
MFG_ID_ANTIK_TECHNOLOGY_LTD.id = 0x026D

MFG_ID_ANYCOMM_CORPORATION = _MFG_ID('anyCOMM Corporation')
MFG_ID_ANYCOMM_CORPORATION.id = 0x0078

MFG_ID_APPLIED_MICRO_ELECTRONICS_AME_BV = _MFG_ID('Applied Micro Electronics "AME" BV')
MFG_ID_APPLIED_MICRO_ELECTRONICS_AME_BV.id = 0x0144

MFG_ID_ARKEA = _MFG_ID('Arkea')
MFG_ID_ARKEA.id = 0x0291

MFG_ID_ASIA_HEADING = _MFG_ID('Asia Heading')
MFG_ID_ASIA_HEADING.id = 0x0029

MFG_ID_ASITEQ = _MFG_ID('ASITEQ')
MFG_ID_ASITEQ.id = 0x0231

MFG_ID_ASKEY_COMPUTER_CORP = _MFG_ID('Askey Computer Corp.')
MFG_ID_ASKEY_COMPUTER_CORP.id = 0x028A

MFG_ID_ASSA_ABLOY = _MFG_ID('ASSA ABLOY')
MFG_ID_ASSA_ABLOY.id = 0x0129

MFG_ID_ASTRALINK = _MFG_ID('AstraLink')
MFG_ID_ASTRALINK.id = 0x013B

MFG_ID_ATT = _MFG_ID('AT&T')
MFG_ID_ATT.id = 0x0134

MFG_ID_ATECH = _MFG_ID('Atech')
MFG_ID_ATECH.id = 0x002B

MFG_ID_ATHOM_BV = _MFG_ID('Athom BV')
MFG_ID_ATHOM_BV.id = 0x0244

MFG_ID_AUCEAN_TECHNOLOGY_INC = _MFG_ID('AUCEAN TECHNOLOGY. INC')
MFG_ID_AUCEAN_TECHNOLOGY_INC.id = 0x032A

MFG_ID_AVADESIGN_TECHNOLOGY_CO_ = _MFG_ID('Avadesign Technology Co.,')
MFG_ID_AVADESIGN_TECHNOLOGY_CO_.id = 0x025D

MFG_ID_AVADESIGN_TECHNOLOGY_CO_LTD = _MFG_ID('Avadesign Technology Co., Ltd.')
MFG_ID_AVADESIGN_TECHNOLOGY_CO_LTD.id = 0x0155

MFG_ID_AXESSTEL_INC = _MFG_ID('Axesstel Inc')
MFG_ID_AXESSTEL_INC.id = 0x0146

MFG_ID_BALBOA_INSTRUMENTS = _MFG_ID('Balboa Instruments')
MFG_ID_BALBOA_INSTRUMENTS.id = 0x0018

MFG_ID_BANDI_COMM_TECH_INC = _MFG_ID('Bandi Comm Tech Inc.')
MFG_ID_BANDI_COMM_TECH_INC.id = 0x0236

MFG_ID_BEIJING_SINOAMERICAN_BOYI_SOFTWARE_DEVELOPMENT_CO_L = _MFG_ID('Beijing Sino-American Boyi Software Development Co., Ltd')
MFG_ID_BEIJING_SINOAMERICAN_BOYI_SOFTWARE_DEVELOPMENT_CO_L.id = 0x0204

MFG_ID_BEIJING_UNIVERSAL_ENERGY_HUAXIA_TECHNOLOGY_CO_LTD = _MFG_ID('Beijing Universal Energy Huaxia Technology Co.,Ltd')
MFG_ID_BEIJING_UNIVERSAL_ENERGY_HUAXIA_TECHNOLOGY_CO_LTD.id = 0x0251

MFG_ID_BELLATRIX_SYSTEMS_INC = _MFG_ID('Bellatrix Systems, Inc.')
MFG_ID_BELLATRIX_SYSTEMS_INC.id = 0x0196

MFG_ID_BENETEK = _MFG_ID('Benetek')
MFG_ID_BENETEK.id = 0x032D

MFG_ID_BENEXT = _MFG_ID('BeNext')
MFG_ID_BENEXT.id = 0x008A

MFG_ID_BESAFER = _MFG_ID('BeSafer')
MFG_ID_BESAFER.id = 0x002C

MFG_ID_BFT_SPA = _MFG_ID('BFT S.p.A.')
MFG_ID_BFT_SPA.id = 0x014B

MFG_ID_BIT7_INC = _MFG_ID('Bit7 Inc.')
MFG_ID_BIT7_INC.id = 0x0052

MFG_ID_BLAZE_AUTOMATION = _MFG_ID('Blaze Automation')
MFG_ID_BLAZE_AUTOMATION.id = 0x0311

MFG_ID_BMS_EVLER_LTD = _MFG_ID('BMS Evler LTD')
MFG_ID_BMS_EVLER_LTD.id = 0x0213

MFG_ID_BOCA_DEVICES = _MFG_ID('Boca Devices')
MFG_ID_BOCA_DEVICES.id = 0x0023

MFG_ID_BONIG_UND_KALLENBACH_OHG = _MFG_ID('B�nig und Kallenbach oHG')
MFG_ID_BONIG_UND_KALLENBACH_OHG.id = 0x0169

MFG_ID_BOSCH_SECURITY_SYSTEMS_INC = _MFG_ID('Bosch Security Systems, Inc')
MFG_ID_BOSCH_SECURITY_SYSTEMS_INC.id = 0x015C

MFG_ID_BRK_BRANDS_INC = _MFG_ID('BRK Brands, Inc.')
MFG_ID_BRK_BRANDS_INC.id = 0x0138

MFG_ID_BROADBAND_ENERGY_NETWORKS_INC = _MFG_ID('Broadband Energy Networks Inc.')
MFG_ID_BROADBAND_ENERGY_NETWORKS_INC.id = 0x002D

MFG_ID_BTSTAR_HK_TECHNOLOGY_COMPANY_LIMITED = _MFG_ID('BTSTAR(HK) TECHNOLOGY COMPANY LIMITED')
MFG_ID_BTSTAR_HK_TECHNOLOGY_COMPANY_LIMITED.id = 0x024A

MFG_ID_BUFFALO_INC = _MFG_ID('Buffalo Inc.')
MFG_ID_BUFFALO_INC.id = 0x0145

MFG_ID_BUILDING_36_TECHNOLOGIES = _MFG_ID('Building 36 Technologies')
MFG_ID_BUILDING_36_TECHNOLOGIES.id = 0x0190

MFG_ID_BULCRAFT_CONTROL = _MFG_ID('Bulcraft Control')
MFG_ID_BULCRAFT_CONTROL.id = 0x0396

MFG_ID_BULOGICS = _MFG_ID('BuLogics')
MFG_ID_BULOGICS.id = 0x0026

MFG_ID_BONIG_UND_KALLENBACH_OHG = _MFG_ID('B�nig und Kallenbach oHG')
MFG_ID_BONIG_UND_KALLENBACH_OHG.id = 0x0169

MFG_ID_CALIX = _MFG_ID('Calix')
MFG_ID_CALIX.id = 0x0398

MFG_ID_CAMEO_COMMUNICATIONS_INC = _MFG_ID('Cameo Communications Inc.')
MFG_ID_CAMEO_COMMUNICATIONS_INC.id = 0x009C

MFG_ID_CARRIER = _MFG_ID('Carrier')
MFG_ID_CARRIER.id = 0x002E

MFG_ID_CASAWORKS = _MFG_ID('CasaWorks')
MFG_ID_CASAWORKS.id = 0x000B

MFG_ID_CASENIO_AG = _MFG_ID('casenio AG')
MFG_ID_CASENIO_AG.id = 0x0243

MFG_ID_CBCC_DOMOTIQUE_SAS = _MFG_ID('CBCC Domotique SAS')
MFG_ID_CBCC_DOMOTIQUE_SAS.id = 0x0166

MFG_ID_CENTRALITE_SYSTEMS_INC = _MFG_ID('CentraLite Systems, Inc')
MFG_ID_CENTRALITE_SYSTEMS_INC.id = 0x0246

MFG_ID_CENTURYLINK = _MFG_ID('Centurylink')
MFG_ID_CENTURYLINK.id = 0x033C

MFG_ID_CHAMBERLAIN_GROUP = _MFG_ID('Chamberlain Group')
MFG_ID_CHAMBERLAIN_GROUP.id = 0x0359

MFG_ID_CHECKIT_SOLUTIONS_INC = _MFG_ID('Check-It Solutions Inc.')
MFG_ID_CHECKIT_SOLUTIONS_INC.id = 0x014E

MFG_ID_CHENGPUTECH = _MFG_ID('CHENGPUTECH')
MFG_ID_CHENGPUTECH.id = 0x038F

MFG_ID_CHINA_SECURITY_FIRE_IOT_SENSING_CO_LTD = _MFG_ID('China Security & Fire IOT Sensing CO., LTD')
MFG_ID_CHINA_SECURITY_FIRE_IOT_SENSING_CO_LTD.id = 0x0320

MFG_ID_CHROMAGIC_TECHNOLOGIES_CORPORATION = _MFG_ID('Chromagic Technologies Corporation')
MFG_ID_CHROMAGIC_TECHNOLOGIES_CORPORATION.id = 0x0116

MFG_ID_CHUANGO_SECURITY_TECHNOLOGY_CORPORATION = _MFG_ID('Chuango Security Technology Corporation')
MFG_ID_CHUANGO_SECURITY_TECHNOLOGY_CORPORATION.id = 0x0280

MFG_ID_CISCO_CONSUMER_BUSINESS_GROUP = _MFG_ID('Cisco Consumer Business Group')
MFG_ID_CISCO_CONSUMER_BUSINESS_GROUP.id = 0x0082

MFG_ID_CLARE_CONTROLS = _MFG_ID('Clare Controls')
MFG_ID_CLARE_CONTROLS.id = 0x0194

MFG_ID_CLIMAX_TECHNOLOGY_LTD = _MFG_ID('Climax Technology, Ltd.')
MFG_ID_CLIMAX_TECHNOLOGY_LTD.id = 0x018E

MFG_ID_CLOUD_MEDIA = _MFG_ID('Cloud Media')
MFG_ID_CLOUD_MEDIA.id = 0x0200

MFG_ID_COLOR_KINETICS_INCORPORATED = _MFG_ID('Color Kinetics Incorporated')
MFG_ID_COLOR_KINETICS_INCORPORATED.id = 0x002F

MFG_ID_COMAP = _MFG_ID('COMAP')
MFG_ID_COMAP.id = 0x0329

MFG_ID_COMFORTABILITY = _MFG_ID('Comfortability')
MFG_ID_COMFORTABILITY.id = 0x0309

MFG_ID_COMPUTIME = _MFG_ID('Computime')
MFG_ID_COMPUTIME.id = 0x0140

MFG_ID_CONNECTED_OBJECT = _MFG_ID('Connected Object')
MFG_ID_CONNECTED_OBJECT.id = 0x011B

MFG_ID_CONNECTHOME = _MFG_ID('ConnectHome')
MFG_ID_CONNECTHOME.id = 0x0179

MFG_ID_CONNECTION_TECHNOLOGY_SYSTEMS = _MFG_ID('CONNECTION TECHNOLOGY SYSTEMS')
MFG_ID_CONNECTION_TECHNOLOGY_SYSTEMS.id = 0x0285

MFG_ID_CONTEC_INTELLIGENT_HOUSING = _MFG_ID('Contec intelligent housing')
MFG_ID_CONTEC_INTELLIGENT_HOUSING.id = 0x025D

MFG_ID_CONTROL4_CORPORATION = _MFG_ID('Control4 Corporation')
MFG_ID_CONTROL4_CORPORATION.id = 0x023F

MFG_ID_CONTROLTHINK_LC = _MFG_ID('ControlThink LC')
MFG_ID_CONTROLTHINK_LC.id = 0x0019

MFG_ID_CONVERGEX_LTD = _MFG_ID('ConvergeX Ltd.')
MFG_ID_CONVERGEX_LTD.id = 0x000F

MFG_ID_COOLGUARD = _MFG_ID('CoolGuard')
MFG_ID_COOLGUARD.id = 0x007D

MFG_ID_COOPER_LIGHTING = _MFG_ID('Cooper Lighting')
MFG_ID_COOPER_LIGHTING.id = 0x0079

MFG_ID_COOPER_WIRING_DEVICES = _MFG_ID('Cooper Wiring Devices')
MFG_ID_COOPER_WIRING_DEVICES.id = 0x001A

MFG_ID_COVENTIVE_TECHNOLOGIES_INC = _MFG_ID('Coventive Technologies Inc.')
MFG_ID_COVENTIVE_TECHNOLOGIES_INC.id = 0x009D

MFG_ID_CPRO = _MFG_ID('CPRO')
MFG_ID_CPRO.id = 0x0379

MFG_ID_CRIBOS = _MFG_ID('CribOS')
MFG_ID_CRIBOS.id = 0x0383

MFG_ID_CVNET = _MFG_ID('Cvnet')
MFG_ID_CVNET.id = 0x0328

MFG_ID_CYBERHOUSE = _MFG_ID('Cyberhouse')
MFG_ID_CYBERHOUSE.id = 0x0014

MFG_ID_CYBERTAN_TECHNOLOGY_INC = _MFG_ID('CyberTAN Technology, Inc.')
MFG_ID_CYBERTAN_TECHNOLOGY_INC.id = 0x0067

MFG_ID_CYTECH_TECHNOLOGY_PRE_LTD = _MFG_ID('Cytech Technology Pre Ltd.')
MFG_ID_CYTECH_TECHNOLOGY_PRE_LTD.id = 0x0030

MFG_ID_D3_TECHNOLOGY_CO_LTD = _MFG_ID('D-3 Technology Co. Ltd')
MFG_ID_D3_TECHNOLOGY_CO_LTD.id = 0x0294

MFG_ID_DANFOSS = _MFG_ID('Danfoss')
MFG_ID_DANFOSS.id = 0x0002

MFG_ID_DAWON_DNS = _MFG_ID('Dawon DNS')
MFG_ID_DAWON_DNS.id = 0x018C

MFG_ID_DECORIS_INTELLIGENT_SYSTEM_LIMITED = _MFG_ID('Decoris Intelligent System Limited')
MFG_ID_DECORIS_INTELLIGENT_SYSTEM_LIMITED.id = 0x020A

MFG_ID_DEFACONTROLS_BV = _MFG_ID('Defacontrols BV')
MFG_ID_DEFACONTROLS_BV.id = 0x013F

MFG_ID_DEFARO = _MFG_ID('DEFARO')
MFG_ID_DEFARO.id = 0x032E

MFG_ID_DESTINY_NETWORKS = _MFG_ID('Destiny Networks')
MFG_ID_DESTINY_NETWORKS.id = 0x0031

MFG_ID_DEVOLO = _MFG_ID('Devolo')
MFG_ID_DEVOLO.id = 0x0175

MFG_ID_DIEHL_AKO = _MFG_ID('Diehl AKO')
MFG_ID_DIEHL_AKO.id = 0x0103

MFG_ID_DIGITAL_5_INC = _MFG_ID('Digital 5, Inc.')
MFG_ID_DIGITAL_5_INC.id = 0x0032

MFG_ID_DIGITAL_WATCHDOG = _MFG_ID('Digital Watchdog')
MFG_ID_DIGITAL_WATCHDOG.id = 0x035D

MFG_ID_DIGITALZONE = _MFG_ID('DigitalZone')
MFG_ID_DIGITALZONE.id = 0x0228

MFG_ID_DLINK = _MFG_ID('D-Link')
MFG_ID_DLINK.id = 0x0108

MFG_ID_DMP_DIGITAL_MONITORING_PRODUCTS = _MFG_ID('DMP (Digital Monitoring Products)')
MFG_ID_DMP_DIGITAL_MONITORING_PRODUCTS.id = 0x0127

MFG_ID_DOMINO_SISTEMI_DOO = _MFG_ID('Domino sistemi d.o.o.')
MFG_ID_DOMINO_SISTEMI_DOO.id = 0x0177

MFG_ID_DOMITECH_PRODUCTS_LLC = _MFG_ID('Domitech Products, LLC')
MFG_ID_DOMITECH_PRODUCTS_LLC.id = 0x020E

MFG_ID_DONGGUAN_ZHOU_DA_ELECTRONICS_CO_LTD = _MFG_ID('Dongguan Zhou Da Electronics Co.,Ltd')
MFG_ID_DONGGUAN_ZHOU_DA_ELECTRONICS_CO_LTD.id = 0x020C

MFG_ID_DRACOR_INC = _MFG_ID('DRACOR Inc.')
MFG_ID_DRACOR_INC.id = 0x017D

MFG_ID_DRAGON_TECH_INDUSTRIAL_LTD = _MFG_ID('Dragon Tech Industrial, Ltd.')
MFG_ID_DRAGON_TECH_INDUSTRIAL_LTD.id = 0x0184

MFG_ID_DTV_RESEARCH_UNIPESSOAL_LDA = _MFG_ID('DTV Research Unipessoal, Lda')
MFG_ID_DTV_RESEARCH_UNIPESSOAL_LDA.id = 0x0223

MFG_ID_DUNEHD = _MFG_ID('Dune-HD')
MFG_ID_DUNEHD.id = 0x0272

MFG_ID_DUSUN_ELECTRON_LTD = _MFG_ID('Dusun Electron Ltd.')
MFG_ID_DUSUN_ELECTRON_LTD.id = 0x0334

MFG_ID_DVACO_GROUP = _MFG_ID('DVACO GROUP')
MFG_ID_DVACO_GROUP.id = 0x031B

MFG_ID_DYNAQUIP_CONTROLS = _MFG_ID('DynaQuip Controls')
MFG_ID_DYNAQUIP_CONTROLS.id = 0x0132

MFG_ID_EASY_SAVER_CO_INC = _MFG_ID('EASY SAVER Co., Inc')
MFG_ID_EASY_SAVER_CO_INC.id = 0x0247

MFG_ID_EATON = _MFG_ID('Eaton')
MFG_ID_EATON.id = 0x001A

MFG_ID_EBV = _MFG_ID('EbV')
MFG_ID_EBV.id = 0x017C

MFG_ID_ECHOSTAR = _MFG_ID('Echostar')
MFG_ID_ECHOSTAR.id = 0x016B

MFG_ID_ECO_AUTOMATION = _MFG_ID('Eco Automation')
MFG_ID_ECO_AUTOMATION.id = 0x028F

MFG_ID_ECO_LIFE_ENGINEERING_CO_LTD = _MFG_ID('Eco Life Engineering Co., Ltd.')
MFG_ID_ECO_LIFE_ENGINEERING_CO_LTD.id = 0x037C

MFG_ID_ECOLINK = _MFG_ID('Ecolink')
MFG_ID_ECOLINK.id = 0x014A

MFG_ID_ECONET_CONTROLS = _MFG_ID('EcoNet Controls')
MFG_ID_ECONET_CONTROLS.id = 0x0157

MFG_ID_ECS = _MFG_ID('ECS')
MFG_ID_ECS.id = 0x039D

MFG_ID_EELECTRON_SPA = _MFG_ID('Eelectron SpA')
MFG_ID_EELECTRON_SPA.id = 0x031F

MFG_ID_EHOME_AUTOMATION = _MFG_ID('e-Home AUTOMATION')
MFG_ID_EHOME_AUTOMATION.id = 0x010D

MFG_ID_EI_ELECTRONICS = _MFG_ID('Ei Electronics')
MFG_ID_EI_ELECTRONICS.id = 0x026B

MFG_ID_EKA_SYSTEMS = _MFG_ID('Eka Systems')
MFG_ID_EKA_SYSTEMS.id = 0x0087

MFG_ID_ELEAR_SOLUTIONS_TECH_PVT_LTD = _MFG_ID('Elear Solutions Tech Pvt. Ltd.')
MFG_ID_ELEAR_SOLUTIONS_TECH_PVT_LTD.id = 0x0389

MFG_ID_ELECTRONIC_SOLUTIONS = _MFG_ID('Electronic Solutions')
MFG_ID_ELECTRONIC_SOLUTIONS.id = 0x0033

MFG_ID_ELEXA_CONSUMER_PRODUCTS_INC = _MFG_ID('Elexa Consumer Products Inc.')
MFG_ID_ELEXA_CONSUMER_PRODUCTS_INC.id = 0x021F

MFG_ID_ELGEV_ELECTRONICS_LTD = _MFG_ID('El-Gev Electronics LTD')
MFG_ID_ELGEV_ELECTRONICS_LTD.id = 0x0034

MFG_ID_ELK_PRODUCTS_INC = _MFG_ID('ELK Products, Inc.')
MFG_ID_ELK_PRODUCTS_INC.id = 0x001B

MFG_ID_EMBEDDED_DATA_SYSTEMS = _MFG_ID('Embedded Data Systems')
MFG_ID_EMBEDDED_DATA_SYSTEMS.id = 0x0393

MFG_ID_EMBEDDED_SYSTEM_DESIGN_LIMITED = _MFG_ID('Embedded System Design Limited')
MFG_ID_EMBEDDED_SYSTEM_DESIGN_LIMITED.id = 0x020B

MFG_ID_EMBEDIT_AS = _MFG_ID('Embedit A/S')
MFG_ID_EMBEDIT_AS.id = 0x0035

MFG_ID_EMPERS_TECH_CO_LTD = _MFG_ID('Empers Tech Co., Ltd.')
MFG_ID_EMPERS_TECH_CO_LTD.id = 0x0284

MFG_ID_EMT_CONTROLS = _MFG_ID('EMT Controls')
MFG_ID_EMT_CONTROLS.id = 0x0336

MFG_ID_ENBLINK_CO_LTD = _MFG_ID('Enblink Co. Ltd')
MFG_ID_ENBLINK_CO_LTD.id = 0x014D

MFG_ID_ENWOX_TECHNOLOGIES_SRO = _MFG_ID('Enwox Technologies s.r.o.')
MFG_ID_ENWOX_TECHNOLOGIES_SRO.id = 0x0219

MFG_ID_ERONE = _MFG_ID('Erone')
MFG_ID_ERONE.id = 0x006F

MFG_ID_ESSENCE_SECURITY = _MFG_ID('Essence Security')
MFG_ID_ESSENCE_SECURITY.id = 0x0160

MFG_ID_ESSENTIAL_TECHNOLOGIES_INC = _MFG_ID('ESSENTIAL TECHNOLOGIES INC.')
MFG_ID_ESSENTIAL_TECHNOLOGIES_INC.id = 0x029B

MFG_ID_EUROTRONICS = _MFG_ID('Eurotronics')
MFG_ID_EUROTRONICS.id = 0x0148

MFG_ID_EVERSPRING = _MFG_ID('Everspring')
MFG_ID_EVERSPRING.id = 0x0060

MFG_ID_EVOLVE = _MFG_ID('Evolve')
MFG_ID_EVOLVE.id = 0x0113

MFG_ID_EVOLVERE_SPA = _MFG_ID('Evolvere SpA')
MFG_ID_EVOLVERE_SPA.id = 0x036F

MFG_ID_EXCEPTIONAL_INNOVATIONS = _MFG_ID('Exceptional Innovations')
MFG_ID_EXCEPTIONAL_INNOVATIONS.id = 0x0036

MFG_ID_EXHAUSTO = _MFG_ID('Exhausto')
MFG_ID_EXHAUSTO.id = 0x0004

MFG_ID_EXIGENT_SENSORS = _MFG_ID('Exigent Sensors')
MFG_ID_EXIGENT_SENSORS.id = 0x009F

MFG_ID_EXPRESS_CONTROLS = _MFG_ID('Express Controls')
MFG_ID_EXPRESS_CONTROLS.id = 0x001E

MFG_ID_EZEX_CORPORATION = _MFG_ID('eZEX Corporation')
MFG_ID_EZEX_CORPORATION.id = 0x0233

MFG_ID_FAKRO = _MFG_ID('Fakro')
MFG_ID_FAKRO.id = 0x0085

MFG_ID_FANTEM = _MFG_ID('Fantem')
MFG_ID_FANTEM.id = 0x016A

MFG_ID_FIBARGROUP = _MFG_ID('Fibargroup')
MFG_ID_FIBARGROUP.id = 0x010F

MFG_ID_FIFTHPLAY_NV = _MFG_ID('fifthplay nv')
MFG_ID_FIFTHPLAY_NV.id = 0x0295

MFG_ID_FLEX_AUTOMATION = _MFG_ID('Flex Automation')
MFG_ID_FLEX_AUTOMATION.id = 0x002C

MFG_ID_FLEX_AUTOMATION_2 = _MFG_ID('Flex Automation')
MFG_ID_FLEX_AUTOMATION_2.id = 0x004F

MFG_ID_FLEXTRONICS = _MFG_ID('Flextronics')
MFG_ID_FLEXTRONICS.id = 0x018D

MFG_ID_FLUE_SENTINEL = _MFG_ID('Flue Sentinel')
MFG_ID_FLUE_SENTINEL.id = 0x0024

MFG_ID_FOARD_SYSTEMS = _MFG_ID('Foard Systems')
MFG_ID_FOARD_SYSTEMS.id = 0x0037

MFG_ID_FOCAL_POINT_LIMITED = _MFG_ID('Focal Point Limited')
MFG_ID_FOCAL_POINT_LIMITED.id = 0x018F

MFG_ID_FOLLOWGOOD_TECHNOLOGY_COMPANY_LTD = _MFG_ID('FollowGood Technology Company Ltd.')
MFG_ID_FOLLOWGOOD_TECHNOLOGY_COMPANY_LTD.id = 0x0137

MFG_ID_FOREST_GROUP_NEDERLAND_BV = _MFG_ID('Forest Group Nederland B.V')
MFG_ID_FOREST_GROUP_NEDERLAND_BV.id = 0x0207

MFG_ID_FORTREZZ_LLC = _MFG_ID('FortrezZ LLC')
MFG_ID_FORTREZZ_LLC.id = 0x0084

MFG_ID_FOXCONN = _MFG_ID('Foxconn')
MFG_ID_FOXCONN.id = 0x011D

MFG_ID_FOXCONN_INDUSTRIAL_INTERNET = _MFG_ID('Foxconn Industrial Internet')
MFG_ID_FOXCONN_INDUSTRIAL_INTERNET.id = 0x039C

MFG_ID_FROSTDALE = _MFG_ID('Frostdale')
MFG_ID_FROSTDALE.id = 0x0110

MFG_ID_FUTURE_HOME_AS = _MFG_ID('Future Home AS')
MFG_ID_FUTURE_HOME_AS.id = 0x0305

MFG_ID_GE = _MFG_ID('GE')
MFG_ID_GE.id = 0x033E

MFG_ID_GES = _MFG_ID('GES')
MFG_ID_GES.id = 0x025A

MFG_ID_GKB_SECURITY_CORPORATION = _MFG_ID('GKB Security Corporation')
MFG_ID_GKB_SECURITY_CORPORATION.id = 0x022B

MFG_ID_GLOBALCHINATECH = _MFG_ID('Globalchina-Tech')
MFG_ID_GLOBALCHINATECH.id = 0x018A

MFG_ID_GOAP = _MFG_ID('Goap')
MFG_ID_GOAP.id = 0x0159

MFG_ID_GOGGIN_RESEARCH = _MFG_ID('Goggin Research')
MFG_ID_GOGGIN_RESEARCH.id = 0x0076

MFG_ID_GOOD_WAY_TECHNOLOGY_CO_LTD = _MFG_ID('Good Way Technology Co., Ltd')
MFG_ID_GOOD_WAY_TECHNOLOGY_CO_LTD.id = 0x0068

MFG_ID_GREENWAVE_REALITY_INC = _MFG_ID('GreenWave Reality Inc.')
MFG_ID_GREENWAVE_REALITY_INC.id = 0x0099

MFG_ID_GRIB = _MFG_ID('Grib')
MFG_ID_GRIB.id = 0x018B

MFG_ID_GUANGDONG_PHNIX_ECOENERGY_SOLUTION_LTD = _MFG_ID('GUANGDONG PHNIX ECO-ENERGY SOLUTION LTD.')
MFG_ID_GUANGDONG_PHNIX_ECOENERGY_SOLUTION_LTD.id = 0x0391

MFG_ID_GUANGZHOU_RUIXIANG_ME_CO_LTD = _MFG_ID('Guangzhou Ruixiang M&E Co., Ltd')
MFG_ID_GUANGZHOU_RUIXIANG_ME_CO_LTD.id = 0x016D

MFG_ID_GUANGZHOU_ZEEWAVE_INFORMATION_TECHNOLOGY_CO_LTD = _MFG_ID('GuangZhou Zeewave Information Technology Co., Ltd.')
MFG_ID_GUANGZHOU_ZEEWAVE_INFORMATION_TECHNOLOGY_CO_LTD.id = 0x0158

MFG_ID_GUANGZHOU_SIMT_LIMITED = _MFG_ID('Guangzhou_SIMT  Limited')
MFG_ID_GUANGZHOU_SIMT_LIMITED.id = 0x0395

MFG_ID_GUARDTEC_INC = _MFG_ID('Guardtec Inc.')
MFG_ID_GUARDTEC_INC.id = 0x037B

MFG_ID_HAB_HOME_INTELLIGENCE_LLC = _MFG_ID('HAB Home Intelligence, LLC')
MFG_ID_HAB_HOME_INTELLIGENCE_LLC.id = 0x0287

MFG_ID_HAMPOO = _MFG_ID('Hampoo')
MFG_ID_HAMPOO.id = 0x030D

MFG_ID_HANGZHOU_IMAGIC_TECHNOLOGY_CO_LTD = _MFG_ID('HangZhou iMagic Technology Co., Ltd')
MFG_ID_HANGZHOU_IMAGIC_TECHNOLOGY_CO_LTD.id = 0x0387

MFG_ID_HANK_ELECTRONICS_LTD = _MFG_ID('HANK Electronics Ltd')
MFG_ID_HANK_ELECTRONICS_LTD.id = 0x0208

MFG_ID_HANKOOK_GAS_KIKI_CO_LTD = _MFG_ID('Hankook Gas Kiki CO.,LTD.')
MFG_ID_HANKOOK_GAS_KIKI_CO_LTD.id = 0x024C

MFG_ID_HAUPPAUGE = _MFG_ID('Hauppauge')
MFG_ID_HAUPPAUGE.id = 0x025C

MFG_ID_HAWKING_TECHNOLOGIES_INC = _MFG_ID('Hawking Technologies Inc.')
MFG_ID_HAWKING_TECHNOLOGIES_INC.id = 0x0073

MFG_ID_HELTUN = _MFG_ID('HELTUN')
MFG_ID_HELTUN.id = 0x0344

MFG_ID_HERALD_DATANETICS_LIMITED = _MFG_ID('Herald Datanetics Limited')
MFG_ID_HERALD_DATANETICS_LIMITED.id = 0x020F

MFG_ID_HITECH_AUTOMATION = _MFG_ID('HiTech Automation')
MFG_ID_HITECH_AUTOMATION.id = 0x0017

MFG_ID_HOLION_ELECTRONIC_ENGINEERING_CO_LTD = _MFG_ID('Holion Electronic Engineering Co., Ltd')
MFG_ID_HOLION_ELECTRONIC_ENGINEERING_CO_LTD.id = 0x0181

MFG_ID_HOLTEC_ELECTRONICS_BV = _MFG_ID('Holtec Electronics BV')
MFG_ID_HOLTEC_ELECTRONICS_BV.id = 0x013E

MFG_ID_HOME_AUTOMATED_LIVING = _MFG_ID('Home Automated Living')
MFG_ID_HOME_AUTOMATED_LIVING.id = 0x000D

MFG_ID_HOME_AUTOMATION_EUROPE = _MFG_ID('Home Automation Europe')
MFG_ID_HOME_AUTOMATION_EUROPE.id = 0x009A

MFG_ID_HOME_AUTOMATION_INC = _MFG_ID('Home Automation Inc.')
MFG_ID_HOME_AUTOMATION_INC.id = 0x005B

MFG_ID_HOME_CONTROLS = _MFG_ID('Home controls')
MFG_ID_HOME_CONTROLS.id = 0x0293

MFG_ID_HOME_DIRECTOR = _MFG_ID('Home Director')
MFG_ID_HOME_DIRECTOR.id = 0x0038

MFG_ID_HOMEMANAGEABLES_INC = _MFG_ID('Homemanageables, Inc.')
MFG_ID_HOMEMANAGEABLES_INC.id = 0x0070

MFG_ID_HOMEPRO = _MFG_ID('Homepro')
MFG_ID_HOMEPRO.id = 0x0050

MFG_ID_HOMESCENARIO = _MFG_ID('HomeScenario')
MFG_ID_HOMESCENARIO.id = 0x0162

MFG_ID_HOMESEER_TECHNOLOGIES = _MFG_ID('HomeSeer Technologies')
MFG_ID_HOMESEER_TECHNOLOGIES.id = 0x000C

MFG_ID_HONEST_TECHNOLOGY = _MFG_ID('Honest Technology')
MFG_ID_HONEST_TECHNOLOGY.id = 0x0275

MFG_ID_HONEST_TECHNOLOGY_CO_LTD = _MFG_ID('Honest Technology Co., Ltd.')
MFG_ID_HONEST_TECHNOLOGY_CO_LTD.id = 0x023D

MFG_ID_HONEYWELL = _MFG_ID('Honeywell')
MFG_ID_HONEYWELL.id = 0x0039

MFG_ID_HOPPE = _MFG_ID('Hoppe')
MFG_ID_HOPPE.id = 0x0313

MFG_ID_HORNBACH_BAUMARKT_AG = _MFG_ID('HORNBACH Baumarkt AG')
MFG_ID_HORNBACH_BAUMARKT_AG.id = 0x0377

MFG_ID_HORUS_SMART_CONTROL = _MFG_ID('Horus Smart Control')
MFG_ID_HORUS_SMART_CONTROL.id = 0x0298

MFG_ID_HOSEOTELNET = _MFG_ID('HOSEOTELNET')
MFG_ID_HOSEOTELNET.id = 0x0221

MFG_ID_HUAPIN_INFORMATION_TECHNOLOGY_CO_LTD = _MFG_ID('Huapin Information Technology Co.,Ltd')
MFG_ID_HUAPIN_INFORMATION_TECHNOLOGY_CO_LTD.id = 0x0180

MFG_ID_HUAWEI_DEVICE_CO_LTD = _MFG_ID('Huawei Device Co., Ltd.')
MFG_ID_HUAWEI_DEVICE_CO_LTD.id = 0x025F

MFG_ID_HUAWEI_TECHNOLOGIES_CO_LTD = _MFG_ID('Huawei Technologies Co., Ltd.')
MFG_ID_HUAWEI_TECHNOLOGIES_CO_LTD.id = 0x024B

MFG_ID_HUNTER_DOUGLAS = _MFG_ID('Hunter Douglas')
MFG_ID_HUNTER_DOUGLAS.id = 0x007C

MFG_ID_HYUNDAI_TELECOM = _MFG_ID('Hyundai Telecom')
MFG_ID_HYUNDAI_TELECOM.id = 0x0374

MFG_ID_IAMSMART = _MFG_ID('iamsmart')
MFG_ID_IAMSMART.id = 0x038A

MFG_ID_IAUTOMADE_PTE_LTD = _MFG_ID('iAutomade Pte Ltd')
MFG_ID_IAUTOMADE_PTE_LTD.id = 0x0218

MFG_ID_ICOM_TECHNOLOGY_BV = _MFG_ID('iCOM Technology b.v.')
MFG_ID_ICOM_TECHNOLOGY_BV.id = 0x0011

MFG_ID_ICONTROL = _MFG_ID('iControl')
MFG_ID_ICONTROL.id = 0x0106

MFG_ID_ICONTROL_NETWORKS = _MFG_ID('Icontrol Networks')
MFG_ID_ICONTROL_NETWORKS.id = 0x0106

MFG_ID_ID_LOCK_AS = _MFG_ID('ID Lock AS')
MFG_ID_ID_LOCK_AS.id = 0x0373

MFG_ID_IDRF = _MFG_ID('ID-RF')
MFG_ID_IDRF.id = 0x0165

MFG_ID_IEXERGY_GMBH = _MFG_ID('iEXERGY GmbH')
MFG_ID_IEXERGY_GMBH.id = 0x019E

MFG_ID_ILEVIA_SRL = _MFG_ID('Ilevia srl')
MFG_ID_ILEVIA_SRL.id = 0x031C

MFG_ID_IMPACT_TECHNOLOGIES_AND_PRODUCTS = _MFG_ID('Impact Technologies and Products')
MFG_ID_IMPACT_TECHNOLOGIES_AND_PRODUCTS.id = 0x0056

MFG_ID_IMPACT_TECHNOLOGIES_BV = _MFG_ID('Impact Technologies BV')
MFG_ID_IMPACT_TECHNOLOGIES_BV.id = 0x0061

MFG_ID_INERGY_SYSTEMS_LLC = _MFG_ID('Inergy Systems LLC')
MFG_ID_INERGY_SYSTEMS_LLC.id = 0x0385

MFG_ID_INFUSION_DEVELOPMENT = _MFG_ID('Infusion Development')
MFG_ID_INFUSION_DEVELOPMENT.id = 0x012B

MFG_ID_INGERSOLL_RAND_SCHLAGE = _MFG_ID('Ingersoll Rand (Schlage)')
MFG_ID_INGERSOLL_RAND_SCHLAGE.id = 0x006C

MFG_ID_INGERSOLL_RAND_ECOLINK = _MFG_ID('Ingersoll Rand (was Ecolink)')
MFG_ID_INGERSOLL_RAND_ECOLINK.id = 0x011F

MFG_ID_INKEL_CORP = _MFG_ID('Inkel Corp.')
MFG_ID_INKEL_CORP.id = 0x0256

MFG_ID_INLON_SRL = _MFG_ID('Inlon Srl')
MFG_ID_INLON_SRL.id = 0x003A

MFG_ID_INNOBAND_TECHNOLOGIES_INC = _MFG_ID('Innoband Technologies, Inc')
MFG_ID_INNOBAND_TECHNOLOGIES_INC.id = 0x0141

MFG_ID_INNOPIA_TECHNOLOGIES_INC = _MFG_ID('INNOPIA Technologies, Inc.')
MFG_ID_INNOPIA_TECHNOLOGIES_INC.id = 0x0382

MFG_ID_INNOVUS = _MFG_ID('INNOVUS')
MFG_ID_INNOVUS.id = 0x0077

MFG_ID_INOVELLI = _MFG_ID('Inovelli')
MFG_ID_INOVELLI.id = 0x031E

MFG_ID_INSIGNIA = _MFG_ID('Insignia')
MFG_ID_INSIGNIA.id = 0x0100

MFG_ID_INTEL = _MFG_ID('Intel')
MFG_ID_INTEL.id = 0x0006

MFG_ID_INTELLICON = _MFG_ID('IntelliCon')
MFG_ID_INTELLICON.id = 0x001C

MFG_ID_INTERACTIVE_ELECTRONICS_SYSTEMS_IES = _MFG_ID('Interactive Electronics Systems (IES)')
MFG_ID_INTERACTIVE_ELECTRONICS_SYSTEMS_IES.id = 0x0072

MFG_ID_INTERMATIC = _MFG_ID('Intermatic')
MFG_ID_INTERMATIC.id = 0x0005

MFG_ID_INTERNATIONAL_INTEGRATED_SYSTEMS_INC_IISI = _MFG_ID('International Integrated Systems, Inc. (IISI)')
MFG_ID_INTERNATIONAL_INTEGRATED_SYSTEMS_INC_IISI.id = 0x0338

MFG_ID_INTERNET_DOM = _MFG_ID('Internet Dom')
MFG_ID_INTERNET_DOM.id = 0x0013

MFG_ID_INTERSOFT = _MFG_ID('INTERSOFT')
MFG_ID_INTERSOFT.id = 0x0288

MFG_ID_INVALANCE = _MFG_ID('Invalance')
MFG_ID_INVALANCE.id = 0x039E

MFG_ID_INVENTEC = _MFG_ID('Inventec')
MFG_ID_INVENTEC.id = 0x0278

MFG_ID_IOOOTA = _MFG_ID('IOOOTA')
MFG_ID_IOOOTA.id = 0x0368

MFG_ID_IQGROUP = _MFG_ID('IQ-Group')
MFG_ID_IQGROUP.id = 0x005F

MFG_ID_IREVO = _MFG_ID('iRevo')
MFG_ID_IREVO.id = 0x0212

MFG_ID_IUNGONL_BV = _MFG_ID('iungo.nl B.V.')
MFG_ID_IUNGONL_BV.id = 0x0253

MFG_ID_IWATSU = _MFG_ID('IWATSU')
MFG_ID_IWATSU.id = 0x0123

MFG_ID_JASCO_PRODUCTS = _MFG_ID('Jasco Products')
MFG_ID_JASCO_PRODUCTS.id = 0x0063

MFG_ID_JIN_TAO_BAO = _MFG_ID('Jin Tao Bao')
MFG_ID_JIN_TAO_BAO.id = 0x015A

MFG_ID_JLABS_CORPORATION = _MFG_ID('JLabs Corporation')
MFG_ID_JLABS_CORPORATION.id = 0x039F

MFG_ID_JSW_PACIFIC_CORPORATION = _MFG_ID('JSW Pacific Corporation')
MFG_ID_JSW_PACIFIC_CORPORATION.id = 0x0164

MFG_ID_KAIPULE_TECHNOLOGY_CO_LTD = _MFG_ID('Kaipule Technology Co., Ltd.')
MFG_ID_KAIPULE_TECHNOLOGY_CO_LTD.id = 0x0214

MFG_ID_KAMSTRUP_AS = _MFG_ID('Kamstrup A/S')
MFG_ID_KAMSTRUP_AS.id = 0x0091

MFG_ID_KELLENDONK_ELEKTRONIK = _MFG_ID('Kellendonk Elektronik')
MFG_ID_KELLENDONK_ELEKTRONIK.id = 0x006A

MFG_ID_KICHLER = _MFG_ID('Kichler')
MFG_ID_KICHLER.id = 0x0114

MFG_ID_KIWILAB = _MFG_ID('KIWILAB')
MFG_ID_KIWILAB.id = 0x035F

MFG_ID_KLICKH_PVT_LTD = _MFG_ID('KlickH Pvt Ltd.')
MFG_ID_KLICKH_PVT_LTD.id = 0x0139

MFG_ID_KOOL_KONCEPTS = _MFG_ID('KOOL KONCEPTS')
MFG_ID_KOOL_KONCEPTS.id = 0x0261

MFG_ID_KOPERA_DEVELOPMENT_INC = _MFG_ID('Kopera Development Inc.')
MFG_ID_KOPERA_DEVELOPMENT_INC.id = 0x0174

MFG_ID_KUMHO_ELECTRIC_INC = _MFG_ID('KUMHO ELECTRIC, INC')
MFG_ID_KUMHO_ELECTRIC_INC.id = 0x023A

MFG_ID_LAGOTEK_CORPORATION = _MFG_ID('Lagotek Corporation')
MFG_ID_LAGOTEK_CORPORATION.id = 0x0051

MFG_ID_LEAK_INTELLIGENCE_LLC = _MFG_ID('Leak Intelligence, LLC')
MFG_ID_LEAK_INTELLIGENCE_LLC.id = 0x0173

MFG_ID_LEEDARSON_LIGHTING_CO_LTD = _MFG_ID('LEEDARSON LIGHTING CO., LTD.')
MFG_ID_LEEDARSON_LIGHTING_CO_LTD.id = 0x0300

MFG_ID_LEVION_TECHNOLOGIES_GMBH = _MFG_ID('LEVION Technologies GmbH')
MFG_ID_LEVION_TECHNOLOGIES_GMBH.id = 0x0187

MFG_ID_LEVITON = _MFG_ID('Leviton')
MFG_ID_LEVITON.id = 0x001D

MFG_ID_LEXEL = _MFG_ID('Lexel')
MFG_ID_LEXEL.id = 0x0015

MFG_ID_LG_ELECTRONICS = _MFG_ID('LG Electronics')
MFG_ID_LG_ELECTRONICS.id = 0x015B

MFG_ID_LIAONING_YOUWANG_LIGHTING_AND_ELECTRONIC_TECHNOLOGY = _MFG_ID('Liaoning Youwang Lighting and Electronic Technology Pty Ltd')
MFG_ID_LIAONING_YOUWANG_LIGHTING_AND_ELECTRONIC_TECHNOLOGY.id = 0x0362

MFG_ID_LIFESHIELD_LLC = _MFG_ID('LifeShield, LLC')
MFG_ID_LIFESHIELD_LLC.id = 0x0224

MFG_ID_LIFESTYLE_NETWORKS = _MFG_ID('Lifestyle Networks')
MFG_ID_LIFESTYLE_NETWORKS.id = 0x003C

MFG_ID_LIGHT_ENGINE_LIMITED = _MFG_ID('Light Engine Limited')
MFG_ID_LIGHT_ENGINE_LIMITED.id = 0x0210

MFG_ID_LIMEI = _MFG_ID('LIMEI')
MFG_ID_LIMEI.id = 0x0342

MFG_ID_LINK_ELECTRONICS_CO_LTD = _MFG_ID('LINK ELECTRONICS Co., Ltd.')
MFG_ID_LINK_ELECTRONICS_CO_LTD.id = 0x035C

MFG_ID_LITE_AUTOMATION = _MFG_ID('Lite Automation')
MFG_ID_LITE_AUTOMATION.id = 0x0316

MFG_ID_LIVEGUARD_LTD = _MFG_ID('Liveguard Ltd.')
MFG_ID_LIVEGUARD_LTD.id = 0x017A

MFG_ID_LIVING_STYLE_ENTERPRISES_LTD = _MFG_ID('Living Style Enterprises, Ltd.')
MFG_ID_LIVING_STYLE_ENTERPRISES_LTD.id = 0x013A

MFG_ID_LOCSTAR_TECHNOLOGY_CO_LTD = _MFG_ID('Locstar Technology Co., Ltd')
MFG_ID_LOCSTAR_TECHNOLOGY_CO_LTD.id = 0x015E

MFG_ID_LOGIC_GROUP = _MFG_ID('Logic Group')
MFG_ID_LOGIC_GROUP.id = 0x0234

MFG_ID_LOGITECH = _MFG_ID('Logitech')
MFG_ID_LOGITECH.id = 0x007F

MFG_ID_LOUDWATER_TECHNOLOGIES_LLC = _MFG_ID('Loudwater Technologies, LLC')
MFG_ID_LOUDWATER_TECHNOLOGIES_LLC.id = 0x0025

MFG_ID_LOWES = _MFG_ID('Lowes')
MFG_ID_LOWES.id = 0x038C

MFG_ID_LS_CONTROL = _MFG_ID('LS Control')
MFG_ID_LS_CONTROL.id = 0x0071

MFG_ID_LUFFANET_CO_LTE = _MFG_ID('Luffanet Co. Lte.')
MFG_ID_LUFFANET_CO_LTE.id = 0x036D

MFG_ID_LUXEASY_TECHNOLOGY_COMPANY_LTD = _MFG_ID('LUXEASY technology company LTD.')
MFG_ID_LUXEASY_TECHNOLOGY_COMPANY_LTD.id = 0x025E

MFG_ID_LVI_PRODUKTER_AB = _MFG_ID('LVI Produkter AB')
MFG_ID_LVI_PRODUKTER_AB.id = 0x0062

MFG_ID_M2M_SOLUTION = _MFG_ID('m2m Solution')
MFG_ID_M2M_SOLUTION.id = 0x0192

MFG_ID_M2M_SOLUTION_2 = _MFG_ID('M2M Solution')
MFG_ID_M2M_SOLUTION_2.id = 0x0195

MFG_ID_MANODO_KTC = _MFG_ID('Manodo / KTC')
MFG_ID_MANODO_KTC.id = 0x006E

MFG_ID_MARMITEK_BV = _MFG_ID('Marmitek BV')
MFG_ID_MARMITEK_BV.id = 0x003D

MFG_ID_MARTEC_ACCESS_PRODUCTS = _MFG_ID('Martec Access Products')
MFG_ID_MARTEC_ACCESS_PRODUCTS.id = 0x003E

MFG_ID_MARTIN_RENZ_GMBH = _MFG_ID('Martin Renz GmbH')
MFG_ID_MARTIN_RENZ_GMBH.id = 0x0092

MFG_ID_MB_TURN_KEY_DESIGN = _MFG_ID('MB Turn Key Design')
MFG_ID_MB_TURN_KEY_DESIGN.id = 0x008F

MFG_ID_MCOHOME_TECHNOLOGY_CO_LTD = _MFG_ID('McoHome Technology Co., Ltd')
MFG_ID_MCOHOME_TECHNOLOGY_CO_LTD.id = 0x015F

MFG_ID_MCT_CO_LTD = _MFG_ID('MCT CO., LTD')
MFG_ID_MCT_CO_LTD.id = 0x0222

MFG_ID_MEEDIO_LLC = _MFG_ID('Meedio, LLC')
MFG_ID_MEEDIO_LLC.id = 0x0027

MFG_ID_MEGACHIPS = _MFG_ID('MegaChips')
MFG_ID_MEGACHIPS.id = 0x0107

MFG_ID_MERCURY_CORPORATION = _MFG_ID('Mercury Corporation')
MFG_ID_MERCURY_CORPORATION.id = 0x022D

MFG_ID_MERTEN = _MFG_ID('Merten')
MFG_ID_MERTEN.id = 0x007A

MFG_ID_MILANITY_INC = _MFG_ID('Milanity, Inc.')
MFG_ID_MILANITY_INC.id = 0x0238

MFG_ID_MITSUMI = _MFG_ID('MITSUMI')
MFG_ID_MITSUMI.id = 0x0112

MFG_ID_MOBILUS_MOTOR_SPOLKA_Z_OO = _MFG_ID('MOBILUS MOTOR Sp�lka z o.o.')
MFG_ID_MOBILUS_MOTOR_SPOLKA_Z_OO.id = 0x019D

MFG_ID_MODACOM_CO_LTD = _MFG_ID('MODACOM CO., LTD.')
MFG_ID_MODACOM_CO_LTD.id = 0x0232

MFG_ID_MODSTROM = _MFG_ID('Modstr�m')
MFG_ID_MODSTROM.id = 0x008D

MFG_ID_MOHITO_NETWORKS = _MFG_ID('Mohito Networks')
MFG_ID_MOHITO_NETWORKS.id = 0x000E

MFG_ID_MONOPRICE = _MFG_ID('Monoprice')
MFG_ID_MONOPRICE.id = 0x0202

MFG_ID_MONSTER_CABLE = _MFG_ID('Monster Cable')
MFG_ID_MONSTER_CABLE.id = 0x007E

MFG_ID_MOTION_CONTROL_SYSTEMS = _MFG_ID('Motion Control Systems')
MFG_ID_MOTION_CONTROL_SYSTEMS.id = 0x0125

MFG_ID_MOTOROLA = _MFG_ID('Motorola')
MFG_ID_MOTOROLA.id = 0x003F

MFG_ID_MSK_MIYAKAWA_SEISAKUSHO = _MFG_ID('MSK - Miyakawa Seisakusho')
MFG_ID_MSK_MIYAKAWA_SEISAKUSHO.id = 0x0122

MFG_ID_MTC_MAINTRONIC_GERMANY = _MFG_ID('MTC Maintronic Germany')
MFG_ID_MTC_MAINTRONIC_GERMANY.id = 0x0083

MFG_ID_MYSTROM = _MFG_ID('myStrom')
MFG_ID_MYSTROM.id = 0x0143

MFG_ID_NANJING_EASTHOUSE_ELECTRICAL_CO_LTD = _MFG_ID('Nanjing Easthouse Electrical Co., Ltd.')
MFG_ID_NANJING_EASTHOUSE_ELECTRICAL_CO_LTD.id = 0x016E

MFG_ID_NAPCO_SECURITY_TECHNOLOGIES_INC = _MFG_ID('Napco Security Technologies, Inc.')
MFG_ID_NAPCO_SECURITY_TECHNOLOGIES_INC.id = 0x0121

MFG_ID_NCUBE = _MFG_ID('nCube')
MFG_ID_NCUBE.id = 0x038D

MFG_ID_NEC_PLATFORMS_LTD = _MFG_ID('NEC Platforms Ltd')
MFG_ID_NEC_PLATFORMS_LTD.id = 0x036B

MFG_ID_NEEO_AG = _MFG_ID('NEEO AG')
MFG_ID_NEEO_AG.id = 0x0241

MFG_ID_NEFIT = _MFG_ID('Nefit')
MFG_ID_NEFIT.id = 0x006D

MFG_ID_NEOCONTROL_US_LLC = _MFG_ID('NEOCONTROL US LLC')
MFG_ID_NEOCONTROL_US_LLC.id = 0x0351

MFG_ID_NESS_CORPORATION_PTY_LTD = _MFG_ID('Ness Corporation Pty Ltd')
MFG_ID_NESS_CORPORATION_PTY_LTD.id = 0x0189

MFG_ID_NETGEAR = _MFG_ID('Netgear')
MFG_ID_NETGEAR.id = 0x0133

MFG_ID_NEUSTA_NEXT_GMBH_CO_KG = _MFG_ID('neusta next GmbH & Co. KG')
MFG_ID_NEUSTA_NEXT_GMBH_CO_KG.id = 0x0248

MFG_ID_NEWLAND_COMMUNICATION_SCIENCE_TECHNOLOGY_CO_LTD = _MFG_ID('Newland Communication Science Technology Co., Ltd.')
MFG_ID_NEWLAND_COMMUNICATION_SCIENCE_TECHNOLOGY_CO_LTD.id = 0x0203

MFG_ID_NEXA_TRADING_AB = _MFG_ID('Nexa Trading AB')
MFG_ID_NEXA_TRADING_AB.id = 0x0268

MFG_ID_NEXIA_HOME_INTELLIGENCE = _MFG_ID('Nexia Home Intelligence')
MFG_ID_NEXIA_HOME_INTELLIGENCE.id = 0x0178

MFG_ID_NEXTENERGY = _MFG_ID('NextEnergy')
MFG_ID_NEXTENERGY.id = 0x0075

MFG_ID_NHN_ENTERTAINMENT = _MFG_ID('NHN Entertainment')
MFG_ID_NHN_ENTERTAINMENT.id = 0x0361

MFG_ID_NIE_TECHNOLOGY_CO_LTD = _MFG_ID('NIE Technology Co., Ltd')
MFG_ID_NIE_TECHNOLOGY_CO_LTD.id = 0x0312

MFG_ID_NINGBO_SENTEK_ELECTRONICS_CO_LTD = _MFG_ID('Ningbo Sentek Electronics Co., Ltd')
MFG_ID_NINGBO_SENTEK_ELECTRONICS_CO_LTD.id = 0x0185

MFG_ID_NORTEK_SECURITY_CONTROL_LLC = _MFG_ID('Nortek Security & Control LLC')
MFG_ID_NORTEK_SECURITY_CONTROL_LLC.id = 0x014F

MFG_ID_NORTH_CHINA_UNIVERSITY_OF_TECHNOLOGY = _MFG_ID('North China University of Technology')
MFG_ID_NORTH_CHINA_UNIVERSITY_OF_TECHNOLOGY.id = 0x0252

MFG_ID_NORTHQ = _MFG_ID('NorthQ')
MFG_ID_NORTHQ.id = 0x0096

MFG_ID_NOVAR_ELECTRICAL_DEVICES_AND_SYSTEMS_EDS = _MFG_ID('Novar Electrical Devices and Systems (EDS)')
MFG_ID_NOVAR_ELECTRICAL_DEVICES_AND_SYSTEMS_EDS.id = 0x0040

MFG_ID_NOVATEQNI_HK_LTD = _MFG_ID('Novateqni HK Ltd')
MFG_ID_NOVATEQNI_HK_LTD.id = 0x020D

MFG_ID_OBLO_LIVING_LLC = _MFG_ID('OBLO LIVING LLC')
MFG_ID_OBLO_LIVING_LLC.id = 0x0296

MFG_ID_OMNIMA_LIMITED = _MFG_ID('Omnima Limited')
MFG_ID_OMNIMA_LIMITED.id = 0x0119

MFG_ID_ONSITE_PRO = _MFG_ID('OnSite Pro')
MFG_ID_ONSITE_PRO.id = 0x014C

MFG_ID_OPENPEAK_INC = _MFG_ID('OpenPeak Inc.')
MFG_ID_OPENPEAK_INC.id = 0x0041

MFG_ID_OREGON_AUTOMATION = _MFG_ID('Oregon Automation')
MFG_ID_OREGON_AUTOMATION.id = 0x027D

MFG_ID_PANASONIC_ELECTRIC_WORKS_CO_LTD = _MFG_ID('Panasonic Electric Works Co., Ltd.')
MFG_ID_PANASONIC_ELECTRIC_WORKS_CO_LTD.id = 0x0104

MFG_ID_PANASONIC_ES_SHIN_DONGA_CO_LTD = _MFG_ID('Panasonic ES Shin Dong-A Co., Ltd')
MFG_ID_PANASONIC_ES_SHIN_DONGA_CO_LTD.id = 0x031A

MFG_ID_PANODIC_ELECTRIC_SHENZHEN_LIMITED = _MFG_ID('Panodic Electric (Shenzhen) Limited')
MFG_ID_PANODIC_ELECTRIC_SHENZHEN_LIMITED.id = 0x028D

MFG_ID_PARATECH = _MFG_ID('PARATECH')
MFG_ID_PARATECH.id = 0x0257

MFG_ID_PASSIVSYSTEMS_LIMITED = _MFG_ID('PassivSystems Limited')
MFG_ID_PASSIVSYSTEMS_LIMITED.id = 0x0172

MFG_ID_PAXTON_ACCESS_LTD = _MFG_ID('Paxton Access Ltd')
MFG_ID_PAXTON_ACCESS_LTD.id = 0x0322

MFG_ID_PC_PARTNER = _MFG_ID('PC Partner')
MFG_ID_PC_PARTNER.id = 0x0281

MFG_ID_PELLA = _MFG_ID('Pella')
MFG_ID_PELLA.id = 0x013D

MFG_ID_PERMUNDO_GMBH = _MFG_ID('permundo GmbH')
MFG_ID_PERMUNDO_GMBH.id = 0x0245

MFG_ID_PHILIA_TECHNOLOGY_CO_LTD = _MFG_ID('PHILIA TECHNOLOGY Co., Ltd.')
MFG_ID_PHILIA_TECHNOLOGY_CO_LTD.id = 0x0366

MFG_ID_PHILIO_TECHNOLOGY_CORP = _MFG_ID('Philio Technology Corp')
MFG_ID_PHILIO_TECHNOLOGY_CORP.id = 0x013C

MFG_ID_PIXELA_CORPORATION = _MFG_ID('Pixela Corporation')
MFG_ID_PIXELA_CORPORATION.id = 0x0277

MFG_ID_POLYCONTROL = _MFG_ID('Poly-control')
MFG_ID_POLYCONTROL.id = 0x010E

MFG_ID_POPP_CO = _MFG_ID('Popp & Co')
MFG_ID_POPP_CO.id = 0x0154

MFG_ID_POWERHOUSE_DYNAMICS = _MFG_ID('Powerhouse Dynamics')
MFG_ID_POWERHOUSE_DYNAMICS.id = 0x0170

MFG_ID_POWERLINX = _MFG_ID('PowerLinx')
MFG_ID_POWERLINX.id = 0x0074

MFG_ID_POWERLYNX = _MFG_ID('PowerLynx')
MFG_ID_POWERLYNX.id = 0x0016

MFG_ID_PRAGMATIC_CONSULTING_INC = _MFG_ID('Pragmatic Consulting Inc.')
MFG_ID_PRAGMATIC_CONSULTING_INC.id = 0x0042

MFG_ID_PRODEA = _MFG_ID('Prodea')
MFG_ID_PRODEA.id = 0x0341

MFG_ID_PRODRIVE_TECHNOLOGIES = _MFG_ID('Prodrive Technologies')
MFG_ID_PRODRIVE_TECHNOLOGIES.id = 0x0128

MFG_ID_PROMIXIS_LLC = _MFG_ID('Promixis, LLC')
MFG_ID_PROMIXIS_LLC.id = 0x0161

MFG_ID_PULSE_TECHNOLOGIES_ASPALIS = _MFG_ID('Pulse Technologies (Aspalis)')
MFG_ID_PULSE_TECHNOLOGIES_ASPALIS.id = 0x005D

MFG_ID_PYTRONIC_AB = _MFG_ID('Pytronic AB')
MFG_ID_PYTRONIC_AB.id = 0x0376

MFG_ID_QEES = _MFG_ID('Qees')
MFG_ID_QEES.id = 0x0095

MFG_ID_QINGDAO_HONGYU_CLES_AIR_CONDITIONING_CO_LTD = _MFG_ID('Qingdao hongyu cles air conditioning co.,ltd.')
MFG_ID_QINGDAO_HONGYU_CLES_AIR_CONDITIONING_CO_LTD.id = 0x0355

MFG_ID_QOLSYS = _MFG_ID('Qolsys')
MFG_ID_QOLSYS.id = 0x012A

MFG_ID_QUBY = _MFG_ID('Quby')
MFG_ID_QUBY.id = 0x0130

MFG_ID_QUEENLOCK_IND_CO_LTD = _MFG_ID('Queenlock Ind. Co., Ltd.')
MFG_ID_QUEENLOCK_IND_CO_LTD.id = 0x0163

MFG_ID_RADEMACHER_GERATEELEKTRONIK_GMBH_CO_KG = _MFG_ID('Rademacher Ger�te-Elektronik GmbH & Co. KG')
MFG_ID_RADEMACHER_GERATEELEKTRONIK_GMBH_CO_KG.id = 0x0142

MFG_ID_RADIO_THERMOSTAT_COMPANY_OF_AMERICA_RTC = _MFG_ID('Radio Thermostat Company of America (RTC)')
MFG_ID_RADIO_THERMOSTAT_COMPANY_OF_AMERICA_RTC.id = 0x0098

MFG_ID_RAONIX_CO_LTD = _MFG_ID('Raonix Co., Ltd.')
MFG_ID_RAONIX_CO_LTD.id = 0x0314

MFG_ID_RARITAN = _MFG_ID('Raritan')
MFG_ID_RARITAN.id = 0x008E

MFG_ID_RAYLIOS = _MFG_ID('Raylios')
MFG_ID_RAYLIOS.id = 0x0370

MFG_ID_RED_BEE_CO_LTD = _MFG_ID('Red Bee Co. Ltd')
MFG_ID_RED_BEE_CO_LTD.id = 0x021E

MFG_ID_REITZGROUPDE = _MFG_ID('Reitz-Group.de')
MFG_ID_REITZGROUPDE.id = 0x0064

MFG_ID_REMOTE_SOLUTION = _MFG_ID('Remote Solution')
MFG_ID_REMOTE_SOLUTION.id = 0x022C

MFG_ID_REMOTE_TECHNOLOGIES_INCORPORATED = _MFG_ID('Remote Technologies Incorporated')
MFG_ID_REMOTE_TECHNOLOGIES_INCORPORATED.id = 0x0255

MFG_ID_REMOTEC = _MFG_ID('Remotec')
MFG_ID_REMOTEC.id = 0x5254

MFG_ID_REPLY_SPA = _MFG_ID('Reply S.p.A.')
MFG_ID_REPLY_SPA.id = 0x039B

MFG_ID_RESIDENTIAL_CONTROL_SYSTEMS_INC_RCS = _MFG_ID('Residential Control Systems, Inc. (RCS)')
MFG_ID_RESIDENTIAL_CONTROL_SYSTEMS_INC_RCS.id = 0x0010

MFG_ID_RET_NANJING_INTELLIGENCE_SYSTEM_CO_LTD = _MFG_ID('RET Nanjing Intelligence System CO.,Ltd')
MFG_ID_RET_NANJING_INTELLIGENCE_SYSTEM_CO_LTD.id = 0x0216

MFG_ID_REVOLV_INC = _MFG_ID('Revolv Inc')
MFG_ID_REVOLV_INC.id = 0x0153

MFG_ID_RIMPORT_LTD = _MFG_ID('R-import Ltd.')
MFG_ID_RIMPORT_LTD.id = 0x0147

MFG_ID_RISCO_GROUP = _MFG_ID('RISCO Group')
MFG_ID_RISCO_GROUP.id = 0x035E

MFG_ID_ROCCONNECT_INC = _MFG_ID('ROC-Connect, Inc.')
MFG_ID_ROCCONNECT_INC.id = 0x023B

MFG_ID_RPE_AJAX_LLC_DBS_SECUR_LTD = _MFG_ID('RPE Ajax LLC (dbs Secur Ltd)')
MFG_ID_RPE_AJAX_LLC_DBS_SECUR_LTD.id = 0x0197

MFG_ID_RS_SCENE_AUTOMATION = _MFG_ID('RS Scene Automation')
MFG_ID_RS_SCENE_AUTOMATION.id = 0x0065

MFG_ID_RUBETEK = _MFG_ID('Rubetek')
MFG_ID_RUBETEK.id = 0x029D

MFG_ID_S1 = _MFG_ID('S1')
MFG_ID_S1.id = 0x0290

MFG_ID_SAFETECH_PRODUCTS = _MFG_ID('SafeTech Products')
MFG_ID_SAFETECH_PRODUCTS.id = 0x023C

MFG_ID_SAMSUNG_ELECTRONICS_CO_LTD = _MFG_ID('Samsung Electronics Co., Ltd.')
MFG_ID_SAMSUNG_ELECTRONICS_CO_LTD.id = 0x0201

MFG_ID_SAMSUNG_SDS = _MFG_ID('Samsung SDS')
MFG_ID_SAMSUNG_SDS.id = 0x022E

MFG_ID_SAN_SHIH_ELECTRICAL_ENTERPRISE_CO_LTD = _MFG_ID('San Shih Electrical Enterprise Co., Ltd.')
MFG_ID_SAN_SHIH_ELECTRICAL_ENTERPRISE_CO_LTD.id = 0x0093

MFG_ID_SANAV = _MFG_ID('SANAV')
MFG_ID_SANAV.id = 0x012C

MFG_ID_SATCO_PRODUCTS_INC = _MFG_ID('SATCO Products, Inc.')
MFG_ID_SATCO_PRODUCTS_INC.id = 0x0307

MFG_ID_SBCK_CORP = _MFG_ID('SBCK Corp.')
MFG_ID_SBCK_CORP.id = 0x0318

MFG_ID_SCIENTIA_TECHNOLOGIES_INC = _MFG_ID('Scientia Technologies, Inc.')
MFG_ID_SCIENTIA_TECHNOLOGIES_INC.id = 0x001F

MFG_ID_SCOUT_ALARM = _MFG_ID('Scout Alarm')
MFG_ID_SCOUT_ALARM.id = 0x029A

MFG_ID_SECURE_METERS_UK_LTD = _MFG_ID('Secure Meters (UK) Ltd')
MFG_ID_SECURE_METERS_UK_LTD.id = 0x0059

MFG_ID_SECURE_WIRELESS = _MFG_ID('Secure Wireless')
MFG_ID_SECURE_WIRELESS.id = 0x011E

MFG_ID_SECURENET_TECHNOLOGIES = _MFG_ID('SecureNet Technologies')
MFG_ID_SECURENET_TECHNOLOGIES.id = 0x0167

MFG_ID_SECURIFI_LTD = _MFG_ID('Securifi Ltd.')
MFG_ID_SECURIFI_LTD.id = 0x0182

MFG_ID_SELUXIT = _MFG_ID('Seluxit')
MFG_ID_SELUXIT.id = 0x0069

MFG_ID_SENMATIC_AS = _MFG_ID('Senmatic A/S')
MFG_ID_SENMATIC_AS.id = 0x0043

MFG_ID_SENSATIVE_AB = _MFG_ID('Sensative AB')
MFG_ID_SENSATIVE_AB.id = 0x019A

MFG_ID_SEQUOIA_TECHNOLOGY_LTD = _MFG_ID('Sequoia Technology LTD')
MFG_ID_SEQUOIA_TECHNOLOGY_LTD.id = 0x0044

MFG_ID_SERCOMM_CORP = _MFG_ID('Sercomm Corp')
MFG_ID_SERCOMM_CORP.id = 0x0151

MFG_ID_SHANDONG_BITTEL_INTELLIGENT_TECHNOLOGY_CO_LTD = _MFG_ID('Shandong Bittel Intelligent Technology Co., Ltd')
MFG_ID_SHANDONG_BITTEL_INTELLIGENT_TECHNOLOGY_CO_LTD.id = 0x0378

MFG_ID_SHANDONG_SMART_LIFE_DATA_SYSTEM_CO_LTD = _MFG_ID('Shandong Smart Life Data System Co .LTD')
MFG_ID_SHANDONG_SMART_LIFE_DATA_SYSTEM_CO_LTD.id = 0x030B

MFG_ID_SHANGDONG_SMART_LIFE_DATA_SYSTEM_CO_LTD = _MFG_ID('Shangdong Smart Life Data System Co.,Ltd')
MFG_ID_SHANGDONG_SMART_LIFE_DATA_SYSTEM_CO_LTD.id = 0x0215

MFG_ID_SHANGHAI_DORLINK_INTELLIGENT_TECHNOLOGIES_CO_LTD = _MFG_ID('Shanghai Dorlink Intelligent Technologies Co.,Ltd')
MFG_ID_SHANGHAI_DORLINK_INTELLIGENT_TECHNOLOGIES_CO_LTD.id = 0x023E

MFG_ID_SHANGHAI_LONGCHUANG_ECOENERGY_SYSTEMS_CO_LTD = _MFG_ID('Shanghai Longchuang Eco-energy Systems Co., Ltd')
MFG_ID_SHANGHAI_LONGCHUANG_ECOENERGY_SYSTEMS_CO_LTD.id = 0x0205

MFG_ID_SHARP = _MFG_ID('Sharp')
MFG_ID_SHARP.id = 0x010B

MFG_ID_SHENZHEN_3NOD_ACOUSTICLINK_CO_LTD = _MFG_ID('Shenzhen 3nod Acousticlink Co., LTD')
MFG_ID_SHENZHEN_3NOD_ACOUSTICLINK_CO_LTD.id = 0x0357

MFG_ID_SHENZHEN_AOYA_INDUSTRY_CO_LTD = _MFG_ID('SHENZHEN AOYA INDUSTRY CO. LTD')
MFG_ID_SHENZHEN_AOYA_INDUSTRY_CO_LTD.id = 0x021A

MFG_ID_SHENZHEN_EASYHOME_TECHNOLOGY_CO_LTD = _MFG_ID('Shenzhen Easyhome Technology Co., Ltd.')
MFG_ID_SHENZHEN_EASYHOME_TECHNOLOGY_CO_LTD.id = 0x0286

MFG_ID_SHENZHEN_ISURPASS_TECHNOLOGY_CO_LTD = _MFG_ID('Shenzhen iSurpass Technology Co. ,Ltd')
MFG_ID_SHENZHEN_ISURPASS_TECHNOLOGY_CO_LTD.id = 0x021C

MFG_ID_SHENZHEN_JBT_SMART_LIGHTING_CO_LTD = _MFG_ID('Shenzhen JBT Smart Lighting Co., Ltd')
MFG_ID_SHENZHEN_JBT_SMART_LIGHTING_CO_LTD.id = 0x037A

MFG_ID_SHENZHEN_KAADAS_INTELLIGENT_TECHNOLOGY_CO_LTD = _MFG_ID('Shenzhen Kaadas Intelligent Technology Co., Ltd')
MFG_ID_SHENZHEN_KAADAS_INTELLIGENT_TECHNOLOGY_CO_LTD.id = 0x021D

MFG_ID_SHENZHEN_LIAO_WANG_TONG_DA_TECHNOLOGY_LTD = _MFG_ID('Shenzhen Liao Wang Tong Da Technology Ltd')
MFG_ID_SHENZHEN_LIAO_WANG_TONG_DA_TECHNOLOGY_LTD.id = 0x0211

MFG_ID_SHENZHEN_NEO_ELECTRONICS_CO_LTD = _MFG_ID('Shenzhen Neo Electronics Co., Ltd')
MFG_ID_SHENZHEN_NEO_ELECTRONICS_CO_LTD.id = 0x0258

MFG_ID_SHENZHEN_SEN5_TECHNOLOGY_CO_LTD = _MFG_ID('Shenzhen Sen5 Technology Co., Ltd.')
MFG_ID_SHENZHEN_SEN5_TECHNOLOGY_CO_LTD.id = 0x036C

MFG_ID_SHENZHEN_THINGSVIEW_TECH = _MFG_ID('Shenzhen Thingsview Tech')
MFG_ID_SHENZHEN_THINGSVIEW_TECH.id = 0x0381

MFG_ID_SHENZHEN_TRIPATH_DIGITAL_AUDIO_EQUIPMENT_CO_LTD = _MFG_ID('Shenzhen Tripath Digital Audio Equipment Co.,Ltd')
MFG_ID_SHENZHEN_TRIPATH_DIGITAL_AUDIO_EQUIPMENT_CO_LTD.id = 0x0250

MFG_ID_SHENZHEN_ZHIQU_TECHNOLOGY_LIMITED = _MFG_ID('Shenzhen ZHIQU Technology Limited')
MFG_ID_SHENZHEN_ZHIQU_TECHNOLOGY_LIMITED.id = 0x0356

MFG_ID_SHENZHEN_HEIMAN_TECHNOLOGY_CO_LTD = _MFG_ID('Shenzhen Heiman Technology Co., Ltd')
MFG_ID_SHENZHEN_HEIMAN_TECHNOLOGY_CO_LTD.id = 0x0260

MFG_ID_SHENZHEN_SAYKEY_TECHNOLOGY_CO_LTD = _MFG_ID('Shenzhen Saykey Technology Co., Ltd')
MFG_ID_SHENZHEN_SAYKEY_TECHNOLOGY_CO_LTD.id = 0x032C

MFG_ID_SIEGENIAAUBI_KG = _MFG_ID('SIEGENIA-AUBI KG')
MFG_ID_SIEGENIAAUBI_KG.id = 0x0081

MFG_ID_ZWAVE = _MFG_ID('Z-Wave')
MFG_ID_ZWAVE.id = 0x0000

MFG_ID_SIMONTECH_SLU = _MFG_ID('SimonTech S.L.U')
MFG_ID_SIMONTECH_SLU.id = 0x0267

MFG_ID_SINE_WIRELESS = _MFG_ID('Sine Wireless')
MFG_ID_SINE_WIRELESS.id = 0x0045

MFG_ID_SITERWELL_TECHNOLOGY_HK_CO_LTD = _MFG_ID('Siterwell Technology HK Co., LTD')
MFG_ID_SITERWELL_TECHNOLOGY_HK_CO_LTD.id = 0x0266

MFG_ID_SMART_ELECTRONIC_INDUSTRIAL_DONGGUAN_CO_LIMITED = _MFG_ID('Smart Electronic Industrial (Dongguan) Co., Limited')
MFG_ID_SMART_ELECTRONIC_INDUSTRIAL_DONGGUAN_CO_LIMITED.id = 0x0282

MFG_ID_SMART_PRODUCTS_INC = _MFG_ID('Smart Products, Inc.')
MFG_ID_SMART_PRODUCTS_INC.id = 0x0046

MFG_ID_SMARTALL_INC = _MFG_ID('SmartAll Inc.')
MFG_ID_SMARTALL_INC.id = 0x026A

MFG_ID_SMARTHOME_PARTNER_GMBH = _MFG_ID('SmartHome Partner GmbH')
MFG_ID_SMARTHOME_PARTNER_GMBH.id = 0x0323

MFG_ID_SMARTLY_AS = _MFG_ID('Smartly AS')
MFG_ID_SMARTLY_AS.id = 0x024F

MFG_ID_SMARTTHINGS_INC = _MFG_ID('SmartThings, Inc.')
MFG_ID_SMARTTHINGS_INC.id = 0x0150

MFG_ID_SMK_MANUFACTURING_INC = _MFG_ID('SMK Manufacturing Inc.')
MFG_ID_SMK_MANUFACTURING_INC.id = 0x0102

MFG_ID_SOFTATHOME = _MFG_ID('SoftAtHome')
MFG_ID_SOFTATHOME.id = 0x029C

MFG_ID_SOMFY = _MFG_ID('Somfy')
MFG_ID_SOMFY.id = 0x0047

MFG_ID_SONG_JIANG_YUNAN_TECHNOLOGY_CO_LTD = _MFG_ID('SONG JIANG YUN-AN TECHNOLOGY CO., LTD.')
MFG_ID_SONG_JIANG_YUNAN_TECHNOLOGY_CO_LTD.id = 0x0394

MFG_ID_SOOSAN_HOMETECH = _MFG_ID('Soosan Hometech')
MFG_ID_SOOSAN_HOMETECH.id = 0x0274

MFG_ID_SOREL_GMBH = _MFG_ID('SOREL GmbH')
MFG_ID_SOREL_GMBH.id = 0x035A

MFG_ID_SPECTRUM_BRANDS = _MFG_ID('Spectrum Brands')
MFG_ID_SPECTRUM_BRANDS.id = 0x0090

MFG_ID_SPRINGS_WINDOW_FASHIONS = _MFG_ID('Springs Window Fashions')
MFG_ID_SPRINGS_WINDOW_FASHIONS.id = 0x026E

MFG_ID_SPRUE_SAFETY_PRODUCTS_LTD = _MFG_ID('Sprue Safety Products Ltd')
MFG_ID_SPRUE_SAFETY_PRODUCTS_LTD.id = 0x026F

MFG_ID_SQUARE_CONNECT = _MFG_ID('Square Connect')
MFG_ID_SQUARE_CONNECT.id = 0x0124

MFG_ID_STT_ELECTRIC_CORPORATION = _MFG_ID('ST&T Electric Corporation')
MFG_ID_STT_ELECTRIC_CORPORATION.id = 0x021B

MFG_ID_STAR_AUTOMATION = _MFG_ID('Star Automation')
MFG_ID_STAR_AUTOMATION.id = 0x0358

MFG_ID_STARKOFF = _MFG_ID('Starkoff')
MFG_ID_STARKOFF.id = 0x0259

MFG_ID_STARVEDIA = _MFG_ID('StarVedia')
MFG_ID_STARVEDIA.id = 0x0265

MFG_ID_STEINEL_GMBH = _MFG_ID('STEINEL GmbH')
MFG_ID_STEINEL_GMBH.id = 0x0271

MFG_ID_STELPRO = _MFG_ID('Stelpro')
MFG_ID_STELPRO.id = 0x0239

MFG_ID_STRATTEC_ADVANCED_LOGIC_LLC = _MFG_ID('Strattec Advanced Logic,LLC')
MFG_ID_STRATTEC_ADVANCED_LOGIC_LLC.id = 0x0217

MFG_ID_STRATTEC_SECURITY_CORPORATION = _MFG_ID('STRATTEC Security Corporation')
MFG_ID_STRATTEC_SECURITY_CORPORATION.id = 0x0168

MFG_ID_SUMITOMO = _MFG_ID('Sumitomo')
MFG_ID_SUMITOMO.id = 0x0105

MFG_ID_SUNJET_COMPONENTS_CORP = _MFG_ID('Sunjet Components Corp.')
MFG_ID_SUNJET_COMPONENTS_CORP.id = 0x028B

MFG_ID_SUPERNA = _MFG_ID('Superna')
MFG_ID_SUPERNA.id = 0x0054

MFG_ID_SWANN_COMMUNICATIONS_PTY_LTD = _MFG_ID('Swann Communications Pty Ltd')
MFG_ID_SWANN_COMMUNICATIONS_PTY_LTD.id = 0x0191

MFG_ID_SWYCS = _MFG_ID('SWYCS')
MFG_ID_SWYCS.id = 0x0339

MFG_ID_SYLVANIA = _MFG_ID('Sylvania')
MFG_ID_SYLVANIA.id = 0x0009

MFG_ID_SYSTECH_CORPORATION = _MFG_ID('Systech Corporation')
MFG_ID_SYSTECH_CORPORATION.id = 0x0136

MFG_ID_SYSTEMAIR_SVERIGE_AB = _MFG_ID('Systemair Sverige AB')
MFG_ID_SYSTEMAIR_SVERIGE_AB.id = 0x0276

MFG_ID_TW_SHENZHEN_GONGJIN_ELECTRONICS_CO_LTD = _MFG_ID('T&W(SHENZHEN GONGJIN ELECTRONICS CO.,LTD)')
MFG_ID_TW_SHENZHEN_GONGJIN_ELECTRONICS_CO_LTD.id = 0x0375

MFG_ID_TAEWON_LIGHTING_CO_LTD = _MFG_ID('TAEWON Lighting Co., Ltd.')
MFG_ID_TAEWON_LIGHTING_CO_LTD.id = 0x0235

MFG_ID_TAIWAN_FU_HSING_INDUSTRIAL_CO_LTD = _MFG_ID('Taiwan Fu Hsing Industrial Co., Ltd.')
MFG_ID_TAIWAN_FU_HSING_INDUSTRIAL_CO_LTD.id = 0x0262

MFG_ID_TAIWAN_ICATCH_INC = _MFG_ID('Taiwan iCATCH Inc.')
MFG_ID_TAIWAN_ICATCH_INC.id = 0x0264

MFG_ID_TEAM_DIGITAL_LIMITED = _MFG_ID('Team Digital Limited')
MFG_ID_TEAM_DIGITAL_LIMITED.id = 0x0186

MFG_ID_TEAM_PRECISION_PCL = _MFG_ID('Team Precision PCL')
MFG_ID_TEAM_PRECISION_PCL.id = 0x0089

MFG_ID_TECHNICOLOR = _MFG_ID('Technicolor')
MFG_ID_TECHNICOLOR.id = 0x0240

MFG_ID_TECHNIKU = _MFG_ID('Techniku')
MFG_ID_TECHNIKU.id = 0x000A

MFG_ID_TECOM_CO_LTD = _MFG_ID('Tecom Co., Ltd.')
MFG_ID_TECOM_CO_LTD.id = 0x012F

MFG_ID_TELL_IT_ONLINE = _MFG_ID('Tell It Online')
MFG_ID_TELL_IT_ONLINE.id = 0x0012

MFG_ID_TELLDUS_TECHNOLOGIES_AB = _MFG_ID('Telldus Technologies AB')
MFG_ID_TELLDUS_TECHNOLOGIES_AB.id = 0x0176

MFG_ID_TELSEY = _MFG_ID('Telsey')
MFG_ID_TELSEY.id = 0x0048

MFG_ID_TELULAR = _MFG_ID('Telular')
MFG_ID_TELULAR.id = 0x017E

MFG_ID_TEPTRON_AB = _MFG_ID('Teptron AB')
MFG_ID_TEPTRON_AB.id = 0x0397

MFG_ID_TERRA_OPTIMA_BV_PRIMAIR_SERVICES = _MFG_ID('Terra Optima B.V. (tidligere Primair Services)')
MFG_ID_TERRA_OPTIMA_BV_PRIMAIR_SERVICES.id = 0x005C

MFG_ID_THERE_CORPORATION = _MFG_ID('There Corporation')
MFG_ID_THERE_CORPORATION.id = 0x010C

MFG_ID_THERMOFLOOR = _MFG_ID('ThermoFloor')
MFG_ID_THERMOFLOOR.id = 0x019B

MFG_ID_THINK_SIMPLE_SRL = _MFG_ID('Think Simple srl')
MFG_ID_THINK_SIMPLE_SRL.id = 0x0317

MFG_ID_TIMEVALVE_INC = _MFG_ID('TIMEVALVE, Inc.')
MFG_ID_TIMEVALVE_INC.id = 0x022A

MFG_ID_TINGCORE_AB_INFO24_AB = _MFG_ID('Tingcore AB  (Info24 AB)')
MFG_ID_TINGCORE_AB_INFO24_AB.id = 0x033B

MFG_ID_TKB_HOME = _MFG_ID('TKB Home')
MFG_ID_TKB_HOME.id = 0x0118

MFG_ID_TKH_GROUP_EMINENT = _MFG_ID('TKH Group / Eminent')
MFG_ID_TKH_GROUP_EMINENT.id = 0x011C

MFG_ID_TMC_TECHNOLOGY_LTD = _MFG_ID('TMC Technology Ltd.')
MFG_ID_TMC_TECHNOLOGY_LTD.id = 0x0327

MFG_ID_TOLEDO_CO_INC = _MFG_ID('Toledo & Co., Inc.')
MFG_ID_TOLEDO_CO_INC.id = 0x0319

MFG_ID_TONG_LUNG_METAL_INDUSTRY_CO_LTD = _MFG_ID('TONG LUNG METAL INDUSTRY CO., LTD.')
MFG_ID_TONG_LUNG_METAL_INDUSTRY_CO_LTD.id = 0x034F

MFG_ID_TOSHIBA_VISUAL_SOLUTION = _MFG_ID('Toshiba Visual Solution')
MFG_ID_TOSHIBA_VISUAL_SOLUTION.id = 0x0333

MFG_ID_TPLINK_TECHNOLOGIES_CO_LTD = _MFG_ID('TP-Link Technologies Co., Ltd.')
MFG_ID_TPLINK_TECHNOLOGIES_CO_LTD.id = 0x0283

MFG_ID_TRANE_CORPORATION = _MFG_ID('Trane Corporation')
MFG_ID_TRANE_CORPORATION.id = 0x008B

MFG_ID_TRICKLESTAR = _MFG_ID('TrickleStar')
MFG_ID_TRICKLESTAR.id = 0x0066

MFG_ID_TRICKLESTAR_LTD_EMPOWER_CONTROLS_LTD = _MFG_ID('Tricklestar Ltd. (former Empower Controls Ltd.)')
MFG_ID_TRICKLESTAR_LTD_EMPOWER_CONTROLS_LTD.id = 0x006B

MFG_ID_TRIDIUM = _MFG_ID('Tridium')
MFG_ID_TRIDIUM.id = 0x0055

MFG_ID_TRONICO_TECHNOLOGY_CO_LTD = _MFG_ID('Tronico Technology Co. Ltd.')
MFG_ID_TRONICO_TECHNOLOGY_CO_LTD.id = 0x0111

MFG_ID_TWISTHINK = _MFG_ID('Twisthink')
MFG_ID_TWISTHINK.id = 0x0049

MFG_ID_UBITECH = _MFG_ID('Ubitech')
MFG_ID_UBITECH.id = 0x0270

MFG_ID_UFAIRY_GR_TECH = _MFG_ID('UFairy G.R. Tech')
MFG_ID_UFAIRY_GR_TECH.id = 0x0152

MFG_ID_UNIVERSAL_DEVICES_INC = _MFG_ID('Universal Devices, Inc')
MFG_ID_UNIVERSAL_DEVICES_INC.id = 0x0193

MFG_ID_UNIVERSAL_ELECTRONICS_INC = _MFG_ID('Universal Electronics Inc.')
MFG_ID_UNIVERSAL_ELECTRONICS_INC.id = 0x0020

MFG_ID_UNIVERSE_FUTURE = _MFG_ID('Universe Future')
MFG_ID_UNIVERSE_FUTURE.id = 0x0183

MFG_ID_UTC_FIRE_AND_SECURITY_AMERICAS_CORP = _MFG_ID('UTC Fire and Security Americas Corp')
MFG_ID_UTC_FIRE_AND_SECURITY_AMERICAS_CORP.id = 0x0209

MFG_ID_VATES = _MFG_ID('Vates')
MFG_ID_VATES.id = 0x0388

MFG_ID_VDA = _MFG_ID('VDA')
MFG_ID_VDA.id = 0x010A

MFG_ID_VEMMIO = _MFG_ID('Vemmio')
MFG_ID_VEMMIO.id = 0x030F

MFG_ID_VENSTAR_INC = _MFG_ID('Venstar Inc.')
MFG_ID_VENSTAR_INC.id = 0x0198

MFG_ID_VERA_CONTROL = _MFG_ID('Vera Control')
MFG_ID_VERA_CONTROL.id = 0x008C

MFG_ID_VERO_DUCO = _MFG_ID('Vero Duco')
MFG_ID_VERO_DUCO.id = 0x0080

MFG_ID_VESTEL_ELEKTRONIK_TICARET_VE_SANAYI_AS = _MFG_ID('Vestel Elektronik Ticaret ve Sanayi A.S.')
MFG_ID_VESTEL_ELEKTRONIK_TICARET_VE_SANAYI_AS.id = 0x0237

MFG_ID_VIEWSONIC = _MFG_ID('Viewsonic')
MFG_ID_VIEWSONIC.id = 0x0053

MFG_ID_VIEWSONIC_CORPORATION = _MFG_ID('ViewSonic Corporation')
MFG_ID_VIEWSONIC_CORPORATION.id = 0x005E

MFG_ID_VIMAR_CRS = _MFG_ID('Vimar CRS')
MFG_ID_VIMAR_CRS.id = 0x0007

MFG_ID_VIPASTAR = _MFG_ID('Vipa-Star')
MFG_ID_VIPASTAR.id = 0x0188

MFG_ID_VISION_SECURITY = _MFG_ID('Vision Security')
MFG_ID_VISION_SECURITY.id = 0x0109

MFG_ID_VISUALIZE = _MFG_ID('Visualize')
MFG_ID_VISUALIZE.id = 0x004A

MFG_ID_VITELEC = _MFG_ID('Vitelec')
MFG_ID_VITELEC.id = 0x0058

MFG_ID_VIVA_LABS_AS = _MFG_ID('Viva Labs AS')
MFG_ID_VIVA_LABS_AS.id = 0x0263

MFG_ID_VIVINT = _MFG_ID('Vivint')
MFG_ID_VIVINT.id = 0x0156

MFG_ID_VSSAFETY_AS = _MFG_ID('Vs-Safety AS')
MFG_ID_VSSAFETY_AS.id = 0x017B

MFG_ID_WATT_STOPPER = _MFG_ID('Watt Stopper')
MFG_ID_WATT_STOPPER.id = 0x004B

MFG_ID_WAYNE_DALTON = _MFG_ID('Wayne Dalton')
MFG_ID_WAYNE_DALTON.id = 0x0008

MFG_ID_WEBEE_LIFE = _MFG_ID('Webee Life')
MFG_ID_WEBEE_LIFE.id = 0x019F

MFG_ID_WEBEHOME_AB = _MFG_ID('WeBeHome AB')
MFG_ID_WEBEHOME_AB.id = 0x0171

MFG_ID_WENZHOU_MTLC_ELECTRIC_APPLIANCES_CO_LTD = _MFG_ID('Wenzhou MTLC Electric Appliances Co.,Ltd.')
MFG_ID_WENZHOU_MTLC_ELECTRIC_APPLIANCES_CO_LTD.id = 0x011A

MFG_ID_WESTCONTROL_AS = _MFG_ID('Westcontrol AS')
MFG_ID_WESTCONTROL_AS.id = 0x026C

MFG_ID_WHIRLPOOL = _MFG_ID('Whirlpool')
MFG_ID_WHIRLPOOL.id = 0x0057

MFG_ID_WHITE_RABBIT = _MFG_ID('White Rabbit')
MFG_ID_WHITE_RABBIT.id = 0x027B

MFG_ID_WIDOM = _MFG_ID('wiDom')
MFG_ID_WIDOM.id = 0x0149

MFG_ID_WILLIS_ELECTRIC_CO_LTD = _MFG_ID('Willis Electric Co., Ltd.')
MFG_ID_WILLIS_ELECTRIC_CO_LTD.id = 0x015D

MFG_ID_WILSHINE_HOLDING_CO_LTD = _MFG_ID('Wilshine Holding Co., Ltd')
MFG_ID_WILSHINE_HOLDING_CO_LTD.id = 0x012D

MFG_ID_WINK_INC = _MFG_ID('Wink Inc.')
MFG_ID_WINK_INC.id = 0x017F

MFG_ID_WINTOP = _MFG_ID('Wintop')
MFG_ID_WINTOP.id = 0x0097

MFG_ID_WINYTECHNOLOGY = _MFG_ID('Winytechnology')
MFG_ID_WINYTECHNOLOGY.id = 0x0242

MFG_ID_WIRELESS_MAINGATE_AB = _MFG_ID('Wireless Maingate AB')
MFG_ID_WIRELESS_MAINGATE_AB.id = 0x0199

MFG_ID_WOODWARD_LABS = _MFG_ID('Woodward Labs')
MFG_ID_WOODWARD_LABS.id = 0x004C

MFG_ID_WOOREE_LIGHTING_CO_LTD = _MFG_ID('WOOREE Lighting Co.,Ltd.')
MFG_ID_WOOREE_LIGHTING_CO_LTD.id = 0x0269

MFG_ID_WRAP = _MFG_ID('Wr@p')
MFG_ID_WRAP.id = 0x0003

MFG_ID_WRT_INTELLIGENT_TECHNOLOGY_CO_LTD = _MFG_ID('WRT Intelligent Technology CO., LTD.')
MFG_ID_WRT_INTELLIGENT_TECHNOLOGY_CO_LTD.id = 0x022F

MFG_ID_WUHAN_NWD_TECHNOLOGY_CO_LTD = _MFG_ID('Wuhan NWD Technology Co., Ltd.')
MFG_ID_WUHAN_NWD_TECHNOLOGY_CO_LTD.id = 0x012E

MFG_ID_XANBOO = _MFG_ID('Xanboo')
MFG_ID_XANBOO.id = 0x004D

MFG_ID_XIAMEN_ACTEC_ELECTRONICS_CO_LTD = _MFG_ID('Xiamen AcTEC Electronics Co., Ltd.')
MFG_ID_XIAMEN_ACTEC_ELECTRONICS_CO_LTD.id = 0x037D

MFG_ID_ZCONNECT = _MFG_ID('zConnect')
MFG_ID_ZCONNECT.id = 0x024E

MFG_ID_ZDATA_LLC = _MFG_ID('Zdata, LLC.')
MFG_ID_ZDATA_LLC.id = 0x004E

MFG_ID_ZHEJIANG_JIUXING_ELECTRIC_CO_LTD = _MFG_ID('Zhejiang Jiuxing Electric Co Ltd')
MFG_ID_ZHEJIANG_JIUXING_ELECTRIC_CO_LTD.id = 0x016F

MFG_ID_ZINNO = _MFG_ID('Zinno')
MFG_ID_ZINNO.id = 0x036E

MFG_ID_ZIPATO = _MFG_ID('Zipato')
MFG_ID_ZIPATO.id = 0x0131

MFG_ID_ZONOFF = _MFG_ID('Zonoff')
MFG_ID_ZONOFF.id = 0x0120

MFG_ID_ZOOZ = _MFG_ID('Zooz')
MFG_ID_ZOOZ.id = 0x027A

MFG_ID_ZWAVE_ALLIANCE = _MFG_ID('Z-Wave Alliance')
MFG_ID_ZWAVE_ALLIANCE.id = 0x031D

MFG_ID_ZWAVE_TECHNOLOGIA = _MFG_ID('Z-Wave Technologia')
MFG_ID_ZWAVE_TECHNOLOGIA.id = 0x004F

MFG_ID_ZWAVEME = _MFG_ID('Z-Wave.Me')
MFG_ID_ZWAVEME.id = 0x0115

MFG_ID_ZWAVEPRODUCTSCOM = _MFG_ID('zwaveproducts.com')
MFG_ID_ZWAVEPRODUCTSCOM.id = 0x0315

MFG_ID_ZWORKS_INC = _MFG_ID('Z-works Inc.')
MFG_ID_ZWORKS_INC.id = 0x024D

MFG_ID_ZYKRONIX = _MFG_ID('Zykronix')
MFG_ID_ZYKRONIX.id = 0x0021

MFG_ID_ZYXEL = _MFG_ID('ZyXEL')
MFG_ID_ZYXEL.id = 0x0135


def MFG_ID(id_):
    for value in globals().values():
        if isinstance(value, _MFG_ID) and value == id_:
            return value

    return MFG_ID_NOT_DEFINED
