
from . import CommandClass, CommandClassCommands


# Association Group Information (AGI) Command Class
# Management
# ==============================

class ASSOCIATION_GRP_INFO_V1_COMMANDS(CommandClassCommands):
    version = 0x01
    NAME_GET = 0x01
    NAME_REPORT = 0x02
    INFO_GET = 0x03
    INFO_REPORT = 0x04
    COMMAND_LIST_GET = 0x05
    COMMAND_LIST_REPORT = 0x06

    INFO_REPORT_VALUES = [

    ]
    GET_VALUES = []
    REPORT_VALUES = []


class COMMAND_CLASS_ASSOCIATION_GRP_INFO(CommandClass):
    id = 0x59
    versions = [
        ASSOCIATION_GRP_INFO_V1_COMMANDS
    ]

# Values used for Association Group Info Get command
ASSOCIATION_GROUP_INFO_GET_PROPERTIES1_RESERVED_MASK = 0x3F
ASSOCIATION_GROUP_INFO_GET_PROPERTIES1_LIST_MODE_BIT_MASK = 0x40
ASSOCIATION_GROUP_INFO_GET_PROPERTIES1_REFRESH_CACHE_BIT_MASK = 0x80
# Values used for Association Group Info Report command
ASSOCIATION_GROUP_INFO_REPORT_PROPERTIES1_GROUP_COUNT_MASK = 0x3F
ASSOCIATION_GROUP_INFO_REPORT_PROPERTIES1_DYNAMIC_INFO_BIT_MASK = 0x40
ASSOCIATION_GROUP_INFO_REPORT_PROPERTIES1_LIST_MODE_BIT_MASK = 0x80

ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_GENERAL = 0x00
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_CONTROL = 0x20
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_SENSOR = 0x31
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_NOTIFICATION = 0x71
ASSOCIATION_GROUP_INFO_REPORT_AGI_GENERAL_NA = 0x00
ASSOCIATION_GROUP_INFO_REPORT_AGI_GENERAL_LIFELINE = 0x01
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY01 = 0x01
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY02 = 0x02
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY03 = 0x03
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY04 = 0x04
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY05 = 0x05
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY06 = 0x06
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY07 = 0x07
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY08 = 0x08
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY09 = 0x09
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY10 = 0x0A
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY11 = 0x0B
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY12 = 0x0C
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY13 = 0x0D
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY14 = 0x0E
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY15 = 0x0F
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY16 = 0x10
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY17 = 0x11
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY18 = 0x12
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY19 = 0x13
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY20 = 0x14
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY21 = 0x15
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY22 = 0x16
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY23 = 0x17
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY24 = 0x18
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY25 = 0x19
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY26 = 0x1A
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY27 = 0x1B
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY28 = 0x1C
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY29 = 0x1D
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY30 = 0x1E
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY31 = 0x1F
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY32 = 0x20
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_SMOKE_ALARM = 0x01
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_C0_ALARM = 0x02
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_CO2_ALARM = 0x03
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_HEAT_ALARM = 0x04
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_WATER_ALARM = 0x05
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_ACCESS_CONTROL = 0x06
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_HOME_SECURITY = 0x07
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_POWER_MANAGEMENT = 0x08
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_SYSTEM = 0x09
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_EMERGENCY_ALARM = 0x0A
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_CLOCK = 0x0B
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_APPLIANCE = 0x0C
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_HOME_HEALTH = 0x0D
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_SIREN = 0x0E
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_WATER_VALVE = 0x0F
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_WEATHER_ALARM = 0x10
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_IRRIGATION = 0x11
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_GAS_ALARM = 0x12
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_PEST_CONTROL = 0x13
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_LIGHT_SENSOR = 0x14
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_WATER_QUALITY_MONITORING = 0x15
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_HOME_MONITORING = 0x16
# Values used for Association Group Command List Get command
ASSOCIATION_GROUP_COMMAND_LIST_GET_PROPERTIES1_RESERVED_MASK = 0x7F
ASSOCIATION_GROUP_COMMAND_LIST_GET_PROPERTIES1_ALLOW_CACHE_BIT_MASK = 0x80

ASSOCIATION_GRP_INFO_VERSION_V2 = 0x02
ASSOCIATION_GROUP_NAME_GET_V2 = 0x01
ASSOCIATION_GROUP_NAME_REPORT_V2 = 0x02
ASSOCIATION_GROUP_INFO_GET_V2 = 0x03
ASSOCIATION_GROUP_INFO_REPORT_V2 = 0x04
ASSOCIATION_GROUP_COMMAND_LIST_GET_V2 = 0x05
ASSOCIATION_GROUP_COMMAND_LIST_REPORT_V2 = 0x06
# Values used for Association Group Info Get command
ASSOCIATION_GROUP_INFO_GET_PROPERTIES1_RESERVED_MASK_V2 = 0x3F
ASSOCIATION_GROUP_INFO_GET_PROPERTIES1_LIST_MODE_BIT_MASK_V2 = 0x40
ASSOCIATION_GROUP_INFO_GET_PROPERTIES1_REFRESH_CACHE_BIT_MASK_V2 = 0x80
# Values used for Association Group Info Report command
ASSOCIATION_GROUP_INFO_REPORT_PROPERTIES1_GROUP_COUNT_MASK_V2 = 0x3F
ASSOCIATION_GROUP_INFO_REPORT_PROPERTIES1_DYNAMIC_INFO_BIT_MASK_V2 = 0x40
ASSOCIATION_GROUP_INFO_REPORT_PROPERTIES1_LIST_MODE_BIT_MASK_V2 = 0x80
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_GENERAL_V2 = 0x00
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_CONTROL_V2 = 0x20
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_SENSOR_V2 = 0x31
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_NOTIFICATION_V2 = 0x71
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_METER_V2 = 0x32
ASSOCIATION_GROUP_INFO_REPORT_AGI_GENERAL_NA_V2 = 0x00
ASSOCIATION_GROUP_INFO_REPORT_AGI_GENERAL_LIFELINE_V2 = 0x01
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY01_V2 = 0x01
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY02_V2 = 0x02
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY03_V2 = 0x03
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY04_V2 = 0x04
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY05_V2 = 0x05
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY06_V2 = 0x06
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY07_V2 = 0x07
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY08_V2 = 0x08
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY09_V2 = 0x09
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY10_V2 = 0x0A
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY11_V2 = 0x0B
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY12_V2 = 0x0C
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY13_V2 = 0x0D
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY14_V2 = 0x0E
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY15_V2 = 0x0F
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY16_V2 = 0x10
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY17_V2 = 0x11
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY18_V2 = 0x12
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY19_V2 = 0x13
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY20_V2 = 0x14
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY21_V2 = 0x15
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY22_V2 = 0x16
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY23_V2 = 0x17
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY24_V2 = 0x18
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY25_V2 = 0x19
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY26_V2 = 0x1A
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY27_V2 = 0x1B
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY28_V2 = 0x1C
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY29_V2 = 0x1D
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY30_V2 = 0x1E
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY31_V2 = 0x1F
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY32_V2 = 0x20
ASSOCIATION_GROUP_INFO_REPORT_MULTILEVEL_SENSOR_TYPE_TEMPERATURE_V2 = 0x01
ASSOCIATION_GROUP_INFO_REPORT_MULTILEVEL_SENSOR_TYPE_HUMIDITY_V2 = 0x05
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_SMOKE_ALARM_V2 = 0x01
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_C0_ALARM_V2 = 0x02
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_CO2_ALARM_V2 = 0x03
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_HEAT_ALARM_V2 = 0x04
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_WATER_ALARM_V2 = 0x05
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_ACCESS_CONTROL_V2 = 0x06
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_HOME_SECURITY_V2 = 0x07
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_POWER_MANAGEMENT_V2 = 0x08
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_SYSTEM_V2 = 0x09
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_EMERGENCY_ALARM_V2 = 0x0A
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_CLOCK_V2 = 0x0B
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_APPLIANCE_V2 = 0x0C
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_HOME_HEALTH_V2 = 0x0D
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_SIREN_V2 = 0x0E
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_WATER_VALVE_V2 = 0x0F
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_WEATHER_ALARM_V2 = 0x10
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_IRRIGATION_V2 = 0x11
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_GAS_ALARM_V2 = 0x12
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_PEST_CONTROL_V2 = 0x13
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_LIGHT_SENSOR_V2 = 0x14
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_WATER_QUALITY_MONITORING_V2 = 0x15
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_HOME_MONITORING_V2 = 0x16
ASSOCIATION_GROUP_INFO_REPORT_METER_TYPE_ELECTRIC_V2 = 0x01
ASSOCIATION_GROUP_INFO_REPORT_METER_TYPE_GAS_V2 = 0x02
ASSOCIATION_GROUP_INFO_REPORT_METER_TYPE_WATER_V2 = 0x03
# Values used for Association Group Command List Get command
ASSOCIATION_GROUP_COMMAND_LIST_GET_PROPERTIES1_RESERVED_MASK_V2 = 0x7F
ASSOCIATION_GROUP_COMMAND_LIST_GET_PROPERTIES1_ALLOW_CACHE_BIT_MASK_V2 = 0x80

ASSOCIATION_GRP_INFO_VERSION_V3 = 0x03
ASSOCIATION_GROUP_NAME_GET_V3 = 0x01
ASSOCIATION_GROUP_NAME_REPORT_V3 = 0x02
ASSOCIATION_GROUP_INFO_GET_V3 = 0x03
ASSOCIATION_GROUP_INFO_REPORT_V3 = 0x04
ASSOCIATION_GROUP_COMMAND_LIST_GET_V3 = 0x05
ASSOCIATION_GROUP_COMMAND_LIST_REPORT_V3 = 0x06
# Values used for Association Group Info Get command
ASSOCIATION_GROUP_INFO_GET_PROPERTIES1_RESERVED_MASK_V3 = 0x3F
ASSOCIATION_GROUP_INFO_GET_PROPERTIES1_LIST_MODE_BIT_MASK_V3 = 0x40
ASSOCIATION_GROUP_INFO_GET_PROPERTIES1_REFRESH_CACHE_BIT_MASK_V3 = 0x80
# Values used for Association Group Info Report command
ASSOCIATION_GROUP_INFO_REPORT_PROPERTIES1_GROUP_COUNT_MASK_V3 = 0x3F
ASSOCIATION_GROUP_INFO_REPORT_PROPERTIES1_DYNAMIC_INFO_BIT_MASK_V3 = 0x40
ASSOCIATION_GROUP_INFO_REPORT_PROPERTIES1_LIST_MODE_BIT_MASK_V3 = 0x80
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_GENERAL_V3 = 0x00
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_CONTROL_V3 = 0x20
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_SENSOR_V3 = 0x31
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_NOTIFICATION_V3 = 0x71
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_METER_V3 = 0x32
ASSOCIATION_GROUP_INFO_REPORT_AGI_PROFILE_IRRIGATION_V3 = 0x6B
ASSOCIATION_GROUP_INFO_REPORT_AGI_GENERAL_NA_V3 = 0x00
ASSOCIATION_GROUP_INFO_REPORT_AGI_GENERAL_LIFELINE_V3 = 0x01
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY01_V3 = 0x01
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY02_V3 = 0x02
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY03_V3 = 0x03
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY04_V3 = 0x04
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY05_V3 = 0x05
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY06_V3 = 0x06
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY07_V3 = 0x07
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY08_V3 = 0x08
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY09_V3 = 0x09
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY10_V3 = 0x0A
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY11_V3 = 0x0B
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY12_V3 = 0x0C
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY13_V3 = 0x0D
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY14_V3 = 0x0E
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY15_V3 = 0x0F
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY16_V3 = 0x10
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY17_V3 = 0x11
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY18_V3 = 0x12
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY19_V3 = 0x13
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY20_V3 = 0x14
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY21_V3 = 0x15
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY22_V3 = 0x16
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY23_V3 = 0x17
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY24_V3 = 0x18
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY25_V3 = 0x19
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY26_V3 = 0x1A
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY27_V3 = 0x1B
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY28_V3 = 0x1C
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY29_V3 = 0x1D
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY30_V3 = 0x1E
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY31_V3 = 0x1F
ASSOCIATION_GROUP_INFO_REPORT_AGI_CONTROL_KEY32_V3 = 0x20
ASSOCIATION_GROUP_INFO_REPORT_MULTILEVEL_SENSOR_TYPE_TEMPERATURE_V3 = 0x01
ASSOCIATION_GROUP_INFO_REPORT_MULTILEVEL_SENSOR_TYPE_HUMIDITY_V3 = 0x05
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_SMOKE_ALARM_V3 = 0x01
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_C0_ALARM_V3 = 0x02
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_CO2_ALARM_V3 = 0x03
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_HEAT_ALARM_V3 = 0x04
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_WATER_ALARM_V3 = 0x05
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_ACCESS_CONTROL_V3 = 0x06
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_HOME_SECURITY_V3 = 0x07
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_POWER_MANAGEMENT_V3 = 0x08
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_SYSTEM_V3 = 0x09
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_EMERGENCY_ALARM_V3 = 0x0A
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_CLOCK_V3 = 0x0B
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_APPLIANCE_V3 = 0x0C
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_HOME_HEALTH_V3 = 0x0D
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_SIREN_V3 = 0x0E
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_WATER_VALVE_V3 = 0x0F
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_WEATHER_ALARM_V3 = 0x10
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_IRRIGATION_V3 = 0x11
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_GAS_ALARM_V3 = 0x12
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_PEST_CONTROL_V3 = 0x13
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_LIGHT_SENSOR_V3 = 0x14
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_WATER_QUALITY_MONITORING_V3 = 0x15
ASSOCIATION_GROUP_INFO_REPORT_NOTIFICATION_TYPE_HOME_MONITORING_V3 = 0x16
ASSOCIATION_GROUP_INFO_REPORT_METER_TYPE_ELECTRIC_V3 = 0x01
ASSOCIATION_GROUP_INFO_REPORT_METER_TYPE_GAS_V3 = 0x02
ASSOCIATION_GROUP_INFO_REPORT_METER_TYPE_WATER_V3 = 0x03
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_01_V3 = 0x01
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_02_V3 = 0x02
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_03_V3 = 0x03
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_04_V3 = 0x04
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_05_V3 = 0x05
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_06_V3 = 0x06
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_07_V3 = 0x07
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_08_V3 = 0x08
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_09_V3 = 0x09
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_10_V3 = 0x0A
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_11_V3 = 0x0B
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_12_V3 = 0x0C
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_13_V3 = 0x0D
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_14_V3 = 0x0E
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_15_V3 = 0x0F
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_16_V3 = 0x10
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_17_V3 = 0x11
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_18_V3 = 0x12
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_19_V3 = 0x13
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_20_V3 = 0x14
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_21_V3 = 0x15
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_22_V3 = 0x16
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_23_V3 = 0x17
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_24_V3 = 0x18
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_25_V3 = 0x19
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_26_V3 = 0x1A
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_27_V3 = 0x1B
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_28_V3 = 0x1C
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_29_V3 = 0x1D
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_30_V3 = 0x1E
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_31_V3 = 0x1F
ASSOCIATION_GROUP_INFO_REPORT_AGI_IRRIGATION_CHANNEL_32_V3 = 0x20
# Values used for Association Group Command List Get command
ASSOCIATION_GROUP_COMMAND_LIST_GET_PROPERTIES1_RESERVED_MASK_V3 = 0x7F
ASSOCIATION_GROUP_COMMAND_LIST_GET_PROPERTIES1_ALLOW_CACHE_BIT_MASK_V3 = 0x80


class ZW_ASSOCIATION_GROUP_NAME_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('groupingIdentifier', uint8_t)]


class ZW_ASSOCIATION_GROUP_NAME_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('groupingIdentifier', uint8_t),
        ('lengthOfName', uint8_t),
        ('name1', uint8_t),
    ]


class ZW_ASSOCIATION_GROUP_INFO_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('groupingIdentifier', uint8_t),
    ]


class VG_ASSOCIATION_GROUP_INFO_REPORT_VG(ctypes.Structure):
    _fields_ = [
        ('groupingIdentifier', uint8_t),
        ('mode', uint8_t),
        ('profile1', uint8_t),
        ('profile2', uint8_t),
        ('reserved', uint8_t),
        ('eventCode1', uint8_t),
        ('eventCode2', uint8_t),
    ]


class ZW_ASSOCIATION_GROUP_INFO_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('variantgroup1', VG_ASSOCIATION_GROUP_INFO_REPORT_VG),
    ]


class ZW_ASSOCIATION_GROUP_COMMAND_LIST_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('groupingIdentifier', uint8_t),
    ]


class ZW_ASSOCIATION_GROUP_COMMAND_LIST_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('groupingIdentifier', uint8_t),
        ('listLength', uint8_t),
        ('command1', uint8_t),
    ]


class ZW_ASSOCIATION_GROUP_NAME_GET_V2_FRAME(ZW_ASSOCIATION_GROUP_NAME_GET_FRAME):
    _fields_ = []


class ZW_ASSOCIATION_GROUP_NAME_REPORT_V2_FRAME(ZW_ASSOCIATION_GROUP_NAME_REPORT_FRAME):
    _fields_ = []


class ZW_ASSOCIATION_GROUP_INFO_GET_V2_FRAME(ZW_ASSOCIATION_GROUP_INFO_GET_FRAME):
    _fields_ = []


class VG_ASSOCIATION_GROUP_INFO_REPORT_V2_VG(ctypes.Structure):
    _fields_ = [
        ('groupingIdentifier', uint8_t),
        ('mode', uint8_t),
        ('profile1', uint8_t),
        ('profile2', uint8_t),
        ('reserved', uint8_t),
        ('eventCode1', uint8_t),
        ('eventCode2', uint8_t),
    ]


class ZW_ASSOCIATION_GROUP_INFO_REPORT_V2_FRAME(ZW_ASSOCIATION_GROUP_INFO_REPORT_FRAME):
    _fields_ = []


class ZW_ASSOCIATION_GROUP_COMMAND_LIST_GET_V2_FRAME(ZW_ASSOCIATION_GROUP_COMMAND_LIST_GET_FRAME):
    _fields_ = []


class ZW_ASSOCIATION_GROUP_COMMAND_LIST_REPORT_V2_FRAME(ZW_ASSOCIATION_GROUP_COMMAND_LIST_REPORT_FRAME):
    _fields_ = []


class ZW_ASSOCIATION_GROUP_NAME_GET_V3_FRAME(ZW_ASSOCIATION_GROUP_NAME_GET_V2_FRAME):
    _fields_ = []


class ZW_ASSOCIATION_GROUP_NAME_REPORT_V3_FRAME(ZW_ASSOCIATION_GROUP_NAME_REPORT_V2_FRAME):
    _fields_ = []


class ZW_ASSOCIATION_GROUP_INFO_GET_V3_FRAME(ZW_ASSOCIATION_GROUP_INFO_GET_V2_FRAME):
    _fields_ = []


class VG_ASSOCIATION_GROUP_INFO_REPORT_V3_VG(ctypes.Structure):
    _fields_ = [
        ('groupingIdentifier', uint8_t),
        ('mode', uint8_t),
        ('profile1', uint8_t),
        ('profile2', uint8_t),
        ('reserved', uint8_t),
        ('eventCode1', uint8_t),
        ('eventCode2', uint8_t),
    ]


class ZW_ASSOCIATION_GROUP_INFO_REPORT_V3_FRAME(ZW_ASSOCIATION_GROUP_INFO_REPORT_V2_FRAME):
    _fields_ = []


class ZW_ASSOCIATION_GROUP_COMMAND_LIST_GET_V3_FRAME(ZW_ASSOCIATION_GROUP_COMMAND_LIST_GET_V2_FRAME):
    _fields_ = []


class ZW_ASSOCIATION_GROUP_COMMAND_LIST_REPORT_V3_FRAME(ZW_ASSOCIATION_GROUP_COMMAND_LIST_REPORT_V2_FRAME):
    _fields_ = []

