from . import CommandClass, CommandClassCommands


# Battery Command Class
# Management
# ==============================


class BATTERY_V1_COMMANDS(CommandClassCommands):
    version = 0x01

    GET = 0x02
    REPORT = 0x03


class BATTERY_V2_COMMANDS(BATTERY_V1_COMMANDS):
    version = 0x02

    HEALTH_GET = 0x04
    HEALTH_REPORT = 0x05

    REPORT_VALUES = {
        0x00: 'Discharging',
        0x01: 'Charging',
        0x02: 'Maintaining'
    }


class BATTERY_V3_COMMANDS(BATTERY_V2_COMMANDS):
    version = 0x03


class COMMAND_CLASS_BATTERY(CommandClass):
    id = 0x80
    versions = [
        BATTERY_V1_COMMANDS,
        BATTERY_V2_COMMANDS,
        BATTERY_V3_COMMANDS
    ]


# Values used for Battery Report command
BATTERY_REPORT_PROPERTIES1_REPLACE_RECHARGE_MASK_V2 = 0x03
BATTERY_REPORT_PROPERTIES1_LOW_FLUID_BIT_MASK_V2 = 0x04
BATTERY_REPORT_PROPERTIES1_OVERHEATING_BIT_MASK_V2 = 0x08
BATTERY_REPORT_PROPERTIES1_BACKUP_BATTERY_BIT_MASK_V2 = 0x10
BATTERY_REPORT_PROPERTIES1_RECHARGEABLE_BIT_MASK_V2 = 0x20
BATTERY_REPORT_PROPERTIES1_CHARGING_STATUS_MASK_V2 = 0xC0
BATTERY_REPORT_PROPERTIES1_CHARGING_STATUS_SHIFT_V2 = 0x06

BATTERY_REPORT_PROPERTIES2_DISCONNECTED_BIT_MASK_V2 = 0x01
BATTERY_REPORT_PROPERTIES2_RESERVED1_MASK_V2 = 0xFE
BATTERY_REPORT_PROPERTIES2_RESERVED1_SHIFT_V2 = 0x01
# Values used for Battery Health Report command
BATTERY_HEALTH_REPORT_PROPERTIES1_SIZE_MASK_V2 = 0x07
BATTERY_HEALTH_REPORT_PROPERTIES1_SCALE_MASK_V2 = 0x18
BATTERY_HEALTH_REPORT_PROPERTIES1_SCALE_SHIFT_V2 = 0x03
BATTERY_HEALTH_REPORT_PROPERTIES1_PRECISION_MASK_V2 = 0xE0
BATTERY_HEALTH_REPORT_PROPERTIES1_PRECISION_SHIFT_V2 = 0x05


# Values used for Battery Report command
BATTERY_REPORT_PROPERTIES1_REPLACE_RECHARGE_MASK_V3 = 0x03
BATTERY_REPORT_PROPERTIES1_LOW_FLUID_BIT_MASK_V3 = 0x04
BATTERY_REPORT_PROPERTIES1_OVERHEATING_BIT_MASK_V3 = 0x08
BATTERY_REPORT_PROPERTIES1_BACKUP_BATTERY_BIT_MASK_V3 = 0x10
BATTERY_REPORT_PROPERTIES1_RECHARGEABLE_BIT_MASK_V3 = 0x20
BATTERY_REPORT_PROPERTIES1_CHARGING_STATUS_MASK_V3 = 0xC0
BATTERY_REPORT_PROPERTIES1_CHARGING_STATUS_SHIFT_V3 = 0x06
BATTERY_REPORT_PROPERTIES2_DISCONNECTED_BIT_MASK_V3 = 0x01
BATTERY_REPORT_PROPERTIES2_LOW_TEMPERATURE_STATUS_BIT_MASK_V3 = 0x02
BATTERY_REPORT_PROPERTIES2_RESERVED1_MASK_V3 = 0xFC
BATTERY_REPORT_PROPERTIES2_RESERVED1_SHIFT_V3 = 0x02
# Values used for Battery Health Report command
BATTERY_HEALTH_REPORT_PROPERTIES1_SIZE_MASK_V3 = 0x07
BATTERY_HEALTH_REPORT_PROPERTIES1_SCALE_MASK_V3 = 0x18
BATTERY_HEALTH_REPORT_PROPERTIES1_SCALE_SHIFT_V3 = 0x03
BATTERY_HEALTH_REPORT_PROPERTIES1_PRECISION_MASK_V3 = 0xE0
BATTERY_HEALTH_REPORT_PROPERTIES1_PRECISION_SHIFT_V3 = 0x05






class ZW_BATTERY_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_BATTERY_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('batteryLevel', uint8_t)]


class ZW_BATTERY_GET_V2_FRAME(ZW_BATTERY_GET_FRAME):
    _fields_ = []


class ZW_BATTERY_REPORT_V2_FRAME(ZW_BATTERY_REPORT_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('properties2', uint8_t),
    ]


class ZW_BATTERY_HEALTH_GET_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_BATTERY_HEALTH_REPORT_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('maximumCapacity', uint8_t),
        ('properties1', uint8_t),
        ('batteryTemperature1', uint8_t),
    ]


class ZW_BATTERY_GET_V3_FRAME(ZW_BATTERY_GET_V2_FRAME):
    _fields_ = []


class ZW_BATTERY_REPORT_V3_FRAME(ZW_BATTERY_REPORT_V2_FRAME):
    _fields_ = []


class ZW_BATTERY_HEALTH_GET_V3_FRAME(ZW_BATTERY_HEALTH_GET_V2_FRAME):
    _fields_ = []


class ZW_BATTERY_HEALTH_REPORT_V3_FRAME(ZW_BATTERY_HEALTH_REPORT_V2_FRAME):
    _fields_ = []


