COMMAND_CLASS_CHIMNEY_FAN = 0x2A

CHIMNEY_FAN_VERSION = 0x01
CHIMNEY_FAN_ALARM_LOG_GET = 0x20
CHIMNEY_FAN_ALARM_LOG_REPORT = 0x21
CHIMNEY_FAN_ALARM_LOG_SET = 0x1F
CHIMNEY_FAN_ALARM_STATUS_GET = 0x23
CHIMNEY_FAN_ALARM_STATUS_REPORT = 0x24
CHIMNEY_FAN_ALARM_STATUS_SET = 0x22
CHIMNEY_FAN_ALARM_TEMP_GET = 0x0E
CHIMNEY_FAN_ALARM_TEMP_REPORT = 0x0F
CHIMNEY_FAN_ALARM_TEMP_SET = 0x0D
CHIMNEY_FAN_BOOST_TIME_GET = 0x11
CHIMNEY_FAN_BOOST_TIME_REPORT = 0x12
CHIMNEY_FAN_BOOST_TIME_SET = 0x10
CHIMNEY_FAN_DEFAULT_SET = 0x28
CHIMNEY_FAN_MIN_SPEED_GET = 0x26
CHIMNEY_FAN_MIN_SPEED_REPORT = 0x27
CHIMNEY_FAN_MIN_SPEED_SET = 0x25
CHIMNEY_FAN_MODE_GET = 0x17
CHIMNEY_FAN_MODE_REPORT = 0x18
CHIMNEY_FAN_MODE_SET = 0x16
CHIMNEY_FAN_SETUP_GET = 0x1A
CHIMNEY_FAN_SETUP_REPORT = 0x1B
CHIMNEY_FAN_SETUP_SET = 0x19
CHIMNEY_FAN_SPEED_GET = 0x05
CHIMNEY_FAN_SPEED_REPORT = 0x06
CHIMNEY_FAN_SPEED_SET = 0x04
CHIMNEY_FAN_START_TEMP_GET = 0x08
CHIMNEY_FAN_START_TEMP_REPORT = 0x09
CHIMNEY_FAN_START_TEMP_SET = 0x07
CHIMNEY_FAN_STATE_GET = 0x02
CHIMNEY_FAN_STATE_REPORT = 0x03
CHIMNEY_FAN_STATE_SET = 0x01
CHIMNEY_FAN_STATUS_GET = 0x1D
CHIMNEY_FAN_STATUS_REPORT = 0x1E
CHIMNEY_FAN_STOP_TEMP_GET = 0x0B
CHIMNEY_FAN_STOP_TEMP_REPORT = 0x0C
CHIMNEY_FAN_STOP_TEMP_SET = 0x0A
CHIMNEY_FAN_STOP_TIME_GET = 0x14
CHIMNEY_FAN_STOP_TIME_REPORT = 0x15
CHIMNEY_FAN_STOP_TIME_SET = 0x13
# Values used for Chimney Fan Alarm Log Report command
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_1_RESERVED11_BIT_MASK = 0x01
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_1_EXTERNAL_ALARM_1_BIT_MASK = 0x02
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_1_SENSOR_ERROR_1_BIT_MASK = 0x04
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_1_ALARM_TEMPERATURE_EXCEEDED_1_BIT_MASK = 0x08
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_1_RESERVED12_MASK = 0x70
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_1_RESERVED12_SHIFT = 0x04
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_1_ALARM_STILL_ACTIVE_1_BIT_MASK = 0x80
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_2_RESERVED21_BIT_MASK = 0x01
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_2_EXTERNAL_ALARM_2_BIT_MASK = 0x02
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_2_SENSOR_ERROR_2_BIT_MASK = 0x04
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_2_ALARM_TEMPERATURE_EXCEEDED_2_BIT_MASK = 0x08
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_2_RESERVED22_MASK = 0x70
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_2_RESERVED22_SHIFT = 0x04
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_2_ALARM_STILL_ACTIVE_2_BIT_MASK = 0x80
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_3_RESERVED31_BIT_MASK = 0x01
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_3_EXTERNAL_ALARM_3_BIT_MASK = 0x02
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_3_SENSOR_ERROR_3_BIT_MASK = 0x04
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_3_ALARM_TEMPERATURE_EXCEEDED_3_BIT_MASK = 0x08
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_3_RESERVED32_MASK = 0x70
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_3_RESERVED32_SHIFT = 0x04
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_3_ALARM_STILL_ACTIVE_3_BIT_MASK = 0x80
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_4_RESERVED41_BIT_MASK = 0x01
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_4_EXTERNAL_ALARM_4_BIT_MASK = 0x02
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_4_SENSOR_ERROR_4_BIT_MASK = 0x04
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_4_ALARM_TEMPERATURE_EXCEEDED_4_BIT_MASK = 0x08
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_4_RESERVED42_MASK = 0x70
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_4_RESERVED42_SHIFT = 0x04
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_4_ALARM_STILL_ACTIVE_4_BIT_MASK = 0x80
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_5_RESERVED51_BIT_MASK = 0x01
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_5_EXTERNAL_ALARM_5_BIT_MASK = 0x02
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_5_SENSOR_ERROR_5_BIT_MASK = 0x04
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_5_ALARM_TEMPERATURE_EXCEEDED_5_BIT_MASK = 0x08
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_5_RESERVED52_MASK = 0x70
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_5_RESERVED52_SHIFT = 0x04
CHIMNEY_FAN_ALARM_LOG_REPORT_ALARM_EVENT_5_ALARM_STILL_ACTIVE_5_BIT_MASK = 0x80
# Values used for Chimney Fan Alarm Log Set command
CHIMNEY_FAN_ALARM_LOG_SET_RESET_LOG = 0x08
# Values used for Chimney Fan Alarm Status Report command
CHIMNEY_FAN_ALARM_STATUS_REPORT_ALARM_STATUS_SERVICE_BIT_MASK = 0x01
CHIMNEY_FAN_ALARM_STATUS_REPORT_ALARM_STATUS_EXTERNAL_ALARM_BIT_MASK = 0x02
CHIMNEY_FAN_ALARM_STATUS_REPORT_ALARM_STATUS_SENSOR_ERROR_BIT_MASK = 0x04
CHIMNEY_FAN_ALARM_STATUS_REPORT_ALARM_STATUS_ALARM_TEMPERATURE_EXCEEDED_BIT_MASK = 0x08
CHIMNEY_FAN_ALARM_STATUS_REPORT_ALARM_STATUS_NOT_USED_MASK = 0x30
CHIMNEY_FAN_ALARM_STATUS_REPORT_ALARM_STATUS_NOT_USED_SHIFT = 0x04
CHIMNEY_FAN_ALARM_STATUS_REPORT_ALARM_STATUS_SPEED_CHANGE_ENABLE_BIT_MASK = 0x40
CHIMNEY_FAN_ALARM_STATUS_REPORT_ALARM_STATUS_START_TEMPERATURE_EXCEEDED_BIT_MASK = 0x80
# Values used for Chimney Fan Alarm Status Set command
CHIMNEY_FAN_ALARM_STATUS_SET_MESSAGE_NOT_USED1_BIT_MASK = 0x01
CHIMNEY_FAN_ALARM_STATUS_SET_MESSAGE_ACKNOWLEDGE_EXTERNAL_ALARM_BIT_MASK = 0x02
CHIMNEY_FAN_ALARM_STATUS_SET_MESSAGE_ACKNOWLEDGE_SENSOR_ERROR_BIT_MASK = 0x04
CHIMNEY_FAN_ALARM_STATUS_SET_MESSAGE_ACKNOWLEDGE_ALARM_TEMPERATURE_EXCEEDED_BIT_MASK = 0x08
CHIMNEY_FAN_ALARM_STATUS_SET_MESSAGE_NOT_USED2_MASK = 0xF0
CHIMNEY_FAN_ALARM_STATUS_SET_MESSAGE_NOT_USED2_SHIFT = 0x04
# Values used for Chimney Fan Alarm Temp Report command
CHIMNEY_FAN_ALARM_TEMP_REPORT_PROPERTIES1_SIZE_MASK = 0x07
CHIMNEY_FAN_ALARM_TEMP_REPORT_PROPERTIES1_SCALE_MASK = 0x18
CHIMNEY_FAN_ALARM_TEMP_REPORT_PROPERTIES1_SCALE_SHIFT = 0x03
CHIMNEY_FAN_ALARM_TEMP_REPORT_PROPERTIES1_PRECISION_MASK = 0xE0
CHIMNEY_FAN_ALARM_TEMP_REPORT_PROPERTIES1_PRECISION_SHIFT = 0x05
# Values used for Chimney Fan Alarm Temp Set command
CHIMNEY_FAN_ALARM_TEMP_SET_PROPERTIES1_SIZE_MASK = 0x07
CHIMNEY_FAN_ALARM_TEMP_SET_PROPERTIES1_SCALE_MASK = 0x18
CHIMNEY_FAN_ALARM_TEMP_SET_PROPERTIES1_SCALE_SHIFT = 0x03
CHIMNEY_FAN_ALARM_TEMP_SET_PROPERTIES1_PRECISION_MASK = 0xE0
CHIMNEY_FAN_ALARM_TEMP_SET_PROPERTIES1_PRECISION_SHIFT = 0x05
# Values used for Chimney Fan Mode Report command
CHIMNEY_FAN_MODE_REPORT_OFF = 0x00
CHIMNEY_FAN_MODE_REPORT_ON = 0xFF
# Values used for Chimney Fan Mode Set command
CHIMNEY_FAN_MODE_SET_OFF = 0x00
CHIMNEY_FAN_MODE_SET_ON = 0xFF
# Values used for Chimney Fan Setup Report command
CHIMNEY_FAN_SETUP_REPORT_OFF = 0x00
CHIMNEY_FAN_SETUP_REPORT_ON = 0xFF
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES1_SIZE_1_MASK = 0x07
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES1_SCALE_1_MASK = 0x18
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES1_SCALE_1_SHIFT = 0x03
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES1_PRECISION_1_MASK = 0xE0
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES1_PRECISION_1_SHIFT = 0x05
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES2_SIZE_2_MASK = 0x07
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES2_SCALE_2_MASK = 0x18
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES2_SCALE_2_SHIFT = 0x03
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES2_PRECISION_2_MASK = 0xE0
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES2_PRECISION_2_SHIFT = 0x05
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES3_SIZE_3_MASK = 0x07
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES3_SCALE_3_MASK = 0x18
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES3_SCALE_3_SHIFT = 0x03
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES3_PRECISION_3_MASK = 0xE0
CHIMNEY_FAN_SETUP_REPORT_PROPERTIES3_PRECISION_3_SHIFT = 0x05
# Values used for Chimney Fan Setup Set command
CHIMNEY_FAN_SETUP_SET_OFF = 0x00
CHIMNEY_FAN_SETUP_SET_ON = 0xFF
CHIMNEY_FAN_SETUP_SET_PROPERTIES1_SIZE_1_MASK = 0x07
CHIMNEY_FAN_SETUP_SET_PROPERTIES1_SCALE_1_MASK = 0x18
CHIMNEY_FAN_SETUP_SET_PROPERTIES1_SCALE_1_SHIFT = 0x03
CHIMNEY_FAN_SETUP_SET_PROPERTIES1_PRECISION_1_MASK = 0xE0
CHIMNEY_FAN_SETUP_SET_PROPERTIES1_PRECISION_1_SHIFT = 0x05
CHIMNEY_FAN_SETUP_SET_PROPERTIES2_SIZE_2_MASK = 0x07
CHIMNEY_FAN_SETUP_SET_PROPERTIES2_SCALE_2_MASK = 0x18
CHIMNEY_FAN_SETUP_SET_PROPERTIES2_SCALE_2_SHIFT = 0x03
CHIMNEY_FAN_SETUP_SET_PROPERTIES2_PRECISION_2_MASK = 0xE0
CHIMNEY_FAN_SETUP_SET_PROPERTIES2_PRECISION_2_SHIFT = 0x05
CHIMNEY_FAN_SETUP_SET_PROPERTIES3_SIZE_3_MASK = 0x07
CHIMNEY_FAN_SETUP_SET_PROPERTIES3_SCALE_3_MASK = 0x18
CHIMNEY_FAN_SETUP_SET_PROPERTIES3_SCALE_3_SHIFT = 0x03
CHIMNEY_FAN_SETUP_SET_PROPERTIES3_PRECISION_3_MASK = 0xE0
CHIMNEY_FAN_SETUP_SET_PROPERTIES3_PRECISION_3_SHIFT = 0x05
# Values used for Chimney Fan Start Temp Report command
CHIMNEY_FAN_START_TEMP_REPORT_PROPERTIES1_SIZE_MASK = 0x07
CHIMNEY_FAN_START_TEMP_REPORT_PROPERTIES1_SCALE_MASK = 0x18
CHIMNEY_FAN_START_TEMP_REPORT_PROPERTIES1_SCALE_SHIFT = 0x03
CHIMNEY_FAN_START_TEMP_REPORT_PROPERTIES1_PRECISION_MASK = 0xE0
CHIMNEY_FAN_START_TEMP_REPORT_PROPERTIES1_PRECISION_SHIFT = 0x05
# Values used for Chimney Fan Start Temp Set command
CHIMNEY_FAN_START_TEMP_SET_PROPERTIES1_SIZE_MASK = 0x07
CHIMNEY_FAN_START_TEMP_SET_PROPERTIES1_SCALE_MASK = 0x18
CHIMNEY_FAN_START_TEMP_SET_PROPERTIES1_SCALE_SHIFT = 0x03
CHIMNEY_FAN_START_TEMP_SET_PROPERTIES1_PRECISION_MASK = 0xE0
CHIMNEY_FAN_START_TEMP_SET_PROPERTIES1_PRECISION_SHIFT = 0x05
# Values used for Chimney Fan State Report command
CHIMNEY_FAN_STATE_REPORT_OFF = 0x00
CHIMNEY_FAN_STATE_REPORT_BOOST = 0x01
CHIMNEY_FAN_STATE_REPORT_EXHAUST = 0x02
CHIMNEY_FAN_STATE_REPORT_RELOAD = 0x03
CHIMNEY_FAN_STATE_REPORT_VENTING = 0x04
CHIMNEY_FAN_STATE_REPORT_STOP = 0x05
CHIMNEY_FAN_STATE_REPORT_VENTING_EX = 0x06
CHIMNEY_FAN_STATE_REPORT_SERVICE = 0x07
CHIMNEY_FAN_STATE_REPORT_SENSOR_FAILURE = 0x08
CHIMNEY_FAN_STATE_REPORT_CHIMNEY_FIRE = 0x09
CHIMNEY_FAN_STATE_REPORT_EXTERNAL_ALARM = 0x0A
# Values used for Chimney Fan State Set command
CHIMNEY_FAN_STATE_SET_NEXT_STATE = 0x01
# Values used for Chimney Fan Status Report command
CHIMNEY_FAN_STATUS_REPORT_OFF = 0x00
CHIMNEY_FAN_STATUS_REPORT_BOOST = 0x01
CHIMNEY_FAN_STATUS_REPORT_EXHAUST = 0x02
CHIMNEY_FAN_STATUS_REPORT_RELOAD = 0x03
CHIMNEY_FAN_STATUS_REPORT_VENTING = 0x04
CHIMNEY_FAN_STATUS_REPORT_STOP = 0x05
CHIMNEY_FAN_STATUS_REPORT_VENTING_EX = 0x06
CHIMNEY_FAN_STATUS_REPORT_SERVICE = 0x07
CHIMNEY_FAN_STATUS_REPORT_SENSOR_FAILURE = 0x08
CHIMNEY_FAN_STATUS_REPORT_CHIMNEY_FIRE = 0x09
CHIMNEY_FAN_STATUS_REPORT_EXTERNAL_ALARM = 0x0A
CHIMNEY_FAN_STATUS_REPORT_ALARM_STATUS_SERVICE_BIT_MASK = 0x01
CHIMNEY_FAN_STATUS_REPORT_ALARM_STATUS_EXTERNAL_ALARM_BIT_MASK = 0x02
CHIMNEY_FAN_STATUS_REPORT_ALARM_STATUS_SENSOR_ERROR_BIT_MASK = 0x04
CHIMNEY_FAN_STATUS_REPORT_ALARM_STATUS_ALARM_TEMPERATURE_EXCEEDED_BIT_MASK = 0x08
CHIMNEY_FAN_STATUS_REPORT_ALARM_STATUS_NOT_USED_MASK = 0x30
CHIMNEY_FAN_STATUS_REPORT_ALARM_STATUS_NOT_USED_SHIFT = 0x04
CHIMNEY_FAN_STATUS_REPORT_ALARM_STATUS_SPEED_CHANGE_ENABLE_BIT_MASK = 0x40
CHIMNEY_FAN_STATUS_REPORT_ALARM_STATUS_START_TEMPERATURE_EXCEEDED_BIT_MASK = 0x80
CHIMNEY_FAN_STATUS_REPORT_PROPERTIES1_SIZE_MASK = 0x07
CHIMNEY_FAN_STATUS_REPORT_PROPERTIES1_SCALE_MASK = 0x18
CHIMNEY_FAN_STATUS_REPORT_PROPERTIES1_SCALE_SHIFT = 0x03
CHIMNEY_FAN_STATUS_REPORT_PROPERTIES1_PRECISION_MASK = 0xE0
CHIMNEY_FAN_STATUS_REPORT_PROPERTIES1_PRECISION_SHIFT = 0x05
# Values used for Chimney Fan Stop Temp Report command
CHIMNEY_FAN_STOP_TEMP_REPORT_PROPERTIES1_SIZE_MASK = 0x07
CHIMNEY_FAN_STOP_TEMP_REPORT_PROPERTIES1_SCALE_MASK = 0x18
CHIMNEY_FAN_STOP_TEMP_REPORT_PROPERTIES1_SCALE_SHIFT = 0x03
CHIMNEY_FAN_STOP_TEMP_REPORT_PROPERTIES1_PRECISION_MASK = 0xE0
CHIMNEY_FAN_STOP_TEMP_REPORT_PROPERTIES1_PRECISION_SHIFT = 0x05
# Values used for Chimney Fan Stop Temp Set command
CHIMNEY_FAN_STOP_TEMP_SET_PROPERTIES1_SIZE_MASK = 0x07
CHIMNEY_FAN_STOP_TEMP_SET_PROPERTIES1_SCALE_MASK = 0x18
CHIMNEY_FAN_STOP_TEMP_SET_PROPERTIES1_SCALE_SHIFT = 0x03
CHIMNEY_FAN_STOP_TEMP_SET_PROPERTIES1_PRECISION_MASK = 0xE0
CHIMNEY_FAN_STOP_TEMP_SET_PROPERTIES1_PRECISION_SHIFT = 0x05





class ZW_CHIMNEY_FAN_ALARM_LOG_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_ALARM_LOG_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('alarmEvent1', uint8_t),
        ('alarmEvent2', uint8_t),
        ('alarmEvent3', uint8_t),
        ('alarmEvent4', uint8_t),
        ('alarmEvent5', uint8_t),
    ]


class ZW_CHIMNEY_FAN_ALARM_LOG_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('message', uint8_t)]


class ZW_CHIMNEY_FAN_ALARM_STATUS_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_ALARM_STATUS_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('alarmStatus', uint8_t)]


class ZW_CHIMNEY_FAN_ALARM_STATUS_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('message', uint8_t)]


class ZW_CHIMNEY_FAN_ALARM_TEMP_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_ALARM_TEMP_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('value1', uint8_t),
    ]


class ZW_CHIMNEY_FAN_ALARM_TEMP_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('value1', uint8_t),
    ]


class ZW_CHIMNEY_FAN_BOOST_TIME_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_BOOST_TIME_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('time', uint8_t)]


class ZW_CHIMNEY_FAN_BOOST_TIME_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('time', uint8_t)]


class ZW_CHIMNEY_FAN_DEFAULT_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_MIN_SPEED_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_MIN_SPEED_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('minSpeed', uint8_t)]


class ZW_CHIMNEY_FAN_MIN_SPEED_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('minSpeed', uint8_t)]


class ZW_CHIMNEY_FAN_MODE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_MODE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('mode', uint8_t)]


class ZW_CHIMNEY_FAN_MODE_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('mode', uint8_t)]


class ZW_CHIMNEY_FAN_SETUP_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_SETUP_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('mode', uint8_t),
        ('boostTime', uint8_t),
        ('stopTime', uint8_t),
        ('minSpeed', uint8_t),
        ('properties1', uint8_t),
        ('startTemperature1', uint8_t),
        ('properties2', uint8_t),
        ('stopTemperature1', uint8_t),
        ('properties3', uint8_t),
        ('alarmTemperatureValue1', uint8_t),
    ]


class ZW_CHIMNEY_FAN_SETUP_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('mode', uint8_t),
        ('boostTime', uint8_t),
        ('stopTime', uint8_t),
        ('minSpeed', uint8_t),
        ('properties1', uint8_t),
        ('startTemperature1', uint8_t),
        ('properties2', uint8_t),
        ('stopTemperature1', uint8_t),
        ('properties3', uint8_t),
        ('alarmTemperatureValue1', uint8_t),
    ]


class ZW_CHIMNEY_FAN_SPEED_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_SPEED_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('speed', uint8_t)]


class ZW_CHIMNEY_FAN_SPEED_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('speed', uint8_t)]


class ZW_CHIMNEY_FAN_START_TEMP_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_START_TEMP_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('value1', uint8_t),
    ]


class ZW_CHIMNEY_FAN_START_TEMP_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('value1', uint8_t),
    ]


class ZW_CHIMNEY_FAN_STATE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_STATE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('state', uint8_t)]


class ZW_CHIMNEY_FAN_STATE_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('state', uint8_t)]


class ZW_CHIMNEY_FAN_STATUS_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_STATUS_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('state', uint8_t),
        ('speed', uint8_t),
        ('alarmStatus', uint8_t),
        ('properties1', uint8_t),
        ('value1', uint8_t),
    ]


class ZW_CHIMNEY_FAN_STOP_TEMP_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_STOP_TEMP_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('value1', uint8_t),
    ]


class ZW_CHIMNEY_FAN_STOP_TEMP_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('value1', uint8_t),
    ]


class ZW_CHIMNEY_FAN_STOP_TIME_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_CHIMNEY_FAN_STOP_TIME_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('time', uint8_t)]


class ZW_CHIMNEY_FAN_STOP_TIME_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('time', uint8_t)]


