# Configuration Command Class
# Application
# ==============================
COMMAND_CLASS_CONFIGURATION = 0x70

CONFIGURATION_VERSION = 0x01
# Configuration Set
CONFIGURATION_SET = 0x04
# Configuration Get
CONFIGURATION_GET = 0x05
# Configuration Report
CONFIGURATION_REPORT = 0x06

# Values used for Configuration Report command
CONFIGURATION_REPORT_LEVEL_SIZE_MASK = 0x07
CONFIGURATION_REPORT_LEVEL_RESERVED_MASK = 0xF8
CONFIGURATION_REPORT_LEVEL_RESERVED_SHIFT = 0x03
# Values used for Configuration Set command
CONFIGURATION_SET_LEVEL_SIZE_MASK = 0x07
CONFIGURATION_SET_LEVEL_RESERVED_MASK = 0x78
CONFIGURATION_SET_LEVEL_RESERVED_SHIFT = 0x03
CONFIGURATION_SET_LEVEL_DEFAULT_BIT_MASK = 0x80

CONFIGURATION_VERSION_V2 = 0x02
CONFIGURATION_GET_V2 = 0x05
CONFIGURATION_REPORT_V2 = 0x06
CONFIGURATION_SET_V2 = 0x04
# Configuration Bulk Set
CONFIGURATION_BULK_SET_V2 = 0x07
# Configuration Bulk Get
CONFIGURATION_BULK_GET_V2 = 0x08
# Configuration Bulk Report
CONFIGURATION_BULK_REPORT_V2 = 0x09

# Values used for Configuration Bulk Report command
CONFIGURATION_BULK_REPORT_PROPERTIES1_SIZE_MASK_V2 = 0x07
CONFIGURATION_BULK_REPORT_PROPERTIES1_RESERVED_MASK_V2 = 0x38
CONFIGURATION_BULK_REPORT_PROPERTIES1_RESERVED_SHIFT_V2 = 0x03
CONFIGURATION_BULK_REPORT_PROPERTIES1_HANDSHAKE_BIT_MASK_V2 = 0x40
CONFIGURATION_BULK_REPORT_PROPERTIES1_DEFAULT_BIT_MASK_V2 = 0x80
# Values used for Configuration Bulk Set command
CONFIGURATION_BULK_SET_PROPERTIES1_SIZE_MASK_V2 = 0x07
CONFIGURATION_BULK_SET_PROPERTIES1_RESERVED_MASK_V2 = 0x38
CONFIGURATION_BULK_SET_PROPERTIES1_RESERVED_SHIFT_V2 = 0x03
CONFIGURATION_BULK_SET_PROPERTIES1_HANDSHAKE_BIT_MASK_V2 = 0x40
CONFIGURATION_BULK_SET_PROPERTIES1_DEFAULT_BIT_MASK_V2 = 0x80
# Values used for Configuration Report command
CONFIGURATION_REPORT_LEVEL_SIZE_MASK_V2 = 0x07
CONFIGURATION_REPORT_LEVEL_RESERVED_MASK_V2 = 0xF8
CONFIGURATION_REPORT_LEVEL_RESERVED_SHIFT_V2 = 0x03
# Values used for Configuration Set command
CONFIGURATION_SET_LEVEL_SIZE_MASK_V2 = 0x07
CONFIGURATION_SET_LEVEL_RESERVED_MASK_V2 = 0x78
CONFIGURATION_SET_LEVEL_RESERVED_SHIFT_V2 = 0x03
CONFIGURATION_SET_LEVEL_DEFAULT_BIT_MASK_V2 = 0x80

CONFIGURATION_VERSION_V3 = 0x03
CONFIGURATION_BULK_GET_V3 = 0x08
CONFIGURATION_BULK_REPORT_V3 = 0x09
CONFIGURATION_BULK_SET_V3 = 0x07
CONFIGURATION_GET_V3 = 0x05
CONFIGURATION_REPORT_V3 = 0x06
CONFIGURATION_SET_V3 = 0x04
# Configuration Name Get
CONFIGURATION_NAME_GET_V3 = 0x0A
# Configuration Name Report
CONFIGURATION_NAME_REPORT_V3 = 0x0B
# Configuration Info Get
CONFIGURATION_INFO_GET_V3 = 0x0C
# Configuration Info Report
CONFIGURATION_INFO_REPORT_V3 = 0x0D
# Configuration Properties Get
CONFIGURATION_PROPERTIES_GET_V3 = 0x0E
# Configuration Properties Report
CONFIGURATION_PROPERTIES_REPORT_V3 = 0x0F


# Values used for Configuration Bulk Report command
CONFIGURATION_BULK_REPORT_PROPERTIES1_SIZE_MASK_V3 = 0x07
CONFIGURATION_BULK_REPORT_PROPERTIES1_RESERVED_MASK_V3 = 0x38
CONFIGURATION_BULK_REPORT_PROPERTIES1_RESERVED_SHIFT_V3 = 0x03
CONFIGURATION_BULK_REPORT_PROPERTIES1_HANDSHAKE_BIT_MASK_V3 = 0x40
CONFIGURATION_BULK_REPORT_PROPERTIES1_DEFAULT_BIT_MASK_V3 = 0x80
# Values used for Configuration Bulk Set command
CONFIGURATION_BULK_SET_PROPERTIES1_SIZE_MASK_V3 = 0x07
CONFIGURATION_BULK_SET_PROPERTIES1_RESERVED_MASK_V3 = 0x38
CONFIGURATION_BULK_SET_PROPERTIES1_RESERVED_SHIFT_V3 = 0x03
CONFIGURATION_BULK_SET_PROPERTIES1_HANDSHAKE_BIT_MASK_V3 = 0x40
CONFIGURATION_BULK_SET_PROPERTIES1_DEFAULT_BIT_MASK_V3 = 0x80
# Values used for Configuration Report command
CONFIGURATION_REPORT_LEVEL_SIZE_MASK_V3 = 0x07
CONFIGURATION_REPORT_LEVEL_RESERVED_MASK_V3 = 0xF8
CONFIGURATION_REPORT_LEVEL_RESERVED_SHIFT_V3 = 0x03
# Values used for Configuration Set command
CONFIGURATION_SET_LEVEL_SIZE_MASK_V3 = 0x07
CONFIGURATION_SET_LEVEL_RESERVED_MASK_V3 = 0x78
CONFIGURATION_SET_LEVEL_RESERVED_SHIFT_V3 = 0x03
CONFIGURATION_SET_LEVEL_DEFAULT_BIT_MASK_V3 = 0x80
# Values used for Configuration Properties Report command
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES1_SIZE_MASK_V3 = 0x07
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES1_FORMAT_MASK_V3 = 0x38
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES1_FORMAT_SHIFT_V3 = 0x03
CONFIGURATION_PROPERTIES_REPORT_FORMAT_SIGNED_INTEGER_V3 = 0x00
CONFIGURATION_PROPERTIES_REPORT_FORMAT_UNSIGNED_INTEGER_V3 = 0x01
CONFIGURATION_PROPERTIES_REPORT_FORMAT_ENUMERATED_V3 = 0x02
CONFIGURATION_PROPERTIES_REPORT_FORMAT_BIT_FIELD_V3 = 0x03
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES1_RESERVED_MASK_V3 = 0xC0
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES1_RESERVED_SHIFT_V3 = 0x06

CONFIGURATION_VERSION_V4 = 0x04
CONFIGURATION_BULK_GET_V4 = 0x08
CONFIGURATION_BULK_REPORT_V4 = 0x09
CONFIGURATION_BULK_SET_V4 = 0x07
CONFIGURATION_GET_V4 = 0x05
CONFIGURATION_REPORT_V4 = 0x06
CONFIGURATION_SET_V4 = 0x04
CONFIGURATION_NAME_GET_V4 = 0x0A
CONFIGURATION_NAME_REPORT_V4 = 0x0B
CONFIGURATION_INFO_GET_V4 = 0x0C
CONFIGURATION_INFO_REPORT_V4 = 0x0D
CONFIGURATION_PROPERTIES_GET_V4 = 0x0E
CONFIGURATION_PROPERTIES_REPORT_V4 = 0x0F
# Configuration Default Reset
CONFIGURATION_DEFAULT_RESET_V4 = 0x01

# Values used for Configuration Bulk Report command
CONFIGURATION_BULK_REPORT_PROPERTIES1_SIZE_MASK_V4 = 0x07
CONFIGURATION_BULK_REPORT_PROPERTIES1_RESERVED_MASK_V4 = 0x38
CONFIGURATION_BULK_REPORT_PROPERTIES1_RESERVED_SHIFT_V4 = 0x03
CONFIGURATION_BULK_REPORT_PROPERTIES1_HANDSHAKE_BIT_MASK_V4 = 0x40
CONFIGURATION_BULK_REPORT_PROPERTIES1_DEFAULT_BIT_MASK_V4 = 0x80
# Values used for Configuration Bulk Set command
CONFIGURATION_BULK_SET_PROPERTIES1_SIZE_MASK_V4 = 0x07
CONFIGURATION_BULK_SET_PROPERTIES1_RESERVED_MASK_V4 = 0x38
CONFIGURATION_BULK_SET_PROPERTIES1_RESERVED_SHIFT_V4 = 0x03
CONFIGURATION_BULK_SET_PROPERTIES1_HANDSHAKE_BIT_MASK_V4 = 0x40
CONFIGURATION_BULK_SET_PROPERTIES1_DEFAULT_BIT_MASK_V4 = 0x80
# Values used for Configuration Report command
CONFIGURATION_REPORT_LEVEL_SIZE_MASK_V4 = 0x07
CONFIGURATION_REPORT_LEVEL_RESERVED_MASK_V4 = 0xF8
CONFIGURATION_REPORT_LEVEL_RESERVED_SHIFT_V4 = 0x03
# Values used for Configuration Set command
CONFIGURATION_SET_LEVEL_SIZE_MASK_V4 = 0x07
CONFIGURATION_SET_LEVEL_RESERVED_MASK_V4 = 0x78
CONFIGURATION_SET_LEVEL_RESERVED_SHIFT_V4 = 0x03
CONFIGURATION_SET_LEVEL_DEFAULT_BIT_MASK_V4 = 0x80
# Values used for Configuration Properties Report command
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES1_SIZE_MASK_V4 = 0x07
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES1_FORMAT_MASK_V4 = 0x38
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES1_FORMAT_SHIFT_V4 = 0x03
CONFIGURATION_PROPERTIES_REPORT_FORMAT_SIGNED_INTEGER_V4 = 0x00
CONFIGURATION_PROPERTIES_REPORT_FORMAT_UNSIGNED_INTEGER_V4 = 0x01
CONFIGURATION_PROPERTIES_REPORT_FORMAT_ENUMERATED_V4 = 0x02
CONFIGURATION_PROPERTIES_REPORT_FORMAT_BIT_FIELD_V4 = 0x03
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES1_READONLY_BIT_MASK_V4 = 0x40
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES1_ALTERING_CAPABILITIES_BIT_MASK_V4 = 0x80
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES2_ADVANCED_BIT_MASK_V4 = 0x01
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES2_NO_BULK_SUPPORT_BIT_MASK_V4 = 0x02
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES2_RESERVED1_MASK_V4 = 0xFC
CONFIGURATION_PROPERTIES_REPORT_PROPERTIES2_RESERVED1_SHIFT_V4 = 0x02






class ZW_CONFIGURATION_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('parameterNumber', uint8_t)]


class ZW_CONFIGURATION_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('parameterNumber', uint8_t),
        ('level', uint8_t),
        ('configurationValue1', uint8_t),
    ]


class ZW_CONFIGURATION_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('parameterNumber', uint8_t),
        ('level', uint8_t),
        ('configurationValue1', uint8_t),
    ]


class ZW_CONFIGURATION_BULK_GET_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('parameterOffset1', uint8_t),
        ('parameterOffset2', uint8_t),
        ('numberOfParameters', uint8_t),
    ]


class VG_CONFIGURATION_BULK_REPORT_V2_VG(ctypes.Structure):
    _fields_ = [('parameter1', uint8_t)]


class ZW_CONFIGURATION_BULK_REPORT_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('parameterOffset1', uint8_t),
        ('parameterOffset2', uint8_t),
        ('numberOfParameters', uint8_t),
        ('reportsToFollow', uint8_t),
        ('properties1', uint8_t),
        ('variantgroup1', VG_CONFIGURATION_BULK_REPORT_V2_VG),
    ]


class VG_CONFIGURATION_BULK_SET_V2_VG(ctypes.Structure):
    _fields_ = [('parameter1', uint8_t)]


class ZW_CONFIGURATION_BULK_SET_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('parameterOffset1', uint8_t),
        ('parameterOffset2', uint8_t),
        ('numberOfParameters', uint8_t),
        ('properties1', uint8_t),
        ('variantgroup1', VG_CONFIGURATION_BULK_SET_V2_VG),
    ]


class ZW_CONFIGURATION_GET_V2_FRAME(ZW_CONFIGURATION_GET_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_REPORT_V2_FRAME(ZW_CONFIGURATION_REPORT_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_SET_V2_FRAME(ZW_CONFIGURATION_SET_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_BULK_GET_V3_FRAME(ZW_CONFIGURATION_BULK_GET_V2_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_BULK_REPORT_V3_FRAME(ZW_CONFIGURATION_BULK_REPORT_V2_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_BULK_SET_V3_FRAME(ZW_CONFIGURATION_BULK_SET_V2_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_GET_V3_FRAME(ZW_CONFIGURATION_GET_V2_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_REPORT_V3_FRAME(ZW_CONFIGURATION_REPORT_V2_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_SET_V3_FRAME(ZW_CONFIGURATION_SET_V2_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_NAME_GET_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('parameterNumber1', uint8_t),
        ('parameterNumber2', uint8_t),
    ]


class ZW_CONFIGURATION_NAME_REPORT_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('parameterNumber1', uint8_t),
        ('parameterNumber2', uint8_t),
        ('reportsToFollow', uint8_t),
        ('name1', uint8_t),
    ]


class ZW_CONFIGURATION_INFO_GET_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('parameterNumber1', uint8_t),
        ('parameterNumber2', uint8_t),
    ]


class ZW_CONFIGURATION_INFO_REPORT_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('parameterNumber1', uint8_t),
        ('parameterNumber2', uint8_t),
        ('reportsToFollow', uint8_t),
        ('info1', uint8_t),
    ]


class ZW_CONFIGURATION_PROPERTIES_GET_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('parameterNumber1', uint8_t),
        ('parameterNumber2', uint8_t),
    ]


class ZW_CONFIGURATION_PROPERTIES_REPORT_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('parameterNumber1', uint8_t),
        ('parameterNumber2', uint8_t),
        ('properties1', uint8_t),
        ('minValue1', uint8_t),
        ('maxValue1', uint8_t),
        ('defaultValue1', uint8_t),
        ('nextParameterNumber1', uint8_t),
        ('nextParameterNumber2', uint8_t),
    ]


class ZW_CONFIGURATION_BULK_GET_V4_FRAME(ZW_CONFIGURATION_BULK_GET_V3_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_BULK_REPORT_V4_FRAME(ZW_CONFIGURATION_BULK_REPORT_V3_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_BULK_SET_V4_FRAME(ZW_CONFIGURATION_BULK_SET_V3_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_GET_V4_FRAME(ZW_CONFIGURATION_GET_V3_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_REPORT_V4_FRAME(ZW_CONFIGURATION_REPORT_V3_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_SET_V4_FRAME(ZW_CONFIGURATION_SET_V3_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_NAME_GET_V4_FRAME(ZW_CONFIGURATION_NAME_GET_V3_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_NAME_REPORT_V4_FRAME(ZW_CONFIGURATION_NAME_REPORT_V3_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_INFO_GET_V4_FRAME(ZW_CONFIGURATION_INFO_GET_V3_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_INFO_REPORT_V4_FRAME(ZW_CONFIGURATION_INFO_REPORT_V3_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_PROPERTIES_GET_V4_FRAME(ZW_CONFIGURATION_PROPERTIES_GET_V3_FRAME):
    _fields_ = []


class ZW_CONFIGURATION_PROPERTIES_REPORT_V4_FRAME(ZW_CONFIGURATION_PROPERTIES_REPORT_V3_FRAME):
    _fields_ = [('properties2', uint8_t)]


class ZW_CONFIGURATION_DEFAULT_RESET_V4_FRAME(ZW_COMMON_FRAME):
    _fields_ = []



