# Door Lock Command Class
# Application
COMMAND_CLASS_DOOR_LOCK = 0x62


# Door Lock Operation Set
DOOR_LOCK_OPERATION_SET = 0x01
# Door Lock Operation Get
DOOR_LOCK_OPERATION_GET = 0x02
# Door Lock Operation Report
DOOR_LOCK_OPERATION_REPORT = 0x03
# Door Lock Configuration Set
DOOR_LOCK_CONFIGURATION_SET = 0x04
# Door Lock Configuration Get
DOOR_LOCK_CONFIGURATION_GET = 0x05
# Door Lock Configuration Report
DOOR_LOCK_CONFIGURATION_REPORT = 0x06
# Door Lock Capabilities Get
DOOR_LOCK_CAPABILITIES_GET = 0x07
# Door Lock Capabilities Report
DOOR_LOCK_CAPABILITIES_REPORT = 0x08


DOOR_LOCK_VERSION = 0x01
DOOR_LOCK_CONFIGURATION_GET = 0x05
DOOR_LOCK_CONFIGURATION_REPORT = 0x06
DOOR_LOCK_CONFIGURATION_SET = 0x04
DOOR_LOCK_OPERATION_GET = 0x02
DOOR_LOCK_OPERATION_REPORT = 0x03
DOOR_LOCK_OPERATION_SET = 0x01
# Values used for Door Lock Configuration Report command
DOOR_LOCK_CONFIGURATION_REPORT_CONSTANT_OPERATION = 0x01
DOOR_LOCK_CONFIGURATION_REPORT_TIMED_OPERATION = 0x02
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES1_INSIDE_DOOR_HANDLES_ENABLED_MASK = 0x0F
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_MASK = 0xF0
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_SHIFT = 0x04
# Values used for Door Lock Configuration Set command
DOOR_LOCK_CONFIGURATION_SET_CONSTANT_OPERATION = 0x01
DOOR_LOCK_CONFIGURATION_SET_TIMED_OPERATION = 0x02
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES1_INSIDE_DOOR_HANDLES_ENABLED_MASK = 0x0F
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_MASK = 0xF0
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_SHIFT = 0x04
# Values used for Door Lock Operation Report command
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED = 0x00
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_WITH_TIMEOUT = 0x01
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES = 0x10
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_WITH_TIMEOUT = 0x11
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES = 0x20
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_WITH_TIMEOUT = 0x21
DOOR_LOCK_OPERATION_REPORT_DOOR_SECURED = 0xFF
DOOR_LOCK_OPERATION_REPORT_PROPERTIES1_INSIDE_DOOR_HANDLES_MODE_MASK = 0x0F
DOOR_LOCK_OPERATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_MODE_MASK = 0xF0
DOOR_LOCK_OPERATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_MODE_SHIFT = 0x04
# Values used for Door Lock Operation Set command
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED = 0x00
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_WITH_TIMEOUT = 0x01
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES = 0x10
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_WITH_TIMEOUT = 0x11
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES = 0x20
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_WITH_TIMEOUT = 0x21
DOOR_LOCK_OPERATION_SET_DOOR_SECURED = 0xFF

DOOR_LOCK_VERSION_V2 = 0x02
DOOR_LOCK_CONFIGURATION_GET_V2 = 0x05
DOOR_LOCK_CONFIGURATION_REPORT_V2 = 0x06
DOOR_LOCK_CONFIGURATION_SET_V2 = 0x04
DOOR_LOCK_OPERATION_GET_V2 = 0x02
DOOR_LOCK_OPERATION_REPORT_V2 = 0x03
DOOR_LOCK_OPERATION_SET_V2 = 0x01
# Values used for Door Lock Configuration Report command
DOOR_LOCK_CONFIGURATION_REPORT_CONSTANT_OPERATION_V2 = 0x01
DOOR_LOCK_CONFIGURATION_REPORT_TIMED_OPERATION_V2 = 0x02
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES1_INSIDE_DOOR_HANDLES_ENABLED_MASK_V2 = 0x0F
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_MASK_V2 = 0xF0
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_SHIFT_V2 = 0x04
# Values used for Door Lock Configuration Set command
DOOR_LOCK_CONFIGURATION_SET_CONSTANT_OPERATION_V2 = 0x01
DOOR_LOCK_CONFIGURATION_SET_TIMED_OPERATION_V2 = 0x02
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES1_INSIDE_DOOR_HANDLES_ENABLED_MASK_V2 = 0x0F
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_MASK_V2 = 0xF0
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_SHIFT_V2 = 0x04
# Values used for Door Lock Operation Report command
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_V2 = 0x00
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_WITH_TIMEOUT_V2 = 0x01
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_V2 = 0x10
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_WITH_TIMEOUT_V2 = 0x11
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_V2 = 0x20
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_WITH_TIMEOUT_V2 = 0x21
DOOR_LOCK_OPERATION_REPORT_DOOR_LOCK_STATE_UNKNOWN_V2 = 0xFE
DOOR_LOCK_OPERATION_REPORT_DOOR_SECURED_V2 = 0xFF
DOOR_LOCK_OPERATION_REPORT_PROPERTIES1_INSIDE_DOOR_HANDLES_MODE_MASK_V2 = 0x0F
DOOR_LOCK_OPERATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_MODE_MASK_V2 = 0xF0
DOOR_LOCK_OPERATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_MODE_SHIFT_V2 = 0x04
# Values used for Door Lock Operation Set command
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_V2 = 0x00
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_WITH_TIMEOUT_V2 = 0x01
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_V2 = 0x10
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_WITH_TIMEOUT_V2 = 0x11
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_V2 = 0x20
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_WITH_TIMEOUT_V2 = 0x21
DOOR_LOCK_OPERATION_SET_DOOR_SECURED_V2 = 0xFF

DOOR_LOCK_VERSION_V3 = 0x03
DOOR_LOCK_CONFIGURATION_GET_V3 = 0x05
DOOR_LOCK_CONFIGURATION_REPORT_V3 = 0x06
DOOR_LOCK_CONFIGURATION_SET_V3 = 0x04
DOOR_LOCK_OPERATION_GET_V3 = 0x02
DOOR_LOCK_OPERATION_REPORT_V3 = 0x03
DOOR_LOCK_OPERATION_SET_V3 = 0x01
# Values used for Door Lock Configuration Report command
DOOR_LOCK_CONFIGURATION_REPORT_CONSTANT_OPERATION_V3 = 0x01
DOOR_LOCK_CONFIGURATION_REPORT_TIMED_OPERATION_V3 = 0x02
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES1_INSIDE_DOOR_HANDLES_ENABLED_MASK_V3 = 0x0F
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_MASK_V3 = 0xF0
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_SHIFT_V3 = 0x04
# Values used for Door Lock Configuration Set command
DOOR_LOCK_CONFIGURATION_SET_CONSTANT_OPERATION_V3 = 0x01
DOOR_LOCK_CONFIGURATION_SET_TIMED_OPERATION_V3 = 0x02
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES1_INSIDE_DOOR_HANDLES_ENABLED_MASK_V3 = 0x0F
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_MASK_V3 = 0xF0
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_SHIFT_V3 = 0x04
# Values used for Door Lock Operation Report command
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_V3 = 0x00
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_WITH_TIMEOUT_V3 = 0x01
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_V3 = 0x10
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_WITH_TIMEOUT_V3 = 0x11
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_V3 = 0x20
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_WITH_TIMEOUT_V3 = 0x21
DOOR_LOCK_OPERATION_REPORT_DOOR_LOCK_STATE_UNKNOWN_V3 = 0xFE
DOOR_LOCK_OPERATION_REPORT_DOOR_SECURED_V3 = 0xFF
DOOR_LOCK_OPERATION_REPORT_PROPERTIES1_INSIDE_DOOR_HANDLES_MODE_MASK_V3 = 0x0F
DOOR_LOCK_OPERATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_MODE_MASK_V3 = 0xF0
DOOR_LOCK_OPERATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_MODE_SHIFT_V3 = 0x04

DOOR_LOCK_OPERATION_REPORT_ALREADY_AT_THE_TARGET_VALUE_V3 = 0x00
DOOR_LOCK_OPERATION_REPORT_UNKNOWN_DURATION_V3 = 0xFE
DOOR_LOCK_OPERATION_REPORT_RESERVED_V3 = 0xFF
# Values used for Door Lock Operation Set command
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_V3 = 0x00
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_WITH_TIMEOUT_V3 = 0x01
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_V3 = 0x10
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_WITH_TIMEOUT_V3 = 0x11
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_V3 = 0x20
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_WITH_TIMEOUT_V3 = 0x21
DOOR_LOCK_OPERATION_SET_DOOR_SECURED_V3 = 0xFF

DOOR_LOCK_VERSION_V4 = 0x04
DOOR_LOCK_CONFIGURATION_GET_V4 = 0x05
DOOR_LOCK_CONFIGURATION_REPORT_V4 = 0x06
DOOR_LOCK_CONFIGURATION_SET_V4 = 0x04
DOOR_LOCK_OPERATION_GET_V4 = 0x02
DOOR_LOCK_OPERATION_REPORT_V4 = 0x03
DOOR_LOCK_OPERATION_SET_V4 = 0x01
DOOR_LOCK_CAPABILITIES_GET_V4 = 0x07
DOOR_LOCK_CAPABILITIES_REPORT_V4 = 0x08
# Values used for Door Lock Configuration Report command
DOOR_LOCK_CONFIGURATION_REPORT_CONSTANT_OPERATION_V4 = 0x01
DOOR_LOCK_CONFIGURATION_REPORT_TIMED_OPERATION_V4 = 0x02
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES1_INSIDE_DOOR_HANDLES_ENABLED_MASK_V4 = 0x0F
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_MASK_V4 = 0xF0
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_SHIFT_V4 = 0x04
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES2_TA_BIT_MASK_V4 = 0x01
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES2_BTB_BIT_MASK_V4 = 0x02
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES2_RESERVED1_MASK_V4 = 0xFC
DOOR_LOCK_CONFIGURATION_REPORT_PROPERTIES2_RESERVED1_SHIFT_V4 = 0x02
# Values used for Door Lock Configuration Set command
DOOR_LOCK_CONFIGURATION_SET_CONSTANT_OPERATION_V4 = 0x01
DOOR_LOCK_CONFIGURATION_SET_TIMED_OPERATION_V4 = 0x02
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES1_INSIDE_DOOR_HANDLES_ENABLED_MASK_V4 = 0x0F
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_MASK_V4 = 0xF0
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES1_OUTSIDE_DOOR_HANDLES_ENABLED_SHIFT_V4 = 0x04
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES2_TA_BIT_MASK_V4 = 0x01
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES2_BTB_BIT_MASK_V4 = 0x02
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES2_RESERVED1_MASK_V4 = 0xFC
DOOR_LOCK_CONFIGURATION_SET_PROPERTIES2_RESERVED1_SHIFT_V4 = 0x02
# Values used for Door Lock Operation Report command
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_V4 = 0x00
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_WITH_TIMEOUT_V4 = 0x01
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_V4 = 0x10
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_WITH_TIMEOUT_V4 = 0x11
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_V4 = 0x20
DOOR_LOCK_OPERATION_REPORT_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_WITH_TIMEOUT_V4 = 0x21
DOOR_LOCK_OPERATION_REPORT_DOOR_MODE_UNKNOWN_V4 = 0xFE
DOOR_LOCK_OPERATION_REPORT_DOOR_SECURED_V4 = 0xFF
DOOR_LOCK_OPERATION_REPORT_PROPERTIES1_INSIDE_DOOR_HANDLES_MODE_MASK_V4 = 0x0F
DOOR_LOCK_OPERATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_MODE_MASK_V4 = 0xF0
DOOR_LOCK_OPERATION_REPORT_PROPERTIES1_OUTSIDE_DOOR_HANDLES_MODE_SHIFT_V4 = 0x04
DOOR_LOCK_OPERATION_REPORT_ALREADY_AT_THE_TARGET_VALUE_V4 = 0x00
DOOR_LOCK_OPERATION_REPORT_UNKNOWN_DURATION_V4 = 0xFE
DOOR_LOCK_OPERATION_REPORT_RESERVED_V4 = 0xFF
# Values used for Door Lock Operation Set command
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_V4 = 0x00
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_WITH_TIMEOUT_V4 = 0x01
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_V4 = 0x10
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_WITH_TIMEOUT_V4 = 0x11
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_V4 = 0x20
DOOR_LOCK_OPERATION_SET_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_WITH_TIMEOUT_V4 = 0x21
DOOR_LOCK_OPERATION_SET_DOOR_SECURED_V4 = 0xFF
# Values used for Door Lock Capabilities Report command
DOOR_LOCK_CAPABILITIES_REPORT_PROPERTIES1_SUPPORTED_OPERATION_TYPE_BIT_MASK_LENGTH_MASK_V4 = 0x1F
DOOR_LOCK_CAPABILITIES_REPORT_PROPERTIES1_RESERVED_MASK_V4 = 0xE0
DOOR_LOCK_CAPABILITIES_REPORT_PROPERTIES1_RESERVED_SHIFT_V4 = 0x05
DOOR_LOCK_CAPABILITIES_REPORT_PROPERTIES2_SUPPORTED_INSIDE_HANDLE_MODES_BITMASK_MASK_V4 = 0x0F
DOOR_LOCK_CAPABILITIES_REPORT_PROPERTIES2_SUPPORTED_OUTSIDE_HANDLE_MODES_BITMASK_MASK_V4 = 0xF0
DOOR_LOCK_CAPABILITIES_REPORT_PROPERTIES2_SUPPORTED_OUTSIDE_HANDLE_MODES_BITMASK_SHIFT_V4 = 0x04
DOOR_LOCK_CAPABILITIES_REPORT_PROPERTIES3_BTBS_BIT_MASK_V4 = 0x01
DOOR_LOCK_CAPABILITIES_REPORT_PROPERTIES3_TAS_BIT_MASK_V4 = 0x02
DOOR_LOCK_CAPABILITIES_REPORT_PROPERTIES3_HRS_BIT_MASK_V4 = 0x04
DOOR_LOCK_CAPABILITIES_REPORT_PROPERTIES3_ARS_BIT_MASK_V4 = 0x08
DOOR_LOCK_CAPABILITIES_REPORT_PROPERTIES3_RESERVED_MASK_V4 = 0xF0
DOOR_LOCK_CAPABILITIES_REPORT_PROPERTIES3_RESERVED_SHIFT_V4 = 0x04





class ZW_DOOR_LOCK_CONFIGURATION_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_CONFIGURATION_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('operationType', uint8_t),
        ('properties1', uint8_t),
        ('lockTimeoutMinutes', uint8_t),
        ('lockTimeoutSeconds', uint8_t),
    ]


class ZW_DOOR_LOCK_CONFIGURATION_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('operationType', uint8_t),
        ('properties1', uint8_t),
        ('lockTimeoutMinutes', uint8_t),
        ('lockTimeoutSeconds', uint8_t),
    ]


class ZW_DOOR_LOCK_OPERATION_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_OPERATION_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('doorLockMode', uint8_t),
        ('properties1', uint8_t),
        ('doorCondition', uint8_t),
        ('remainingLockTimeMinutes', uint8_t),
        ('remainingLockTimeSeconds', uint8_t),
    ]


class ZW_DOOR_LOCK_OPERATION_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('doorLockMode', uint8_t)]


class ZW_DOOR_LOCK_CONFIGURATION_GET_V2_FRAME(ZW_DOOR_LOCK_CONFIGURATION_GET_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_CONFIGURATION_REPORT_V2_FRAME(ZW_DOOR_LOCK_CONFIGURATION_REPORT_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_CONFIGURATION_SET_V2_FRAME(ZW_DOOR_LOCK_CONFIGURATION_SET_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_OPERATION_GET_V2_FRAME(ZW_DOOR_LOCK_OPERATION_GET_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_OPERATION_REPORT_V2_FRAME(ZW_DOOR_LOCK_OPERATION_REPORT_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_OPERATION_SET_V2_FRAME(ZW_DOOR_LOCK_OPERATION_SET_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_CONFIGURATION_GET_V3_FRAME(ZW_DOOR_LOCK_CONFIGURATION_GET_V2_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_CONFIGURATION_REPORT_V3_FRAME(ZW_DOOR_LOCK_CONFIGURATION_REPORT_V2_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_CONFIGURATION_SET_V3_FRAME(ZW_DOOR_LOCK_CONFIGURATION_SET_V2_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_OPERATION_GET_V3_FRAME(ZW_DOOR_LOCK_OPERATION_GET_V2_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_OPERATION_REPORT_V3_FRAME(ZW_DOOR_LOCK_OPERATION_REPORT_V2_FRAME):
    _fields_ = [
        ('currentDoorLockMode', uint8_t),
        ('targetDoorLockMode', uint8_t),
        ('duration', uint8_t),
    ]


class ZW_DOOR_LOCK_OPERATION_SET_V3_FRAME(ZW_DOOR_LOCK_OPERATION_SET_V2_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_CONFIGURATION_GET_V4_FRAME(ZW_DOOR_LOCK_CONFIGURATION_GET_V3_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_CONFIGURATION_REPORT_V4_FRAME(ZW_DOOR_LOCK_CONFIGURATION_REPORT_V3_FRAME):
    _fields_ = [
        ('autoRelockTime1', uint8_t),
        ('autoRelockTime2', uint8_t),
        ('holdAndReleaseTime1', uint8_t),
        ('holdAndReleaseTime2', uint8_t),
        ('properties2', uint8_t),
    ]


class ZW_DOOR_LOCK_CONFIGURATION_SET_V4_FRAME(ZW_DOOR_LOCK_CONFIGURATION_SET_V3_FRAME):
    _fields_ = [
        ('autoRelockTime1', uint8_t),
        ('autoRelockTime2', uint8_t),
        ('holdAndReleaseTime1', uint8_t),
        ('holdAndReleaseTime2', uint8_t),
        ('properties2', uint8_t),
    ]


class ZW_DOOR_LOCK_OPERATION_GET_V4_FRAME(ZW_DOOR_LOCK_OPERATION_GET_V3_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_OPERATION_REPORT_V4_FRAME(ZW_DOOR_LOCK_OPERATION_REPORT_V3_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_OPERATION_SET_V4_FRAME(ZW_DOOR_LOCK_OPERATION_SET_V3_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_CAPABILITIES_GET_V4_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_DOOR_LOCK_CAPABILITIES_REPORT_V4_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('supportedOperationTypeBitMask1', uint8_t),
        ('supportedDoorLockModeListLength', uint8_t),
        ('supportedDoorLockMode1', uint8_t),
        ('properties2', uint8_t),
        ('supportedDoorComponents', uint8_t),
        ('properties3', uint8_t),
    ]




