# Energy Production Command Class
# Application
# ==============================
COMMAND_CLASS_ENERGY_PRODUCTION = 0x90

ENERGY_PRODUCTION_VERSION = 0x01
# Energy Production Get
ENERGY_PRODUCTION_GET = 0x02
# Energy Production Report
ENERGY_PRODUCTION_REPORT = 0x03

# Values used for Energy Production Get command
ENERGY_PRODUCTION_GET_INSTANT_ENERGY_PRODUCTION = 0x00
ENERGY_PRODUCTION_GET_TOTAL_ENERGY_PRODUCTION = 0x01
ENERGY_PRODUCTION_GET_ENERGY_PRODUCTION_TODAY = 0x02
ENERGY_PRODUCTION_GET_TOTAL_PRODUCTION_TIME = 0x03
# Values used for Energy Production Report command
ENERGY_PRODUCTION_REPORT_INSTANT_ENERGY_PRODUCTION = 0x00
ENERGY_PRODUCTION_REPORT_TOTAL_ENERGY_PRODUCTION = 0x01
ENERGY_PRODUCTION_REPORT_ENERGY_PRODUCTION_TODAY = 0x02
ENERGY_PRODUCTION_REPORT_TOTAL_PRODUCTION_TIME = 0x03
ENERGY_PRODUCTION_REPORT_LEVEL_SIZE_MASK = 0x07
ENERGY_PRODUCTION_REPORT_LEVEL_SCALE_MASK = 0x18
ENERGY_PRODUCTION_REPORT_LEVEL_SCALE_SHIFT = 0x03
ENERGY_PRODUCTION_REPORT_LEVEL_PRECISION_MASK = 0xE0
ENERGY_PRODUCTION_REPORT_LEVEL_PRECISION_SHIFT = 0x05


class ZW_ENERGY_PRODUCTION_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('parameterNumber', uint8_t)]


class ZW_ENERGY_PRODUCTION_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('parameterNumber', uint8_t),
        ('level', uint8_t),
        ('value1', uint8_t),
    ]


