# Generic Schedule Command Class
# Application
# ==============================
COMMAND_CLASS_GENERIC_SCHEDULE = 0xA3

GENERIC_SCHEDULE_VERSION = 0x01
# Generic Schedule Capabilities Get Command
GENERIC_SCHEDULE_CAPABILITIES_GET = 0x01
# Generic Schedule Capabilities Report Command
GENERIC_SCHEDULE_CAPABILITIES_REPORT = 0x02
# Generic Schedule Time Range Set Command
GENERIC_SCHEDULE_TIME_RANGE_SET = 0x03
# Generic Schedule Time Range Get Command
GENERIC_SCHEDULE_TIME_RANGE_GET = 0x04
# Generic Schedule Time Range Report Command
GENERIC_SCHEDULE_TIME_RANGE_REPORT = 0x05
# Generic Schedule Set Command
GENERIC_SCHEDULE_SET = 0x06
# Generic Schedule Get Command
GENERIC_SCHEDULE_GET = 0x07
# Generic Schedule Report Command
GENERIC_SCHEDULE_REPORT = 0x08

# Values used for Generic Schedule Capabilities Report command
GENERIC_SCHEDULE_CAPABILITIES_REPORT_PROPERTIES1_NUMBER_OF_SUPPORTED_TIME_RANGE_IDS_1_MASK = 0x7F
GENERIC_SCHEDULE_CAPABILITIES_REPORT_PROPERTIES1_RESERVED1_BIT_MASK = 0x80
GENERIC_SCHEDULE_CAPABILITIES_REPORT_PROPERTIES2_HOUR_MINUTE_BIT_MASK = 0x01
GENERIC_SCHEDULE_CAPABILITIES_REPORT_PROPERTIES2_DATE_BIT_MASK = 0x02
GENERIC_SCHEDULE_CAPABILITIES_REPORT_PROPERTIES2_WEEKDAYS_BIT_MASK = 0x04
GENERIC_SCHEDULE_CAPABILITIES_REPORT_PROPERTIES2_RESERVED2_MASK = 0xF8
GENERIC_SCHEDULE_CAPABILITIES_REPORT_PROPERTIES2_RESERVED2_SHIFT = 0x03
# Values used for Generic Schedule Time Range Set command
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES1_TIME_RANGE_ID_1_MASK = 0x7F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES1_RESERVED1_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES2_WEEKDAY_BITMASK_MASK = 0x7F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES2_IN_USE_1_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES3_START_YEAR_1_MASK = 0x7F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES3_IN_USE_2_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES4_STOP_YEAR_1_MASK = 0x7F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES4_IN_USE_3_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES5_START_MONTH_MASK = 0x0F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES5_RESERVED2_MASK = 0x70
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES5_RESERVED2_SHIFT = 0x04
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES5_IN_USE_4_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES6_STOP_MONTH_MASK = 0x0F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES6_RESERVED3_MASK = 0x70
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES6_RESERVED3_SHIFT = 0x04
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES6_IN_USE_5_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES7_START_DAY_MASK = 0x1F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES7_RESERVED4_MASK = 0x60
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES7_RESERVED4_SHIFT = 0x05
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES7_IN_USE_6_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES8_STOP_DAY_MASK = 0x1F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES8_RESERVED5_MASK = 0x60
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES8_RESERVED5_SHIFT = 0x05
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES8_IN_USE_7_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES9_START_HOUR_MASK = 0x1F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES9_RESERVED6_MASK = 0x60
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES9_RESERVED6_SHIFT = 0x05
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES9_IN_USE_8_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES10_STOP_HOUR_MASK = 0x1F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES10_RESERVED7_MASK = 0x60
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES10_RESERVED7_SHIFT = 0x05
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES10_IN_USE_9_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES11_START_MINUTE_MASK = 0x3F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES11_RESERVED8_BIT_MASK = 0x40
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES11_IN_USE_10_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES12_STOP_MINUTE_MASK = 0x3F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES12_RESERVED9_BIT_MASK = 0x40
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES12_IN_USE_11_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES13_DAILY_START_HOUR_MASK = 0x1F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES13_RESERVED10_MASK = 0x60
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES13_RESERVED10_SHIFT = 0x05
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES13_IN_USE_12_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES14_DAILY_STOP_HOUR_MASK = 0x1F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES14_RESERVED11_MASK = 0x60
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES14_RESERVED11_SHIFT = 0x05
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES14_IN_USE_13_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES15_DAILY_START_MINUTE_MASK = 0x3F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES15_RESERVED12_BIT_MASK = 0x40
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES15_IN_USE_14_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES16_DAILY_STOP_MINUTE_MASK = 0x3F
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES16_RESERVED13_BIT_MASK = 0x40
GENERIC_SCHEDULE_TIME_RANGE_SET_PROPERTIES16_IN_USE_15_BIT_MASK = 0x80
# Values used for Generic Schedule Time Range Get command
GENERIC_SCHEDULE_TIME_RANGE_GET_PROPERTIES1_TIME_RANGE_ID_1_MASK = 0x7F
GENERIC_SCHEDULE_TIME_RANGE_GET_PROPERTIES1_RESERVED1_BIT_MASK = 0x80
# Values used for Generic Schedule Time Range Report command
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES1_TIME_RANGE_ID_1_MASK = 0x7F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES1_RESERVED1_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES2_WEEKDAY_BITMASK_MASK = 0x7F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES2_IN_USE_1_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES3_START_YEAR_1_MASK = 0x7F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES3_IN_USE_2_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES4_STOP_YEAR_1_MASK = 0x7F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES4_IN_USE_3_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES5_START_MONTH_MASK = 0x0F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES5_RESERVED2_MASK = 0x70
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES5_RESERVED2_SHIFT = 0x04
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES5_IN_USE_4_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES6_STOP_MONTH_MASK = 0x0F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES6_RESERVED3_MASK = 0x70
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES6_RESERVED3_SHIFT = 0x04
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES6_IN_USE_5_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES7_START_DAY_MASK = 0x1F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES7_RESERVED4_MASK = 0x60
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES7_RESERVED4_SHIFT = 0x05
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES7_IN_USE_6_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES8_STOP_DAY_MASK = 0x1F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES8_RESERVED5_MASK = 0x60
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES8_RESERVED5_SHIFT = 0x05
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES8_IN_USE_7_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES9_START_HOUR_MASK = 0x1F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES9_RESERVED6_MASK = 0x60
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES9_RESERVED6_SHIFT = 0x05
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES9_IN_USE_8_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES10_STOP_HOUR_MASK = 0x1F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES10_RESERVED7_MASK = 0x60
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES10_RESERVED7_SHIFT = 0x05
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES10_IN_USE_9_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES11_START_MINUTE_MASK = 0x3F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES11_RESERVED8_BIT_MASK = 0x40
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES11_IN_USE_10_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES12_STOP_MINUTE_MASK = 0x3F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES12_RESERVED9_BIT_MASK = 0x40
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES12_IN_USE_11_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES13_DAILY_START_HOUR_MASK = 0x1F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES13_RESERVED10_MASK = 0x60
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES13_RESERVED10_SHIFT = 0x05
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES13_IN_USE_12_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES14_DAILY_STOP_HOUR_MASK = 0x1F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES14_RESERVED11_MASK = 0x60
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES14_RESERVED11_SHIFT = 0x05
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES14_IN_USE_13_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES15_DAILY_START_MINUTE_MASK = 0x3F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES15_RESERVED12_BIT_MASK = 0x40
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES15_IN_USE_14_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES16_DAILY_STOP_MINUTE_MASK = 0x3F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES16_RESERVED13_BIT_MASK = 0x40
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES16_IN_USE_15_BIT_MASK = 0x80
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES17_NEXT_TIME_RANGE_ID_1_MASK = 0x7F
GENERIC_SCHEDULE_TIME_RANGE_REPORT_PROPERTIES17_RESERVED14_BIT_MASK = 0x80


class ZW_GENERIC_SCHEDULE_CAPABILITIES_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_GENERIC_SCHEDULE_CAPABILITIES_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('numberOfSupportedScheduleIds1', uint8_t),
        ('numberOfSupportedScheduleIds2', uint8_t),
        ('properties1', uint8_t),
        ('numberOfSupportedTimeRangeIds2', uint8_t),
        ('numberOfSupportedTimeRangesPerSchedule', uint8_t),
        ('properties2', uint8_t),
    ]


class ZW_GENERIC_SCHEDULE_TIME_RANGE_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('timeRangeId2', uint8_t),
        ('properties2', uint8_t),
        ('properties3', uint8_t),
        ('startYear2', uint8_t),
        ('properties4', uint8_t),
        ('stopYear2', uint8_t),
        ('properties5', uint8_t),
        ('properties6', uint8_t),
        ('properties7', uint8_t),
        ('properties8', uint8_t),
        ('properties9', uint8_t),
        ('properties10', uint8_t),
        ('properties11', uint8_t),
        ('properties12', uint8_t),
        ('properties13', uint8_t),
        ('properties14', uint8_t),
        ('properties15', uint8_t),
        ('properties16', uint8_t),
    ]


class ZW_GENERIC_SCHEDULE_TIME_RANGE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('timeRangeId2', uint8_t),
    ]


class ZW_GENERIC_SCHEDULE_TIME_RANGE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('timeRangeId2', uint8_t),
        ('properties2', uint8_t),
        ('properties3', uint8_t),
        ('startYear2', uint8_t),
        ('properties4', uint8_t),
        ('stopYear2', uint8_t),
        ('properties5', uint8_t),
        ('properties6', uint8_t),
        ('properties7', uint8_t),
        ('properties8', uint8_t),
        ('properties9', uint8_t),
        ('properties10', uint8_t),
        ('properties11', uint8_t),
        ('properties12', uint8_t),
        ('properties13', uint8_t),
        ('properties14', uint8_t),
        ('properties15', uint8_t),
        ('properties16', uint8_t),
        ('properties17', uint8_t),
        ('nextTimeRangeId2', uint8_t),
    ]


class VG_GENERIC_SCHEDULE_SET_VG(ctypes.Structure):
    _fields_ = [
        ('properties1', uint8_t),
        ('timeRangeId2', uint8_t),
    ]


class ZW_GENERIC_SCHEDULE_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('scheduleId1', uint8_t),
        ('scheduleId2', uint8_t),
        ('numberOfTimeRangeIds', uint8_t),
        ('variantgroup1', VG_GENERIC_SCHEDULE_SET_VG),
    ]


class ZW_GENERIC_SCHEDULE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('scheduleId1', uint8_t),
        ('scheduleId2', uint8_t),
    ]


class VG_GENERIC_SCHEDULE_REPORT_VG(ctypes.Structure):
    _fields_ = [
        ('properties1', uint8_t),
        ('timeRangeId2', uint8_t),
    ]


class ZW_GENERIC_SCHEDULE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('scheduleId1', uint8_t),
        ('scheduleId2', uint8_t),
        ('numberOfTimeRangeIds', uint8_t),
        ('variantgroup1', VG_GENERIC_SCHEDULE_REPORT_VG),
        ('nextScheduleId1', uint8_t),
        ('nextScheduleId2', uint8_t),
    ]

