# HRV Control Command Class
# Application
# ==============================
COMMAND_CLASS_HRV_CONTROL = 0x39

HRV_CONTROL_VERSION = 0x01
# HRV Mode Set
HRV_CONTROL_MODE_SET = 0x01
# HRV Mode Get
HRV_CONTROL_MODE_GET = 0x02
# HRV Mode Report
HRV_CONTROL_MODE_REPORT = 0x03
# HRV Bypass Set
HRV_CONTROL_BYPASS_SET = 0x04
# HRV Bypass Get
HRV_CONTROL_BYPASS_GET = 0x05
# HRV Bypass Report
HRV_CONTROL_BYPASS_REPORT = 0x06
# HRV Ventilation Rate Set
HRV_CONTROL_VENTILATION_RATE_SET = 0x07
# HRV Ventilation Rate Get
HRV_CONTROL_VENTILATION_RATE_GET = 0x08
# HRV Ventilation Rate Report
HRV_CONTROL_VENTILATION_RATE_REPORT = 0x09
# HRV Mode Supported Get
HRV_CONTROL_MODE_SUPPORTED_GET = 0x0A
# HRV Mode Supported Report
HRV_CONTROL_MODE_SUPPORTED_REPORT = 0x0B

# Values used for Hrv Control Mode Report command
HRV_CONTROL_MODE_REPORT_PROPERTIES1_MODE_MASK = 0x1F
HRV_CONTROL_MODE_REPORT_MODE_OFF = 0x00
HRV_CONTROL_MODE_REPORT_MODE_DEMAND_AUTOMATIC = 0x01
HRV_CONTROL_MODE_REPORT_MODE_SCHEDULE = 0x02
HRV_CONTROL_MODE_REPORT_MODE_ENERGY_SAVINGS_MODE = 0x03
HRV_CONTROL_MODE_REPORT_MODE_MANUAL = 0x04
HRV_CONTROL_MODE_REPORT_PROPERTIES1_RESERVED_MASK = 0xE0
HRV_CONTROL_MODE_REPORT_PROPERTIES1_RESERVED_SHIFT = 0x05
# Values used for Hrv Control Mode Set command
HRV_CONTROL_MODE_SET_PROPERTIES1_MODE_MASK = 0x1F
HRV_CONTROL_MODE_SET_MODE_OFF = 0x00
HRV_CONTROL_MODE_SET_MODE_DEMAND_AUTOMATIC = 0x01
HRV_CONTROL_MODE_SET_MODE_SCHEDULE = 0x02
HRV_CONTROL_MODE_SET_MODE_ENERGY_SAVINGS_MODE = 0x03
HRV_CONTROL_MODE_SET_MODE_MANUAL = 0x04
HRV_CONTROL_MODE_SET_PROPERTIES1_RESERVED_MASK = 0xE0
HRV_CONTROL_MODE_SET_PROPERTIES1_RESERVED_SHIFT = 0x05
# Values used for Hrv Control Mode Supported Report command
HRV_CONTROL_MODE_SUPPORTED_REPORT_PROPERTIES1_MANUAL_CONTROL_SUPPORTED_MASK = 0x0F
HRV_CONTROL_MODE_SUPPORTED_REPORT_MANUAL_CONTROL_SUPPORTED_BYPASS_OPEN_CLOSE = 0x00
HRV_CONTROL_MODE_SUPPORTED_REPORT_MANUAL_CONTROL_SUPPORTED_BYPASS_AUTO = 0x01
HRV_CONTROL_MODE_SUPPORTED_REPORT_MANUAL_CONTROL_SUPPORTED_MODULATED_BYPASS = 0x02
HRV_CONTROL_MODE_SUPPORTED_REPORT_MANUAL_CONTROL_SUPPORTED_VENTILATION_RATE = 0x03
HRV_CONTROL_MODE_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK = 0xF0
HRV_CONTROL_MODE_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT = 0x04


class ZW_HRV_CONTROL_BYPASS_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_HRV_CONTROL_BYPASS_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('bypass', uint8_t)]


class ZW_HRV_CONTROL_BYPASS_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('bypass', uint8_t)]


class ZW_HRV_CONTROL_MODE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_HRV_CONTROL_MODE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('properties1', uint8_t)]


class ZW_HRV_CONTROL_MODE_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('properties1', uint8_t)]


class ZW_HRV_CONTROL_MODE_SUPPORTED_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_HRV_CONTROL_MODE_SUPPORTED_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('bitMask1', uint8_t),
    ]


class ZW_HRV_CONTROL_VENTILATION_RATE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_HRV_CONTROL_VENTILATION_RATE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('ventilationRate', uint8_t)]


class ZW_HRV_CONTROL_VENTILATION_RATE_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('ventilationRate', uint8_t)]


