# HRV Status Command Class
# Application
# ==============================
COMMAND_CLASS_HRV_STATUS = 0x37

HRV_STATUS_VERSION = 0x01
# HRV Status Get
HRV_STATUS_GET = 0x01
# HRV Status Report
HRV_STATUS_REPORT = 0x02
# HRV Status Supported Get
HRV_STATUS_SUPPORTED_GET = 0x03
# HRV Status Supported Report
HRV_STATUS_SUPPORTED_REPORT = 0x04

# Values used for Hrv Status Get command
HRV_STATUS_GET_OUTDOOR_AIR_TEMPERATURE = 0x00
HRV_STATUS_GET_SUPPLY_AIR_TEMPERATURE = 0x01
HRV_STATUS_GET_EXHAUST_AIR_TEMPERATURE = 0x02
HRV_STATUS_GET_DISCHARGE_AIR_TEMPERATURE = 0x03
HRV_STATUS_GET_ROOM_TEMPERATURE = 0x04
HRV_STATUS_GET_RELATIVE_HUMIDITY_IN_ROOM = 0x05
HRV_STATUS_GET_REMAINING_FILTER_LIFE = 0x06
# Values used for Hrv Status Report command
HRV_STATUS_REPORT_OUTDOOR_AIR_TEMPERATURE = 0x00
HRV_STATUS_REPORT_SUPPLY_AIR_TEMPERATURE = 0x01
HRV_STATUS_REPORT_EXHAUST_AIR_TEMPERATURE = 0x02
HRV_STATUS_REPORT_DISCHARGE_AIR_TEMPERATURE = 0x03
HRV_STATUS_REPORT_ROOM_TEMPERATURE = 0x04
HRV_STATUS_REPORT_RELATIVE_HUMIDITY_IN_ROOM = 0x05
HRV_STATUS_REPORT_REMAINING_FILTER_LIFE = 0x06
HRV_STATUS_REPORT_PROPERTIES1_SIZE_MASK = 0x07
HRV_STATUS_REPORT_PROPERTIES1_SCALE_MASK = 0x18
HRV_STATUS_REPORT_PROPERTIES1_SCALE_SHIFT = 0x03
HRV_STATUS_REPORT_PROPERTIES1_PRECISION_MASK = 0xE0
HRV_STATUS_REPORT_PROPERTIES1_PRECISION_SHIFT = 0x05

class ZW_HRV_STATUS_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('statusParameter', uint8_t)]


class ZW_HRV_STATUS_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('statusParameter', uint8_t),
        ('properties1', uint8_t),
        ('value1', uint8_t),
    ]


class ZW_HRV_STATUS_SUPPORTED_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_HRV_STATUS_SUPPORTED_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('bitMask1', uint8_t)]

