# Humidity Control Operating State Command Class
# Application
# ==============================
COMMAND_CLASS_HUMIDITY_CONTROL_OPERATING_STATE = 0x6E

HUMIDITY_CONTROL_OPERATING_STATE_VERSION = 0x01
# Humidity Control Operating State Get
HUMIDITY_CONTROL_OPERATING_STATE_GET = 0x01
# Humidity Control Operating State Report
HUMIDITY_CONTROL_OPERATING_STATE_REPORT = 0x02

# Values used for Humidity Control Operating State Report command
HUMIDITY_CONTROL_OPERATING_STATE_REPORT_PROPERTIES1_OPERATING_STATE_MASK = 0x0F
HUMIDITY_CONTROL_OPERATING_STATE_REPORT_OPERATING_STATE_IDLE = 0x00
HUMIDITY_CONTROL_OPERATING_STATE_REPORT_OPERATING_STATE_HUMIDIFYING = 0x01
HUMIDITY_CONTROL_OPERATING_STATE_REPORT_OPERATING_STATE_DEHUMIDIFYING = 0x02
HUMIDITY_CONTROL_OPERATING_STATE_REPORT_PROPERTIES1_RESERVED_MASK = 0xF0
HUMIDITY_CONTROL_OPERATING_STATE_REPORT_PROPERTIES1_RESERVED_SHIFT = 0x04


class ZW_HUMIDITY_CONTROL_OPERATING_STATE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_HUMIDITY_CONTROL_OPERATING_STATE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('properties1', uint8_t)]

