# Humidity Control Mode Command Class
# Application
# ==============================
COMMAND_CLASS_HUMIDITY_CONTROL_MODE = 0x6D

HUMIDITY_CONTROL_MODE_VERSION = 0x01
# Humidity Control Mode Set
HUMIDITY_CONTROL_MODE_SET = 0x01
# Humidity Control Mode Get
HUMIDITY_CONTROL_MODE_GET = 0x02
# Humidity Control Mode Report
HUMIDITY_CONTROL_MODE_REPORT = 0x03
# Humidity Control Mode Supported Get
HUMIDITY_CONTROL_MODE_SUPPORTED_GET = 0x04
# Humidity Control Mode Supported Report
HUMIDITY_CONTROL_MODE_SUPPORTED_REPORT = 0x05

# Values used for Humidity Control Mode Set command
HUMIDITY_CONTROL_MODE_SET_PROPERTIES1_MODE_MASK = 0x0F
HUMIDITY_CONTROL_MODE_SET_MODE_OFF = 0x00
HUMIDITY_CONTROL_MODE_SET_MODE_HUMIDIFY = 0x01
HUMIDITY_CONTROL_MODE_SET_MODE_DEHUMIDIFY = 0x02
HUMIDITY_CONTROL_MODE_SET_PROPERTIES1_RESERVED_MASK = 0xF0
HUMIDITY_CONTROL_MODE_SET_PROPERTIES1_RESERVED_SHIFT = 0x04
# Values used for Humidity Control Mode Report command
HUMIDITY_CONTROL_MODE_REPORT_PROPERTIES1_MODE_MASK = 0x0F
HUMIDITY_CONTROL_MODE_REPORT_MODE_OFF = 0x00
HUMIDITY_CONTROL_MODE_REPORT_MODE_HUMIDIFY = 0x01
HUMIDITY_CONTROL_MODE_REPORT_MODE_DEHUMIDIFY = 0x02
HUMIDITY_CONTROL_MODE_REPORT_PROPERTIES1_RESERVED_MASK = 0xF0
HUMIDITY_CONTROL_MODE_REPORT_PROPERTIES1_RESERVED_SHIFT = 0x04

HUMIDITY_CONTROL_MODE_VERSION_V2 = 0x02
HUMIDITY_CONTROL_MODE_SET_V2 = 0x01
HUMIDITY_CONTROL_MODE_GET_V2 = 0x02
HUMIDITY_CONTROL_MODE_REPORT_V2 = 0x03
HUMIDITY_CONTROL_MODE_SUPPORTED_GET_V2 = 0x04
HUMIDITY_CONTROL_MODE_SUPPORTED_REPORT_V2 = 0x05
# Values used for Humidity Control Mode Set command
HUMIDITY_CONTROL_MODE_SET_PROPERTIES1_MODE_MASK_V2 = 0x0F
HUMIDITY_CONTROL_MODE_SET_MODE_OFF_V2 = 0x00
HUMIDITY_CONTROL_MODE_SET_MODE_HUMIDIFY_V2 = 0x01
HUMIDITY_CONTROL_MODE_SET_MODE_DEHUMIDIFY_V2 = 0x02
HUMIDITY_CONTROL_MODE_SET_MODE_AUTO_V2 = 0x03
HUMIDITY_CONTROL_MODE_SET_PROPERTIES1_RESERVED_MASK_V2 = 0xF0
HUMIDITY_CONTROL_MODE_SET_PROPERTIES1_RESERVED_SHIFT_V2 = 0x04
# Values used for Humidity Control Mode Report command
HUMIDITY_CONTROL_MODE_REPORT_PROPERTIES1_MODE_MASK_V2 = 0x0F
HUMIDITY_CONTROL_MODE_REPORT_MODE_OFF_V2 = 0x00
HUMIDITY_CONTROL_MODE_REPORT_MODE_HUMIDIFY_V2 = 0x01
HUMIDITY_CONTROL_MODE_REPORT_MODE_DEHUMIDIFY_V2 = 0x02
HUMIDITY_CONTROL_MODE_REPORT_MODE_AUTO_V2 = 0x03
HUMIDITY_CONTROL_MODE_REPORT_PROPERTIES1_RESERVED_MASK_V2 = 0xF0
HUMIDITY_CONTROL_MODE_REPORT_PROPERTIES1_RESERVED_SHIFT_V2 = 0x04

class ZW_HUMIDITY_CONTROL_MODE_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('properties1', uint8_t)]


class ZW_HUMIDITY_CONTROL_MODE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_HUMIDITY_CONTROL_MODE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('properties1', uint8_t)]


class ZW_HUMIDITY_CONTROL_MODE_SUPPORTED_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_HUMIDITY_CONTROL_MODE_SUPPORTED_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('bitMask', uint8_t)]


class ZW_HUMIDITY_CONTROL_MODE_SET_V2_FRAME(ZW_HUMIDITY_CONTROL_MODE_SET_FRAME):
    _fields_ = []


class ZW_HUMIDITY_CONTROL_MODE_GET_V2_FRAME(ZW_HUMIDITY_CONTROL_MODE_GET_FRAME):
    _fields_ = []


class ZW_HUMIDITY_CONTROL_MODE_REPORT_V2_FRAME(ZW_HUMIDITY_CONTROL_MODE_REPORT_FRAME):
    _fields_ = []


class ZW_HUMIDITY_CONTROL_MODE_SUPPORTED_GET_V2_FRAME(ZW_HUMIDITY_CONTROL_MODE_SUPPORTED_GET_FRAME):
    _fields_ = []


class ZW_HUMIDITY_CONTROL_MODE_SUPPORTED_REPORT_V2_FRAME(ZW_HUMIDITY_CONTROL_MODE_SUPPORTED_REPORT_FRAME):
    _fields_ = []
