# Indicator Command Class
# Management
# ==============================
COMMAND_CLASS_INDICATOR = 0x87

INDICATOR_VERSION = 0x01
# Indicator Set
INDICATOR_SET = 0x01
# Indicator Get
INDICATOR_GET = 0x02
# Indicator Report
INDICATOR_REPORT = 0x03


INDICATOR_VERSION_V2 = 0x02
INDICATOR_GET_V2 = 0x02
INDICATOR_REPORT_V2 = 0x03
INDICATOR_SET_V2 = 0x01
# Indicator Supported Get
INDICATOR_SUPPORTED_GET_V2 = 0x04
# Indicator Supported Report
INDICATOR_SUPPORTED_REPORT_V2 = 0x05

# Values used for Indicator Get command
INDICATOR_GET_NA_V2 = 0x00
INDICATOR_GET_ARMED_V2 = 0x01
INDICATOR_GET_NOT_ARMED_V2 = 0x02
INDICATOR_GET_READY_V2 = 0x03
INDICATOR_GET_FAULT_V2 = 0x04
INDICATOR_GET_BUSY_V2 = 0x05
INDICATOR_GET_ENTER_ID_V2 = 0x06
INDICATOR_GET_ENTER_PIN_V2 = 0x07
INDICATOR_GET_OK_V2 = 0x08
INDICATOR_GET_NOT_OK_V2 = 0x09
INDICATOR_GET_ZONE1_ARMED_V2 = 0x20
INDICATOR_GET_ZONE2_ARMED_V2 = 0x21
INDICATOR_GET_ZONE3_ARMED_V2 = 0x22
INDICATOR_GET_ZONE4_ARMED_V2 = 0x23
INDICATOR_GET_ZONE5_ARMED_V2 = 0x24
INDICATOR_GET_ZONE6_ARMED_V2 = 0x25
INDICATOR_GET_LCD_BACKLIGHT_V2 = 0x30
INDICATOR_GET_BUTTON_BACKLIGHT_LETTERS_V2 = 0x40
INDICATOR_GET_BUTTON_BACKLIGHT_DIGITS_V2 = 0x41
INDICATOR_GET_BUTTON_BACKLIGHT_COMMAND_V2 = 0x42
INDICATOR_GET_BUTTON1_INDICATION_V2 = 0x43
INDICATOR_GET_BUTTON2_INDICATION_V2 = 0x44
INDICATOR_GET_BUTTON3_INDICATION_V2 = 0x45
INDICATOR_GET_BUTTON4_INDICATION_V2 = 0x46
INDICATOR_GET_BUTTON5_INDICATION_V2 = 0x47
INDICATOR_GET_BUTTON6_INDICATION_V2 = 0x48
INDICATOR_GET_BUTTON7_INDICATION_V2 = 0x49
INDICATOR_GET_BUTTON8_INDICATION_V2 = 0x4A
INDICATOR_GET_BUTTON9_INDICATION_V2 = 0x4B
INDICATOR_GET_BUTTON10_INDICATION_V2 = 0x4C
INDICATOR_GET_BUTTON11_INDICATION_V2 = 0x4D
INDICATOR_GET_BUTTON12_INDICATION_V2 = 0x4E
INDICATOR_GET_BUZZER_V2 = 0xF0
# Values used for Indicator Report command
INDICATOR_REPORT_PROPERTIES1_INDICATOR_OBJECT_COUNT_MASK_V2 = 0x1F
INDICATOR_REPORT_PROPERTIES1_RESERVED_MASK_V2 = 0xE0
INDICATOR_REPORT_PROPERTIES1_RESERVED_SHIFT_V2 = 0x05
INDICATOR_REPORT_NA_V2 = 0x00
INDICATOR_REPORT_ARMED_V2 = 0x01
INDICATOR_REPORT_NOT_ARMED_V2 = 0x02
INDICATOR_REPORT_READY_V2 = 0x03
INDICATOR_REPORT_FAULT_V2 = 0x04
INDICATOR_REPORT_BUSY_V2 = 0x05
INDICATOR_REPORT_ENTER_ID_V2 = 0x06
INDICATOR_REPORT_ENTER_PIN_V2 = 0x07
INDICATOR_REPORT_OK_V2 = 0x08
INDICATOR_REPORT_NOT_OK_V2 = 0x09
INDICATOR_REPORT_ZONE1_ARMED_V2 = 0x20
INDICATOR_REPORT_ZONE2_ARMED_V2 = 0x21
INDICATOR_REPORT_ZONE3_ARMED_V2 = 0x22
INDICATOR_REPORT_ZONE4_ARMED_V2 = 0x23
INDICATOR_REPORT_ZONE5_ARMED_V2 = 0x24
INDICATOR_REPORT_ZONE6_ARMED_V2 = 0x25
INDICATOR_REPORT_LCD_BACKLIGHT_V2 = 0x30
INDICATOR_REPORT_BUTTON_BACKLIGHT_LETTERS_V2 = 0x40
INDICATOR_REPORT_BUTTON_BACKLIGHT_DIGITS_V2 = 0x41
INDICATOR_REPORT_BUTTON_BACKLIGHT_COMMAND_V2 = 0x42
INDICATOR_REPORT_BUTTON1_INDICATION_V2 = 0x43
INDICATOR_REPORT_BUTTON2_INDICATION_V2 = 0x44
INDICATOR_REPORT_BUTTON3_INDICATION_V2 = 0x45
INDICATOR_REPORT_BUTTON4_INDICATION_V2 = 0x46
INDICATOR_REPORT_BUTTON5_INDICATION_V2 = 0x47
INDICATOR_REPORT_BUTTON6_INDICATION_V2 = 0x48
INDICATOR_REPORT_BUTTON7_INDICATION_V2 = 0x49
INDICATOR_REPORT_BUTTON8_INDICATION_V2 = 0x4A
INDICATOR_REPORT_BUTTON9_INDICATION_V2 = 0x4B
INDICATOR_REPORT_BUTTON10_INDICATION_V2 = 0x4C
INDICATOR_REPORT_BUTTON11_INDICATION_V2 = 0x4D
INDICATOR_REPORT_BUTTON12_INDICATION_V2 = 0x4E
INDICATOR_REPORT_BUZZER_V2 = 0xF0
INDICATOR_REPORT_MULTILEVEL_V2 = 0x01
INDICATOR_REPORT_BINARY_V2 = 0x02
INDICATOR_REPORT_ON_OFF_PERIOD_V2 = 0x03
INDICATOR_REPORT_ON_OFF_CYCLES_V2 = 0x04
INDICATOR_REPORT_LOW_POWER_V2 = 0x10
# Values used for Indicator Set command
INDICATOR_SET_PROPERTIES1_INDICATOR_OBJECT_COUNT_MASK_V2 = 0x1F
INDICATOR_SET_PROPERTIES1_RESERVED_MASK_V2 = 0xE0
INDICATOR_SET_PROPERTIES1_RESERVED_SHIFT_V2 = 0x05
INDICATOR_SET_NA_V2 = 0x00
INDICATOR_SET_ARMED_V2 = 0x01
INDICATOR_SET_NOT_ARMED_V2 = 0x02
INDICATOR_SET_READY_V2 = 0x03
INDICATOR_SET_FAULT_V2 = 0x04
INDICATOR_SET_BUSY_V2 = 0x05
INDICATOR_SET_ENTER_ID_V2 = 0x06
INDICATOR_SET_ENTER_PIN_V2 = 0x07
INDICATOR_SET_OK_V2 = 0x08
INDICATOR_SET_NOT_OK_V2 = 0x09
INDICATOR_SET_ZONE1_ARMED_V2 = 0x20
INDICATOR_SET_ZONE2_ARMED_V2 = 0x21
INDICATOR_SET_ZONE3_ARMED_V2 = 0x22
INDICATOR_SET_ZONE4_ARMED_V2 = 0x23
INDICATOR_SET_ZONE5_ARMED_V2 = 0x24
INDICATOR_SET_ZONE6_ARMED_V2 = 0x25
INDICATOR_SET_LCD_BACKLIGHT_V2 = 0x30
INDICATOR_SET_BUTTON_BACKLIGHT_LETTERS_V2 = 0x40
INDICATOR_SET_BUTTON_BACKLIGHT_DIGITS_V2 = 0x41
INDICATOR_SET_BUTTON_BACKLIGHT_COMMAND_V2 = 0x42
INDICATOR_SET_BUTTON1_INDICATION_V2 = 0x43
INDICATOR_SET_BUTTON2_INDICATION_V2 = 0x44
INDICATOR_SET_BUTTON3_INDICATION_V2 = 0x45
INDICATOR_SET_BUTTON4_INDICATION_V2 = 0x46
INDICATOR_SET_BUTTON5_INDICATION_V2 = 0x47
INDICATOR_SET_BUTTON6_INDICATION_V2 = 0x48
INDICATOR_SET_BUTTON7_INDICATION_V2 = 0x49
INDICATOR_SET_BUTTON8_INDICATION_V2 = 0x4A
INDICATOR_SET_BUTTON9_INDICATION_V2 = 0x4B
INDICATOR_SET_BUTTON10_INDICATION_V2 = 0x4C
INDICATOR_SET_BUTTON11_INDICATION_V2 = 0x4D
INDICATOR_SET_BUTTON12_INDICATION_V2 = 0x4E
INDICATOR_SET_BUZZER_V2 = 0xF0
INDICATOR_SET_MULTILEVEL_V2 = 0x01
INDICATOR_SET_BINARY_V2 = 0x02
INDICATOR_SET_ON_OFF_PERIOD_V2 = 0x03
INDICATOR_SET_ON_OFF_CYCLES_V2 = 0x04
INDICATOR_SET_LOW_POWER_V2 = 0x10
# Values used for Indicator Supported Get command
INDICATOR_SUPPORTED_GET_NA_V2 = 0x00
INDICATOR_SUPPORTED_GET_ARMED_V2 = 0x01
INDICATOR_SUPPORTED_GET_NOT_ARMED_V2 = 0x02
INDICATOR_SUPPORTED_GET_READY_V2 = 0x03
INDICATOR_SUPPORTED_GET_FAULT_V2 = 0x04
INDICATOR_SUPPORTED_GET_BUSY_V2 = 0x05
INDICATOR_SUPPORTED_GET_ENTER_ID_V2 = 0x06
INDICATOR_SUPPORTED_GET_ENTER_PIN_V2 = 0x07
INDICATOR_SUPPORTED_GET_OK_V2 = 0x08
INDICATOR_SUPPORTED_GET_NOT_OK_V2 = 0x09
INDICATOR_SUPPORTED_GET_ZONE1_ARMED_V2 = 0x20
INDICATOR_SUPPORTED_GET_ZONE2_ARMED_V2 = 0x21
INDICATOR_SUPPORTED_GET_ZONE3_ARMED_V2 = 0x22
INDICATOR_SUPPORTED_GET_ZONE4_ARMED_V2 = 0x23
INDICATOR_SUPPORTED_GET_ZONE5_ARMED_V2 = 0x24
INDICATOR_SUPPORTED_GET_ZONE6_ARMED_V2 = 0x25
INDICATOR_SUPPORTED_GET_LCD_BACKLIGHT_V2 = 0x30
INDICATOR_SUPPORTED_GET_BUTTON_BACKLIGHT_LETTERS_V2 = 0x40
INDICATOR_SUPPORTED_GET_BUTTON_BACKLIGHT_DIGITS_V2 = 0x41
INDICATOR_SUPPORTED_GET_BUTTON_BACKLIGHT_COMMAND_V2 = 0x42
INDICATOR_SUPPORTED_GET_BUTTON1_INDICATION_V2 = 0x43
INDICATOR_SUPPORTED_GET_BUTTON2_INDICATION_V2 = 0x44
INDICATOR_SUPPORTED_GET_BUTTON3_INDICATION_V2 = 0x45
INDICATOR_SUPPORTED_GET_BUTTON4_INDICATION_V2 = 0x46
INDICATOR_SUPPORTED_GET_BUTTON5_INDICATION_V2 = 0x47
INDICATOR_SUPPORTED_GET_BUTTON6_INDICATION_V2 = 0x48
INDICATOR_SUPPORTED_GET_BUTTON7_INDICATION_V2 = 0x49
INDICATOR_SUPPORTED_GET_BUTTON8_INDICATION_V2 = 0x4A
INDICATOR_SUPPORTED_GET_BUTTON9_INDICATION_V2 = 0x4B
INDICATOR_SUPPORTED_GET_BUTTON10_INDICATION_V2 = 0x4C
INDICATOR_SUPPORTED_GET_BUTTON11_INDICATION_V2 = 0x4D
INDICATOR_SUPPORTED_GET_BUTTON12_INDICATION_V2 = 0x4E
INDICATOR_SUPPORTED_GET_BUZZER_V2 = 0xF0
# Values used for Indicator Supported Report command
INDICATOR_SUPPORTED_REPORT_NA_V2 = 0x00
INDICATOR_SUPPORTED_REPORT_ARMED_V2 = 0x01
INDICATOR_SUPPORTED_REPORT_NOT_ARMED_V2 = 0x02
INDICATOR_SUPPORTED_REPORT_READY_V2 = 0x03
INDICATOR_SUPPORTED_REPORT_FAULT_V2 = 0x04
INDICATOR_SUPPORTED_REPORT_BUSY_V2 = 0x05
INDICATOR_SUPPORTED_REPORT_ENTER_ID_V2 = 0x06
INDICATOR_SUPPORTED_REPORT_ENTER_PIN_V2 = 0x07
INDICATOR_SUPPORTED_REPORT_OK_V2 = 0x08
INDICATOR_SUPPORTED_REPORT_NOT_OK_V2 = 0x09
INDICATOR_SUPPORTED_REPORT_ZONE1_ARMED_V2 = 0x20
INDICATOR_SUPPORTED_REPORT_ZONE2_ARMED_V2 = 0x21
INDICATOR_SUPPORTED_REPORT_ZONE3_ARMED_V2 = 0x22
INDICATOR_SUPPORTED_REPORT_ZONE4_ARMED_V2 = 0x23
INDICATOR_SUPPORTED_REPORT_ZONE5_ARMED_V2 = 0x24
INDICATOR_SUPPORTED_REPORT_ZONE6_ARMED_V2 = 0x25
INDICATOR_SUPPORTED_REPORT_LCD_BACKLIGHT_V2 = 0x30
INDICATOR_SUPPORTED_REPORT_BUTTON_BACKLIGHT_LETTERS_V2 = 0x40
INDICATOR_SUPPORTED_REPORT_BUTTON_BACKLIGHT_DIGITS_V2 = 0x41
INDICATOR_SUPPORTED_REPORT_BUTTON_BACKLIGHT_COMMAND_V2 = 0x42
INDICATOR_SUPPORTED_REPORT_BUTTON1_INDICATION_V2 = 0x43
INDICATOR_SUPPORTED_REPORT_BUTTON2_INDICATION_V2 = 0x44
INDICATOR_SUPPORTED_REPORT_BUTTON3_INDICATION_V2 = 0x45
INDICATOR_SUPPORTED_REPORT_BUTTON4_INDICATION_V2 = 0x46
INDICATOR_SUPPORTED_REPORT_BUTTON5_INDICATION_V2 = 0x47
INDICATOR_SUPPORTED_REPORT_BUTTON6_INDICATION_V2 = 0x48
INDICATOR_SUPPORTED_REPORT_BUTTON7_INDICATION_V2 = 0x49
INDICATOR_SUPPORTED_REPORT_BUTTON8_INDICATION_V2 = 0x4A
INDICATOR_SUPPORTED_REPORT_BUTTON9_INDICATION_V2 = 0x4B
INDICATOR_SUPPORTED_REPORT_BUTTON10_INDICATION_V2 = 0x4C
INDICATOR_SUPPORTED_REPORT_BUTTON11_INDICATION_V2 = 0x4D
INDICATOR_SUPPORTED_REPORT_BUTTON12_INDICATION_V2 = 0x4E
INDICATOR_SUPPORTED_REPORT_BUZZER_V2 = 0xF0

INDICATOR_SUPPORTED_REPORT_PROPERTIES1_PROPERTY_SUPPORTED_BIT_MASK_LENGTH_MASK_V2 = 0x1F
INDICATOR_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V2 = 0xE0
INDICATOR_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V2 = 0x05

INDICATOR_VERSION_V3 = 0x03
INDICATOR_GET_V3 = 0x02
INDICATOR_REPORT_V3 = 0x03
INDICATOR_SET_V3 = 0x01
INDICATOR_SUPPORTED_GET_V3 = 0x04
INDICATOR_SUPPORTED_REPORT_V3 = 0x05

# Values used for Indicator Get command
INDICATOR_GET_NA_V3 = 0x00
INDICATOR_GET_ARMED_V3 = 0x01
INDICATOR_GET_NOT_ARMED_V3 = 0x02
INDICATOR_GET_READY_V3 = 0x03
INDICATOR_GET_FAULT_V3 = 0x04
INDICATOR_GET_BUSY_V3 = 0x05
INDICATOR_GET_ENTER_ID_V3 = 0x06
INDICATOR_GET_ENTER_PIN_V3 = 0x07
INDICATOR_GET_OK_V3 = 0x08
INDICATOR_GET_NOT_OK_V3 = 0x09
INDICATOR_GET_ARMED_STAY_V3 = 0x0A
INDICATOR_GET_ARMED_AWAY_V3 = 0x0B
INDICATOR_GET_ALARMING_V3 = 0x0C
INDICATOR_GET_ALARMING_BURGLAR_V3 = 0x0D
INDICATOR_GET_ALARMING_SMOKE_FIRE_V3 = 0x0E
INDICATOR_GET_ALARMING_CARBON_MONOXIDE_V3 = 0x0F
INDICATOR_GET_BYPASS_CHALLENGE_V3 = 0x10
INDICATOR_GET_ENTRY_DELAY_V3 = 0x11
INDICATOR_GET_EXIT_DELAY_V3 = 0x12
INDICATOR_GET_ZONE1_ARMED_V3 = 0x20
INDICATOR_GET_ZONE2_ARMED_V3 = 0x21
INDICATOR_GET_ZONE3_ARMED_V3 = 0x22
INDICATOR_GET_ZONE4_ARMED_V3 = 0x23
INDICATOR_GET_ZONE5_ARMED_V3 = 0x24
INDICATOR_GET_ZONE6_ARMED_V3 = 0x25
INDICATOR_GET_LCD_BACKLIGHT_V3 = 0x30
INDICATOR_GET_BUTTON_BACKLIGHT_LETTERS_V3 = 0x40
INDICATOR_GET_BUTTON_BACKLIGHT_DIGITS_V3 = 0x41
INDICATOR_GET_BUTTON_BACKLIGHT_COMMAND_V3 = 0x42
INDICATOR_GET_BUTTON1_INDICATION_V3 = 0x43
INDICATOR_GET_BUTTON2_INDICATION_V3 = 0x44
INDICATOR_GET_BUTTON3_INDICATION_V3 = 0x45
INDICATOR_GET_BUTTON4_INDICATION_V3 = 0x46
INDICATOR_GET_BUTTON5_INDICATION_V3 = 0x47
INDICATOR_GET_BUTTON6_INDICATION_V3 = 0x48
INDICATOR_GET_BUTTON7_INDICATION_V3 = 0x49
INDICATOR_GET_BUTTON8_INDICATION_V3 = 0x4A
INDICATOR_GET_BUTTON9_INDICATION_V3 = 0x4B
INDICATOR_GET_BUTTON10_INDICATION_V3 = 0x4C
INDICATOR_GET_BUTTON11_INDICATION_V3 = 0x4D
INDICATOR_GET_BUTTON12_INDICATION_V3 = 0x4E
INDICATOR_GET_NODE_IDENTIFY_V3 = 0x50
INDICATOR_GET_BUZZER_V3 = 0xF0
# Values used for Indicator Report command
INDICATOR_REPORT_PROPERTIES1_INDICATOR_OBJECT_COUNT_MASK_V3 = 0x1F
INDICATOR_REPORT_PROPERTIES1_RESERVED_MASK_V3 = 0xE0
INDICATOR_REPORT_PROPERTIES1_RESERVED_SHIFT_V3 = 0x05
INDICATOR_REPORT_NA_V3 = 0x00
INDICATOR_REPORT_ARMED_V3 = 0x01
INDICATOR_REPORT_NOT_ARMED_V3 = 0x02
INDICATOR_REPORT_READY_V3 = 0x03
INDICATOR_REPORT_FAULT_V3 = 0x04
INDICATOR_REPORT_BUSY_V3 = 0x05
INDICATOR_REPORT_ENTER_ID_V3 = 0x06
INDICATOR_REPORT_ENTER_PIN_V3 = 0x07
INDICATOR_REPORT_OK_V3 = 0x08
INDICATOR_REPORT_NOT_OK_V3 = 0x09
INDICATOR_REPORT_ARMED_STAY_V3 = 0x0A
INDICATOR_REPORT_ARMED_AWAY_V3 = 0x0B
INDICATOR_REPORT_ALARMING_V3 = 0x0C
INDICATOR_REPORT_ALARMING_BURGLAR_V3 = 0x0D
INDICATOR_REPORT_ALARMING_SMOKE_FIRE_V3 = 0x0E
INDICATOR_REPORT_ALARMING_CARBON_MONOXIDE_V3 = 0x0F
INDICATOR_REPORT_BYPASS_CHALLENGE_V3 = 0x10
INDICATOR_REPORT_ENTRY_DELAY_V3 = 0x11
INDICATOR_REPORT_EXIT_DELAY_V3 = 0x12
INDICATOR_REPORT_ZONE1_ARMED_V3 = 0x20
INDICATOR_REPORT_ZONE2_ARMED_V3 = 0x21
INDICATOR_REPORT_ZONE3_ARMED_V3 = 0x22
INDICATOR_REPORT_ZONE4_ARMED_V3 = 0x23
INDICATOR_REPORT_ZONE5_ARMED_V3 = 0x24
INDICATOR_REPORT_ZONE6_ARMED_V3 = 0x25
INDICATOR_REPORT_LCD_BACKLIGHT_V3 = 0x30
INDICATOR_REPORT_BUTTON_BACKLIGHT_LETTERS_V3 = 0x40
INDICATOR_REPORT_BUTTON_BACKLIGHT_DIGITS_V3 = 0x41
INDICATOR_REPORT_BUTTON_BACKLIGHT_COMMAND_V3 = 0x42
INDICATOR_REPORT_BUTTON1_INDICATION_V3 = 0x43
INDICATOR_REPORT_BUTTON2_INDICATION_V3 = 0x44
INDICATOR_REPORT_BUTTON3_INDICATION_V3 = 0x45
INDICATOR_REPORT_BUTTON4_INDICATION_V3 = 0x46
INDICATOR_REPORT_BUTTON5_INDICATION_V3 = 0x47
INDICATOR_REPORT_BUTTON6_INDICATION_V3 = 0x48
INDICATOR_REPORT_BUTTON7_INDICATION_V3 = 0x49
INDICATOR_REPORT_BUTTON8_INDICATION_V3 = 0x4A
INDICATOR_REPORT_BUTTON9_INDICATION_V3 = 0x4B
INDICATOR_REPORT_BUTTON10_INDICATION_V3 = 0x4C
INDICATOR_REPORT_BUTTON11_INDICATION_V3 = 0x4D
INDICATOR_REPORT_BUTTON12_INDICATION_V3 = 0x4E
INDICATOR_REPORT_NODE_IDENTIFY_V3 = 0x50
INDICATOR_REPORT_BUZZER_V3 = 0xF0
INDICATOR_REPORT_MULTILEVEL_V3 = 0x01
INDICATOR_REPORT_BINARY_V3 = 0x02
INDICATOR_REPORT_ON_OFF_PERIOD_V3 = 0x03
INDICATOR_REPORT_ON_OFF_CYCLES_V3 = 0x04
INDICATOR_REPORT_ONE_TIME_ON_OFF_PERIOD_V3 = 0x05
INDICATOR_REPORT_TIMEOUT_MINUTES_V3 = 0x06
INDICATOR_REPORT_TIMEOUT_SECONDS_V3 = 0x07
INDICATOR_REPORT_TIMEOUT_1_100_SECONDS_V3 = 0x08
INDICATOR_REPORT_SPECIFIC_VOLUME_V3 = 0x09
INDICATOR_REPORT_LOW_POWER_V3 = 0x10
# Values used for Indicator Set command
INDICATOR_SET_PROPERTIES1_INDICATOR_OBJECT_COUNT_MASK_V3 = 0x1F
INDICATOR_SET_PROPERTIES1_RESERVED_MASK_V3 = 0xE0
INDICATOR_SET_PROPERTIES1_RESERVED_SHIFT_V3 = 0x05
INDICATOR_SET_NA_V3 = 0x00
INDICATOR_SET_ARMED_V3 = 0x01
INDICATOR_SET_NOT_ARMED_V3 = 0x02
INDICATOR_SET_READY_V3 = 0x03
INDICATOR_SET_FAULT_V3 = 0x04
INDICATOR_SET_BUSY_V3 = 0x05
INDICATOR_SET_ENTER_ID_V3 = 0x06
INDICATOR_SET_ENTER_PIN_V3 = 0x07
INDICATOR_SET_OK_V3 = 0x08
INDICATOR_SET_NOT_OK_V3 = 0x09
INDICATOR_SET_ARMED_STAY_V3 = 0x0A
INDICATOR_SET_ARMED_AWAY_V3 = 0x0B
INDICATOR_SET_ALARMING_V3 = 0x0C
INDICATOR_SET_ALARMING_BURGLAR_V3 = 0x0D
INDICATOR_SET_ALARMING_SMOKE_FIRE_V3 = 0x0E
INDICATOR_SET_ALARMING_CARBON_MONOXIDE_V3 = 0x0F
INDICATOR_SET_BYPASS_CHALLENGE_V3 = 0x10
INDICATOR_SET_ENTRY_DELAY_V3 = 0x11
INDICATOR_SET_EXIT_DELAY_V3 = 0x12
INDICATOR_SET_ZONE1_ARMED_V3 = 0x20
INDICATOR_SET_ZONE2_ARMED_V3 = 0x21
INDICATOR_SET_ZONE3_ARMED_V3 = 0x22
INDICATOR_SET_ZONE4_ARMED_V3 = 0x23
INDICATOR_SET_ZONE5_ARMED_V3 = 0x24
INDICATOR_SET_ZONE6_ARMED_V3 = 0x25
INDICATOR_SET_LCD_BACKLIGHT_V3 = 0x30
INDICATOR_SET_BUTTON_BACKLIGHT_LETTERS_V3 = 0x40
INDICATOR_SET_BUTTON_BACKLIGHT_DIGITS_V3 = 0x41
INDICATOR_SET_BUTTON_BACKLIGHT_COMMAND_V3 = 0x42
INDICATOR_SET_BUTTON1_INDICATION_V3 = 0x43
INDICATOR_SET_BUTTON2_INDICATION_V3 = 0x44
INDICATOR_SET_BUTTON3_INDICATION_V3 = 0x45
INDICATOR_SET_BUTTON4_INDICATION_V3 = 0x46
INDICATOR_SET_BUTTON5_INDICATION_V3 = 0x47
INDICATOR_SET_BUTTON6_INDICATION_V3 = 0x48
INDICATOR_SET_BUTTON7_INDICATION_V3 = 0x49
INDICATOR_SET_BUTTON8_INDICATION_V3 = 0x4A
INDICATOR_SET_BUTTON9_INDICATION_V3 = 0x4B
INDICATOR_SET_BUTTON10_INDICATION_V3 = 0x4C
INDICATOR_SET_BUTTON11_INDICATION_V3 = 0x4D
INDICATOR_SET_BUTTON12_INDICATION_V3 = 0x4E
INDICATOR_SET_NODE_IDENTIFY_V3 = 0x50
INDICATOR_SET_BUZZER_V3 = 0xF0
INDICATOR_SET_MULTILEVEL_V3 = 0x01
INDICATOR_SET_BINARY_V3 = 0x02
INDICATOR_SET_ON_OFF_PERIOD_V3 = 0x03
INDICATOR_SET_ON_OFF_CYCLES_V3 = 0x04
INDICATOR_SET_ONE_TIME_ON_OFF_PERIOD_V3 = 0x05
INDICATOR_SET_TIMEOUT_MINUTES_V3 = 0x06
INDICATOR_SET_TIMEOUT_SECONDS_V3 = 0x07
INDICATOR_SET_TIMEOUT_1_100_SECONDS_V3 = 0x08
INDICATOR_SET_SPECIFIC_VOLUME_V3 = 0x09
INDICATOR_SET_LOW_POWER_V3 = 0x10
# Values used for Indicator Supported Get command
INDICATOR_SUPPORTED_GET_NA_V3 = 0x00
INDICATOR_SUPPORTED_GET_ARMED_V3 = 0x01
INDICATOR_SUPPORTED_GET_NOT_ARMED_V3 = 0x02
INDICATOR_SUPPORTED_GET_READY_V3 = 0x03
INDICATOR_SUPPORTED_GET_FAULT_V3 = 0x04
INDICATOR_SUPPORTED_GET_BUSY_V3 = 0x05
INDICATOR_SUPPORTED_GET_ENTER_ID_V3 = 0x06
INDICATOR_SUPPORTED_GET_ENTER_PIN_V3 = 0x07
INDICATOR_SUPPORTED_GET_OK_V3 = 0x08
INDICATOR_SUPPORTED_GET_NOT_OK_V3 = 0x09
INDICATOR_SUPPORTED_GET_ARMED_STAY_V3 = 0x0A
INDICATOR_SUPPORTED_GET_ARMED_AWAY_V3 = 0x0B
INDICATOR_SUPPORTED_GET_ALARMING_V3 = 0x0C
INDICATOR_SUPPORTED_GET_ALARMING_BURGLAR_V3 = 0x0D
INDICATOR_SUPPORTED_GET_ALARMING_SMOKE_FIRE_V3 = 0x0E
INDICATOR_SUPPORTED_GET_ALARMING_CARBON_MONOXIDE_V3 = 0x0F
INDICATOR_SUPPORTED_GET_BYPASS_CHALLENGE_V3 = 0x10
INDICATOR_SUPPORTED_GET_ENTRY_DELAY_V3 = 0x11
INDICATOR_SUPPORTED_GET_EXIT_DELAY_V3 = 0x12
INDICATOR_SUPPORTED_GET_ZONE1_ARMED_V3 = 0x20
INDICATOR_SUPPORTED_GET_ZONE2_ARMED_V3 = 0x21
INDICATOR_SUPPORTED_GET_ZONE3_ARMED_V3 = 0x22
INDICATOR_SUPPORTED_GET_ZONE4_ARMED_V3 = 0x23
INDICATOR_SUPPORTED_GET_ZONE5_ARMED_V3 = 0x24
INDICATOR_SUPPORTED_GET_ZONE6_ARMED_V3 = 0x25
INDICATOR_SUPPORTED_GET_LCD_BACKLIGHT_V3 = 0x30
INDICATOR_SUPPORTED_GET_BUTTON_BACKLIGHT_LETTERS_V3 = 0x40
INDICATOR_SUPPORTED_GET_BUTTON_BACKLIGHT_DIGITS_V3 = 0x41
INDICATOR_SUPPORTED_GET_BUTTON_BACKLIGHT_COMMAND_V3 = 0x42
INDICATOR_SUPPORTED_GET_BUTTON1_INDICATION_V3 = 0x43
INDICATOR_SUPPORTED_GET_BUTTON2_INDICATION_V3 = 0x44
INDICATOR_SUPPORTED_GET_BUTTON3_INDICATION_V3 = 0x45
INDICATOR_SUPPORTED_GET_BUTTON4_INDICATION_V3 = 0x46
INDICATOR_SUPPORTED_GET_BUTTON5_INDICATION_V3 = 0x47
INDICATOR_SUPPORTED_GET_BUTTON6_INDICATION_V3 = 0x48
INDICATOR_SUPPORTED_GET_BUTTON7_INDICATION_V3 = 0x49
INDICATOR_SUPPORTED_GET_BUTTON8_INDICATION_V3 = 0x4A
INDICATOR_SUPPORTED_GET_BUTTON9_INDICATION_V3 = 0x4B
INDICATOR_SUPPORTED_GET_BUTTON10_INDICATION_V3 = 0x4C
INDICATOR_SUPPORTED_GET_BUTTON11_INDICATION_V3 = 0x4D
INDICATOR_SUPPORTED_GET_BUTTON12_INDICATION_V3 = 0x4E
INDICATOR_SUPPORTED_GET_NODE_IDENTIFY_V3 = 0x50
INDICATOR_SUPPORTED_GET_BUZZER_V3 = 0xF0
# Values used for Indicator Supported Report command
INDICATOR_SUPPORTED_REPORT_NA_V3 = 0x00
INDICATOR_SUPPORTED_REPORT_ARMED_V3 = 0x01
INDICATOR_SUPPORTED_REPORT_NOT_ARMED_V3 = 0x02
INDICATOR_SUPPORTED_REPORT_READY_V3 = 0x03
INDICATOR_SUPPORTED_REPORT_FAULT_V3 = 0x04
INDICATOR_SUPPORTED_REPORT_BUSY_V3 = 0x05
INDICATOR_SUPPORTED_REPORT_ENTER_ID_V3 = 0x06
INDICATOR_SUPPORTED_REPORT_ENTER_PIN_V3 = 0x07
INDICATOR_SUPPORTED_REPORT_OK_V3 = 0x08
INDICATOR_SUPPORTED_REPORT_NOT_OK_V3 = 0x09
INDICATOR_SUPPORTED_REPORT_ARMED_STAY_V3 = 0x0A
INDICATOR_SUPPORTED_REPORT_ARMED_AWAY_V3 = 0x0B
INDICATOR_SUPPORTED_REPORT_ALARMING_V3 = 0x0C
INDICATOR_SUPPORTED_REPORT_ALARMING_BURGLAR_V3 = 0x0D
INDICATOR_SUPPORTED_REPORT_ALARMING_SMOKE_FIRE_V3 = 0x0E
INDICATOR_SUPPORTED_REPORT_ALARMING_CARBON_MONOXIDE_V3 = 0x0F
INDICATOR_SUPPORTED_REPORT_BYPASS_CHALLENGE_V3 = 0x10
INDICATOR_SUPPORTED_REPORT_ENTRY_DELAY_V3 = 0x11
INDICATOR_SUPPORTED_REPORT_EXIT_DELAY_V3 = 0x12
INDICATOR_SUPPORTED_REPORT_ZONE1_ARMED_V3 = 0x20
INDICATOR_SUPPORTED_REPORT_ZONE2_ARMED_V3 = 0x21
INDICATOR_SUPPORTED_REPORT_ZONE3_ARMED_V3 = 0x22
INDICATOR_SUPPORTED_REPORT_ZONE4_ARMED_V3 = 0x23
INDICATOR_SUPPORTED_REPORT_ZONE5_ARMED_V3 = 0x24
INDICATOR_SUPPORTED_REPORT_ZONE6_ARMED_V3 = 0x25
INDICATOR_SUPPORTED_REPORT_LCD_BACKLIGHT_V3 = 0x30
INDICATOR_SUPPORTED_REPORT_BUTTON_BACKLIGHT_LETTERS_V3 = 0x40
INDICATOR_SUPPORTED_REPORT_BUTTON_BACKLIGHT_DIGITS_V3 = 0x41
INDICATOR_SUPPORTED_REPORT_BUTTON_BACKLIGHT_COMMAND_V3 = 0x42
INDICATOR_SUPPORTED_REPORT_BUTTON1_INDICATION_V3 = 0x43
INDICATOR_SUPPORTED_REPORT_BUTTON2_INDICATION_V3 = 0x44
INDICATOR_SUPPORTED_REPORT_BUTTON3_INDICATION_V3 = 0x45
INDICATOR_SUPPORTED_REPORT_BUTTON4_INDICATION_V3 = 0x46
INDICATOR_SUPPORTED_REPORT_BUTTON5_INDICATION_V3 = 0x47
INDICATOR_SUPPORTED_REPORT_BUTTON6_INDICATION_V3 = 0x48
INDICATOR_SUPPORTED_REPORT_BUTTON7_INDICATION_V3 = 0x49
INDICATOR_SUPPORTED_REPORT_BUTTON8_INDICATION_V3 = 0x4A
INDICATOR_SUPPORTED_REPORT_BUTTON9_INDICATION_V3 = 0x4B
INDICATOR_SUPPORTED_REPORT_BUTTON10_INDICATION_V3 = 0x4C
INDICATOR_SUPPORTED_REPORT_BUTTON11_INDICATION_V3 = 0x4D
INDICATOR_SUPPORTED_REPORT_BUTTON12_INDICATION_V3 = 0x4E
INDICATOR_SUPPORTED_REPORT_NODE_IDENTIFY_V3 = 0x50
INDICATOR_SUPPORTED_REPORT_BUZZER_V3 = 0xF0

INDICATOR_SUPPORTED_REPORT_PROPERTIES1_PROPERTY_SUPPORTED_BIT_MASK_LENGTH_MASK_V3 = 0x1F
INDICATOR_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V3 = 0xE0
INDICATOR_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V3 = 0x05

INDICATOR_VERSION_V4 = 0x04
INDICATOR_GET_V4 = 0x02
INDICATOR_REPORT_V4 = 0x03
INDICATOR_SET_V4 = 0x01
INDICATOR_SUPPORTED_GET_V4 = 0x04
INDICATOR_SUPPORTED_REPORT_V4 = 0x05
# Indicator description Get
INDICATOR_DESCRIPTION_GET_V4 = 0x06
# Indicator Description Report
INDICATOR_DESCRIPTION_REPORT_V4 = 0x07

# Values used for Indicator Get command
INDICATOR_GET_NA_V4 = 0x00
INDICATOR_GET_ARMED_V4 = 0x01
INDICATOR_GET_NOT_ARMED_V4 = 0x02
INDICATOR_GET_READY_V4 = 0x03
INDICATOR_GET_FAULT_V4 = 0x04
INDICATOR_GET_BUSY_V4 = 0x05
INDICATOR_GET_ENTER_ID_V4 = 0x06
INDICATOR_GET_ENTER_PIN_V4 = 0x07
INDICATOR_GET_OK_V4 = 0x08
INDICATOR_GET_NOT_OK_V4 = 0x09
INDICATOR_GET_ARMED_STAY_V4 = 0x0A
INDICATOR_GET_ARMED_AWAY_V4 = 0x0B
INDICATOR_GET_ALARMING_V4 = 0x0C
INDICATOR_GET_ALARMING_BURGLAR_V4 = 0x0D
INDICATOR_GET_ALARMING_SMOKE_FIRE_V4 = 0x0E
INDICATOR_GET_ALARMING_CARBON_MONOXIDE_V4 = 0x0F
INDICATOR_GET_BYPASS_CHALLENGE_V4 = 0x10
INDICATOR_GET_ENTRY_DELAY_V4 = 0x11
INDICATOR_GET_EXIT_DELAY_V4 = 0x12
INDICATOR_GET_ZONE1_ARMED_V4 = 0x20
INDICATOR_GET_ZONE2_ARMED_V4 = 0x21
INDICATOR_GET_ZONE3_ARMED_V4 = 0x22
INDICATOR_GET_ZONE4_ARMED_V4 = 0x23
INDICATOR_GET_ZONE5_ARMED_V4 = 0x24
INDICATOR_GET_ZONE6_ARMED_V4 = 0x25
INDICATOR_GET_LCD_BACKLIGHT_V4 = 0x30
INDICATOR_GET_BUTTON_BACKLIGHT_LETTERS_V4 = 0x40
INDICATOR_GET_BUTTON_BACKLIGHT_DIGITS_V4 = 0x41
INDICATOR_GET_BUTTON_BACKLIGHT_COMMAND_V4 = 0x42
INDICATOR_GET_BUTTON1_INDICATION_V4 = 0x43
INDICATOR_GET_BUTTON2_INDICATION_V4 = 0x44
INDICATOR_GET_BUTTON3_INDICATION_V4 = 0x45
INDICATOR_GET_BUTTON4_INDICATION_V4 = 0x46
INDICATOR_GET_BUTTON5_INDICATION_V4 = 0x47
INDICATOR_GET_BUTTON6_INDICATION_V4 = 0x48
INDICATOR_GET_BUTTON7_INDICATION_V4 = 0x49
INDICATOR_GET_BUTTON8_INDICATION_V4 = 0x4A
INDICATOR_GET_BUTTON9_INDICATION_V4 = 0x4B
INDICATOR_GET_BUTTON10_INDICATION_V4 = 0x4C
INDICATOR_GET_BUTTON11_INDICATION_V4 = 0x4D
INDICATOR_GET_BUTTON12_INDICATION_V4 = 0x4E
INDICATOR_GET_NODE_IDENTIFY_V4 = 0x50
INDICATOR_GET_BUZZER_V4 = 0xF0
# Values used for Indicator Report command
INDICATOR_REPORT_PROPERTIES1_INDICATOR_OBJECT_COUNT_MASK_V4 = 0x1F
INDICATOR_REPORT_PROPERTIES1_RESERVED_MASK_V4 = 0xE0
INDICATOR_REPORT_PROPERTIES1_RESERVED_SHIFT_V4 = 0x05
INDICATOR_REPORT_NA_V4 = 0x00
INDICATOR_REPORT_ARMED_V4 = 0x01
INDICATOR_REPORT_NOT_ARMED_V4 = 0x02
INDICATOR_REPORT_READY_V4 = 0x03
INDICATOR_REPORT_FAULT_V4 = 0x04
INDICATOR_REPORT_BUSY_V4 = 0x05
INDICATOR_REPORT_ENTER_ID_V4 = 0x06
INDICATOR_REPORT_ENTER_PIN_V4 = 0x07
INDICATOR_REPORT_OK_V4 = 0x08
INDICATOR_REPORT_NOT_OK_V4 = 0x09
INDICATOR_REPORT_ARMED_STAY_V4 = 0x0A
INDICATOR_REPORT_ARMED_AWAY_V4 = 0x0B
INDICATOR_REPORT_ALARMING_V4 = 0x0C
INDICATOR_REPORT_ALARMING_BURGLAR_V4 = 0x0D
INDICATOR_REPORT_ALARMING_SMOKE_FIRE_V4 = 0x0E
INDICATOR_REPORT_ALARMING_CARBON_MONOXIDE_V4 = 0x0F
INDICATOR_REPORT_BYPASS_CHALLENGE_V4 = 0x10
INDICATOR_REPORT_ENTRY_DELAY_V4 = 0x11
INDICATOR_REPORT_EXIT_DELAY_V4 = 0x12
INDICATOR_REPORT_ZONE1_ARMED_V4 = 0x20
INDICATOR_REPORT_ZONE2_ARMED_V4 = 0x21
INDICATOR_REPORT_ZONE3_ARMED_V4 = 0x22
INDICATOR_REPORT_ZONE4_ARMED_V4 = 0x23
INDICATOR_REPORT_ZONE5_ARMED_V4 = 0x24
INDICATOR_REPORT_ZONE6_ARMED_V4 = 0x25
INDICATOR_REPORT_LCD_BACKLIGHT_V4 = 0x30
INDICATOR_REPORT_BUTTON_BACKLIGHT_LETTERS_V4 = 0x40
INDICATOR_REPORT_BUTTON_BACKLIGHT_DIGITS_V4 = 0x41
INDICATOR_REPORT_BUTTON_BACKLIGHT_COMMAND_V4 = 0x42
INDICATOR_REPORT_BUTTON1_INDICATION_V4 = 0x43
INDICATOR_REPORT_BUTTON2_INDICATION_V4 = 0x44
INDICATOR_REPORT_BUTTON3_INDICATION_V4 = 0x45
INDICATOR_REPORT_BUTTON4_INDICATION_V4 = 0x46
INDICATOR_REPORT_BUTTON5_INDICATION_V4 = 0x47
INDICATOR_REPORT_BUTTON6_INDICATION_V4 = 0x48
INDICATOR_REPORT_BUTTON7_INDICATION_V4 = 0x49
INDICATOR_REPORT_BUTTON8_INDICATION_V4 = 0x4A
INDICATOR_REPORT_BUTTON9_INDICATION_V4 = 0x4B
INDICATOR_REPORT_BUTTON10_INDICATION_V4 = 0x4C
INDICATOR_REPORT_BUTTON11_INDICATION_V4 = 0x4D
INDICATOR_REPORT_BUTTON12_INDICATION_V4 = 0x4E
INDICATOR_REPORT_NODE_IDENTIFY_V4 = 0x50
INDICATOR_REPORT_BUZZER_V4 = 0xF0
INDICATOR_REPORT_MULTILEVEL_V4 = 0x01
INDICATOR_REPORT_BINARY_V4 = 0x02
INDICATOR_REPORT_ON_OFF_PERIOD_V4 = 0x03
INDICATOR_REPORT_ON_OFF_CYCLES_V4 = 0x04
INDICATOR_REPORT_ONE_TIME_ON_OFF_PERIOD_V4 = 0x05
INDICATOR_REPORT_TIMEOUT_MINUTES_V4 = 0x06
INDICATOR_REPORT_TIMEOUT_SECONDS_V4 = 0x07
INDICATOR_REPORT_TIMEOUT_1_100_SECONDS_V4 = 0x08
INDICATOR_REPORT_SPECIFIC_VOLUME_V4 = 0x09
INDICATOR_REPORT_LOW_POWER_V4 = 0x10
# Values used for Indicator Set command
INDICATOR_SET_PROPERTIES1_INDICATOR_OBJECT_COUNT_MASK_V4 = 0x1F
INDICATOR_SET_PROPERTIES1_RESERVED_MASK_V4 = 0xE0
INDICATOR_SET_PROPERTIES1_RESERVED_SHIFT_V4 = 0x05
INDICATOR_SET_NA_V4 = 0x00
INDICATOR_SET_ARMED_V4 = 0x01
INDICATOR_SET_NOT_ARMED_V4 = 0x02
INDICATOR_SET_READY_V4 = 0x03
INDICATOR_SET_FAULT_V4 = 0x04
INDICATOR_SET_BUSY_V4 = 0x05
INDICATOR_SET_ENTER_ID_V4 = 0x06
INDICATOR_SET_ENTER_PIN_V4 = 0x07
INDICATOR_SET_OK_V4 = 0x08
INDICATOR_SET_NOT_OK_V4 = 0x09
INDICATOR_SET_ARMED_STAY_V4 = 0x0A
INDICATOR_SET_ARMED_AWAY_V4 = 0x0B
INDICATOR_SET_ALARMING_V4 = 0x0C
INDICATOR_SET_ALARMING_BURGLAR_V4 = 0x0D
INDICATOR_SET_ALARMING_SMOKE_FIRE_V4 = 0x0E
INDICATOR_SET_ALARMING_CARBON_MONOXIDE_V4 = 0x0F
INDICATOR_SET_BYPASS_CHALLENGE_V4 = 0x10
INDICATOR_SET_ENTRY_DELAY_V4 = 0x11
INDICATOR_SET_EXIT_DELAY_V4 = 0x12
INDICATOR_SET_ZONE1_ARMED_V4 = 0x20
INDICATOR_SET_ZONE2_ARMED_V4 = 0x21
INDICATOR_SET_ZONE3_ARMED_V4 = 0x22
INDICATOR_SET_ZONE4_ARMED_V4 = 0x23
INDICATOR_SET_ZONE5_ARMED_V4 = 0x24
INDICATOR_SET_ZONE6_ARMED_V4 = 0x25
INDICATOR_SET_LCD_BACKLIGHT_V4 = 0x30
INDICATOR_SET_BUTTON_BACKLIGHT_LETTERS_V4 = 0x40
INDICATOR_SET_BUTTON_BACKLIGHT_DIGITS_V4 = 0x41
INDICATOR_SET_BUTTON_BACKLIGHT_COMMAND_V4 = 0x42
INDICATOR_SET_BUTTON1_INDICATION_V4 = 0x43
INDICATOR_SET_BUTTON2_INDICATION_V4 = 0x44
INDICATOR_SET_BUTTON3_INDICATION_V4 = 0x45
INDICATOR_SET_BUTTON4_INDICATION_V4 = 0x46
INDICATOR_SET_BUTTON5_INDICATION_V4 = 0x47
INDICATOR_SET_BUTTON6_INDICATION_V4 = 0x48
INDICATOR_SET_BUTTON7_INDICATION_V4 = 0x49
INDICATOR_SET_BUTTON8_INDICATION_V4 = 0x4A
INDICATOR_SET_BUTTON9_INDICATION_V4 = 0x4B
INDICATOR_SET_BUTTON10_INDICATION_V4 = 0x4C
INDICATOR_SET_BUTTON11_INDICATION_V4 = 0x4D
INDICATOR_SET_BUTTON12_INDICATION_V4 = 0x4E
INDICATOR_SET_NODE_IDENTIFY_V4 = 0x50
INDICATOR_SET_BUZZER_V4 = 0xF0
INDICATOR_SET_MULTILEVEL_V4 = 0x01
INDICATOR_SET_BINARY_V4 = 0x02
INDICATOR_SET_ON_OFF_PERIOD_V4 = 0x03
INDICATOR_SET_ON_OFF_CYCLES_V4 = 0x04
INDICATOR_SET_ONE_TIME_ON_OFF_PERIOD_V4 = 0x05
INDICATOR_SET_TIMEOUT_MINUTES_V4 = 0x06
INDICATOR_SET_TIMEOUT_SECONDS_V4 = 0x07
INDICATOR_SET_TIMEOUT_1_100_SECONDS_V4 = 0x08
INDICATOR_SET_SPECIFIC_VOLUME_V4 = 0x09
INDICATOR_SET_LOW_POWER_V4 = 0x10
# Values used for Indicator Supported Get command
INDICATOR_SUPPORTED_GET_NA_V4 = 0x00
INDICATOR_SUPPORTED_GET_ARMED_V4 = 0x01
INDICATOR_SUPPORTED_GET_NOT_ARMED_V4 = 0x02
INDICATOR_SUPPORTED_GET_READY_V4 = 0x03
INDICATOR_SUPPORTED_GET_FAULT_V4 = 0x04
INDICATOR_SUPPORTED_GET_BUSY_V4 = 0x05
INDICATOR_SUPPORTED_GET_ENTER_ID_V4 = 0x06
INDICATOR_SUPPORTED_GET_ENTER_PIN_V4 = 0x07
INDICATOR_SUPPORTED_GET_OK_V4 = 0x08
INDICATOR_SUPPORTED_GET_NOT_OK_V4 = 0x09
INDICATOR_SUPPORTED_GET_ARMED_STAY_V4 = 0x0A
INDICATOR_SUPPORTED_GET_ARMED_AWAY_V4 = 0x0B
INDICATOR_SUPPORTED_GET_ALARMING_V4 = 0x0C
INDICATOR_SUPPORTED_GET_ALARMING_BURGLAR_V4 = 0x0D
INDICATOR_SUPPORTED_GET_ALARMING_SMOKE_FIRE_V4 = 0x0E
INDICATOR_SUPPORTED_GET_ALARMING_CARBON_MONOXIDE_V4 = 0x0F
INDICATOR_SUPPORTED_GET_BYPASS_CHALLENGE_V4 = 0x10
INDICATOR_SUPPORTED_GET_ENTRY_DELAY_V4 = 0x11
INDICATOR_SUPPORTED_GET_EXIT_DELAY_V4 = 0x12
INDICATOR_SUPPORTED_GET_ZONE1_ARMED_V4 = 0x20
INDICATOR_SUPPORTED_GET_ZONE2_ARMED_V4 = 0x21
INDICATOR_SUPPORTED_GET_ZONE3_ARMED_V4 = 0x22
INDICATOR_SUPPORTED_GET_ZONE4_ARMED_V4 = 0x23
INDICATOR_SUPPORTED_GET_ZONE5_ARMED_V4 = 0x24
INDICATOR_SUPPORTED_GET_ZONE6_ARMED_V4 = 0x25
INDICATOR_SUPPORTED_GET_LCD_BACKLIGHT_V4 = 0x30
INDICATOR_SUPPORTED_GET_BUTTON_BACKLIGHT_LETTERS_V4 = 0x40
INDICATOR_SUPPORTED_GET_BUTTON_BACKLIGHT_DIGITS_V4 = 0x41
INDICATOR_SUPPORTED_GET_BUTTON_BACKLIGHT_COMMAND_V4 = 0x42
INDICATOR_SUPPORTED_GET_BUTTON1_INDICATION_V4 = 0x43
INDICATOR_SUPPORTED_GET_BUTTON2_INDICATION_V4 = 0x44
INDICATOR_SUPPORTED_GET_BUTTON3_INDICATION_V4 = 0x45
INDICATOR_SUPPORTED_GET_BUTTON4_INDICATION_V4 = 0x46
INDICATOR_SUPPORTED_GET_BUTTON5_INDICATION_V4 = 0x47
INDICATOR_SUPPORTED_GET_BUTTON6_INDICATION_V4 = 0x48
INDICATOR_SUPPORTED_GET_BUTTON7_INDICATION_V4 = 0x49
INDICATOR_SUPPORTED_GET_BUTTON8_INDICATION_V4 = 0x4A
INDICATOR_SUPPORTED_GET_BUTTON9_INDICATION_V4 = 0x4B
INDICATOR_SUPPORTED_GET_BUTTON10_INDICATION_V4 = 0x4C
INDICATOR_SUPPORTED_GET_BUTTON11_INDICATION_V4 = 0x4D
INDICATOR_SUPPORTED_GET_BUTTON12_INDICATION_V4 = 0x4E
INDICATOR_SUPPORTED_GET_NODE_IDENTIFY_V4 = 0x50
INDICATOR_SUPPORTED_GET_BUZZER_V4 = 0xF0
# Values used for Indicator Supported Report command
INDICATOR_SUPPORTED_REPORT_NA_V4 = 0x00
INDICATOR_SUPPORTED_REPORT_ARMED_V4 = 0x01
INDICATOR_SUPPORTED_REPORT_NOT_ARMED_V4 = 0x02
INDICATOR_SUPPORTED_REPORT_READY_V4 = 0x03
INDICATOR_SUPPORTED_REPORT_FAULT_V4 = 0x04
INDICATOR_SUPPORTED_REPORT_BUSY_V4 = 0x05
INDICATOR_SUPPORTED_REPORT_ENTER_ID_V4 = 0x06
INDICATOR_SUPPORTED_REPORT_ENTER_PIN_V4 = 0x07
INDICATOR_SUPPORTED_REPORT_OK_V4 = 0x08
INDICATOR_SUPPORTED_REPORT_NOT_OK_V4 = 0x09
INDICATOR_SUPPORTED_REPORT_ARMED_STAY_V4 = 0x0A
INDICATOR_SUPPORTED_REPORT_ARMED_AWAY_V4 = 0x0B
INDICATOR_SUPPORTED_REPORT_ALARMING_V4 = 0x0C
INDICATOR_SUPPORTED_REPORT_ALARMING_BURGLAR_V4 = 0x0D
INDICATOR_SUPPORTED_REPORT_ALARMING_SMOKE_FIRE_V4 = 0x0E
INDICATOR_SUPPORTED_REPORT_ALARMING_CARBON_MONOXIDE_V4 = 0x0F
INDICATOR_SUPPORTED_REPORT_BYPASS_CHALLENGE_V4 = 0x10
INDICATOR_SUPPORTED_REPORT_ENTRY_DELAY_V4 = 0x11
INDICATOR_SUPPORTED_REPORT_EXIT_DELAY_V4 = 0x12
INDICATOR_SUPPORTED_REPORT_ZONE1_ARMED_V4 = 0x20
INDICATOR_SUPPORTED_REPORT_ZONE2_ARMED_V4 = 0x21
INDICATOR_SUPPORTED_REPORT_ZONE3_ARMED_V4 = 0x22
INDICATOR_SUPPORTED_REPORT_ZONE4_ARMED_V4 = 0x23
INDICATOR_SUPPORTED_REPORT_ZONE5_ARMED_V4 = 0x24
INDICATOR_SUPPORTED_REPORT_ZONE6_ARMED_V4 = 0x25
INDICATOR_SUPPORTED_REPORT_LCD_BACKLIGHT_V4 = 0x30
INDICATOR_SUPPORTED_REPORT_BUTTON_BACKLIGHT_LETTERS_V4 = 0x40
INDICATOR_SUPPORTED_REPORT_BUTTON_BACKLIGHT_DIGITS_V4 = 0x41
INDICATOR_SUPPORTED_REPORT_BUTTON_BACKLIGHT_COMMAND_V4 = 0x42
INDICATOR_SUPPORTED_REPORT_BUTTON1_INDICATION_V4 = 0x43
INDICATOR_SUPPORTED_REPORT_BUTTON2_INDICATION_V4 = 0x44
INDICATOR_SUPPORTED_REPORT_BUTTON3_INDICATION_V4 = 0x45
INDICATOR_SUPPORTED_REPORT_BUTTON4_INDICATION_V4 = 0x46
INDICATOR_SUPPORTED_REPORT_BUTTON5_INDICATION_V4 = 0x47
INDICATOR_SUPPORTED_REPORT_BUTTON6_INDICATION_V4 = 0x48
INDICATOR_SUPPORTED_REPORT_BUTTON7_INDICATION_V4 = 0x49
INDICATOR_SUPPORTED_REPORT_BUTTON8_INDICATION_V4 = 0x4A
INDICATOR_SUPPORTED_REPORT_BUTTON9_INDICATION_V4 = 0x4B
INDICATOR_SUPPORTED_REPORT_BUTTON10_INDICATION_V4 = 0x4C
INDICATOR_SUPPORTED_REPORT_BUTTON11_INDICATION_V4 = 0x4D
INDICATOR_SUPPORTED_REPORT_BUTTON12_INDICATION_V4 = 0x4E
INDICATOR_SUPPORTED_REPORT_NODE_IDENTIFY_V4 = 0x50
INDICATOR_SUPPORTED_REPORT_BUZZER_V4 = 0xF0

INDICATOR_SUPPORTED_REPORT_PROPERTIES1_PROPERTY_SUPPORTED_BIT_MASK_LENGTH_MASK_V4 = 0x1F
INDICATOR_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V4 = 0xE0
INDICATOR_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V4 = 0x05


class ZW_INDICATOR_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_INDICATOR_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('value', uint8_t)]


class ZW_INDICATOR_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('value', uint8_t)]


class ZW_INDICATOR_GET_V2_FRAME(ZW_INDICATOR_GET_FRAME):
    _fields_ = [('indicatorId', uint8_t)]


class VG_INDICATOR_REPORT_V2_VG(ctypes.Structure):
    _fields_ = [
        ('indicatorId', uint8_t),
        ('propertyId', uint8_t),
        ('value', uint8_t),
    ]


class ZW_INDICATOR_REPORT_V2_FRAME(ZW_INDICATOR_REPORT_FRAME):
    _fields_ = [
        ('indicator0Value', uint8_t),
        ('properties1', uint8_t),
        ('variantgroup1', VG_INDICATOR_REPORT_V2_VG),
    ]


class VG_INDICATOR_SET_V2_VG(ctypes.Structure):
    _fields_ = [
        ('indicatorId', uint8_t),
        ('propertyId', uint8_t),
        ('value', uint8_t),
    ]


class ZW_INDICATOR_SET_V2_FRAME(ZW_INDICATOR_SET_FRAME):
    _fields_ = [
        ('indicator0Value', uint8_t),
        ('properties1', uint8_t),
        ('variantgroup1', VG_INDICATOR_SET_V2_VG),
    ]


class ZW_INDICATOR_SUPPORTED_GET_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('indicatorId', uint8_t)]


class ZW_INDICATOR_SUPPORTED_REPORT_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('indicatorId', uint8_t),
        ('nextIndicatorId', uint8_t),
        ('properties1', uint8_t),
        ('propertySupportedBitMask1', uint8_t),
    ]


class ZW_INDICATOR_GET_V3_FRAME(ZW_INDICATOR_GET_V2_FRAME):
    _fields_ = []


class VG_INDICATOR_REPORT_V3_VG(ctypes.Structure):
    _fields_ = [
        ('indicatorId', uint8_t),
        ('propertyId', uint8_t),
        ('value', uint8_t),
    ]


class ZW_INDICATOR_REPORT_V3_FRAME(ZW_INDICATOR_REPORT_V2_FRAME):
    _fields_ = []


class VG_INDICATOR_SET_V3_VG(ctypes.Structure):
    _fields_ = [
        ('indicatorId', uint8_t),
        ('propertyId', uint8_t),
        ('value', uint8_t),
    ]


class ZW_INDICATOR_SET_V3_FRAME(ZW_INDICATOR_SET_V2_FRAME):
    _fields_ = []


class ZW_INDICATOR_SUPPORTED_GET_V3_FRAME(ZW_INDICATOR_SUPPORTED_GET_V2_FRAME):
    _fields_ = []


class ZW_INDICATOR_SUPPORTED_REPORT_V3_FRAME(ZW_INDICATOR_SUPPORTED_REPORT_V2_FRAME):
    _fields_ = []


class ZW_INDICATOR_GET_V4_FRAME(ZW_INDICATOR_GET_V3_FRAME):
    _fields_ = []


class VG_INDICATOR_REPORT_V4_VG(ctypes.Structure):
    _fields_ = [
        ('indicatorId', uint8_t),
        ('propertyId', uint8_t),
        ('value', uint8_t),
    ]


class ZW_INDICATOR_REPORT_V4_FRAME(ZW_INDICATOR_REPORT_V3_FRAME):
    _fields_ = []


class VG_INDICATOR_SET_V4_VG(ctypes.Structure):
    _fields_ = [
        ('indicatorId', uint8_t),
        ('propertyId', uint8_t),
        ('value', uint8_t),
    ]


class ZW_INDICATOR_SET_V4_FRAME(ZW_INDICATOR_SET_V3_FRAME):
    _fields_ = []


class ZW_INDICATOR_SUPPORTED_GET_V4_FRAME(ZW_INDICATOR_SUPPORTED_GET_V3_FRAME):
    _fields_ = []


class ZW_INDICATOR_SUPPORTED_REPORT_V4_FRAME(ZW_INDICATOR_SUPPORTED_REPORT_V3_FRAME):
    _fields_ = []


class ZW_INDICATOR_DESCRIPTION_GET_V4_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('indicatorId', uint8_t)]


class ZW_INDICATOR_DESCRIPTION_REPORT_V4_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('indicatorId', uint8_t),
        ('descriptionLength', uint8_t),
        ('description1', uint8_t),
    ]


