# Irrigation Command Class
# Application
# ==============================
COMMAND_CLASS_IRRIGATION = 0x6B

IRRIGATION_VERSION = 0x01
# Irrigation System Info Get
IRRIGATION_SYSTEM_INFO_GET = 0x01
# Irrigation System Info Report
IRRIGATION_SYSTEM_INFO_REPORT = 0x02
# Irrigation System Status Get
IRRIGATION_SYSTEM_STATUS_GET = 0x03
# Irrigation System Status Report
IRRIGATION_SYSTEM_STATUS_REPORT = 0x04
# Irrigation System Config Set
IRRIGATION_SYSTEM_CONFIG_SET = 0x05
# Irrigation System Config Get
IRRIGATION_SYSTEM_CONFIG_GET = 0x06
# Irrigation System Config Report
IRRIGATION_SYSTEM_CONFIG_REPORT = 0x07
# Irrigation Valve Info Get
IRRIGATION_VALVE_INFO_GET = 0x08
# Irrigation Valve Info Report
IRRIGATION_VALVE_INFO_REPORT = 0x09
# Irrigation Valve Config Set
IRRIGATION_VALVE_CONFIG_SET = 0x0A
# Irrigation Valve Config Get
IRRIGATION_VALVE_CONFIG_GET = 0x0B
# Irrigation Valve Config Report
IRRIGATION_VALVE_CONFIG_REPORT = 0x0C
# Irrigation Valve Run
IRRIGATION_VALVE_RUN = 0x0D
# Irrigation Valve Table Set
IRRIGATION_VALVE_TABLE_SET = 0x0E
# Irrigation Valve Table Get
IRRIGATION_VALVE_TABLE_GET = 0x0F
# Irrigation Valve Table Report
IRRIGATION_VALVE_TABLE_REPORT = 0x10
# Irrigation Valve Table Run
IRRIGATION_VALVE_TABLE_RUN = 0x11
# Irrigation System Shutoff
IRRIGATION_SYSTEM_SHUTOFF = 0x12

# Values used for Irrigation System Info Report command
IRRIGATION_SYSTEM_INFO_REPORT_PROPERTIES1_MAIN_VALVE_BIT_MASK = 0x01
IRRIGATION_SYSTEM_INFO_REPORT_PROPERTIES1_RESERVED1_MASK = 0x06
IRRIGATION_SYSTEM_INFO_REPORT_PROPERTIES1_RESERVED1_SHIFT = 0x01
IRRIGATION_SYSTEM_INFO_REPORT_PROPERTIES1_RESERVED2_MASK = 0x18
IRRIGATION_SYSTEM_INFO_REPORT_PROPERTIES1_RESERVED2_SHIFT = 0x03
IRRIGATION_SYSTEM_INFO_REPORT_PROPERTIES1_RESERVED3_MASK = 0xE0
IRRIGATION_SYSTEM_INFO_REPORT_PROPERTIES1_RESERVED3_SHIFT = 0x05
IRRIGATION_SYSTEM_INFO_REPORT_PROPERTIES2_VALVE_TABLE_MAX_SIZE_MASK = 0x0F
IRRIGATION_SYSTEM_INFO_REPORT_PROPERTIES2_RESERVED_MASK = 0xF0
IRRIGATION_SYSTEM_INFO_REPORT_PROPERTIES2_RESERVED_SHIFT = 0x04
# Values used for Irrigation System Status Report command
IRRIGATION_SYSTEM_STATUS_REPORT_FLOW_SENSOR_DETECTED = 0x00
IRRIGATION_SYSTEM_STATUS_REPORT_PRESSURE_SENSOR_DETECTED = 0x01
IRRIGATION_SYSTEM_STATUS_REPORT_RAIN_SENSOR_DETECTED = 0x02
IRRIGATION_SYSTEM_STATUS_REPORT_MOISTURE_SENSOR_DETECTED = 0x03
IRRIGATION_SYSTEM_STATUS_REPORT_PROPERTIES1_FLOW_SIZE_MASK = 0x07
IRRIGATION_SYSTEM_STATUS_REPORT_PROPERTIES1_FLOW_SCALE_MASK = 0x18
IRRIGATION_SYSTEM_STATUS_REPORT_PROPERTIES1_FLOW_SCALE_SHIFT = 0x03
IRRIGATION_SYSTEM_STATUS_REPORT_PROPERTIES1_FLOW_PRECISION_MASK = 0xE0
IRRIGATION_SYSTEM_STATUS_REPORT_PROPERTIES1_FLOW_PRECISION_SHIFT = 0x05
IRRIGATION_SYSTEM_STATUS_REPORT_PROPERTIES2_PRESSURE_SIZE_MASK = 0x07
IRRIGATION_SYSTEM_STATUS_REPORT_PROPERTIES2_PRESSURE_SCALE_MASK = 0x18
IRRIGATION_SYSTEM_STATUS_REPORT_PROPERTIES2_PRESSURE_SCALE_SHIFT = 0x03
IRRIGATION_SYSTEM_STATUS_REPORT_PROPERTIES2_PRESSURE_PRECISION_MASK = 0xE0
IRRIGATION_SYSTEM_STATUS_REPORT_PROPERTIES2_PRESSURE_PRECISION_SHIFT = 0x05
IRRIGATION_SYSTEM_STATUS_REPORT_PROPERTIES3_MAIN_VALVE_BIT_MASK = 0x01
IRRIGATION_SYSTEM_STATUS_REPORT_PROPERTIES3_RESERVED_MASK = 0xFE
IRRIGATION_SYSTEM_STATUS_REPORT_PROPERTIES3_RESERVED_SHIFT = 0x01
# Values used for Irrigation System Config Set command
IRRIGATION_SYSTEM_CONFIG_SET_PROPERTIES1_HIGH_PRESSURE_THRESHOLD_SIZE_MASK = 0x07
IRRIGATION_SYSTEM_CONFIG_SET_PROPERTIES1_HIGH_PRESSURE_THRESHOLD_SCALE_MASK = 0x18
IRRIGATION_SYSTEM_CONFIG_SET_PROPERTIES1_HIGH_PRESSURE_THRESHOLD_SCALE_SHIFT = 0x03
IRRIGATION_SYSTEM_CONFIG_SET_PROPERTIES1_HIGH_PRESSURE_THRESHOLD_PRECISION_MASK = 0xE0
IRRIGATION_SYSTEM_CONFIG_SET_PROPERTIES1_HIGH_PRESSURE_THRESHOLD_PRECISION_SHIFT = 0x05
IRRIGATION_SYSTEM_CONFIG_SET_PROPERTIES2_LOW_PRESSURE_THRESHOLD_SIZE_MASK = 0x07
IRRIGATION_SYSTEM_CONFIG_SET_PROPERTIES2_LOW_PRESSURE_THRESHOLD_SCALE_MASK = 0x18
IRRIGATION_SYSTEM_CONFIG_SET_PROPERTIES2_LOW_PRESSURE_THRESHOLD_SCALE_SHIFT = 0x03
IRRIGATION_SYSTEM_CONFIG_SET_PROPERTIES2_LOW_PRESSURE_THRESHOLD_PRECISION_MASK = 0xE0
IRRIGATION_SYSTEM_CONFIG_SET_PROPERTIES2_LOW_PRESSURE_THRESHOLD_PRECISION_SHIFT = 0x05
# Values used for Irrigation System Config Report command
IRRIGATION_SYSTEM_CONFIG_REPORT_PROPERTIES1_HIGH_PRESSURE_THRESHOLD_SIZE_MASK = 0x07
IRRIGATION_SYSTEM_CONFIG_REPORT_PROPERTIES1_HIGH_PRESSURE_THRESHOLD_SCALE_MASK = 0x18
IRRIGATION_SYSTEM_CONFIG_REPORT_PROPERTIES1_HIGH_PRESSURE_THRESHOLD_SCALE_SHIFT = 0x03
IRRIGATION_SYSTEM_CONFIG_REPORT_PROPERTIES1_HIGH_PRESSURE_THRESHOLD_PRECISION_MASK = 0xE0
IRRIGATION_SYSTEM_CONFIG_REPORT_PROPERTIES1_HIGH_PRESSURE_THRESHOLD_PRECISION_SHIFT = 0x05
IRRIGATION_SYSTEM_CONFIG_REPORT_PROPERTIES2_LOW_PRESSURE_THRESHOLD_SIZE_MASK = 0x07
IRRIGATION_SYSTEM_CONFIG_REPORT_PROPERTIES2_LOW_PRESSURE_THRESHOLD_SCALE_MASK = 0x18
IRRIGATION_SYSTEM_CONFIG_REPORT_PROPERTIES2_LOW_PRESSURE_THRESHOLD_SCALE_SHIFT = 0x03
IRRIGATION_SYSTEM_CONFIG_REPORT_PROPERTIES2_LOW_PRESSURE_THRESHOLD_PRECISION_MASK = 0xE0
IRRIGATION_SYSTEM_CONFIG_REPORT_PROPERTIES2_LOW_PRESSURE_THRESHOLD_PRECISION_SHIFT = 0x05
# Values used for Irrigation Valve Info Get command
IRRIGATION_VALVE_INFO_GET_PROPERTIES1_MAIN_VALVE_BIT_MASK = 0x01
IRRIGATION_VALVE_INFO_GET_PROPERTIES1_RESERVED_MASK = 0xFE
IRRIGATION_VALVE_INFO_GET_PROPERTIES1_RESERVED_SHIFT = 0x01
# Values used for Irrigation Valve Info Report command
IRRIGATION_VALVE_INFO_REPORT_PROPERTIES1_MAIN_BIT_MASK = 0x01
IRRIGATION_VALVE_INFO_REPORT_PROPERTIES1_CONNECTED_BIT_MASK = 0x02
IRRIGATION_VALVE_INFO_REPORT_PROPERTIES1_RESERVED_MASK = 0xFC
IRRIGATION_VALVE_INFO_REPORT_PROPERTIES1_RESERVED_SHIFT = 0x02
# Values used for Irrigation Valve Config Set command
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES1_MAIN_VALVE_BIT_MASK = 0x01
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES1_RESERVED_MASK = 0xFE
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES1_RESERVED_SHIFT = 0x01
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES2_MAXIMUM_FLOW_SIZE_MASK = 0x07
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES2_MAXIMUM_FLOW_SCALE_MASK = 0x18
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES2_MAXIMUM_FLOW_SCALE_SHIFT = 0x03
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES2_MAXIMUM_FLOW_PRECISION_MASK = 0xE0
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES2_MAXIMUM_FLOW_PRECISION_SHIFT = 0x05
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES3_FLOW_HIGH_THRESHOLD_SIZE_MASK = 0x07
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES3_FLOW_HIGH_THRESHOLD_SCALE_MASK = 0x18
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES3_FLOW_HIGH_THRESHOLD_SCALE_SHIFT = 0x03
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES3_FLOW_HIGH_THRESHOLD_PRECISION_MASK = 0xE0
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES3_FLOW_HIGH_THRESHOLD_PRECISION_SHIFT = 0x05
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES4_FLOW_LOW_THRESHOLD_SIZE_MASK = 0x07
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES4_FLOW_LOW_THRESHOLD_SCALE_MASK = 0x18
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES4_FLOW_LOW_THRESHOLD_SCALE_SHIFT = 0x03
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES4_FLOW_LOW_THRESHOLD_PRECISION_MASK = 0xE0
IRRIGATION_VALVE_CONFIG_SET_PROPERTIES4_FLOW_LOW_THRESHOLD_PRECISION_SHIFT = 0x05
# Values used for Irrigation Valve Config Get command
IRRIGATION_VALVE_CONFIG_GET_PROPERTIES1_MAIN_VALVE_BIT_MASK = 0x01
IRRIGATION_VALVE_CONFIG_GET_PROPERTIES1_RESERVED_MASK = 0xFE
IRRIGATION_VALVE_CONFIG_GET_PROPERTIES1_RESERVED_SHIFT = 0x01
# Values used for Irrigation Valve Config Report command
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES1_MAIN_VALVE_BIT_MASK = 0x01
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES1_RESERVED_MASK = 0xFE
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES1_RESERVED_SHIFT = 0x01
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES2_MAXIMUM_FLOW_SIZE_MASK = 0x07
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES2_MAXIMUM_FLOW_SCALE_MASK = 0x18
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES2_MAXIMUM_FLOW_SCALE_SHIFT = 0x03
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES2_MAXIMUM_FLOW_PRECISION_MASK = 0xE0
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES2_MAXIMUM_FLOW_PRECISION_SHIFT = 0x05
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES3_FLOW_HIGH_THRESHOLD_SIZE_MASK = 0x07
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES3_FLOW_HIGH_THRESHOLD_SCALE_MASK = 0x18
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES3_FLOW_HIGH_THRESHOLD_SCALE_SHIFT = 0x03
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES3_FLOW_HIGH_THRESHOLD_PRECISION_MASK = 0xE0
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES3_FLOW_HIGH_THRESHOLD_PRECISION_SHIFT = 0x05
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES4_FLOW_LOW_THRESHOLD_SIZE_MASK = 0x07
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES4_FLOW_LOW_THRESHOLD_SCALE_MASK = 0x18
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES4_FLOW_LOW_THRESHOLD_SCALE_SHIFT = 0x03
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES4_FLOW_LOW_THRESHOLD_PRECISION_MASK = 0xE0
IRRIGATION_VALVE_CONFIG_REPORT_PROPERTIES4_FLOW_LOW_THRESHOLD_PRECISION_SHIFT = 0x05
# Values used for Irrigation Valve Run command
IRRIGATION_VALVE_RUN_PROPERTIES1_MAIN_VALVE_BIT_MASK = 0x01
IRRIGATION_VALVE_RUN_PROPERTIES1_RESERVED_MASK = 0xFE
IRRIGATION_VALVE_RUN_PROPERTIES1_RESERVED_SHIFT = 0x01

class ZW_IRRIGATION_SYSTEM_INFO_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_IRRIGATION_SYSTEM_INFO_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('totalNumberOfValves', uint8_t),
        ('totalNumberOfValveTables', uint8_t),
        ('properties2', uint8_t),
    ]


class ZW_IRRIGATION_SYSTEM_STATUS_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_IRRIGATION_SYSTEM_STATUS_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('systemVoltage', uint8_t),
        ('sensorStatus', uint8_t),
        ('properties1', uint8_t),
        ('flowValue1', uint8_t),
        ('properties2', uint8_t),
        ('pressureValue1', uint8_t),
        ('shutoffDuration', uint8_t),
        ('systemErrorStatus', uint8_t),
        ('properties3', uint8_t),
        ('valveId', uint8_t),
    ]


class ZW_IRRIGATION_SYSTEM_CONFIG_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('mainValveDelay', uint8_t),
        ('properties1', uint8_t),
        ('highPressureThresholdValue1', uint8_t),
        ('properties2', uint8_t),
        ('lowPressureThresholdValue1', uint8_t),
        ('sensorPolarity', uint8_t),
    ]


class ZW_IRRIGATION_SYSTEM_CONFIG_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_IRRIGATION_SYSTEM_CONFIG_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('mainValveDelay', uint8_t),
        ('properties1', uint8_t),
        ('highPressureThresholdValue1', uint8_t),
        ('properties2', uint8_t),
        ('lowPressureThresholdValue1', uint8_t),
        ('sensorPolarity', uint8_t),
    ]


class ZW_IRRIGATION_VALVE_INFO_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('valveId', uint8_t),
    ]


class ZW_IRRIGATION_VALVE_INFO_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('valveId', uint8_t),
        ('nominalCurrent', uint8_t),
        ('valveErrorStatus', uint8_t),
    ]


class ZW_IRRIGATION_VALVE_CONFIG_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('valveId', uint8_t),
        ('nominalCurrentHighThreshold', uint8_t),
        ('nominalCurrentLowThreshold', uint8_t),
        ('properties2', uint8_t),
        ('maximumFlowValue1', uint8_t),
        ('properties3', uint8_t),
        ('flowHighThresholdValue1', uint8_t),
        ('properties4', uint8_t),
        ('flowLowThresholdValue1', uint8_t),
        ('sensorUsage', uint8_t),
    ]


class ZW_IRRIGATION_VALVE_CONFIG_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('valveId', uint8_t),
    ]


class ZW_IRRIGATION_VALVE_CONFIG_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('valveId', uint8_t),
        ('nominalCurrentHighThreshold', uint8_t),
        ('nominalCurrentLowThreshold', uint8_t),
        ('properties2', uint8_t),
        ('maximumFlowValue1', uint8_t),
        ('properties3', uint8_t),
        ('flowHighThresholdValue1', uint8_t),
        ('properties4', uint8_t),
        ('flowLowThresholdValue1', uint8_t),
        ('sensorUsage', uint8_t),
    ]


class ZW_IRRIGATION_VALVE_RUN_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('valveId', uint8_t),
        ('duration1', uint8_t),
        ('duration2', uint8_t),
    ]


class VG_IRRIGATION_VALVE_TABLE_SET_VG(ctypes.Structure):
    _fields_ = [
        ('valveId', uint8_t),
        ('duration1', uint8_t),
        ('duration2', uint8_t),
    ]


class ZW_IRRIGATION_VALVE_TABLE_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('valveTableId', uint8_t),
        ('variantgroup1', VG_IRRIGATION_VALVE_TABLE_SET_VG),
    ]


class ZW_IRRIGATION_VALVE_TABLE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('valveTableId', uint8_t)]


class VG_IRRIGATION_VALVE_TABLE_REPORT_VG(ctypes.Structure):
    _fields_ = [
        ('valveId', uint8_t),
        ('duration1', uint8_t),
        ('duration2', uint8_t),
    ]



class ZW_IRRIGATION_VALVE_TABLE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('valveTableId', uint8_t),
        ('variantgroup1', VG_IRRIGATION_VALVE_TABLE_REPORT_VG),
    ]


class ZW_IRRIGATION_VALVE_TABLE_RUN_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('valveTableId1', uint8_t)]


class ZW_IRRIGATION_SYSTEM_SHUTOFF_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('duration', uint8_t)]

