# Manufacturer Specific Command Class
# Management
# ==============================
COMMAND_CLASS_MANUFACTURER_SPECIFIC = 0x72

MANUFACTURER_SPECIFIC_VERSION = 0x01
# Manufacturer Specific Get
MANUFACTURER_SPECIFIC_GET = 0x04
# Manufacturer Specific Report
MANUFACTURER_SPECIFIC_REPORT = 0x05

MANUFACTURER_SPECIFIC_VERSION_V2 = 0x02
MANUFACTURER_SPECIFIC_GET_V2 = 0x04
MANUFACTURER_SPECIFIC_REPORT_V2 = 0x05
# Device Specific Get
DEVICE_SPECIFIC_GET_V2 = 0x06
# Device Specific Report
DEVICE_SPECIFIC_REPORT_V2 = 0x07

# Values used for Device Specific Get command
DEVICE_SPECIFIC_GET_PROPERTIES1_DEVICE_ID_TYPE_MASK_V2 = 0x07
DEVICE_SPECIFIC_GET_DEVICE_ID_TYPE_RESERVED_V2 = 0x00
DEVICE_SPECIFIC_GET_DEVICE_ID_TYPE_SERIAL_NUMBER_V2 = 0x01
DEVICE_SPECIFIC_GET_PROPERTIES1_RESERVED_MASK_V2 = 0xF8
DEVICE_SPECIFIC_GET_PROPERTIES1_RESERVED_SHIFT_V2 = 0x03
# Values used for Device Specific Report command
DEVICE_SPECIFIC_REPORT_PROPERTIES1_DEVICE_ID_TYPE_MASK_V2 = 0x07
DEVICE_SPECIFIC_REPORT_DEVICE_ID_TYPE_RESERVED_V2 = 0x00
DEVICE_SPECIFIC_REPORT_DEVICE_ID_TYPE_SERIAL_NUMBER_V2 = 0x01
DEVICE_SPECIFIC_REPORT_PROPERTIES1_RESERVED_MASK_V2 = 0xF8
DEVICE_SPECIFIC_REPORT_PROPERTIES1_RESERVED_SHIFT_V2 = 0x03
DEVICE_SPECIFIC_REPORT_PROPERTIES2_DEVICE_ID_DATA_LENGTH_INDICATOR_MASK_V2 = 0x1F
DEVICE_SPECIFIC_REPORT_PROPERTIES2_DEVICE_ID_DATA_FORMAT_MASK_V2 = 0xE0
DEVICE_SPECIFIC_REPORT_PROPERTIES2_DEVICE_ID_DATA_FORMAT_SHIFT_V2 = 0x05
DEVICE_SPECIFIC_REPORT_DEVICE_ID_DATA_FORMAT_RESERVED_V2 = 0x00
DEVICE_SPECIFIC_REPORT_DEVICE_ID_DATA_FORMAT_BINARY_V2 = 0x01




class ZW_MANUFACTURER_SPECIFIC_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_MANUFACTURER_SPECIFIC_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('manufacturerId1', uint8_t),
        ('manufacturerId2', uint8_t),
        ('productTypeId1', uint8_t),
        ('productTypeId2', uint8_t),
        ('productId1', uint8_t),
        ('productId2', uint8_t),
    ]


class ZW_MANUFACTURER_SPECIFIC_GET_V2_FRAME(ZW_MANUFACTURER_SPECIFIC_GET_FRAME):
    _fields_ = []


class ZW_MANUFACTURER_SPECIFIC_REPORT_V2_FRAME(ZW_MANUFACTURER_SPECIFIC_REPORT_FRAME):
    _fields_ = []


class ZW_DEVICE_SPECIFIC_GET_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('properties1', uint8_t)]


class ZW_DEVICE_SPECIFIC_REPORT_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('properties2', uint8_t),
        ('deviceIdData1', uint8_t),
    ]




