# Meter Command Class
# Application
# ==============================
COMMAND_CLASS_METER = 0x32

METER_VERSION = 0x01
# Meter Get
METER_GET = 0x01
# Meter Report
METER_REPORT = 0x02

# Values used for Meter Report command
METER_REPORT_ELECTRIC_METER = 0x01
METER_REPORT_GAS_METER = 0x02
METER_REPORT_WATER_METER = 0x03
METER_REPORT_PROPERTIES1_SIZE_MASK = 0x07
METER_REPORT_PROPERTIES1_SCALE_MASK = 0x18
METER_REPORT_PROPERTIES1_SCALE_SHIFT = 0x03
METER_REPORT_PROPERTIES1_PRECISION_MASK = 0xE0
METER_REPORT_PROPERTIES1_PRECISION_SHIFT = 0x05

METER_VERSION_V2 = 0x02
METER_GET_V2 = 0x01
METER_REPORT_V2 = 0x02
# Meter Supported Get
METER_SUPPORTED_GET_V2 = 0x03
# Meter Supported Report
METER_SUPPORTED_REPORT_V2 = 0x04
# Meter Reset
METER_RESET_V2 = 0x05

# Values used for Meter Get command
METER_GET_PROPERTIES1_RESERVED_MASK_V2 = 0x07
METER_GET_PROPERTIES1_SCALE_MASK_V2 = 0x18
METER_GET_PROPERTIES1_SCALE_SHIFT_V2 = 0x03
METER_GET_PROPERTIES1_RESERVED2_MASK_V2 = 0xE0
METER_GET_PROPERTIES1_RESERVED2_SHIFT_V2 = 0x05
# Values used for Meter Report command
METER_REPORT_PROPERTIES1_METER_TYPE_MASK_V2 = 0x1F
METER_REPORT_PROPERTIES1_RATE_TYPE_MASK_V2 = 0x60
METER_REPORT_PROPERTIES1_RATE_TYPE_SHIFT_V2 = 0x05
METER_REPORT_PROPERTIES1_RESERVED_BIT_MASK_V2 = 0x80
METER_REPORT_PROPERTIES2_SIZE_MASK_V2 = 0x07
METER_REPORT_PROPERTIES2_SCALE_MASK_V2 = 0x18
METER_REPORT_PROPERTIES2_SCALE_SHIFT_V2 = 0x03
METER_REPORT_PROPERTIES2_PRECISION_MASK_V2 = 0xE0
METER_REPORT_PROPERTIES2_PRECISION_SHIFT_V2 = 0x05
# Values used for Meter Supported Report command
METER_SUPPORTED_REPORT_PROPERTIES1_METER_TYPE_MASK_V2 = 0x1F
METER_SUPPORTED_REPORT_PROPERTIES1_RESERVED1_MASK_V2 = 0x60
METER_SUPPORTED_REPORT_PROPERTIES1_RESERVED1_SHIFT_V2 = 0x05
METER_SUPPORTED_REPORT_PROPERTIES1_METER_RESET_BIT_MASK_V2 = 0x80
METER_SUPPORTED_REPORT_PROPERTIES2_SCALE_SUPPORTED_MASK_V2 = 0x0F
METER_SUPPORTED_REPORT_PROPERTIES2_RESERVED2_MASK_V2 = 0xF0
METER_SUPPORTED_REPORT_PROPERTIES2_RESERVED2_SHIFT_V2 = 0x04

METER_VERSION_V3 = 0x03
METER_GET_V3 = 0x01
METER_REPORT_V3 = 0x02
METER_RESET_V3 = 0x05
METER_SUPPORTED_GET_V3 = 0x03
METER_SUPPORTED_REPORT_V3 = 0x04
# Values used for Meter Get command
METER_GET_PROPERTIES1_RESERVED_MASK_V3 = 0x07
METER_GET_PROPERTIES1_SCALE_MASK_V3 = 0x38
METER_GET_PROPERTIES1_SCALE_SHIFT_V3 = 0x03
METER_GET_PROPERTIES1_RESERVED2_MASK_V3 = 0xC0
METER_GET_PROPERTIES1_RESERVED2_SHIFT_V3 = 0x06
# Values used for Meter Report command
METER_REPORT_PROPERTIES1_METER_TYPE_MASK_V3 = 0x1F
METER_REPORT_PROPERTIES1_RATE_TYPE_MASK_V3 = 0x60
METER_REPORT_PROPERTIES1_RATE_TYPE_SHIFT_V3 = 0x05
METER_REPORT_PROPERTIES1_SCALE_BIT_2_BIT_MASK_V3 = 0x80
METER_REPORT_PROPERTIES2_SIZE_MASK_V3 = 0x07
METER_REPORT_PROPERTIES2_SCALE_BITS_10_MASK_V3 = 0x18
METER_REPORT_PROPERTIES2_SCALE_BITS_10_SHIFT_V3 = 0x03
METER_REPORT_PROPERTIES2_PRECISION_MASK_V3 = 0xE0
METER_REPORT_PROPERTIES2_PRECISION_SHIFT_V3 = 0x05
# Values used for Meter Supported Report command
METER_SUPPORTED_REPORT_PROPERTIES1_METER_TYPE_MASK_V3 = 0x1F
METER_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V3 = 0x60
METER_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V3 = 0x05
METER_SUPPORTED_REPORT_PROPERTIES1_METER_RESET_BIT_MASK_V3 = 0x80

METER_VERSION_V4 = 0x04
METER_GET_V4 = 0x01
METER_REPORT_V4 = 0x02
METER_RESET_V4 = 0x05
METER_SUPPORTED_GET_V4 = 0x03
METER_SUPPORTED_REPORT_V4 = 0x04
# Values used for Meter Get command
METER_GET_PROPERTIES1_RESERVED_MASK_V4 = 0x07
METER_GET_PROPERTIES1_SCALE_MASK_V4 = 0x38
METER_GET_PROPERTIES1_SCALE_SHIFT_V4 = 0x03
METER_GET_PROPERTIES1_RATE_TYPE_MASK_V4 = 0xC0
METER_GET_PROPERTIES1_RATE_TYPE_SHIFT_V4 = 0x06
METER_GET_RATE_TYPE_RESERVED_V4 = 0x00
METER_GET_RATE_TYPE_IMPORT_V4 = 0x01
METER_GET_RATE_TYPE_EXPORT_V4 = 0x02
METER_GET_RATE_TYPE_NOT_TO_BE_USED_V4 = 0x03
# Values used for Meter Report command
METER_REPORT_PROPERTIES1_METER_TYPE_MASK_V4 = 0x1F
METER_REPORT_METER_TYPE_RESERVED_V4 = 0x00
METER_REPORT_METER_TYPE_ELECTRIC_METER_V4 = 0x01
METER_REPORT_METER_TYPE_GAS_METER_V4 = 0x02
METER_REPORT_METER_TYPE_WATER_METER_V4 = 0x03
METER_REPORT_PROPERTIES1_RATE_TYPE_MASK_V4 = 0x60
METER_REPORT_PROPERTIES1_RATE_TYPE_SHIFT_V4 = 0x05
METER_REPORT_RATE_TYPE_RESERVED_V4 = 0x00
METER_REPORT_RATE_TYPE_IMPORT_V4 = 0x01
METER_REPORT_RATE_TYPE_EXPORT_V4 = 0x02
METER_REPORT_RATE_TYPE_NOT_TO_BE_USED_V4 = 0x03
METER_REPORT_PROPERTIES1_SCALE_BIT_2_BIT_MASK_V4 = 0x80
METER_REPORT_PROPERTIES2_SIZE_MASK_V4 = 0x07
METER_REPORT_PROPERTIES2_SCALE_BITS_10_MASK_V4 = 0x18
METER_REPORT_PROPERTIES2_SCALE_BITS_10_SHIFT_V4 = 0x03
METER_REPORT_PROPERTIES2_PRECISION_MASK_V4 = 0xE0
METER_REPORT_PROPERTIES2_PRECISION_SHIFT_V4 = 0x05
# Values used for Meter Supported Report command
METER_SUPPORTED_REPORT_PROPERTIES1_METER_TYPE_MASK_V4 = 0x1F
METER_SUPPORTED_REPORT_METER_TYPE_RESERVED_V4 = 0x00
METER_SUPPORTED_REPORT_METER_TYPE_ELECTRIC_METER_V4 = 0x01
METER_SUPPORTED_REPORT_METER_TYPE_GAS_METER_V4 = 0x02
METER_SUPPORTED_REPORT_METER_TYPE_WATER_METER_V4 = 0x03
METER_SUPPORTED_REPORT_PROPERTIES1_RATE_TYPE_MASK_V4 = 0x60
METER_SUPPORTED_REPORT_PROPERTIES1_RATE_TYPE_SHIFT_V4 = 0x05
METER_SUPPORTED_REPORT_RATE_TYPE_RESERVED_V4 = 0x00
METER_SUPPORTED_REPORT_RATE_TYPE_IMPORT_ONLY_V4 = 0x01
METER_SUPPORTED_REPORT_RATE_TYPE_EXPORT_ONLY_V4 = 0x02
METER_SUPPORTED_REPORT_RATE_TYPE_IMPORT_AND_EXPORT_V4 = 0x03
METER_SUPPORTED_REPORT_PROPERTIES1_METER_RESET_BIT_MASK_V4 = 0x80
METER_SUPPORTED_REPORT_PROPERTIES2_SCALE_SUPPORTED_0_MASK_V4 = 0x7F
METER_SUPPORTED_REPORT_PROPERTIES2_M_S_T_BIT_MASK_V4 = 0x80

METER_VERSION_V5 = 0x05
METER_GET_V5 = 0x01
METER_REPORT_V5 = 0x02
METER_RESET_V5 = 0x05
METER_SUPPORTED_GET_V5 = 0x03
METER_SUPPORTED_REPORT_V5 = 0x04
# Values used for Meter Get command
METER_GET_PROPERTIES1_RESERVED_MASK_V5 = 0x07
METER_GET_PROPERTIES1_SCALE_MASK_V5 = 0x38
METER_GET_PROPERTIES1_SCALE_SHIFT_V5 = 0x03
METER_GET_PROPERTIES1_RATE_TYPE_MASK_V5 = 0xC0
METER_GET_PROPERTIES1_RATE_TYPE_SHIFT_V5 = 0x06
METER_GET_RATE_TYPE_RESERVED_V5 = 0x00
METER_GET_RATE_TYPE_IMPORT_V5 = 0x01
METER_GET_RATE_TYPE_EXPORT_V5 = 0x02
METER_GET_RATE_TYPE_NOT_TO_BE_USED_V5 = 0x03
# Values used for Meter Report command
METER_REPORT_PROPERTIES1_METER_TYPE_MASK_V5 = 0x1F
METER_REPORT_METER_TYPE_RESERVED_V5 = 0x00
METER_REPORT_METER_TYPE_ELECTRIC_METER_V5 = 0x01
METER_REPORT_METER_TYPE_GAS_METER_V5 = 0x02
METER_REPORT_METER_TYPE_WATER_METER_V5 = 0x03
METER_REPORT_METER_TYPE_HEATING_METER_V5 = 0x04
METER_REPORT_METER_TYPE_COOLING_METER_V5 = 0x05
METER_REPORT_PROPERTIES1_RATE_TYPE_MASK_V5 = 0x60
METER_REPORT_PROPERTIES1_RATE_TYPE_SHIFT_V5 = 0x05
METER_REPORT_RATE_TYPE_RESERVED_V5 = 0x00
METER_REPORT_RATE_TYPE_IMPORT_V5 = 0x01
METER_REPORT_RATE_TYPE_EXPORT_V5 = 0x02
METER_REPORT_RATE_TYPE_NOT_TO_BE_USED_V5 = 0x03
METER_REPORT_PROPERTIES1_SCALE_BIT_2_BIT_MASK_V5 = 0x80
METER_REPORT_PROPERTIES2_SIZE_MASK_V5 = 0x07
METER_REPORT_PROPERTIES2_SCALE_BITS_10_MASK_V5 = 0x18
METER_REPORT_PROPERTIES2_SCALE_BITS_10_SHIFT_V5 = 0x03
METER_REPORT_PROPERTIES2_PRECISION_MASK_V5 = 0xE0
METER_REPORT_PROPERTIES2_PRECISION_SHIFT_V5 = 0x05
# Values used for Meter Supported Report command
METER_SUPPORTED_REPORT_PROPERTIES1_METER_TYPE_MASK_V5 = 0x1F
METER_SUPPORTED_REPORT_METER_TYPE_RESERVED_V5 = 0x00
METER_SUPPORTED_REPORT_METER_TYPE_ELECTRIC_METER_V5 = 0x01
METER_SUPPORTED_REPORT_METER_TYPE_GAS_METER_V5 = 0x02
METER_SUPPORTED_REPORT_METER_TYPE_WATER_METER_V5 = 0x03
METER_SUPPORTED_REPORT_METER_TYPE_HEATING_METER_V5 = 0x04
METER_SUPPORTED_REPORT_METER_TYPE_COOLING_METER_V5 = 0x05
METER_SUPPORTED_REPORT_PROPERTIES1_RATE_TYPE_MASK_V5 = 0x60
METER_SUPPORTED_REPORT_PROPERTIES1_RATE_TYPE_SHIFT_V5 = 0x05
METER_SUPPORTED_REPORT_RATE_TYPE_RESERVED_V5 = 0x00
METER_SUPPORTED_REPORT_RATE_TYPE_IMPORT_ONLY_V5 = 0x01
METER_SUPPORTED_REPORT_RATE_TYPE_EXPORT_ONLY_V5 = 0x02
METER_SUPPORTED_REPORT_RATE_TYPE_IMPORT_AND_EXPORT_V5 = 0x03
METER_SUPPORTED_REPORT_PROPERTIES1_METER_RESET_BIT_MASK_V5 = 0x80
METER_SUPPORTED_REPORT_PROPERTIES2_SCALE_SUPPORTED_0_MASK_V5 = 0x7F
METER_SUPPORTED_REPORT_PROPERTIES2_M_S_T_BIT_MASK_V5 = 0x80

METER_VERSION_V6 = 0x06
METER_GET_V6 = 0x01
METER_REPORT_V6 = 0x02
METER_RESET_V6 = 0x05
METER_SUPPORTED_GET_V6 = 0x03
METER_SUPPORTED_REPORT_V6 = 0x04
# Values used for Meter Get command
METER_GET_PROPERTIES1_RESERVED_MASK_V6 = 0x07
METER_GET_PROPERTIES1_SCALE_MASK_V6 = 0x38
METER_GET_PROPERTIES1_SCALE_SHIFT_V6 = 0x03
METER_GET_PROPERTIES1_RATE_TYPE_MASK_V6 = 0xC0
METER_GET_PROPERTIES1_RATE_TYPE_SHIFT_V6 = 0x06
METER_GET_RATE_TYPE_RESERVED_V6 = 0x00
METER_GET_RATE_TYPE_IMPORT_V6 = 0x01
METER_GET_RATE_TYPE_EXPORT_V6 = 0x02
METER_GET_RATE_TYPE_NOT_TO_BE_USED_V6 = 0x03
# Values used for Meter Report command
METER_REPORT_PROPERTIES1_METER_TYPE_MASK_V6 = 0x1F
METER_REPORT_METER_TYPE_RESERVED_V6 = 0x00
METER_REPORT_METER_TYPE_ELECTRIC_METER_V6 = 0x01
METER_REPORT_METER_TYPE_GAS_METER_V6 = 0x02
METER_REPORT_METER_TYPE_WATER_METER_V6 = 0x03
METER_REPORT_METER_TYPE_HEATING_METER_V6 = 0x04
METER_REPORT_METER_TYPE_COOLING_METER_V6 = 0x05
METER_REPORT_PROPERTIES1_RATE_TYPE_MASK_V6 = 0x60
METER_REPORT_PROPERTIES1_RATE_TYPE_SHIFT_V6 = 0x05
METER_REPORT_RATE_TYPE_RESERVED_V6 = 0x00
METER_REPORT_RATE_TYPE_IMPORT_V6 = 0x01
METER_REPORT_RATE_TYPE_EXPORT_V6 = 0x02
METER_REPORT_RATE_TYPE_NOT_TO_BE_USED_V6 = 0x03
METER_REPORT_PROPERTIES1_SCALE_BIT_2_BIT_MASK_V6 = 0x80
METER_REPORT_PROPERTIES2_SIZE_MASK_V6 = 0x07
METER_REPORT_PROPERTIES2_SCALE_BITS_10_MASK_V6 = 0x18
METER_REPORT_PROPERTIES2_SCALE_BITS_10_SHIFT_V6 = 0x03
METER_REPORT_PROPERTIES2_PRECISION_MASK_V6 = 0xE0
METER_REPORT_PROPERTIES2_PRECISION_SHIFT_V6 = 0x05
# Values used for Meter Reset command
METER_RESET_PROPERTIES1_METER_TYPE_MASK_V6 = 0x1F
METER_RESET_METER_TYPE_RESERVED_V6 = 0x00
METER_RESET_METER_TYPE_ELECTRIC_METER_V6 = 0x01
METER_RESET_METER_TYPE_GAS_METER_V6 = 0x02
METER_RESET_METER_TYPE_WATER_METER_V6 = 0x03
METER_RESET_METER_TYPE_HEATING_METER_V6 = 0x04
METER_RESET_METER_TYPE_COOLING_METER_V6 = 0x05
METER_RESET_PROPERTIES1_RATE_TYPE_MASK_V6 = 0x60
METER_RESET_PROPERTIES1_RATE_TYPE_SHIFT_V6 = 0x05
METER_RESET_PROPERTIES1_SCALE_BIT_2_BIT_MASK_V6 = 0x80
METER_RESET_PROPERTIES2_SIZE_MASK_V6 = 0x07
METER_RESET_PROPERTIES2_SCALE_BITS_10_MASK_V6 = 0x18
METER_RESET_PROPERTIES2_SCALE_BITS_10_SHIFT_V6 = 0x03
METER_RESET_PROPERTIES2_PRECISION_MASK_V6 = 0xE0
METER_RESET_PROPERTIES2_PRECISION_SHIFT_V6 = 0x05
# Values used for Meter Supported Report command
METER_SUPPORTED_REPORT_PROPERTIES1_METER_TYPE_MASK_V6 = 0x1F
METER_SUPPORTED_REPORT_METER_TYPE_RESERVED_V6 = 0x00
METER_SUPPORTED_REPORT_METER_TYPE_ELECTRIC_METER_V6 = 0x01
METER_SUPPORTED_REPORT_METER_TYPE_GAS_METER_V6 = 0x02
METER_SUPPORTED_REPORT_METER_TYPE_WATER_METER_V6 = 0x03
METER_SUPPORTED_REPORT_METER_TYPE_HEATING_METER_V6 = 0x04
METER_SUPPORTED_REPORT_METER_TYPE_COOLING_METER_V6 = 0x05
METER_SUPPORTED_REPORT_PROPERTIES1_RATE_TYPE_MASK_V6 = 0x60
METER_SUPPORTED_REPORT_PROPERTIES1_RATE_TYPE_SHIFT_V6 = 0x05
METER_SUPPORTED_REPORT_RATE_TYPE_RESERVED_V6 = 0x00
METER_SUPPORTED_REPORT_RATE_TYPE_IMPORT_ONLY_V6 = 0x01
METER_SUPPORTED_REPORT_RATE_TYPE_EXPORT_ONLY_V6 = 0x02
METER_SUPPORTED_REPORT_RATE_TYPE_IMPORT_AND_EXPORT_V6 = 0x03
METER_SUPPORTED_REPORT_PROPERTIES1_METER_RESET_BIT_MASK_V6 = 0x80
METER_SUPPORTED_REPORT_PROPERTIES2_SCALE_SUPPORTED_0_MASK_V6 = 0x7F
METER_SUPPORTED_REPORT_PROPERTIES2_M_S_T_BIT_MASK_V6 = 0x80


class ZW_METER_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_METER_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('meterType', uint8_t),
        ('properties1', uint8_t),
        ('meterValue1', uint8_t),
    ]


class ZW_METER_GET_V2_FRAME(ZW_METER_GET_FRAME):
    _fields_ = [('properties1', uint8_t)]


class ZW_METER_REPORT_V2_FRAME(ZW_METER_REPORT_FRAME):
    _fields_ = [
        ('properties2', uint8_t),
        ('deltaTime1', uint8_t),
        ('deltaTime2', uint8_t),
        ('previousMeterValue1', uint8_t),
    ]


class ZW_METER_RESET_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_METER_SUPPORTED_GET_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_METER_SUPPORTED_REPORT_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('properties2', uint8_t),
    ]


class ZW_METER_GET_V3_FRAME(ZW_METER_GET_V2_FRAME):
    _fields_ = []


class ZW_METER_REPORT_V3_FRAME(ZW_METER_REPORT_V2_FRAME):
    _fields_ = []


class ZW_METER_RESET_V3_FRAME(ZW_METER_RESET_V2_FRAME):
    _fields_ = []


class ZW_METER_SUPPORTED_GET_V3_FRAME(ZW_METER_SUPPORTED_GET_V2_FRAME):
    _fields_ = []


class ZW_METER_SUPPORTED_REPORT_V3_FRAME(ZW_METER_SUPPORTED_REPORT_V2_FRAME):
    _fields_ = [('scaleSupported', uint8_t)]


class ZW_METER_GET_V4_FRAME(ZW_METER_GET_V3_FRAME):
    _fields_ = [('scale2', uint8_t)]


class ZW_METER_REPORT_V4_FRAME(ZW_METER_REPORT_V3_FRAME):
    _fields_ = [('scale2', uint8_t)]


class ZW_METER_RESET_V4_FRAME(ZW_METER_RESET_V3_FRAME):
    _fields_ = []


class ZW_METER_SUPPORTED_GET_V4_FRAME(ZW_METER_SUPPORTED_GET_V3_FRAME):
    _fields_ = []


class ZW_METER_SUPPORTED_REPORT_V4_FRAME(ZW_METER_SUPPORTED_REPORT_V3_FRAME):
    _fields_ = [
        ('properties2', uint8_t),
        ('numberOfScaleSupportedBytesToFollow', uint8_t),
        ('scaleSupported1', uint8_t),
    ]


class ZW_METER_GET_V5_FRAME(ZW_METER_GET_V4_FRAME):
    _fields_ = []


class ZW_METER_REPORT_V5_FRAME(ZW_METER_REPORT_V4_FRAME):
    _fields_ = []


class ZW_METER_RESET_V5_FRAME(ZW_METER_RESET_V4_FRAME):
    _fields_ = []


class ZW_METER_SUPPORTED_GET_V5_FRAME(ZW_METER_SUPPORTED_GET_V4_FRAME):
    _fields_ = []


class ZW_METER_SUPPORTED_REPORT_V5_FRAME(ZW_METER_SUPPORTED_REPORT_V4_FRAME):
    _fields_ = []


class ZW_METER_GET_V6_FRAME(ZW_METER_GET_V5_FRAME):
    _fields_ = []


class ZW_METER_REPORT_V6_FRAME(ZW_METER_REPORT_V5_FRAME):
    _fields_ = []


class ZW_METER_RESET_V6_FRAME(ZW_METER_RESET_V5_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('properties2', uint8_t),
        ('meterValue1', uint8_t),
        ('scale2', uint8_t),
    ]


class ZW_METER_SUPPORTED_GET_V6_FRAME(ZW_METER_SUPPORTED_GET_V5_FRAME):
    _fields_ = []


class ZW_METER_SUPPORTED_REPORT_V6_FRAME(ZW_METER_SUPPORTED_REPORT_V5_FRAME):
    _fields_ = []

