# Network Management Proxy Command Class
# Network-Protocol
# ==============================
COMMAND_CLASS_NETWORK_MANAGEMENT_PROXY = 0x52

NETWORK_MANAGEMENT_PROXY_VERSION = 0x01
# Node List Get
COMMAND_NODE_LIST_GET = 0x01
# Node List Report
COMMAND_NODE_LIST_REPORT = 0x02
# Node List Cached Get
COMMAND_NODE_INFO_CACHED_GET = 0x03
# Node List Cached Report
COMMAND_NODE_INFO_CACHED_REPORT = 0x04

# Values used for Node Info Cached Get command
NODE_INFO_CACHED_GET_PROPERTIES1_MAX_AGE_MASK = 0x0F
NODE_INFO_CACHED_GET_PROPERTIES1_RESERVED_MASK = 0xF0
NODE_INFO_CACHED_GET_PROPERTIES1_RESERVED_SHIFT = 0x04
# Values used for Node Info Cached Report command
NODE_INFO_CACHED_REPORT_PROPERTIES1_AGE_MASK = 0x0F
NODE_INFO_CACHED_REPORT_PROPERTIES1_STATUS_MASK = 0xF0
NODE_INFO_CACHED_REPORT_PROPERTIES1_STATUS_SHIFT = 0x04
NODE_INFO_CACHED_REPORT_STATUS_STATUS_OK = 0x00
NODE_INFO_CACHED_REPORT_STATUS_STATUS_NOT_RESPONDING = 0x01
NODE_INFO_CACHED_REPORT_STATUS_STATUS_UNKNOWN = 0x02
NODE_INFO_CACHED_REPORT_PROPERTIES2_Z_WAVE_PROTOCOL_SPECIFIC_PART_1_MASK = 0x7F
NODE_INFO_CACHED_REPORT_PROPERTIES2_LISTENING_BIT_MASK = 0x80
NODE_INFO_CACHED_REPORT_PROPERTIES3_Z_WAVE_PROTOCOL_SPECIFIC_PART_2_MASK = 0x7F
NODE_INFO_CACHED_REPORT_PROPERTIES3_OPT_BIT_MASK = 0x80

NETWORK_MANAGEMENT_PROXY_VERSION_V2 = 0x02
COMMAND_NODE_INFO_CACHED_GET_V2 = 0x03
COMMAND_NODE_INFO_CACHED_REPORT_V2 = 0x04
COMMAND_NODE_LIST_GET_V2 = 0x01
COMMAND_NODE_LIST_REPORT_V2 = 0x02
# Network Management Multi Channel End Point Get
NM_MULTI_CHANNEL_END_POINT_GET_V2 = 0x05
# Network Management Multi Channel End Point Report
NM_MULTI_CHANNEL_END_POINT_REPORT_V2 = 0x06
# Network Management Multi Channel Capability Get
NM_MULTI_CHANNEL_CAPABILITY_GET_V2 = 0x07
# Network Management Multi Channel Capability Report
NM_MULTI_CHANNEL_CAPABILITY_REPORT_V2 = 0x08
# Network Management Multi Channel Aggregated Members Get
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_V2 = 0x09
# Network Management Multi Channel Aggregated Members Report
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_V2 = 0x0A

# Values used for Node Info Cached Get command
NODE_INFO_CACHED_GET_PROPERTIES1_MAX_AGE_MASK_V2 = 0x0F
NODE_INFO_CACHED_GET_PROPERTIES1_RESERVED_MASK_V2 = 0xF0
NODE_INFO_CACHED_GET_PROPERTIES1_RESERVED_SHIFT_V2 = 0x04
# Values used for Node Info Cached Report command
NODE_INFO_CACHED_REPORT_PROPERTIES1_AGE_MASK_V2 = 0x0F
NODE_INFO_CACHED_REPORT_PROPERTIES1_STATUS_MASK_V2 = 0xF0
NODE_INFO_CACHED_REPORT_PROPERTIES1_STATUS_SHIFT_V2 = 0x04
NODE_INFO_CACHED_REPORT_STATUS_STATUS_OK_V2 = 0x00
NODE_INFO_CACHED_REPORT_STATUS_STATUS_NOT_RESPONDING_V2 = 0x01
NODE_INFO_CACHED_REPORT_STATUS_STATUS_UNKNOWN_V2 = 0x02
NODE_INFO_CACHED_REPORT_PROPERTIES2_Z_WAVE_PROTOCOL_SPECIFIC_PART_1_MASK_V2 = 0x7F
NODE_INFO_CACHED_REPORT_PROPERTIES2_LISTENING_BIT_MASK_V2 = 0x80
NODE_INFO_CACHED_REPORT_PROPERTIES3_Z_WAVE_PROTOCOL_SPECIFIC_PART_2_MASK_V2 = 0x7F
NODE_INFO_CACHED_REPORT_PROPERTIES3_OPT_BIT_MASK_V2 = 0x80
# Values used for Nm Multi Channel End Point Report command
NM_MULTI_CHANNEL_END_POINT_REPORT_PROPERTIES1_INDIVIDUAL_END_POINTS_MASK_V2 = 0x7F
NM_MULTI_CHANNEL_END_POINT_REPORT_PROPERTIES1_RES1_BIT_MASK_V2 = 0x80
NM_MULTI_CHANNEL_END_POINT_REPORT_PROPERTIES2_AGGREGATED_END_POINTS_MASK_V2 = 0x7F
NM_MULTI_CHANNEL_END_POINT_REPORT_PROPERTIES2_RES2_BIT_MASK_V2 = 0x80
# Values used for Nm Multi Channel Capability Get command
NM_MULTI_CHANNEL_CAPABILITY_GET_PROPERTIES1_END_POINT_MASK_V2 = 0x7F
NM_MULTI_CHANNEL_CAPABILITY_GET_PROPERTIES1_RES1_BIT_MASK_V2 = 0x80
# Values used for Nm Multi Channel Capability Report command
NM_MULTI_CHANNEL_CAPABILITY_REPORT_PROPERTIES1_END_POINT_MASK_V2 = 0x7F
NM_MULTI_CHANNEL_CAPABILITY_REPORT_PROPERTIES1_RES1_BIT_MASK_V2 = 0x80
# Values used for Nm Multi Channel Aggregated Members Get command
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_PROPERTIES1_AGGREGATED_END_POINT_MASK_V2 = 0x7F
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_PROPERTIES1_RES1_BIT_MASK_V2 = 0x80
# Values used for Nm Multi Channel Aggregated Members Report command
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_PROPERTIES1_AGGREGATED_END_POINT_MASK_V2 = 0x7F
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_PROPERTIES1_RES1_BIT_MASK_V2 = 0x80

NETWORK_MANAGEMENT_PROXY_VERSION_V3 = 0x03
COMMAND_NODE_INFO_CACHED_GET_V3 = 0x03
COMMAND_NODE_INFO_CACHED_REPORT_V3 = 0x04
COMMAND_NODE_LIST_GET_V3 = 0x01
COMMAND_NODE_LIST_REPORT_V3 = 0x02
NM_MULTI_CHANNEL_END_POINT_GET_V3 = 0x05
NM_MULTI_CHANNEL_END_POINT_REPORT_V3 = 0x06
NM_MULTI_CHANNEL_CAPABILITY_GET_V3 = 0x07
NM_MULTI_CHANNEL_CAPABILITY_REPORT_V3 = 0x08
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_V3 = 0x09
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_V3 = 0x0A
# Failed Node List Get
COMMAND_FAILED_NODE_LIST_GET_V3 = 0x0B
# Failed Node List Report
COMMAND_FAILED_NODE_LIST_REPORT_V3 = 0x0C


# Values used for Node Info Cached Get command
NODE_INFO_CACHED_GET_PROPERTIES1_MAX_AGE_MASK_V3 = 0x0F
NODE_INFO_CACHED_GET_PROPERTIES1_RESERVED_MASK_V3 = 0xF0
NODE_INFO_CACHED_GET_PROPERTIES1_RESERVED_SHIFT_V3 = 0x04
# Values used for Node Info Cached Report command
NODE_INFO_CACHED_REPORT_PROPERTIES1_AGE_MASK_V3 = 0x0F
NODE_INFO_CACHED_REPORT_PROPERTIES1_STATUS_MASK_V3 = 0xF0
NODE_INFO_CACHED_REPORT_PROPERTIES1_STATUS_SHIFT_V3 = 0x04
NODE_INFO_CACHED_REPORT_STATUS_STATUS_OK_V3 = 0x00
NODE_INFO_CACHED_REPORT_STATUS_STATUS_NOT_RESPONDING_V3 = 0x01
NODE_INFO_CACHED_REPORT_STATUS_STATUS_UNKNOWN_V3 = 0x02
NODE_INFO_CACHED_REPORT_PROPERTIES2_Z_WAVE_PROTOCOL_SPECIFIC_PART_1_MASK_V3 = 0x7F
NODE_INFO_CACHED_REPORT_PROPERTIES2_LISTENING_BIT_MASK_V3 = 0x80
NODE_INFO_CACHED_REPORT_PROPERTIES3_Z_WAVE_PROTOCOL_SPECIFIC_PART_2_MASK_V3 = 0x7F
NODE_INFO_CACHED_REPORT_PROPERTIES3_OPT_BIT_MASK_V3 = 0x80
# Values used for Nm Multi Channel End Point Report command
NM_MULTI_CHANNEL_END_POINT_REPORT_PROPERTIES1_INDIVIDUAL_END_POINTS_MASK_V3 = 0x7F
NM_MULTI_CHANNEL_END_POINT_REPORT_PROPERTIES1_RES1_BIT_MASK_V3 = 0x80
NM_MULTI_CHANNEL_END_POINT_REPORT_PROPERTIES2_AGGREGATED_END_POINTS_MASK_V3 = 0x7F
NM_MULTI_CHANNEL_END_POINT_REPORT_PROPERTIES2_RES2_BIT_MASK_V3 = 0x80
# Values used for Nm Multi Channel Capability Get command
NM_MULTI_CHANNEL_CAPABILITY_GET_PROPERTIES1_END_POINT_MASK_V3 = 0x7F
NM_MULTI_CHANNEL_CAPABILITY_GET_PROPERTIES1_RES1_BIT_MASK_V3 = 0x80
# Values used for Nm Multi Channel Capability Report command
NM_MULTI_CHANNEL_CAPABILITY_REPORT_PROPERTIES1_END_POINT_MASK_V3 = 0x7F
NM_MULTI_CHANNEL_CAPABILITY_REPORT_PROPERTIES1_RES1_BIT_MASK_V3 = 0x80
# Values used for Nm Multi Channel Aggregated Members Get command
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_PROPERTIES1_AGGREGATED_END_POINT_MASK_V3 = 0x7F
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_PROPERTIES1_RES1_BIT_MASK_V3 = 0x80
# Values used for Nm Multi Channel Aggregated Members Report command
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_PROPERTIES1_AGGREGATED_END_POINT_MASK_V3 = 0x7F
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_PROPERTIES1_RES1_BIT_MASK_V3 = 0x80

NETWORK_MANAGEMENT_PROXY_VERSION_V4 = 0x04
COMMAND_NODE_INFO_CACHED_GET_V4 = 0x03
COMMAND_NODE_INFO_CACHED_REPORT_V4 = 0x04
COMMAND_NODE_LIST_GET_V4 = 0x01
COMMAND_NODE_LIST_REPORT_V4 = 0x02
NM_MULTI_CHANNEL_END_POINT_GET_V4 = 0x05
NM_MULTI_CHANNEL_END_POINT_REPORT_V4 = 0x06
NM_MULTI_CHANNEL_CAPABILITY_GET_V4 = 0x07
NM_MULTI_CHANNEL_CAPABILITY_REPORT_V4 = 0x08
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_V4 = 0x09
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_V4 = 0x0A
COMMAND_FAILED_NODE_LIST_GET_V4 = 0x0B
COMMAND_FAILED_NODE_LIST_REPORT_V4 = 0x0C
# Values used for Node Info Cached Get command
NODE_INFO_CACHED_GET_PROPERTIES1_MAX_AGE_MASK_V4 = 0x0F
NODE_INFO_CACHED_GET_PROPERTIES1_RESERVED_MASK_V4 = 0xF0
NODE_INFO_CACHED_GET_PROPERTIES1_RESERVED_SHIFT_V4 = 0x04
# Values used for Node Info Cached Report command
NODE_INFO_CACHED_REPORT_PROPERTIES1_AGE_MASK_V4 = 0x0F
NODE_INFO_CACHED_REPORT_PROPERTIES1_STATUS_MASK_V4 = 0xF0
NODE_INFO_CACHED_REPORT_PROPERTIES1_STATUS_SHIFT_V4 = 0x04
NODE_INFO_CACHED_REPORT_STATUS_STATUS_OK_V4 = 0x00
NODE_INFO_CACHED_REPORT_STATUS_STATUS_NOT_RESPONDING_V4 = 0x01
NODE_INFO_CACHED_REPORT_STATUS_STATUS_UNKNOWN_V4 = 0x02
NODE_INFO_CACHED_REPORT_PROPERTIES2_Z_WAVE_PROTOCOL_SPECIFIC_PART_1_MASK_V4 = 0x7F
NODE_INFO_CACHED_REPORT_PROPERTIES2_LISTENING_BIT_MASK_V4 = 0x80
NODE_INFO_CACHED_REPORT_PROPERTIES3_Z_WAVE_PROTOCOL_SPECIFIC_PART_2_MASK_V4 = 0x7F
NODE_INFO_CACHED_REPORT_PROPERTIES3_OPT_BIT_MASK_V4 = 0x80
# Values used for Nm Multi Channel End Point Report command
NM_MULTI_CHANNEL_END_POINT_REPORT_PROPERTIES1_INDIVIDUAL_END_POINTS_MASK_V4 = 0x7F
NM_MULTI_CHANNEL_END_POINT_REPORT_PROPERTIES1_RES1_BIT_MASK_V4 = 0x80
NM_MULTI_CHANNEL_END_POINT_REPORT_PROPERTIES2_AGGREGATED_END_POINTS_MASK_V4 = 0x7F
NM_MULTI_CHANNEL_END_POINT_REPORT_PROPERTIES2_RES2_BIT_MASK_V4 = 0x80
# Values used for Nm Multi Channel Capability Get command
NM_MULTI_CHANNEL_CAPABILITY_GET_PROPERTIES1_END_POINT_MASK_V4 = 0x7F
NM_MULTI_CHANNEL_CAPABILITY_GET_PROPERTIES1_RES1_BIT_MASK_V4 = 0x80
# Values used for Nm Multi Channel Capability Report command
NM_MULTI_CHANNEL_CAPABILITY_REPORT_PROPERTIES1_END_POINT_MASK_V4 = 0x7F
NM_MULTI_CHANNEL_CAPABILITY_REPORT_PROPERTIES1_RES1_BIT_MASK_V4 = 0x80
# Values used for Nm Multi Channel Aggregated Members Get command
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_PROPERTIES1_AGGREGATED_END_POINT_MASK_V4 = 0x7F
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_PROPERTIES1_RES1_BIT_MASK_V4 = 0x80
# Values used for Nm Multi Channel Aggregated Members Report command
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_PROPERTIES1_AGGREGATED_END_POINT_MASK_V4 = 0x7F
NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_PROPERTIES1_RES1_BIT_MASK_V4 = 0x80


class ZW_NODE_INFO_CACHED_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('seqNo', uint8_t),
        ('properties1', uint8_t),
        ('nodeId', uint8_t),
    ]


class ZW_NODE_INFO_CACHED_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('seqNo', uint8_t),
        ('properties1', uint8_t),
        ('properties2', uint8_t),
        ('properties3', uint8_t),
        ('reserved', uint8_t),
        ('basicDeviceClass', uint8_t),
        ('genericDeviceClass', uint8_t),
        ('specificDeviceClass', uint8_t),
        ('commandClass1', uint8_t),
    ]


class ZW_NODE_LIST_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('seqNo', uint8_t)]


class ZW_NODE_LIST_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('seqNo', uint8_t),
        ('status', uint8_t),
        ('nodeListControllerId', uint8_t),
        ('nodeListData1', uint8_t),
    ]


class ZW_NODE_INFO_CACHED_GET_V2_FRAME(ZW_NODE_INFO_CACHED_GET_FRAME):
    _fields_ = []


class ZW_NODE_INFO_CACHED_REPORT_V2_FRAME(ZW_NODE_INFO_CACHED_REPORT_FRAME):
    _fields_ = [('grantedKeys', uint8_t)]


class ZW_NODE_LIST_GET_V2_FRAME(ZW_NODE_LIST_GET_FRAME):
    _fields_ = []


class ZW_NODE_LIST_REPORT_V2_FRAME(ZW_NODE_LIST_REPORT_FRAME):
    _fields_ = []






class ZW_NM_MULTI_CHANNEL_END_POINT_GET_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('seqNo', uint8_t),
        ('nodeid', uint8_t),
    ]


class ZW_NM_MULTI_CHANNEL_END_POINT_REPORT_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('seqNo', uint8_t),
        ('nodeid', uint8_t),
        ('reserved', uint8_t),
        ('properties1', uint8_t),
        ('properties2', uint8_t),
    ]


class ZW_NM_MULTI_CHANNEL_CAPABILITY_GET_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('seqNo', uint8_t),
        ('nodeid', uint8_t),
        ('properties1', uint8_t),
    ]


class ZW_NM_MULTI_CHANNEL_CAPABILITY_REPORT_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('seqNo', uint8_t),
        ('nodeid', uint8_t),
        ('commandClassLength', uint8_t),
        ('properties1', uint8_t),
        ('genericDeviceClass', uint8_t),
        ('specificDeviceClass', uint8_t),
        ('commandClass1', uint8_t),
    ]


class ZW_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('seqNo', uint8_t),
        ('nodeid', uint8_t),
        ('properties1', uint8_t),
    ]


class VG_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_V2_VG(ctypes.Structure):
    _fields_ = [('properties1', uint8_t)]



class ZW_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('seqNo', uint8_t),
        ('nodeid', uint8_t),
        ('properties1', uint8_t),
        ('numberOfMembers', uint8_t),
        ('variantgroup1', VG_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_V2_VG),
    ]

class ZW_NODE_INFO_CACHED_GET_V3_FRAME(ZW_NODE_INFO_CACHED_GET_V2_FRAME):
    _fields_ = []


class ZW_NODE_INFO_CACHED_REPORT_V3_FRAME(ZW_NODE_INFO_CACHED_REPORT_V2_FRAME):
    _fields_ = []


class ZW_NODE_LIST_GET_V3_FRAME(ZW_NODE_LIST_GET_V2_FRAME):
    _fields_ = []


class ZW_NODE_LIST_REPORT_V3_FRAME(ZW_NODE_LIST_REPORT_V2_FRAME):
    _fields_ = []


class ZW_NM_MULTI_CHANNEL_END_POINT_GET_V3_FRAME(ZW_NM_MULTI_CHANNEL_END_POINT_GET_V2_FRAME):
    _fields_ = []


class ZW_NM_MULTI_CHANNEL_END_POINT_REPORT_V3_FRAME(ZW_NM_MULTI_CHANNEL_END_POINT_REPORT_V2_FRAME):
    _fields_ = []


class ZW_NM_MULTI_CHANNEL_CAPABILITY_GET_V3_FRAME(ZW_NM_MULTI_CHANNEL_CAPABILITY_GET_V2_FRAME):
    _fields_ = []


class ZW_NM_MULTI_CHANNEL_CAPABILITY_REPORT_V3_FRAME(ZW_NM_MULTI_CHANNEL_CAPABILITY_REPORT_V2_FRAME):
    _fields_ = []


class ZW_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_V3_FRAME(ZW_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_V2_FRAME):
    _fields_ = []


class VG_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_V3_VG(ctypes.Structure):
    _fields_ = [('properties1', uint8_t)]



class ZW_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_V3_FRAME(ZW_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_V2_FRAME):
    _fields_ = []


class ZW_FAILED_NODE_LIST_GET_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('seqNo', uint8_t)]


class ZW_FAILED_NODE_LIST_REPORT_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('seqNo', uint8_t),
        ('failedNodeListData1', uint8_t),
        ('failedNodeListData2', uint8_t),
        ('failedNodeListData3', uint8_t),
        ('failedNodeListData4', uint8_t),
        ('failedNodeListData5', uint8_t),
        ('failedNodeListData6', uint8_t),
        ('failedNodeListData7', uint8_t),
        ('failedNodeListData8', uint8_t),
        ('failedNodeListData9', uint8_t),
        ('failedNodeListData10', uint8_t),
        ('failedNodeListData11', uint8_t),
        ('failedNodeListData12', uint8_t),
        ('failedNodeListData13', uint8_t),
        ('failedNodeListData14', uint8_t),
        ('failedNodeListData15', uint8_t),
        ('failedNodeListData16', uint8_t),
        ('failedNodeListData17', uint8_t),
        ('failedNodeListData18', uint8_t),
        ('failedNodeListData19', uint8_t),
        ('failedNodeListData20', uint8_t),
        ('failedNodeListData21', uint8_t),
        ('failedNodeListData22', uint8_t),
        ('failedNodeListData23', uint8_t),
        ('failedNodeListData24', uint8_t),
        ('failedNodeListData25', uint8_t),
        ('failedNodeListData26', uint8_t),
        ('failedNodeListData27', uint8_t),
        ('failedNodeListData28', uint8_t),
        ('failedNodeListData29', uint8_t),
    ]


class ZW_NODE_INFO_CACHED_GET_V4_FRAME(ZW_NODE_INFO_CACHED_GET_V3_FRAME):
    _fields_ = [
        ('extendedNodeid1', uint8_t),
        ('extendedNodeid2', uint8_t),
    ]


class ZW_NODE_INFO_CACHED_REPORT_V4_FRAME(ZW_NODE_INFO_CACHED_REPORT_V3_FRAME):
    _fields_ = []


class ZW_NODE_LIST_GET_V4_FRAME(ZW_NODE_LIST_GET_V3_FRAME):
    _fields_ = []


class ZW_NODE_LIST_REPORT_V4_FRAME(ZW_NODE_LIST_REPORT_V3_FRAME):
    _fields_ = [
        ('extendedNodeListLength1', uint8_t),
        ('extendedNodeListLength2', uint8_t),
        ('extendedNodeList1', uint8_t),
    ]


class ZW_NM_MULTI_CHANNEL_END_POINT_GET_V4_FRAME(ZW_NM_MULTI_CHANNEL_END_POINT_GET_V3_FRAME):
    _fields_ = [
        ('extendedNodeid1', uint8_t),
        ('extendedNodeid2', uint8_t),
    ]


class ZW_NM_MULTI_CHANNEL_END_POINT_REPORT_V4_FRAME(ZW_NM_MULTI_CHANNEL_END_POINT_REPORT_V3_FRAME):
    _fields_ = [
        ('extendedNodeid1', uint8_t),
        ('extendedNodeid2', uint8_t),
    ]


class ZW_NM_MULTI_CHANNEL_CAPABILITY_GET_V4_FRAME(ZW_NM_MULTI_CHANNEL_CAPABILITY_GET_V3_FRAME):
    _fields_ = [
        ('extendedNodeid1', uint8_t),
        ('extendedNodeid2', uint8_t),
    ]


class ZW_NM_MULTI_CHANNEL_CAPABILITY_REPORT_V4_FRAME(ZW_NM_MULTI_CHANNEL_CAPABILITY_REPORT_V3_FRAME):
    _fields_ = [
        ('extendedNodeid1', uint8_t),
        ('extendedNodeid2', uint8_t),
    ]


class ZW_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_V4_FRAME(ZW_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_GET_V3_FRAME):
    _fields_ = [
        ('extendedNodeid1', uint8_t),
        ('extendedNodeid2', uint8_t),
    ]


class VG_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_V4_VG(ctypes.Structure):
    _fields_ = [('properties1', uint8_t)]



class ZW_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_V4_FRAME(ZW_NM_MULTI_CHANNEL_AGGREGATED_MEMBERS_REPORT_V3_FRAME):
    _fields_ = [
        ('extendedNodeid1', uint8_t),
        ('extendedNodeid2', uint8_t),
    ]


class ZW_FAILED_NODE_LIST_GET_V4_FRAME(ZW_FAILED_NODE_LIST_GET_V3_FRAME):
    _fields_ = []


class ZW_FAILED_NODE_LIST_REPORT_V4_FRAME(ZW_FAILED_NODE_LIST_REPORT_V3_FRAME):
    _fields_ = [
        ('extendedFailedNodeListLength1', uint8_t),
        ('extendedFailedNodeListLength2', uint8_t),
        ('extendedFailedNodeList1', uint8_t),
    ]
