# Network Management Installation and Maintenance Command Class
# Network-Protocol
# ==============================
NETWORK_MANAGEMENT_INSTALLATION_MAINTENANCE = 0x67

NETWORK_MANAGEMENT_INSTALLATION_MAINTENANCE_VERSION = 0x01
# Last Working Route Set
PRIORITY_ROUTE_SET = 0x01
# Last Working Route Get
PRIORITY_ROUTE_GET = 0x02
# Last Working Route Report
PRIORITY_ROUTE_REPORT = 0x03
# Statistics Get
STATISTICS_GET = 0x04
# Statistics Report
STATISTICS_REPORT = 0x05
# Statistics Clear
STATISTICS_CLEAR = 0x06


# Values used for Priority Route Set command
PRIORITY_ROUTE_SET_9_6_KBIT_SEC = 0x01
PRIORITY_ROUTE_SET_40_KBIT_SEC = 0x02
PRIORITY_ROUTE_SET_100_KBIT_SEC = 0x03
# Values used for Priority Route Report command
PRIORITY_ROUTE_REPORT_NONE = 0x00
PRIORITY_ROUTE_REPORT_ZW_PRIORITY_ROUTE_ZW_LWR = 0x01
PRIORITY_ROUTE_REPORT_ZW_PRIORITY_ROUTE_ZW_NLWR = 0x02
PRIORITY_ROUTE_REPORT_ZW_PRIORITY_ROUTE_APP_PR = 0x10
PRIORITY_ROUTE_REPORT_9_6_KBIT_SEC = 0x01
PRIORITY_ROUTE_REPORT_40_KBIT_SEC = 0x02
PRIORITY_ROUTE_REPORT_100_KBIT_SEC = 0x03
# Values used for Statistics Report command
STATISTICS_REPORT_ROUTE_CHANGES_RC = 0x00
STATISTICS_REPORT_TRANSMISSION_COUNT_TC = 0x01
STATISTICS_REPORT_NEIGHBORS_NB = 0x02
STATISTICS_REPORT_PACKET_ERROR_COUNT_PEC = 0x03
STATISTICS_REPORT_SUM_OF_TRANSMISSION_TIMES_TS = 0x04
STATISTICS_REPORT_SUM_OF_TRANSMISSION_TIMES_SQURARED_TS2 = 0x05

NETWORK_MANAGEMENT_INSTALLATION_MAINTENANCE_VERSION_V2 = 0x02
PRIORITY_ROUTE_SET_V2 = 0x01
PRIORITY_ROUTE_GET_V2 = 0x02
PRIORITY_ROUTE_REPORT_V2 = 0x03
STATISTICS_GET_V2 = 0x04
STATISTICS_REPORT_V2 = 0x05
STATISTICS_CLEAR_V2 = 0x06
# RSSI Get
COMMAND_RSSI_GET_V2 = 0x07
# RSSI Report
COMMAND_RSSI_REPORT_V2 = 0x08

# Values used for Priority Route Set command
PRIORITY_ROUTE_SET_9_6_KBIT_SEC_V2 = 0x01
PRIORITY_ROUTE_SET_40_KBIT_SEC_V2 = 0x02
PRIORITY_ROUTE_SET_100_KBIT_SEC_V2 = 0x03
# Values used for Priority Route Report command
PRIORITY_ROUTE_REPORT_NONE_V2 = 0x00
PRIORITY_ROUTE_REPORT_ZW_PRIORITY_ROUTE_ZW_LWR_V2 = 0x01
PRIORITY_ROUTE_REPORT_ZW_PRIORITY_ROUTE_ZW_NLWR_V2 = 0x02
PRIORITY_ROUTE_REPORT_ZW_PRIORITY_ROUTE_APP_PR_V2 = 0x10
PRIORITY_ROUTE_REPORT_9_6_KBIT_SEC_V2 = 0x01
PRIORITY_ROUTE_REPORT_40_KBIT_SEC_V2 = 0x02
PRIORITY_ROUTE_REPORT_100_KBIT_SEC_V2 = 0x03
# Values used for Statistics Report command
STATISTICS_REPORT_ROUTE_CHANGES_RC_V2 = 0x00
STATISTICS_REPORT_TRANSMISSION_COUNT_TC_V2 = 0x01
STATISTICS_REPORT_NEIGHBORS_NB_V2 = 0x02
STATISTICS_REPORT_PACKET_ERROR_COUNT_PEC_V2 = 0x03
STATISTICS_REPORT_SUM_OF_TRANSMISSION_TIMES_TS_V2 = 0x04
STATISTICS_REPORT_SUM_OF_TRANSMISSION_TIMES_SQURARED_TS2_V2 = 0x05

NETWORK_MANAGEMENT_INSTALLATION_MAINTENANCE_VERSION_V3 = 0x03
PRIORITY_ROUTE_SET_V3 = 0x01
PRIORITY_ROUTE_GET_V3 = 0x02
PRIORITY_ROUTE_REPORT_V3 = 0x03
STATISTICS_GET_V3 = 0x04
STATISTICS_REPORT_V3 = 0x05
STATISTICS_CLEAR_V3 = 0x06
RSSI_GET_V3 = 0x07
RSSI_REPORT_V3 = 0x08
# S2 Resynchronization Event Command
S2_RESYNCHRONIZATION_EVENT_V3 = 0x09
# Extended Statistics Get
EXTENDED_STATISTICS_GET_V3 = 0x0B
# Extended Statistics Report
EXTENDED_STATISTICS_REPORT_V3 = 0x0C

# Values used for Priority Route Set command
PRIORITY_ROUTE_SET_9_6_KBIT_SEC_V3 = 0x01
PRIORITY_ROUTE_SET_40_KBIT_SEC_V3 = 0x02
PRIORITY_ROUTE_SET_100_KBIT_SEC_V3 = 0x03
# Values used for Priority Route Report command
PRIORITY_ROUTE_REPORT_NONE_V3 = 0x00
PRIORITY_ROUTE_REPORT_ZW_PRIORITY_ROUTE_ZW_LWR_V3 = 0x01
PRIORITY_ROUTE_REPORT_ZW_PRIORITY_ROUTE_ZW_NLWR_V3 = 0x02
PRIORITY_ROUTE_REPORT_ZW_PRIORITY_ROUTE_APP_PR_V3 = 0x10
PRIORITY_ROUTE_REPORT_9_6_KBIT_SEC_V3 = 0x01
PRIORITY_ROUTE_REPORT_40_KBIT_SEC_V3 = 0x02
PRIORITY_ROUTE_REPORT_100_KBIT_SEC_V3 = 0x03
# Values used for Statistics Report command
STATISTICS_REPORT_ROUTE_CHANGES_RC_V3 = 0x00
STATISTICS_REPORT_TRANSMISSION_COUNT_TC_V3 = 0x01
STATISTICS_REPORT_NEIGHBORS_NB_V3 = 0x02
STATISTICS_REPORT_PACKET_ERROR_COUNT_PEC_V3 = 0x03
STATISTICS_REPORT_SUM_OF_TRANSMISSION_TIMES_TS_V3 = 0x04
STATISTICS_REPORT_SUM_OF_TRANSMISSION_TIMES_SQURARED_TS2_V3 = 0x05
# Values used for S2 Resynchronization Event command
S2_RESYNCHRONIZATION_EVENT_SOS_EVENT_REASON_UNANSWERED_V3 = 0x00

NETWORK_MANAGEMENT_INSTALLATION_MAINTENANCE_VERSION_V4 = 0x04
PRIORITY_ROUTE_SET_V4 = 0x01
PRIORITY_ROUTE_GET_V4 = 0x02
PRIORITY_ROUTE_REPORT_V4 = 0x03
STATISTICS_GET_V4 = 0x04
STATISTICS_REPORT_V4 = 0x05
STATISTICS_CLEAR_V4 = 0x06
RSSI_GET_V4 = 0x07
RSSI_REPORT_V4 = 0x08
S2_RESYNCHRONIZATION_EVENT_V4 = 0x09
EXTENDED_STATISTICS_GET_V4 = 0x0B
EXTENDED_STATISTICS_REPORT_V4 = 0x0C
# Z-Wave Long Range Channel Configuration Set
ZWAVE_LR_CHANNEL_CONFIGURATION_SET_V4 = 0x0A
# Z-Wave Long Range Channel Configuration Set
ZWAVE_LR_CHANNEL_CONFIGURATION_GET_V4 = 0x0D
# Z-Wave Long Range Channel Configuration Report
ZWAVE_LR_CHANNEL_CONFIGURATION_REPORT_V4 = 0x0E

# Values used for Priority Route Set command
PRIORITY_ROUTE_SET_9_6_KBIT_SEC_V4 = 0x01
PRIORITY_ROUTE_SET_40_KBIT_SEC_V4 = 0x02
PRIORITY_ROUTE_SET_100_KBIT_SEC_V4 = 0x03
# Values used for Priority Route Report command
PRIORITY_ROUTE_REPORT_NONE_V4 = 0x00
PRIORITY_ROUTE_REPORT_ZW_PRIORITY_ROUTE_ZW_LWR_V4 = 0x01
PRIORITY_ROUTE_REPORT_ZW_PRIORITY_ROUTE_ZW_NLWR_V4 = 0x02
PRIORITY_ROUTE_REPORT_ZW_PRIORITY_ROUTE_APP_PR_V4 = 0x10
PRIORITY_ROUTE_REPORT_9_6_KBIT_SEC_V4 = 0x01
PRIORITY_ROUTE_REPORT_40_KBIT_SEC_V4 = 0x02
PRIORITY_ROUTE_REPORT_100_KBIT_SEC_V4 = 0x03
# Values used for Statistics Report command
STATISTICS_REPORT_ROUTE_CHANGES_RC_V4 = 0x00
STATISTICS_REPORT_TRANSMISSION_COUNT_TC_V4 = 0x01
STATISTICS_REPORT_NEIGHBORS_NB_V4 = 0x02
STATISTICS_REPORT_PACKET_ERROR_COUNT_PEC_V4 = 0x03
STATISTICS_REPORT_SUM_OF_TRANSMISSION_TIMES_TS_V4 = 0x04
STATISTICS_REPORT_SUM_OF_TRANSMISSION_TIMES_SQURARED_TS2_V4 = 0x05
# Values used for S2 Resynchronization Event command
S2_RESYNCHRONIZATION_EVENT_SOS_EVENT_REASON_UNANSWERED_V4 = 0x00

class ZW_PRIORITY_ROUTE_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('nodeid', uint8_t),
        ('repeater1', uint8_t),
        ('repeater2', uint8_t),
        ('repeater3', uint8_t),
        ('repeater4', uint8_t),
        ('speed', uint8_t),
    ]


class ZW_PRIORITY_ROUTE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('nodeid', uint8_t)]


class ZW_PRIORITY_ROUTE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('nodeid', uint8_t),
        ('type', uint8_t),
        ('repeater1', uint8_t),
        ('repeater2', uint8_t),
        ('repeater3', uint8_t),
        ('repeater4', uint8_t),
        ('speed', uint8_t),
    ]


class ZW_STATISTICS_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('nodeid', uint8_t)]


class VG_STATISTICS_REPORT_VG(ctypes.Structure):
    _fields_ = [
        ('type', uint8_t),
        ('length', uint8_t),
        ('value1', uint8_t),
    ]


class ZW_STATISTICS_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('nodeid', uint8_t),
        ('variantgroup1', VG_STATISTICS_REPORT_VG),
    ]


class ZW_STATISTICS_CLEAR_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_PRIORITY_ROUTE_SET_V2_FRAME(ZW_PRIORITY_ROUTE_SET_FRAME):
    _fields_ = []


class ZW_PRIORITY_ROUTE_GET_V2_FRAME(ZW_PRIORITY_ROUTE_GET_FRAME):
    _fields_ = []


class ZW_PRIORITY_ROUTE_REPORT_V2_FRAME(ZW_PRIORITY_ROUTE_REPORT_FRAME):
    _fields_ = []


class ZW_STATISTICS_GET_V2_FRAME(ZW_STATISTICS_GET_FRAME):
    _fields_ = []


class ZW_STATISTICS_REPORT_V2_FRAME(ZW_STATISTICS_REPORT_FRAME):
    _fields_ = []


class ZW_STATISTICS_CLEAR_V2_FRAME(ZW_STATISTICS_CLEAR_FRAME):
    _fields_ = []


class ZW_RSSI_GET_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_RSSI_REPORT_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('channel1Rssi', uint8_t),
        ('channel2Rssi', uint8_t),
        ('channel3Rssi', uint8_t),
    ]


class ZW_PRIORITY_ROUTE_SET_V3_FRAME(ZW_PRIORITY_ROUTE_SET_V2_FRAME):
    _fields_ = []


class ZW_PRIORITY_ROUTE_GET_V3_FRAME(ZW_PRIORITY_ROUTE_GET_V2_FRAME):
    _fields_ = []


class ZW_PRIORITY_ROUTE_REPORT_V3_FRAME(ZW_PRIORITY_ROUTE_REPORT_V2_FRAME):
    _fields_ = []


class ZW_STATISTICS_GET_V3_FRAME(ZW_STATISTICS_GET_V2_FRAME):
    _fields_ = []


class ZW_STATISTICS_REPORT_V3_FRAME(ZW_STATISTICS_REPORT_V2_FRAME):
    _fields_ = []


class ZW_STATISTICS_CLEAR_V3_FRAME(ZW_STATISTICS_CLEAR_V2_FRAME):
    _fields_ = []


class ZW_RSSI_GET_V3_FRAME(ZW_RSSI_GET_V2_FRAME):
    _fields_ = []


class ZW_RSSI_REPORT_V3_FRAME(ZW_RSSI_REPORT_V2_FRAME):
    _fields_ = []


class ZW_S2_RESYNCHRONIZATION_EVENT_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('nodeid', uint8_t),
        ('reason', uint8_t),
        ('extendedNodeid1', uint8_t),
        ('extendedNodeid2', uint8_t),
    ]


class ZW_EXTENDED_STATISTICS_GET_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('extendedNodeid1', uint8_t),
        ('extendedNodeid2', uint8_t),
    ]



class VG_EXTENDED_STATISTICS_REPORT_V3_VG(ctypes.Structure):
    _fields_ = [
        ('type', uint8_t),
        ('length', uint8_t),
        ('value1', uint8_t),
    ]


class ZW_EXTENDED_STATISTICS_REPORT_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('extendedNodeid1', uint8_t),
        ('extendedNodeid2', uint8_t),
        ('variantgroup1', VG_EXTENDED_STATISTICS_REPORT_V3_VG),
    ]


class ZW_PRIORITY_ROUTE_SET_V4_FRAME(ZW_PRIORITY_ROUTE_SET_V3_FRAME):
    _fields_ = []


class ZW_PRIORITY_ROUTE_GET_V4_FRAME(ZW_PRIORITY_ROUTE_GET_V3_FRAME):
    _fields_ = []


class ZW_PRIORITY_ROUTE_REPORT_V4_FRAME(ZW_PRIORITY_ROUTE_REPORT_V3_FRAME):
    _fields_ = []


class ZW_STATISTICS_GET_V4_FRAME(ZW_STATISTICS_GET_V3_FRAME):
    _fields_ = []


class ZW_STATISTICS_REPORT_V4_FRAME(ZW_STATISTICS_REPORT_V3_FRAME):
    _fields_ = []


class ZW_STATISTICS_CLEAR_V4_FRAME(ZW_STATISTICS_CLEAR_V3_FRAME):
    _fields_ = []


class ZW_RSSI_GET_V4_FRAME(ZW_RSSI_GET_V3_FRAME):
    _fields_ = []


class ZW_RSSI_REPORT_V4_FRAME(ZW_RSSI_REPORT_V3_FRAME):
    _fields_ = []


class ZW_S2_RESYNCHRONIZATION_EVENT_V4_FRAME(ZW_S2_RESYNCHRONIZATION_EVENT_V3_FRAME):
    _fields_ = []


class ZW_EXTENDED_STATISTICS_GET_V4_FRAME(ZW_EXTENDED_STATISTICS_GET_V3_FRAME):
    _fields_ = []


class ZW_EXTENDED_STATISTICS_REPORT_V4_FRAME(ZW_EXTENDED_STATISTICS_REPORT_V3_FRAME):
    _fields_ = []


class ZW_ZWAVE_LR_CHANNEL_CONFIGURATION_SET_V4_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('zWaveLongRangeChannel', uint8_t)]


class ZW_ZWAVE_LR_CHANNEL_CONFIGURATION_GET_V4_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_ZWAVE_LR_CHANNEL_CONFIGURATION_REPORT_V4_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('zWaveLongRangeChannel', uint8_t)]

