# Notification Command Class
# Application
# ==============================
from .alarm import ALARM_V2_COMMANDS

from . import CommandClass
from . import StringValue
from . import Command


class NotificationType(StringValue):
    pass


class NotificationTypeReserved(NotificationType):
    value = 0x00
    name = 'Reserved'
    version = 1


class NotificationTypeSmoke(NotificationType):
    value = 0x01
    name = 'Smoke'
    version = 1


class NotificationTypeCO(NotificationType):
    value = 0x02
    name = 'CO'
    version = 1


class NotificationTypeCO2(NotificationType):
    value = 0x03
    name = 'CO2'
    version = 1


class NotificationTypeHeat(NotificationType):
    value = 0x04
    name = 'Heat'
    version = 1


class NotificationTypeWater(NotificationType):
    value = 0x05
    name = 'Water'
    version = 1


class NotificationTypeAccessControl(NotificationType):
    value = 0x06
    name = 'Access Control'
    version = 1


class NotificationTypeBurglar(NotificationType):
    value = 0x07
    name = 'Burglar'
    version = 1


class NotificationTypePowerManagement(NotificationType):
    value = 0x08
    name = 'Power Management'
    version = 1


class NotificationTypeSystem(NotificationType):
    value = 0x09
    name = 'System'
    version = 1


class NotificationTypeEmergency(NotificationType):
    value = 0x0A
    name = 'Emergency'
    version = 1


class NotificationTypeClock(NotificationType):
    value = 0x0B
    name = 'Clock'
    version = 1


class NotificationTypeAppliance(NotificationType):
    value = 0x0C
    name = 'Appliance'
    version = 4


class NotificationTypeHomeHealth(NotificationType):
    value = 0x0D
    name = 'Home Health'
    version = 4


class NotificationTypeSiren(NotificationType):
    value = 0x0E
    name = 'Siren'
    version = 6


class NotificationTypeWaterValve(NotificationType):
    value = 0x0F
    name = 'Water Valve'
    version = 7


class NotificationTypeWeatherAlarm(NotificationType):
    value = 0x10
    name = 'Weather Alarm'
    version = 7


class NotificationTypeIrrigation(NotificationType):
    value = 0x11
    name = 'Irrigation'
    version = 7


class NotificationTypeGasAlarm(NotificationType):
    value = 0x12
    name = 'Gas Alarm'
    version = 7


class NotificationTypePestControl(NotificationType):
    value = 0x13
    name = 'Pest Control'
    version = 8


class NotificationTypeLightsensor(NotificationType):
    value = 0x14
    name = 'Light sensor'
    version = 8


class NotificationTypeWaterQualityMonitoring(NotificationType):
    value = 0x15
    name = 'Water Quality Monitoring'
    version = 8


class NotificationTypeHomeMonitoring(NotificationType):
    value = 0x16
    name = 'Home Monitoring'
    version = 8


class NotificationTypeFirst(NotificationType):
    value = 0xFF
    name = 'First'
    version = 1


NotificationTypeValues = (
    NotificationTypeReserved,
    NotificationTypeSmoke,
    NotificationTypeCO,
    NotificationTypeCO2,
    NotificationTypeHeat,
    NotificationTypeWater,
    NotificationTypeAccessControl,
    NotificationTypeBurglar,
    NotificationTypePowerManagement,
    NotificationTypeSystem,
    NotificationTypeEmergency,
    NotificationTypeClock,
    NotificationTypeAppliance,
    NotificationTypeHomeHealth,
    NotificationTypeSiren,
    NotificationTypeWaterValve,
    NotificationTypeWeatherAlarm,
    NotificationTypeIrrigation,
    NotificationTypeGasAlarm,
    NotificationTypePestControl,
    NotificationTypeLightsensor,
    NotificationTypeHomeMonitoring,
    NotificationTypeFirst
)


class NotificationStatus(StringValue):
    pass


class NotificationStatusOff(NotificationStatus):
    value = 0x00
    name = 'Off'
    version = 1


class NotificationStatusOn(NotificationStatus):
    value = 0xFF
    name = 'On'
    version = 1


class NotificationStatusNonePending(NotificationStatus):
    value = 0xFE
    name = 'None Pending'
    version = 4


NotificationStatusValues = (
    NotificationStatusOff,
    NotificationStatusOn,
    NotificationStatusNonePending
)


class GET(Command):
    # byte 0: V1 Alarm Type
    # byte 1: Notification Type
    # byte 2: Event

    version = 0x03
    id = 0x04


class REPORT(Command):
    # byte 0: V1 Alarm Type
    # byte 1: V1 Alarm Level
    # byte 2: Reserved
    # byte 3: Notification Status
    # byte 4: Notification Type
    # byte 5: Event
    # byte 6: Properties1
    #     bits 4 - 0: Event Parameters Length     byte6 & 0x1F
    #     bits 5 - 6: Reserved2                   (byte6 & 0x60) >> 5
    #     bits     7: Sequence                    bool(byte6 & 0x80)
    # byte 7: Event Parameter
    # byte 8: Sequence Number

    version = 0x03
    id = 0x05


class SET(Command):
    # byte 0: Notification Type
    # byte 1: Notification Status

    version = 0x03
    id = 0x06


class SUPPORTED_GET(Command):
    # no parameters

    version = 0x03
    id = 0x07


class SUPPORTED_REPORT(Command):
    # byte 0: Properties1
    #     bits 4 - 0: Number of Bit Masks   byte0 & 0x1F
    #     bits 5 - 6: Reserved              (byte0 & 0x60) >> 5
    #     bits     7: V1 Alarm              bool(byte0 & 0x80)
    # byte 1: Bit Mask  (notification types)

    version = 0x03
    id = 0x08


class EVENT_SUPPORTED_GET(Command):
    # byte 0: notification types

    version = 0x03
    id = 0x01


class EVENT_SUPPORTED_REPORT(Command):
    # byte 0: notification types
    # byte 1: Properties1
    #     bits 0 - 4: Number of Bit Masks   byte1 & 0x1F
    #     bits 5 - 7:  Reserved             (byte1 & 0xE0) >> 5
    # byte 2: Bit Mask                      byte2 & 0x1F

    version = 0x03
    id = 0x02

    @classmethod
    def read(cls, cc, in_data):
        in_data[0]



'''
COMMAND_CLASS_NOTIFICATION
  cls name: cmd_class
  key: 0x71
  help: 
  version: 9
'''


class COMMAND_CLASS_NOTIFICATION(CommandClass):
    """
    Command Class Notification
    """

    id = 0x71
    versions = tuple(range(3, 10, 1))


# Event Supported Get
EVENT_SUPPORTED_GET = 0x01
# Event Supported Report
EVENT_SUPPORTED_REPORT = 0x02
# Notification Get
NOTIFICATION_GET = 0x04
# Notification Report
NOTIFICATION_REPORT = 0x05
# Notification Set
NOTIFICATION_SET = 0x06
# Notification Supported Get
NOTIFICATION_SUPPORTED_GET = 0x07
# Notification Supported Report
NOTIFICATION_SUPPORTED_REPORT = 0x08

NOTIFICATION_VERSION_V3 = 0x03
NOTIFICATION_GET_V3 = 0x04
NOTIFICATION_REPORT_V3 = 0x05
NOTIFICATION_SET_V3 = 0x06
NOTIFICATION_SUPPORTED_GET_V3 = 0x07
NOTIFICATION_SUPPORTED_REPORT_V3 = 0x08
EVENT_SUPPORTED_GET_V3 = 0x01
EVENT_SUPPORTED_REPORT_V3 = 0x02
# Values used for Notification Get command
NOTIFICATION_GET_RESERVED_V3 = 0x00
NOTIFICATION_GET_SMOKE_V3 = 0x01
NOTIFICATION_GET_CO_V3 = 0x02
NOTIFICATION_GET_CO2_V3 = 0x03
NOTIFICATION_GET_HEAT_V3 = 0x04
NOTIFICATION_GET_WATER_V3 = 0x05
NOTIFICATION_GET_ACCESS_CONTROL_V3 = 0x06
NOTIFICATION_GET_BURGLAR_V3 = 0x07
NOTIFICATION_GET_POWER_MANAGEMENT_V3 = 0x08
NOTIFICATION_GET_SYSTEM_V3 = 0x09
NOTIFICATION_GET_EMERGENCY_V3 = 0x0A
NOTIFICATION_GET_CLOCK_V3 = 0x0B
NOTIFICATION_GET_FIRST_V3 = 0xFF
# Values used for Notification Report command
NOTIFICATION_REPORT_RESERVED_V3 = 0x00
NOTIFICATION_REPORT_SMOKE_V3 = 0x01
NOTIFICATION_REPORT_CO_V3 = 0x02
NOTIFICATION_REPORT_CO2_V3 = 0x03
NOTIFICATION_REPORT_HEAT_V3 = 0x04
NOTIFICATION_REPORT_WATER_V3 = 0x05
NOTIFICATION_REPORT_ACCESS_CONTROL_V3 = 0x06
NOTIFICATION_REPORT_BURGLAR_V3 = 0x07
NOTIFICATION_REPORT_POWER_MANAGEMENT_V3 = 0x08
NOTIFICATION_REPORT_SYSTEM_V3 = 0x09
NOTIFICATION_REPORT_EMERGENCY_V3 = 0x0A
NOTIFICATION_REPORT_CLOCK_V3 = 0x0B
NOTIFICATION_REPORT_FIRST_V3 = 0xFF
NOTIFICATION_REPORT_PROPERTIES1_EVENT_PARAMETERS_LENGTH_MASK_V3 = 0x1F
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_MASK_V3 = 0x60
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_SHIFT_V3 = 0x05
NOTIFICATION_REPORT_PROPERTIES1_SEQUENCE_BIT_MASK_V3 = 0x80
# Values used for Notification Set command
NOTIFICATION_SET_RESERVED_V3 = 0x00
NOTIFICATION_SET_SMOKE_V3 = 0x01
NOTIFICATION_SET_CO_V3 = 0x02
NOTIFICATION_SET_CO2_V3 = 0x03
NOTIFICATION_SET_HEAT_V3 = 0x04
NOTIFICATION_SET_WATER_V3 = 0x05
NOTIFICATION_SET_ACCESS_CONTROL_V3 = 0x06
NOTIFICATION_SET_BURGLAR_V3 = 0x07
NOTIFICATION_SET_POWER_MANAGEMENT_V3 = 0x08
NOTIFICATION_SET_SYSTEM_V3 = 0x09
NOTIFICATION_SET_EMERGENCY_V3 = 0x0A
NOTIFICATION_SET_CLOCK_V3 = 0x0B
NOTIFICATION_SET_FIRST_V3 = 0xFF
# Values used for Notification Supported Report command
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V3 = 0x1F
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V3 = 0x60
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V3 = 0x05
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_V1_ALARM_BIT_MASK_V3 = 0x80
# Values used for Event Supported Get command
EVENT_SUPPORTED_GET_RESERVED_V3 = 0x00
EVENT_SUPPORTED_GET_SMOKE_V3 = 0x01
EVENT_SUPPORTED_GET_CO_V3 = 0x02
EVENT_SUPPORTED_GET_CO2_V3 = 0x03
EVENT_SUPPORTED_GET_HEAT_V3 = 0x04
EVENT_SUPPORTED_GET_WATER_V3 = 0x05
EVENT_SUPPORTED_GET_ACCESS_CONTROL_V3 = 0x06
EVENT_SUPPORTED_GET_BURGLAR_V3 = 0x07
EVENT_SUPPORTED_GET_POWER_MANAGEMENT_V3 = 0x08
EVENT_SUPPORTED_GET_SYSTEM_V3 = 0x09
EVENT_SUPPORTED_GET_EMERGENCY_V3 = 0x0A
EVENT_SUPPORTED_GET_CLOCK_V3 = 0x0B
EVENT_SUPPORTED_GET_FIRST_V3 = 0xFF
# Values used for Event Supported Report command
EVENT_SUPPORTED_REPORT_RESERVED_V3 = 0x00
EVENT_SUPPORTED_REPORT_SMOKE_V3 = 0x01
EVENT_SUPPORTED_REPORT_CO_V3 = 0x02
EVENT_SUPPORTED_REPORT_CO2_V3 = 0x03
EVENT_SUPPORTED_REPORT_HEAT_V3 = 0x04
EVENT_SUPPORTED_REPORT_WATER_V3 = 0x05
EVENT_SUPPORTED_REPORT_ACCESS_CONTROL_V3 = 0x06
EVENT_SUPPORTED_REPORT_BURGLAR_V3 = 0x07
EVENT_SUPPORTED_REPORT_POWER_MANAGEMENT_V3 = 0x08
EVENT_SUPPORTED_REPORT_SYSTEM_V3 = 0x09
EVENT_SUPPORTED_REPORT_EMERGENCY_V3 = 0x0A
EVENT_SUPPORTED_REPORT_CLOCK_V3 = 0x0B
EVENT_SUPPORTED_REPORT_FIRST_V3 = 0xFF
EVENT_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V3 = 0x1F
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V3 = 0xE0
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V3 = 0x05

NOTIFICATION_VERSION_V4 = 0x04
NOTIFICATION_GET_V4 = 0x04
NOTIFICATION_REPORT_V4 = 0x05
NOTIFICATION_SET_V4 = 0x06
NOTIFICATION_SUPPORTED_GET_V4 = 0x07
NOTIFICATION_SUPPORTED_REPORT_V4 = 0x08
EVENT_SUPPORTED_GET_V4 = 0x01
EVENT_SUPPORTED_REPORT_V4 = 0x02
# Values used for Notification Get command
NOTIFICATION_GET_RESERVED_V4 = 0x00
NOTIFICATION_GET_SMOKE_V4 = 0x01
NOTIFICATION_GET_CO_V4 = 0x02
NOTIFICATION_GET_CO2_V4 = 0x03
NOTIFICATION_GET_HEAT_V4 = 0x04
NOTIFICATION_GET_WATER_V4 = 0x05
NOTIFICATION_GET_ACCESS_CONTROL_V4 = 0x06
NOTIFICATION_GET_HOME_SECURITY_V4 = 0x07
NOTIFICATION_GET_POWER_MANAGEMENT_V4 = 0x08
NOTIFICATION_GET_SYSTEM_V4 = 0x09
NOTIFICATION_GET_EMERGENCY_V4 = 0x0A
NOTIFICATION_GET_CLOCK_V4 = 0x0B
NOTIFICATION_GET_APPLIANCE_V4 = 0x0C
NOTIFICATION_GET_HOME_HEALTH_V4 = 0x0D
NOTIFICATION_GET_FIRST_V4 = 0xFF
# Values used for Notification Report command
NOTIFICATION_REPORT_OFF_V4 = 0x00
NOTIFICATION_REPORT_NO_PENDING_NOTIFICATIONS_V4 = 0xFE
NOTIFICATION_REPORT_ON_V4 = 0xFF
NOTIFICATION_REPORT_RESERVED_V4 = 0x00
NOTIFICATION_REPORT_SMOKE_V4 = 0x01
NOTIFICATION_REPORT_CO_V4 = 0x02
NOTIFICATION_REPORT_CO2_V4 = 0x03
NOTIFICATION_REPORT_HEAT_V4 = 0x04
NOTIFICATION_REPORT_WATER_V4 = 0x05
NOTIFICATION_REPORT_ACCESS_CONTROL_V4 = 0x06
NOTIFICATION_REPORT_HOME_SECURITY_V4 = 0x07
NOTIFICATION_REPORT_POWER_MANAGEMENT_V4 = 0x08
NOTIFICATION_REPORT_SYSTEM_V4 = 0x09
NOTIFICATION_REPORT_EMERGENCY_V4 = 0x0A
NOTIFICATION_REPORT_CLOCK_V4 = 0x0B
NOTIFICATION_REPORT_APPLIANCE_V4 = 0x0C
NOTIFICATION_REPORT_HOME_HEALTH_V4 = 0x0D
NOTIFICATION_REPORT_FIRST_V4 = 0xFF
NOTIFICATION_REPORT_PROPERTIES1_EVENT_PARAMETERS_LENGTH_MASK_V4 = 0x1F
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_MASK_V4 = 0x60
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_SHIFT_V4 = 0x05
NOTIFICATION_REPORT_PROPERTIES1_SEQUENCE_BIT_MASK_V4 = 0x80
# Values used for Notification Set command
NOTIFICATION_SET_RESERVED_V4 = 0x00
NOTIFICATION_SET_SMOKE_V4 = 0x01
NOTIFICATION_SET_CO_V4 = 0x02
NOTIFICATION_SET_CO2_V4 = 0x03
NOTIFICATION_SET_HEAT_V4 = 0x04
NOTIFICATION_SET_WATER_V4 = 0x05
NOTIFICATION_SET_ACCESS_CONTROL_V4 = 0x06
NOTIFICATION_SET_HOME_SECURITY_V4 = 0x07
NOTIFICATION_SET_POWER_MANAGEMENT_V4 = 0x08
NOTIFICATION_SET_SYSTEM_V4 = 0x09
NOTIFICATION_SET_EMERGENCY_V4 = 0x0A
NOTIFICATION_SET_CLOCK_V4 = 0x0B
NOTIFICATION_SET_APPLIANCE_V4 = 0x0C
NOTIFICATION_SET_HOME_HEALTH_V4 = 0x0D
NOTIFICATION_SET_FIRST_V4 = 0xFF
NOTIFICATION_SET_OFF_V4 = 0x00
NOTIFICATION_SET_NO_PENDING_NOTIFICATIONS_V4 = 0xFE
NOTIFICATION_SET_ON_V4 = 0xFF
# Values used for Notification Supported Report command
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V4 = 0x1F
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V4 = 0x60
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V4 = 0x05
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_V1_ALARM_BIT_MASK_V4 = 0x80
# Values used for Event Supported Get command
EVENT_SUPPORTED_GET_RESERVED_V4 = 0x00
EVENT_SUPPORTED_GET_SMOKE_V4 = 0x01
EVENT_SUPPORTED_GET_CO_V4 = 0x02
EVENT_SUPPORTED_GET_CO2_V4 = 0x03
EVENT_SUPPORTED_GET_HEAT_V4 = 0x04
EVENT_SUPPORTED_GET_WATER_V4 = 0x05
EVENT_SUPPORTED_GET_ACCESS_CONTROL_V4 = 0x06
EVENT_SUPPORTED_GET_HOME_SECURITY_V4 = 0x07
EVENT_SUPPORTED_GET_POWER_MANAGEMENT_V4 = 0x08
EVENT_SUPPORTED_GET_SYSTEM_V4 = 0x09
EVENT_SUPPORTED_GET_EMERGENCY_V4 = 0x0A
EVENT_SUPPORTED_GET_CLOCK_V4 = 0x0B
EVENT_SUPPORTED_GET_APPLIANCE_V4 = 0x0C
EVENT_SUPPORTED_GET_HOME_HEALTH_V4 = 0x0D
EVENT_SUPPORTED_GET_FIRST_V4 = 0xFF
# Values used for Event Supported Report command
EVENT_SUPPORTED_REPORT_RESERVED_V4 = 0x00
EVENT_SUPPORTED_REPORT_SMOKE_V4 = 0x01
EVENT_SUPPORTED_REPORT_CO_V4 = 0x02
EVENT_SUPPORTED_REPORT_CO2_V4 = 0x03
EVENT_SUPPORTED_REPORT_HEAT_V4 = 0x04
EVENT_SUPPORTED_REPORT_WATER_V4 = 0x05
EVENT_SUPPORTED_REPORT_ACCESS_CONTROL_V4 = 0x06
EVENT_SUPPORTED_REPORT_HOME_SECURITY_V4 = 0x07
EVENT_SUPPORTED_REPORT_POWER_MANAGEMENT_V4 = 0x08
EVENT_SUPPORTED_REPORT_SYSTEM_V4 = 0x09
EVENT_SUPPORTED_REPORT_EMERGENCY_V4 = 0x0A
EVENT_SUPPORTED_REPORT_CLOCK_V4 = 0x0B
EVENT_SUPPORTED_REPORT_APPLIANCE_V4 = 0x0C
EVENT_SUPPORTED_REPORT_HOME_HEALTH_V4 = 0x0D
EVENT_SUPPORTED_REPORT_FIRST_V4 = 0xFF
EVENT_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V4 = 0x1F
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V4 = 0xE0
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V4 = 0x05

NOTIFICATION_VERSION_V5 = 0x05
NOTIFICATION_GET_V5 = 0x04
NOTIFICATION_REPORT_V5 = 0x05
NOTIFICATION_SET_V5 = 0x06
NOTIFICATION_SUPPORTED_GET_V5 = 0x07
NOTIFICATION_SUPPORTED_REPORT_V5 = 0x08
EVENT_SUPPORTED_GET_V5 = 0x01
EVENT_SUPPORTED_REPORT_V5 = 0x02
# Values used for Notification Get command
NOTIFICATION_GET_RESERVED_V5 = 0x00
NOTIFICATION_GET_SMOKE_V5 = 0x01
NOTIFICATION_GET_CO_V5 = 0x02
NOTIFICATION_GET_CO2_V5 = 0x03
NOTIFICATION_GET_HEAT_V5 = 0x04
NOTIFICATION_GET_WATER_V5 = 0x05
NOTIFICATION_GET_ACCESS_CONTROL_V5 = 0x06
NOTIFICATION_GET_HOME_SECURITY_V5 = 0x07
NOTIFICATION_GET_POWER_MANAGEMENT_V5 = 0x08
NOTIFICATION_GET_SYSTEM_V5 = 0x09
NOTIFICATION_GET_EMERGENCY_V5 = 0x0A
NOTIFICATION_GET_CLOCK_V5 = 0x0B
NOTIFICATION_GET_APPLIANCE_V5 = 0x0C
NOTIFICATION_GET_HOME_HEALTH_V5 = 0x0D
NOTIFICATION_GET_FIRST_V5 = 0xFF
# Values used for Notification Report command
NOTIFICATION_REPORT_OFF_V5 = 0x00
NOTIFICATION_REPORT_NO_PENDING_NOTIFICATIONS_V5 = 0xFE
NOTIFICATION_REPORT_ON_V5 = 0xFF
NOTIFICATION_REPORT_RESERVED_V5 = 0x00
NOTIFICATION_REPORT_SMOKE_V5 = 0x01
NOTIFICATION_REPORT_CO_V5 = 0x02
NOTIFICATION_REPORT_CO2_V5 = 0x03
NOTIFICATION_REPORT_HEAT_V5 = 0x04
NOTIFICATION_REPORT_WATER_V5 = 0x05
NOTIFICATION_REPORT_ACCESS_CONTROL_V5 = 0x06
NOTIFICATION_REPORT_HOME_SECURITY_V5 = 0x07
NOTIFICATION_REPORT_POWER_MANAGEMENT_V5 = 0x08
NOTIFICATION_REPORT_SYSTEM_V5 = 0x09
NOTIFICATION_REPORT_EMERGENCY_V5 = 0x0A
NOTIFICATION_REPORT_CLOCK_V5 = 0x0B
NOTIFICATION_REPORT_APPLIANCE_V5 = 0x0C
NOTIFICATION_REPORT_HOME_HEALTH_V5 = 0x0D
NOTIFICATION_REPORT_FIRST_V5 = 0xFF
NOTIFICATION_REPORT_PROPERTIES1_EVENT_PARAMETERS_LENGTH_MASK_V5 = 0x1F
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_MASK_V5 = 0x60
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_SHIFT_V5 = 0x05
NOTIFICATION_REPORT_PROPERTIES1_SEQUENCE_BIT_MASK_V5 = 0x80
# Values used for Notification Set command
NOTIFICATION_SET_RESERVED_V5 = 0x00
NOTIFICATION_SET_SMOKE_V5 = 0x01
NOTIFICATION_SET_CO_V5 = 0x02
NOTIFICATION_SET_CO2_V5 = 0x03
NOTIFICATION_SET_HEAT_V5 = 0x04
NOTIFICATION_SET_WATER_V5 = 0x05
NOTIFICATION_SET_ACCESS_CONTROL_V5 = 0x06
NOTIFICATION_SET_HOME_SECURITY_V5 = 0x07
NOTIFICATION_SET_POWER_MANAGEMENT_V5 = 0x08
NOTIFICATION_SET_SYSTEM_V5 = 0x09
NOTIFICATION_SET_EMERGENCY_V5 = 0x0A
NOTIFICATION_SET_CLOCK_V5 = 0x0B
NOTIFICATION_SET_APPLIANCE_V5 = 0x0C
NOTIFICATION_SET_HOME_HEALTH_V5 = 0x0D
NOTIFICATION_SET_FIRST_V5 = 0xFF
NOTIFICATION_SET_OFF_V5 = 0x00
NOTIFICATION_SET_NO_PENDING_NOTIFICATIONS_V5 = 0xFE
NOTIFICATION_SET_ON_V5 = 0xFF
# Values used for Notification Supported Report command
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V5 = 0x1F
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V5 = 0x60
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V5 = 0x05
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_V1_ALARM_BIT_MASK_V5 = 0x80
# Values used for Event Supported Get command
EVENT_SUPPORTED_GET_RESERVED_V5 = 0x00
EVENT_SUPPORTED_GET_SMOKE_V5 = 0x01
EVENT_SUPPORTED_GET_CO_V5 = 0x02
EVENT_SUPPORTED_GET_CO2_V5 = 0x03
EVENT_SUPPORTED_GET_HEAT_V5 = 0x04
EVENT_SUPPORTED_GET_WATER_V5 = 0x05
EVENT_SUPPORTED_GET_ACCESS_CONTROL_V5 = 0x06
EVENT_SUPPORTED_GET_HOME_SECURITY_V5 = 0x07
EVENT_SUPPORTED_GET_POWER_MANAGEMENT_V5 = 0x08
EVENT_SUPPORTED_GET_SYSTEM_V5 = 0x09
EVENT_SUPPORTED_GET_EMERGENCY_V5 = 0x0A
EVENT_SUPPORTED_GET_CLOCK_V5 = 0x0B
EVENT_SUPPORTED_GET_APPLIANCE_V5 = 0x0C
EVENT_SUPPORTED_GET_HOME_HEALTH_V5 = 0x0D
EVENT_SUPPORTED_GET_FIRST_V5 = 0xFF
# Values used for Event Supported Report command
EVENT_SUPPORTED_REPORT_RESERVED_V5 = 0x00
EVENT_SUPPORTED_REPORT_SMOKE_V5 = 0x01
EVENT_SUPPORTED_REPORT_CO_V5 = 0x02
EVENT_SUPPORTED_REPORT_CO2_V5 = 0x03
EVENT_SUPPORTED_REPORT_HEAT_V5 = 0x04
EVENT_SUPPORTED_REPORT_WATER_V5 = 0x05
EVENT_SUPPORTED_REPORT_ACCESS_CONTROL_V5 = 0x06
EVENT_SUPPORTED_REPORT_HOME_SECURITY_V5 = 0x07
EVENT_SUPPORTED_REPORT_POWER_MANAGEMENT_V5 = 0x08
EVENT_SUPPORTED_REPORT_SYSTEM_V5 = 0x09
EVENT_SUPPORTED_REPORT_EMERGENCY_V5 = 0x0A
EVENT_SUPPORTED_REPORT_CLOCK_V5 = 0x0B
EVENT_SUPPORTED_REPORT_APPLIANCE_V5 = 0x0C
EVENT_SUPPORTED_REPORT_HOME_HEALTH_V5 = 0x0D
EVENT_SUPPORTED_REPORT_FIRST_V5 = 0xFF
EVENT_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V5 = 0x1F
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V5 = 0xE0
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V5 = 0x05

NOTIFICATION_VERSION_V6 = 0x06
NOTIFICATION_GET_V6 = 0x04
NOTIFICATION_REPORT_V6 = 0x05
NOTIFICATION_SET_V6 = 0x06
NOTIFICATION_SUPPORTED_GET_V6 = 0x07
NOTIFICATION_SUPPORTED_REPORT_V6 = 0x08
EVENT_SUPPORTED_GET_V6 = 0x01
EVENT_SUPPORTED_REPORT_V6 = 0x02
# Values used for Notification Get command
NOTIFICATION_GET_RESERVED_V6 = 0x00
NOTIFICATION_GET_SMOKE_V6 = 0x01
NOTIFICATION_GET_CO_V6 = 0x02
NOTIFICATION_GET_CO2_V6 = 0x03
NOTIFICATION_GET_HEAT_V6 = 0x04
NOTIFICATION_GET_WATER_V6 = 0x05
NOTIFICATION_GET_ACCESS_CONTROL_V6 = 0x06
NOTIFICATION_GET_HOME_SECURITY_V6 = 0x07
NOTIFICATION_GET_POWER_MANAGEMENT_V6 = 0x08
NOTIFICATION_GET_SYSTEM_V6 = 0x09
NOTIFICATION_GET_EMERGENCY_V6 = 0x0A
NOTIFICATION_GET_CLOCK_V6 = 0x0B
NOTIFICATION_GET_APPLIANCE_V6 = 0x0C
NOTIFICATION_GET_HOME_HEALTH_V6 = 0x0D
NOTIFICATION_GET_SIREN_V6 = 0x0E
NOTIFICATION_GET_FIRST_V6 = 0xFF
# Values used for Notification Report command
NOTIFICATION_REPORT_OFF_V6 = 0x00
NOTIFICATION_REPORT_NO_PENDING_NOTIFICATIONS_V6 = 0xFE
NOTIFICATION_REPORT_ON_V6 = 0xFF
NOTIFICATION_REPORT_RESERVED_V6 = 0x00
NOTIFICATION_REPORT_SMOKE_V6 = 0x01
NOTIFICATION_REPORT_CO_V6 = 0x02
NOTIFICATION_REPORT_CO2_V6 = 0x03
NOTIFICATION_REPORT_HEAT_V6 = 0x04
NOTIFICATION_REPORT_WATER_V6 = 0x05
NOTIFICATION_REPORT_ACCESS_CONTROL_V6 = 0x06
NOTIFICATION_REPORT_HOME_SECURITY_V6 = 0x07
NOTIFICATION_REPORT_POWER_MANAGEMENT_V6 = 0x08
NOTIFICATION_REPORT_SYSTEM_V6 = 0x09
NOTIFICATION_REPORT_EMERGENCY_V6 = 0x0A
NOTIFICATION_REPORT_CLOCK_V6 = 0x0B
NOTIFICATION_REPORT_APPLIANCE_V6 = 0x0C
NOTIFICATION_REPORT_HOME_HEALTH_V6 = 0x0D
NOTIFICATION_REPORT_SIREN_V6 = 0x0E
NOTIFICATION_REPORT_FIRST_V6 = 0xFF
NOTIFICATION_REPORT_PROPERTIES1_EVENT_PARAMETERS_LENGTH_MASK_V6 = 0x1F
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_MASK_V6 = 0x60
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_SHIFT_V6 = 0x05
NOTIFICATION_REPORT_PROPERTIES1_SEQUENCE_BIT_MASK_V6 = 0x80
# Values used for Notification Set command
NOTIFICATION_SET_RESERVED_V6 = 0x00
NOTIFICATION_SET_SMOKE_V6 = 0x01
NOTIFICATION_SET_CO_V6 = 0x02
NOTIFICATION_SET_CO2_V6 = 0x03
NOTIFICATION_SET_HEAT_V6 = 0x04
NOTIFICATION_SET_WATER_V6 = 0x05
NOTIFICATION_SET_ACCESS_CONTROL_V6 = 0x06
NOTIFICATION_SET_HOME_SECURITY_V6 = 0x07
NOTIFICATION_SET_POWER_MANAGEMENT_V6 = 0x08
NOTIFICATION_SET_SYSTEM_V6 = 0x09
NOTIFICATION_SET_EMERGENCY_V6 = 0x0A
NOTIFICATION_SET_CLOCK_V6 = 0x0B
NOTIFICATION_SET_APPLIANCE_V6 = 0x0C
NOTIFICATION_SET_HOME_HEALTH_V6 = 0x0D
NOTIFICATION_SET_SIREN_V6 = 0x0E
NOTIFICATION_SET_FIRST_V6 = 0xFF
NOTIFICATION_SET_OFF_V6 = 0x00
NOTIFICATION_SET_NO_PENDING_NOTIFICATIONS_V6 = 0xFE
NOTIFICATION_SET_ON_V6 = 0xFF
# Values used for Notification Supported Report command
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V6 = 0x1F
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V6 = 0x60
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V6 = 0x05
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_V1_ALARM_BIT_MASK_V6 = 0x80
# Values used for Event Supported Get command
EVENT_SUPPORTED_GET_RESERVED_V6 = 0x00
EVENT_SUPPORTED_GET_SMOKE_V6 = 0x01
EVENT_SUPPORTED_GET_CO_V6 = 0x02
EVENT_SUPPORTED_GET_CO2_V6 = 0x03
EVENT_SUPPORTED_GET_HEAT_V6 = 0x04
EVENT_SUPPORTED_GET_WATER_V6 = 0x05
EVENT_SUPPORTED_GET_ACCESS_CONTROL_V6 = 0x06
EVENT_SUPPORTED_GET_HOME_SECURITY_V6 = 0x07
EVENT_SUPPORTED_GET_POWER_MANAGEMENT_V6 = 0x08
EVENT_SUPPORTED_GET_SYSTEM_V6 = 0x09
EVENT_SUPPORTED_GET_EMERGENCY_V6 = 0x0A
EVENT_SUPPORTED_GET_CLOCK_V6 = 0x0B
EVENT_SUPPORTED_GET_APPLIANCE_V6 = 0x0C
EVENT_SUPPORTED_GET_HOME_HEALTH_V6 = 0x0D
EVENT_SUPPORTED_GET_SIREN_V6 = 0x0E
EVENT_SUPPORTED_GET_FIRST_V6 = 0xFF
# Values used for Event Supported Report command
EVENT_SUPPORTED_REPORT_RESERVED_V6 = 0x00
EVENT_SUPPORTED_REPORT_SMOKE_V6 = 0x01
EVENT_SUPPORTED_REPORT_CO_V6 = 0x02
EVENT_SUPPORTED_REPORT_CO2_V6 = 0x03
EVENT_SUPPORTED_REPORT_HEAT_V6 = 0x04
EVENT_SUPPORTED_REPORT_WATER_V6 = 0x05
EVENT_SUPPORTED_REPORT_ACCESS_CONTROL_V6 = 0x06
EVENT_SUPPORTED_REPORT_HOME_SECURITY_V6 = 0x07
EVENT_SUPPORTED_REPORT_POWER_MANAGEMENT_V6 = 0x08
EVENT_SUPPORTED_REPORT_SYSTEM_V6 = 0x09
EVENT_SUPPORTED_REPORT_EMERGENCY_V6 = 0x0A
EVENT_SUPPORTED_REPORT_CLOCK_V6 = 0x0B
EVENT_SUPPORTED_REPORT_APPLIANCE_V6 = 0x0C
EVENT_SUPPORTED_REPORT_HOME_HEALTH_V6 = 0x0D
EVENT_SUPPORTED_REPORT_SIREN_V6 = 0x0E
EVENT_SUPPORTED_REPORT_FIRST_V6 = 0xFF
EVENT_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V6 = 0x1F
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V6 = 0xE0
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V6 = 0x05

NOTIFICATION_VERSION_V7 = 0x07
NOTIFICATION_GET_V7 = 0x04
NOTIFICATION_REPORT_V7 = 0x05
NOTIFICATION_SET_V7 = 0x06
NOTIFICATION_SUPPORTED_GET_V7 = 0x07
NOTIFICATION_SUPPORTED_REPORT_V7 = 0x08
EVENT_SUPPORTED_GET_V7 = 0x01
EVENT_SUPPORTED_REPORT_V7 = 0x02
# Values used for Notification Get command
NOTIFICATION_GET_RESERVED_V7 = 0x00
NOTIFICATION_GET_SMOKE_V7 = 0x01
NOTIFICATION_GET_CO_V7 = 0x02
NOTIFICATION_GET_CO2_V7 = 0x03
NOTIFICATION_GET_HEAT_V7 = 0x04
NOTIFICATION_GET_WATER_V7 = 0x05
NOTIFICATION_GET_ACCESS_CONTROL_V7 = 0x06
NOTIFICATION_GET_HOME_SECURITY_V7 = 0x07
NOTIFICATION_GET_POWER_MANAGEMENT_V7 = 0x08
NOTIFICATION_GET_SYSTEM_V7 = 0x09
NOTIFICATION_GET_EMERGENCY_V7 = 0x0A
NOTIFICATION_GET_CLOCK_V7 = 0x0B
NOTIFICATION_GET_APPLIANCE_V7 = 0x0C
NOTIFICATION_GET_HOME_HEALTH_V7 = 0x0D
NOTIFICATION_GET_SIREN_V7 = 0x0E
NOTIFICATION_GET_WATER_VALVE_V7 = 0x0F
NOTIFICATION_GET_WEATHER_ALARM_V7 = 0x10
NOTIFICATION_GET_IRRIGATION_V7 = 0x11
NOTIFICATION_GET_GAS_ALARM_V7 = 0x12
NOTIFICATION_GET_FIRST_V7 = 0xFF
# Values used for Notification Report command
NOTIFICATION_REPORT_OFF_V7 = 0x00
NOTIFICATION_REPORT_NO_PENDING_NOTIFICATIONS_V7 = 0xFE
NOTIFICATION_REPORT_ON_V7 = 0xFF
NOTIFICATION_REPORT_RESERVED_V7 = 0x00
NOTIFICATION_REPORT_SMOKE_V7 = 0x01
NOTIFICATION_REPORT_CO_V7 = 0x02
NOTIFICATION_REPORT_CO2_V7 = 0x03
NOTIFICATION_REPORT_HEAT_V7 = 0x04
NOTIFICATION_REPORT_WATER_V7 = 0x05
NOTIFICATION_REPORT_ACCESS_CONTROL_V7 = 0x06
NOTIFICATION_REPORT_HOME_SECURITY_V7 = 0x07
NOTIFICATION_REPORT_POWER_MANAGEMENT_V7 = 0x08
NOTIFICATION_REPORT_SYSTEM_V7 = 0x09
NOTIFICATION_REPORT_EMERGENCY_V7 = 0x0A
NOTIFICATION_REPORT_CLOCK_V7 = 0x0B
NOTIFICATION_REPORT_APPLIANCE_V7 = 0x0C
NOTIFICATION_REPORT_HOME_HEALTH_V7 = 0x0D
NOTIFICATION_REPORT_SIREN_V7 = 0x0E
NOTIFICATION_REPORT_WATER_VALVE_V7 = 0x0F
NOTIFICATION_REPORT_WEATHER_ALARM_V7 = 0x10
NOTIFICATION_REPORT_IRRIGATION_V7 = 0x11
NOTIFICATION_REPORT_GAS_ALARM_V7 = 0x12
NOTIFICATION_REPORT_FIRST_V7 = 0xFF
NOTIFICATION_REPORT_PROPERTIES1_EVENT_PARAMETERS_LENGTH_MASK_V7 = 0x1F
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_MASK_V7 = 0x60
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_SHIFT_V7 = 0x05
NOTIFICATION_REPORT_PROPERTIES1_SEQUENCE_BIT_MASK_V7 = 0x80
# Values used for Notification Set command
NOTIFICATION_SET_RESERVED_V7 = 0x00
NOTIFICATION_SET_SMOKE_V7 = 0x01
NOTIFICATION_SET_CO_V7 = 0x02
NOTIFICATION_SET_CO2_V7 = 0x03
NOTIFICATION_SET_HEAT_V7 = 0x04
NOTIFICATION_SET_WATER_V7 = 0x05
NOTIFICATION_SET_ACCESS_CONTROL_V7 = 0x06
NOTIFICATION_SET_HOME_SECURITY_V7 = 0x07
NOTIFICATION_SET_POWER_MANAGEMENT_V7 = 0x08
NOTIFICATION_SET_SYSTEM_V7 = 0x09
NOTIFICATION_SET_EMERGENCY_V7 = 0x0A
NOTIFICATION_SET_CLOCK_V7 = 0x0B
NOTIFICATION_SET_APPLIANCE_V7 = 0x0C
NOTIFICATION_SET_HOME_HEALTH_V7 = 0x0D
NOTIFICATION_SET_SIREN_V7 = 0x0E
NOTIFICATION_SET_WATER_VALVE_V7 = 0x0F
NOTIFICATION_SET_WEATHER_ALARM_V7 = 0x10
NOTIFICATION_SET_IRRIGATION_V7 = 0x11
NOTIFICATION_SET_GAS_ALARM_V7 = 0x12
NOTIFICATION_SET_FIRST_V7 = 0xFF
NOTIFICATION_SET_OFF_V7 = 0x00
NOTIFICATION_SET_NO_PENDING_NOTIFICATIONS_V7 = 0xFE
NOTIFICATION_SET_ON_V7 = 0xFF
# Values used for Notification Supported Report command
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V7 = 0x1F
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V7 = 0x60
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V7 = 0x05
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_V1_ALARM_BIT_MASK_V7 = 0x80
# Values used for Event Supported Get command
EVENT_SUPPORTED_GET_RESERVED_V7 = 0x00
EVENT_SUPPORTED_GET_SMOKE_V7 = 0x01
EVENT_SUPPORTED_GET_CO_V7 = 0x02
EVENT_SUPPORTED_GET_CO2_V7 = 0x03
EVENT_SUPPORTED_GET_HEAT_V7 = 0x04
EVENT_SUPPORTED_GET_WATER_V7 = 0x05
EVENT_SUPPORTED_GET_ACCESS_CONTROL_V7 = 0x06
EVENT_SUPPORTED_GET_HOME_SECURITY_V7 = 0x07
EVENT_SUPPORTED_GET_POWER_MANAGEMENT_V7 = 0x08
EVENT_SUPPORTED_GET_SYSTEM_V7 = 0x09
EVENT_SUPPORTED_GET_EMERGENCY_V7 = 0x0A
EVENT_SUPPORTED_GET_CLOCK_V7 = 0x0B
EVENT_SUPPORTED_GET_APPLIANCE_V7 = 0x0C
EVENT_SUPPORTED_GET_HOME_HEALTH_V7 = 0x0D
EVENT_SUPPORTED_GET_SIREN_V7 = 0x0E
EVENT_SUPPORTED_GET_WATER_VALVE_V7 = 0x0F
EVENT_SUPPORTED_GET_WEATHER_ALARM_V7 = 0x10
EVENT_SUPPORTED_GET_IRRIGATION_V7 = 0x11
EVENT_SUPPORTED_GET_GAS_ALARM_V7 = 0x12
EVENT_SUPPORTED_GET_FIRST_V7 = 0xFF
# Values used for Event Supported Report command
EVENT_SUPPORTED_REPORT_RESERVED_V7 = 0x00
EVENT_SUPPORTED_REPORT_SMOKE_V7 = 0x01
EVENT_SUPPORTED_REPORT_CO_V7 = 0x02
EVENT_SUPPORTED_REPORT_CO2_V7 = 0x03
EVENT_SUPPORTED_REPORT_HEAT_V7 = 0x04
EVENT_SUPPORTED_REPORT_WATER_V7 = 0x05
EVENT_SUPPORTED_REPORT_ACCESS_CONTROL_V7 = 0x06
EVENT_SUPPORTED_REPORT_HOME_SECURITY_V7 = 0x07
EVENT_SUPPORTED_REPORT_POWER_MANAGEMENT_V7 = 0x08
EVENT_SUPPORTED_REPORT_SYSTEM_V7 = 0x09
EVENT_SUPPORTED_REPORT_EMERGENCY_V7 = 0x0A
EVENT_SUPPORTED_REPORT_CLOCK_V7 = 0x0B
EVENT_SUPPORTED_REPORT_APPLIANCE_V7 = 0x0C
EVENT_SUPPORTED_REPORT_HOME_HEALTH_V7 = 0x0D
EVENT_SUPPORTED_REPORT_SIREN_V7 = 0x0E
EVENT_SUPPORTED_REPORT_WATER_VALVE_V7 = 0x0F
EVENT_SUPPORTED_REPORT_WEATHER_ALARM_V7 = 0x10
EVENT_SUPPORTED_REPORT_IRRIGATION_V7 = 0x11
EVENT_SUPPORTED_REPORT_GAS_ALARM_V7 = 0x12
EVENT_SUPPORTED_REPORT_FIRST_V7 = 0xFF
EVENT_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V7 = 0x1F
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V7 = 0xE0
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V7 = 0x05

NOTIFICATION_VERSION_V8 = 0x08
NOTIFICATION_GET_V8 = 0x04
NOTIFICATION_REPORT_V8 = 0x05
NOTIFICATION_SET_V8 = 0x06
NOTIFICATION_SUPPORTED_GET_V8 = 0x07
NOTIFICATION_SUPPORTED_REPORT_V8 = 0x08
EVENT_SUPPORTED_GET_V8 = 0x01
EVENT_SUPPORTED_REPORT_V8 = 0x02
# Values used for Notification Get command
NOTIFICATION_GET_RESERVED_V8 = 0x00
NOTIFICATION_GET_SMOKE_V8 = 0x01
NOTIFICATION_GET_CO_V8 = 0x02
NOTIFICATION_GET_CO2_V8 = 0x03
NOTIFICATION_GET_HEAT_V8 = 0x04
NOTIFICATION_GET_WATER_V8 = 0x05
NOTIFICATION_GET_ACCESS_CONTROL_V8 = 0x06
NOTIFICATION_GET_HOME_SECURITY_V8 = 0x07
NOTIFICATION_GET_POWER_MANAGEMENT_V8 = 0x08
NOTIFICATION_GET_SYSTEM_V8 = 0x09
NOTIFICATION_GET_EMERGENCY_V8 = 0x0A
NOTIFICATION_GET_CLOCK_V8 = 0x0B
NOTIFICATION_GET_APPLIANCE_V8 = 0x0C
NOTIFICATION_GET_HOME_HEALTH_V8 = 0x0D
NOTIFICATION_GET_SIREN_V8 = 0x0E
NOTIFICATION_GET_WATER_VALVE_V8 = 0x0F
NOTIFICATION_GET_WEATHER_ALARM_V8 = 0x10
NOTIFICATION_GET_IRRIGATION_V8 = 0x11
NOTIFICATION_GET_GAS_ALARM_V8 = 0x12
NOTIFICATION_GET_PEST_CONTROL_V8 = 0x13
NOTIFICATION_GET_LIGHT_SENSOR_V8 = 0x14
NOTIFICATION_GET_WATER_QUALITY_MONITORING_V8 = 0x15
NOTIFICATION_GET_HOME_MONITORING_V8 = 0x16
NOTIFICATION_GET_FIRST_V8 = 0xFF
# Values used for Notification Report command
NOTIFICATION_REPORT_OFF_V8 = 0x00
NOTIFICATION_REPORT_NO_PENDING_NOTIFICATIONS_V8 = 0xFE
NOTIFICATION_REPORT_ON_V8 = 0xFF
NOTIFICATION_REPORT_RESERVED_V8 = 0x00
NOTIFICATION_REPORT_SMOKE_V8 = 0x01
NOTIFICATION_REPORT_CO_V8 = 0x02
NOTIFICATION_REPORT_CO2_V8 = 0x03
NOTIFICATION_REPORT_HEAT_V8 = 0x04
NOTIFICATION_REPORT_WATER_V8 = 0x05
NOTIFICATION_REPORT_ACCESS_CONTROL_V8 = 0x06
NOTIFICATION_REPORT_HOME_SECURITY_V8 = 0x07
NOTIFICATION_REPORT_POWER_MANAGEMENT_V8 = 0x08
NOTIFICATION_REPORT_SYSTEM_V8 = 0x09
NOTIFICATION_REPORT_EMERGENCY_V8 = 0x0A
NOTIFICATION_REPORT_CLOCK_V8 = 0x0B
NOTIFICATION_REPORT_APPLIANCE_V8 = 0x0C
NOTIFICATION_REPORT_HOME_HEALTH_V8 = 0x0D
NOTIFICATION_REPORT_SIREN_V8 = 0x0E
NOTIFICATION_REPORT_WATER_VALVE_V8 = 0x0F
NOTIFICATION_REPORT_WEATHER_ALARM_V8 = 0x10
NOTIFICATION_REPORT_IRRIGATION_V8 = 0x11
NOTIFICATION_REPORT_GAS_ALARM_V8 = 0x12
NOTIFICATION_REPORT_PEST_CONTROL_V8 = 0x13
NOTIFICATION_REPORT_LIGHT_SENSOR_V8 = 0x14
NOTIFICATION_REPORT_WATER_QUALITY_MONITORING_V8 = 0x15
NOTIFICATION_REPORT_HOME_MONITORING_V8 = 0x16
NOTIFICATION_REPORT_FIRST_V8 = 0xFF
NOTIFICATION_REPORT_PROPERTIES1_EVENT_PARAMETERS_LENGTH_MASK_V8 = 0x1F
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_MASK_V8 = 0x60
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_SHIFT_V8 = 0x05
NOTIFICATION_REPORT_PROPERTIES1_SEQUENCE_BIT_MASK_V8 = 0x80
# Values used for Notification Set command
NOTIFICATION_SET_RESERVED_V8 = 0x00
NOTIFICATION_SET_SMOKE_V8 = 0x01
NOTIFICATION_SET_CO_V8 = 0x02
NOTIFICATION_SET_CO2_V8 = 0x03
NOTIFICATION_SET_HEAT_V8 = 0x04
NOTIFICATION_SET_WATER_V8 = 0x05
NOTIFICATION_SET_ACCESS_CONTROL_V8 = 0x06
NOTIFICATION_SET_HOME_SECURITY_V8 = 0x07
NOTIFICATION_SET_POWER_MANAGEMENT_V8 = 0x08
NOTIFICATION_SET_SYSTEM_V8 = 0x09
NOTIFICATION_SET_EMERGENCY_V8 = 0x0A
NOTIFICATION_SET_CLOCK_V8 = 0x0B
NOTIFICATION_SET_APPLIANCE_V8 = 0x0C
NOTIFICATION_SET_HOME_HEALTH_V8 = 0x0D
NOTIFICATION_SET_SIREN_V8 = 0x0E
NOTIFICATION_SET_WATER_VALVE_V8 = 0x0F
NOTIFICATION_SET_WEATHER_ALARM_V8 = 0x10
NOTIFICATION_SET_IRRIGATION_V8 = 0x11
NOTIFICATION_SET_GAS_ALARM_V8 = 0x12
NOTIFICATION_SET_PEST_CONTROL_V8 = 0x13
NOTIFICATION_SET_LIGHT_SENSOR_V8 = 0x14
NOTIFICATION_SET_WATER_QUALITY_MONITORING_V8 = 0x15
NOTIFICATION_SET_HOME_MONITORING_V8 = 0x16
NOTIFICATION_SET_FIRST_V8 = 0xFF
NOTIFICATION_SET_OFF_V8 = 0x00
NOTIFICATION_SET_NO_PENDING_NOTIFICATIONS_V8 = 0xFE
NOTIFICATION_SET_ON_V8 = 0xFF
# Values used for Notification Supported Report command
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V8 = 0x1F
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V8 = 0x60
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V8 = 0x05
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_V1_ALARM_BIT_MASK_V8 = 0x80
# Values used for Event Supported Get command
EVENT_SUPPORTED_GET_RESERVED_V8 = 0x00
EVENT_SUPPORTED_GET_SMOKE_V8 = 0x01
EVENT_SUPPORTED_GET_CO_V8 = 0x02
EVENT_SUPPORTED_GET_CO2_V8 = 0x03
EVENT_SUPPORTED_GET_HEAT_V8 = 0x04
EVENT_SUPPORTED_GET_WATER_V8 = 0x05
EVENT_SUPPORTED_GET_ACCESS_CONTROL_V8 = 0x06
EVENT_SUPPORTED_GET_HOME_SECURITY_V8 = 0x07
EVENT_SUPPORTED_GET_POWER_MANAGEMENT_V8 = 0x08
EVENT_SUPPORTED_GET_SYSTEM_V8 = 0x09
EVENT_SUPPORTED_GET_EMERGENCY_V8 = 0x0A
EVENT_SUPPORTED_GET_CLOCK_V8 = 0x0B
EVENT_SUPPORTED_GET_APPLIANCE_V8 = 0x0C
EVENT_SUPPORTED_GET_HOME_HEALTH_V8 = 0x0D
EVENT_SUPPORTED_GET_SIREN_V8 = 0x0E
EVENT_SUPPORTED_GET_WATER_VALVE_V8 = 0x0F
EVENT_SUPPORTED_GET_WEATHER_ALARM_V8 = 0x10
EVENT_SUPPORTED_GET_IRRIGATION_V8 = 0x11
EVENT_SUPPORTED_GET_GAS_ALARM_V8 = 0x12
EVENT_SUPPORTED_GET_PEST_CONTROL_V8 = 0x13
EVENT_SUPPORTED_GET_LIGHT_SENSOR_V8 = 0x14
EVENT_SUPPORTED_GET_WATER_QUALITY_MONITORING_V8 = 0x15
EVENT_SUPPORTED_GET_HOME_MONITORING_V8 = 0x16
EVENT_SUPPORTED_GET_FIRST_V8 = 0xFF
# Values used for Event Supported Report command
EVENT_SUPPORTED_REPORT_RESERVED_V8 = 0x00
EVENT_SUPPORTED_REPORT_SMOKE_V8 = 0x01
EVENT_SUPPORTED_REPORT_CO_V8 = 0x02
EVENT_SUPPORTED_REPORT_CO2_V8 = 0x03
EVENT_SUPPORTED_REPORT_HEAT_V8 = 0x04
EVENT_SUPPORTED_REPORT_WATER_V8 = 0x05
EVENT_SUPPORTED_REPORT_ACCESS_CONTROL_V8 = 0x06
EVENT_SUPPORTED_REPORT_HOME_SECURITY_V8 = 0x07
EVENT_SUPPORTED_REPORT_POWER_MANAGEMENT_V8 = 0x08
EVENT_SUPPORTED_REPORT_SYSTEM_V8 = 0x09
EVENT_SUPPORTED_REPORT_EMERGENCY_V8 = 0x0A
EVENT_SUPPORTED_REPORT_CLOCK_V8 = 0x0B
EVENT_SUPPORTED_REPORT_APPLIANCE_V8 = 0x0C
EVENT_SUPPORTED_REPORT_HOME_HEALTH_V8 = 0x0D
EVENT_SUPPORTED_REPORT_SIREN_V8 = 0x0E
EVENT_SUPPORTED_REPORT_WATER_VALVE_V8 = 0x0F
EVENT_SUPPORTED_REPORT_WEATHER_ALARM_V8 = 0x10
EVENT_SUPPORTED_REPORT_IRRIGATION_V8 = 0x11
EVENT_SUPPORTED_REPORT_GAS_ALARM_V8 = 0x12
EVENT_SUPPORTED_REPORT_PEST_CONTROL_V8 = 0x13
EVENT_SUPPORTED_REPORT_LIGHT_SENSOR_V8 = 0x14
EVENT_SUPPORTED_REPORT_WATER_QUALITY_MONITORING_V8 = 0x15
EVENT_SUPPORTED_REPORT_HOME_MONITORING_V8 = 0x16
EVENT_SUPPORTED_REPORT_FIRST_V8 = 0xFF
EVENT_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V8 = 0x1F
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V8 = 0xE0
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V8 = 0x05

NOTIFICATION_VERSION_V9 = 0x09
NOTIFICATION_GET_V9 = 0x04

# Values used for Notification Get command
NOTIFICATION_GET_RESERVED_V9 = 0x00
NOTIFICATION_GET_SMOKE_V9 = 0x01
NOTIFICATION_GET_CO_V9 = 0x02
NOTIFICATION_GET_CO2_V9 = 0x03
NOTIFICATION_GET_HEAT_V9 = 0x04
NOTIFICATION_GET_WATER_V9 = 0x05
NOTIFICATION_GET_ACCESS_CONTROL_V9 = 0x06
NOTIFICATION_GET_HOME_SECURITY_V9 = 0x07
NOTIFICATION_GET_POWER_MANAGEMENT_V9 = 0x08
NOTIFICATION_GET_SYSTEM_V9 = 0x09
NOTIFICATION_GET_EMERGENCY_V9 = 0x0A
NOTIFICATION_GET_CLOCK_V9 = 0x0B
NOTIFICATION_GET_APPLIANCE_V9 = 0x0C
NOTIFICATION_GET_HOME_HEALTH_V9 = 0x0D
NOTIFICATION_GET_SIREN_V9 = 0x0E
NOTIFICATION_GET_WATER_VALVE_V9 = 0x0F
NOTIFICATION_GET_WEATHER_ALARM_V9 = 0x10
NOTIFICATION_GET_IRRIGATION_V9 = 0x11
NOTIFICATION_GET_GAS_ALARM_V9 = 0x12
NOTIFICATION_GET_PEST_CONTROL_V9 = 0x13
NOTIFICATION_GET_LIGHT_SENSOR_V9 = 0x14
NOTIFICATION_GET_WATER_QUALITY_MONITORING_V9 = 0x15
NOTIFICATION_GET_HOME_MONITORING_V9 = 0x16
NOTIFICATION_GET_FIRST_V9 = 0xFF


NOTIFICATION_REPORT_V9 = 0x05

# Values used for Notification Report command
NOTIFICATION_REPORT_OFF_V9 = 0x00
NOTIFICATION_REPORT_NO_PENDING_NOTIFICATIONS_V9 = 0xFE
NOTIFICATION_REPORT_ON_V9 = 0xFF
NOTIFICATION_REPORT_RESERVED_V9 = 0x00
NOTIFICATION_REPORT_SMOKE_V9 = 0x01
NOTIFICATION_REPORT_CO_V9 = 0x02
NOTIFICATION_REPORT_CO2_V9 = 0x03
NOTIFICATION_REPORT_HEAT_V9 = 0x04
NOTIFICATION_REPORT_WATER_V9 = 0x05
NOTIFICATION_REPORT_ACCESS_CONTROL_V9 = 0x06
NOTIFICATION_REPORT_HOME_SECURITY_V9 = 0x07
NOTIFICATION_REPORT_POWER_MANAGEMENT_V9 = 0x08
NOTIFICATION_REPORT_SYSTEM_V9 = 0x09
NOTIFICATION_REPORT_EMERGENCY_V9 = 0x0A
NOTIFICATION_REPORT_CLOCK_V9 = 0x0B
NOTIFICATION_REPORT_APPLIANCE_V9 = 0x0C
NOTIFICATION_REPORT_HOME_HEALTH_V9 = 0x0D
NOTIFICATION_REPORT_SIREN_V9 = 0x0E
NOTIFICATION_REPORT_WATER_VALVE_V9 = 0x0F
NOTIFICATION_REPORT_WEATHER_ALARM_V9 = 0x10
NOTIFICATION_REPORT_IRRIGATION_V9 = 0x11
NOTIFICATION_REPORT_GAS_ALARM_V9 = 0x12
NOTIFICATION_REPORT_PEST_CONTROL_V9 = 0x13
NOTIFICATION_REPORT_LIGHT_SENSOR_V9 = 0x14
NOTIFICATION_REPORT_WATER_QUALITY_MONITORING_V9 = 0x15
NOTIFICATION_REPORT_HOME_MONITORING_V9 = 0x16
NOTIFICATION_REPORT_FIRST_V9 = 0xFF
NOTIFICATION_REPORT_PROPERTIES1_EVENT_PARAMETERS_LENGTH_MASK_V9 = 0x1F
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_MASK_V9 = 0x60
NOTIFICATION_REPORT_PROPERTIES1_RESERVED2_SHIFT_V9 = 0x05
NOTIFICATION_REPORT_PROPERTIES1_SEQUENCE_BIT_MASK_V9 = 0x80


NOTIFICATION_SET_V9 = 0x06

# Values used for Notification Set command
NOTIFICATION_SET_RESERVED_V9 = 0x00
NOTIFICATION_SET_SMOKE_V9 = 0x01
NOTIFICATION_SET_CO_V9 = 0x02
NOTIFICATION_SET_CO2_V9 = 0x03
NOTIFICATION_SET_HEAT_V9 = 0x04
NOTIFICATION_SET_WATER_V9 = 0x05
NOTIFICATION_SET_ACCESS_CONTROL_V9 = 0x06
NOTIFICATION_SET_HOME_SECURITY_V9 = 0x07
NOTIFICATION_SET_POWER_MANAGEMENT_V9 = 0x08
NOTIFICATION_SET_SYSTEM_V9 = 0x09
NOTIFICATION_SET_EMERGENCY_V9 = 0x0A
NOTIFICATION_SET_CLOCK_V9 = 0x0B
NOTIFICATION_SET_APPLIANCE_V9 = 0x0C
NOTIFICATION_SET_HOME_HEALTH_V9 = 0x0D
NOTIFICATION_SET_SIREN_V9 = 0x0E
NOTIFICATION_SET_WATER_VALVE_V9 = 0x0F
NOTIFICATION_SET_WEATHER_ALARM_V9 = 0x10
NOTIFICATION_SET_IRRIGATION_V9 = 0x11
NOTIFICATION_SET_GAS_ALARM_V9 = 0x12
NOTIFICATION_SET_PEST_CONTROL_V9 = 0x13
NOTIFICATION_SET_LIGHT_SENSOR_V9 = 0x14
NOTIFICATION_SET_WATER_QUALITY_MONITORING_V9 = 0x15
NOTIFICATION_SET_HOME_MONITORING_V9 = 0x16
NOTIFICATION_SET_FIRST_V9 = 0xFF
NOTIFICATION_SET_OFF_V9 = 0x00
NOTIFICATION_SET_NO_PENDING_NOTIFICATIONS_V9 = 0xFE
NOTIFICATION_SET_ON_V9 = 0xFF


NOTIFICATION_SUPPORTED_GET_V9 = 0x07


NOTIFICATION_SUPPORTED_REPORT_V9 = 0x08

# Values used for Notification Supported Report command
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V9 = 0x1F
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V9 = 0x60
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V9 = 0x05
NOTIFICATION_SUPPORTED_REPORT_PROPERTIES1_V1_ALARM_BIT_MASK_V9 = 0x80


EVENT_SUPPORTED_GET_V9 = 0x01
# Values used for Event Supported Get command
EVENT_SUPPORTED_GET_RESERVED_V9 = 0x00
EVENT_SUPPORTED_GET_SMOKE_V9 = 0x01
EVENT_SUPPORTED_GET_CO_V9 = 0x02
EVENT_SUPPORTED_GET_CO2_V9 = 0x03
EVENT_SUPPORTED_GET_HEAT_V9 = 0x04
EVENT_SUPPORTED_GET_WATER_V9 = 0x05
EVENT_SUPPORTED_GET_ACCESS_CONTROL_V9 = 0x06
EVENT_SUPPORTED_GET_HOME_SECURITY_V9 = 0x07
EVENT_SUPPORTED_GET_POWER_MANAGEMENT_V9 = 0x08
EVENT_SUPPORTED_GET_SYSTEM_V9 = 0x09
EVENT_SUPPORTED_GET_EMERGENCY_V9 = 0x0A
EVENT_SUPPORTED_GET_CLOCK_V9 = 0x0B
EVENT_SUPPORTED_GET_APPLIANCE_V9 = 0x0C
EVENT_SUPPORTED_GET_HOME_HEALTH_V9 = 0x0D
EVENT_SUPPORTED_GET_SIREN_V9 = 0x0E
EVENT_SUPPORTED_GET_WATER_VALVE_V9 = 0x0F
EVENT_SUPPORTED_GET_WEATHER_ALARM_V9 = 0x10
EVENT_SUPPORTED_GET_IRRIGATION_V9 = 0x11
EVENT_SUPPORTED_GET_GAS_ALARM_V9 = 0x12
EVENT_SUPPORTED_GET_PEST_CONTROL_V9 = 0x13
EVENT_SUPPORTED_GET_LIGHT_SENSOR_V9 = 0x14
EVENT_SUPPORTED_GET_WATER_QUALITY_MONITORING_V9 = 0x15
EVENT_SUPPORTED_GET_HOME_MONITORING_V9 = 0x16
EVENT_SUPPORTED_GET_FIRST_V9 = 0xFF


EVENT_SUPPORTED_REPORT_V9 = 0x02
# Values used for Event Supported Report command
EVENT_SUPPORTED_REPORT_RESERVED_V9 = 0x00
EVENT_SUPPORTED_REPORT_SMOKE_V9 = 0x01
EVENT_SUPPORTED_REPORT_CO_V9 = 0x02
EVENT_SUPPORTED_REPORT_CO2_V9 = 0x03
EVENT_SUPPORTED_REPORT_HEAT_V9 = 0x04
EVENT_SUPPORTED_REPORT_WATER_V9 = 0x05
EVENT_SUPPORTED_REPORT_ACCESS_CONTROL_V9 = 0x06
EVENT_SUPPORTED_REPORT_HOME_SECURITY_V9 = 0x07
EVENT_SUPPORTED_REPORT_POWER_MANAGEMENT_V9 = 0x08
EVENT_SUPPORTED_REPORT_SYSTEM_V9 = 0x09
EVENT_SUPPORTED_REPORT_EMERGENCY_V9 = 0x0A
EVENT_SUPPORTED_REPORT_CLOCK_V9 = 0x0B
EVENT_SUPPORTED_REPORT_APPLIANCE_V9 = 0x0C
EVENT_SUPPORTED_REPORT_HOME_HEALTH_V9 = 0x0D
EVENT_SUPPORTED_REPORT_SIREN_V9 = 0x0E
EVENT_SUPPORTED_REPORT_WATER_VALVE_V9 = 0x0F
EVENT_SUPPORTED_REPORT_WEATHER_ALARM_V9 = 0x10
EVENT_SUPPORTED_REPORT_IRRIGATION_V9 = 0x11
EVENT_SUPPORTED_REPORT_GAS_ALARM_V9 = 0x12
EVENT_SUPPORTED_REPORT_PEST_CONTROL_V9 = 0x13
EVENT_SUPPORTED_REPORT_LIGHT_SENSOR_V9 = 0x14
EVENT_SUPPORTED_REPORT_WATER_QUALITY_MONITORING_V9 = 0x15
EVENT_SUPPORTED_REPORT_HOME_MONITORING_V9 = 0x16
EVENT_SUPPORTED_REPORT_FIRST_V9 = 0xFF
EVENT_SUPPORTED_REPORT_PROPERTIES1_NUMBER_OF_BIT_MASKS_MASK_V9 = 0x1F
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_MASK_V9 = 0xE0
EVENT_SUPPORTED_REPORT_PROPERTIES1_RESERVED_SHIFT_V9 = 0x05


class ZW_NOTIFICATION_GET_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('v1AlarmType', uint8_t),
        ('notificationType', uint8_t),
        ('mevent', uint8_t),
    ]


class ZW_NOTIFICATION_GET_V4_FRAME(ZW_NOTIFICATION_GET_V3_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_GET_V5_FRAME(ZW_NOTIFICATION_GET_V4_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_GET_V6_FRAME(ZW_NOTIFICATION_GET_V5_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_GET_V7_FRAME(ZW_NOTIFICATION_GET_V6_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_GET_V8_FRAME(ZW_NOTIFICATION_GET_V7_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_GET_V9_FRAME(ZW_NOTIFICATION_GET_V8_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_REPORT_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('v1AlarmType', uint8_t),
        ('v1AlarmLevel', uint8_t),
        ('reserved', uint8_t),
        ('notificationStatus', uint8_t),
        ('notificationType', uint8_t),
        ('mevent', uint8_t),
        ('properties1', uint8_t),
        ('eventParameter1', uint8_t),
        ('sequenceNumber', uint8_t),
    ]


class ZW_NOTIFICATION_REPORT_V4_FRAME(ZW_NOTIFICATION_REPORT_V3_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_REPORT_V5_FRAME(ZW_NOTIFICATION_REPORT_V4_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_REPORT_V6_FRAME(ZW_NOTIFICATION_REPORT_V5_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_REPORT_V7_FRAME(ZW_NOTIFICATION_REPORT_V6_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_REPORT_V8_FRAME(ZW_NOTIFICATION_REPORT_V7_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_REPORT_V9_FRAME(ZW_NOTIFICATION_REPORT_V8_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_SET_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('notificationType', uint8_t),
        ('notificationStatus', uint8_t),
    ]


class ZW_NOTIFICATION_SET_V4_FRAME(ZW_NOTIFICATION_SET_V3_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_SET_V5_FRAME(ZW_NOTIFICATION_SET_V4_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_SET_V6_FRAME(ZW_NOTIFICATION_SET_V5_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_SET_V7_FRAME(ZW_NOTIFICATION_SET_V6_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_SET_V8_FRAME(ZW_NOTIFICATION_SET_V7_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_SET_V9_FRAME(ZW_NOTIFICATION_SET_V8_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_SUPPORTED_GET_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_NOTIFICATION_SUPPORTED_GET_V4_FRAME(
    ZW_NOTIFICATION_SUPPORTED_GET_V3_FRAME
    ):
    _fields_ = []


class ZW_NOTIFICATION_SUPPORTED_GET_V5_FRAME(
    ZW_NOTIFICATION_SUPPORTED_GET_V4_FRAME
    ):
    _fields_ = []


class ZW_NOTIFICATION_SUPPORTED_GET_V6_FRAME(
    ZW_NOTIFICATION_SUPPORTED_GET_V5_FRAME
    ):
    _fields_ = []


class ZW_NOTIFICATION_SUPPORTED_GET_V7_FRAME(
    ZW_NOTIFICATION_SUPPORTED_GET_V6_FRAME
    ):
    _fields_ = []


class ZW_NOTIFICATION_SUPPORTED_GET_V8_FRAME(
    ZW_NOTIFICATION_SUPPORTED_GET_V7_FRAME
    ):
    _fields_ = []


class ZW_NOTIFICATION_SUPPORTED_GET_V9_FRAME(
    ZW_NOTIFICATION_SUPPORTED_GET_V8_FRAME
    ):
    _fields_ = []


class ZW_NOTIFICATION_SUPPORTED_REPORT_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('bitMask1', uint8_t),
    ]


class ZW_NOTIFICATION_SUPPORTED_REPORT_V4_FRAME(
    ZW_NOTIFICATION_SUPPORTED_REPORT_V3_FRAME
    ):
    _fields_ = []


class ZW_NOTIFICATION_SUPPORTED_REPORT_V5_FRAME(
    ZW_NOTIFICATION_SUPPORTED_REPORT_V4_FRAME
    ):
    _fields_ = []


class ZW_NOTIFICATION_SUPPORTED_REPORT_V6_FRAME(
    ZW_NOTIFICATION_SUPPORTED_REPORT_V5_FRAME
    ):
    _fields_ = []


class ZW_NOTIFICATION_SUPPORTED_REPORT_V7_FRAME(
    ZW_NOTIFICATION_SUPPORTED_REPORT_V6_FRAME
    ):
    _fields_ = []


class ZW_NOTIFICATION_SUPPORTED_REPORT_V8_FRAME(
    ZW_NOTIFICATION_SUPPORTED_REPORT_V7_FRAME
    ):
    _fields_ = []


class ZW_NOTIFICATION_SUPPORTED_REPORT_V9_FRAME(
    ZW_NOTIFICATION_SUPPORTED_REPORT_V8_FRAME
    ):
    _fields_ = []


class ZW_EVENT_SUPPORTED_GET_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('notificationType', uint8_t)]


class ZW_EVENT_SUPPORTED_GET_V4_FRAME(ZW_EVENT_SUPPORTED_GET_V3_FRAME):
    _fields_ = []


class ZW_EVENT_SUPPORTED_GET_V5_FRAME(ZW_EVENT_SUPPORTED_GET_V4_FRAME):
    _fields_ = []


class ZW_EVENT_SUPPORTED_GET_V6_FRAME(ZW_EVENT_SUPPORTED_GET_V5_FRAME):
    _fields_ = []


class ZW_EVENT_SUPPORTED_GET_V7_FRAME(ZW_EVENT_SUPPORTED_GET_V6_FRAME):
    _fields_ = []


class ZW_EVENT_SUPPORTED_GET_V8_FRAME(ZW_EVENT_SUPPORTED_GET_V7_FRAME):
    _fields_ = []


class ZW_EVENT_SUPPORTED_GET_V9_FRAME(ZW_EVENT_SUPPORTED_GET_V8_FRAME):
    _fields_ = []


class ZW_EVENT_SUPPORTED_REPORT_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('notificationType', uint8_t),
        ('properties1', uint8_t),
        ('bitMask1', uint8_t),
    ]


class ZW_EVENT_SUPPORTED_REPORT_V4_FRAME(ZW_EVENT_SUPPORTED_REPORT_V3_FRAME):
    _fields_ = []


class ZW_EVENT_SUPPORTED_REPORT_V5_FRAME(ZW_EVENT_SUPPORTED_REPORT_V4_FRAME):
    _fields_ = []


class ZW_EVENT_SUPPORTED_REPORT_V6_FRAME(ZW_EVENT_SUPPORTED_REPORT_V5_FRAME):
    _fields_ = []


class ZW_EVENT_SUPPORTED_REPORT_V7_FRAME(ZW_EVENT_SUPPORTED_REPORT_V6_FRAME):
    _fields_ = []


class ZW_EVENT_SUPPORTED_REPORT_V8_FRAME(ZW_EVENT_SUPPORTED_REPORT_V7_FRAME):
    _fields_ = []


class ZW_EVENT_SUPPORTED_REPORT_V9_FRAME(ZW_EVENT_SUPPORTED_REPORT_V8_FRAME):
    _fields_ = []


