# Powerlevel Command Class
# Network-Protocol
# ==============================
COMMAND_CLASS_POWERLEVEL = 0x73

POWERLEVEL_VERSION = 0x01
# Powerlevel Set
POWERLEVEL_SET = 0x01
# Powerlevel Get
POWERLEVEL_GET = 0x02
# Powerlevel Report
POWERLEVEL_REPORT = 0x03
# Powerlevel Test Node Set
POWERLEVEL_TEST_NODE_SET = 0x04
# Powerlevel Test Node Get
POWERLEVEL_TEST_NODE_GET = 0x05
# Powerlevel Test Node Report
POWERLEVEL_TEST_NODE_REPORT = 0x06

# Values used for Powerlevel Report command
POWERLEVEL_REPORT_NORMALPOWER = 0x00
POWERLEVEL_REPORT_MINUS1DBM = 0x01
POWERLEVEL_REPORT_MINUS2DBM = 0x02
POWERLEVEL_REPORT_MINUS3DBM = 0x03
POWERLEVEL_REPORT_MINUS4DBM = 0x04
POWERLEVEL_REPORT_MINUS5DBM = 0x05
POWERLEVEL_REPORT_MINUS6DBM = 0x06
POWERLEVEL_REPORT_MINUS7DBM = 0x07
POWERLEVEL_REPORT_MINUS8DBM = 0x08
POWERLEVEL_REPORT_MINUS9DBM = 0x09
# Values used for Powerlevel Set command
POWERLEVEL_SET_NORMALPOWER = 0x00
POWERLEVEL_SET_MINUS1DBM = 0x01
POWERLEVEL_SET_MINUS2DBM = 0x02
POWERLEVEL_SET_MINUS3DBM = 0x03
POWERLEVEL_SET_MINUS4DBM = 0x04
POWERLEVEL_SET_MINUS5DBM = 0x05
POWERLEVEL_SET_MINUS6DBM = 0x06
POWERLEVEL_SET_MINUS7DBM = 0x07
POWERLEVEL_SET_MINUS8DBM = 0x08
POWERLEVEL_SET_MINUS9DBM = 0x09
# Values used for Powerlevel Test Node Report command
POWERLEVEL_TEST_NODE_REPORT_ZW_TEST_NOT_A_NODEID = 0x00
POWERLEVEL_TEST_NODE_REPORT_ZW_TEST_FAILED = 0x00
POWERLEVEL_TEST_NODE_REPORT_ZW_TEST_SUCCES = 0x01
POWERLEVEL_TEST_NODE_REPORT_ZW_TEST_INPROGRESS = 0x02
# Values used for Powerlevel Test Node Set command
POWERLEVEL_TEST_NODE_SET_NORMALPOWER = 0x00
POWERLEVEL_TEST_NODE_SET_MINUS1DBM = 0x01
POWERLEVEL_TEST_NODE_SET_MINUS2DBM = 0x02
POWERLEVEL_TEST_NODE_SET_MINUS3DBM = 0x03
POWERLEVEL_TEST_NODE_SET_MINUS4DBM = 0x04
POWERLEVEL_TEST_NODE_SET_MINUS5DBM = 0x05
POWERLEVEL_TEST_NODE_SET_MINUS6DBM = 0x06
POWERLEVEL_TEST_NODE_SET_MINUS7DBM = 0x07
POWERLEVEL_TEST_NODE_SET_MINUS8DBM = 0x08
POWERLEVEL_TEST_NODE_SET_MINUS9DBM = 0x09


class ZW_POWERLEVEL_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_POWERLEVEL_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('powerLevel', uint8_t),
        ('timeout', uint8_t),
    ]


class ZW_POWERLEVEL_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('powerLevel', uint8_t),
        ('timeout', uint8_t),
    ]


class ZW_POWERLEVEL_TEST_NODE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_POWERLEVEL_TEST_NODE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('testNodeid', uint8_t),
        ('statusOfOperation', uint8_t),
        ('testFrameCount1', uint8_t),
        ('testFrameCount2', uint8_t),
    ]


class ZW_POWERLEVEL_TEST_NODE_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('testNodeid', uint8_t),
        ('powerLevel', uint8_t),
        ('testFrameCount1', uint8_t),
        ('testFrameCount2', uint8_t),
    ]

