# Screen Meta Data Command Class
# Application
# ==============================
COMMAND_CLASS_SCREEN_MD = 0x92

SCREEN_MD_VERSION = 0x01
# Screen Meta Data Get
SCREEN_MD_GET = 0x01
# Screen Meta Data Report
SCREEN_MD_REPORT = 0x02

# Values used for Screen Md Report command
SCREEN_MD_REPORT_PROPERTIES1_CHAR_PRESENTATION_MASK = 0x07
SCREEN_MD_REPORT_PROPERTIES1_SCREEN_SETTINGS_MASK = 0x38
SCREEN_MD_REPORT_PROPERTIES1_SCREEN_SETTINGS_SHIFT = 0x03
SCREEN_MD_REPORT_PROPERTIES1_RESERVED_BIT_MASK = 0x40
SCREEN_MD_REPORT_PROPERTIES1_MORE_DATA_BIT_MASK = 0x80

SCREEN_MD_VERSION_V2 = 0x02
SCREEN_MD_GET_V2 = 0x01
SCREEN_MD_REPORT_V2 = 0x02
SCREEN_MD_REPORT_LEGACY_V2 = 0x03
# Values used for Screen Md Report command
SCREEN_MD_REPORT_PROPERTIES1_CHAR_PRESENTATION_MASK_V2 = 0x07
SCREEN_MD_REPORT_PROPERTIES1_SCREEN_SETTINGS_MASK_V2 = 0x38
SCREEN_MD_REPORT_PROPERTIES1_SCREEN_SETTINGS_SHIFT_V2 = 0x03
SCREEN_MD_REPORT_PROPERTIES1_RESERVED1_BIT_MASK_V2 = 0x40
SCREEN_MD_REPORT_PROPERTIES1_MORE_DATA_BIT_MASK_V2 = 0x80
SCREEN_MD_REPORT_PROPERTIES2_SCREEN_TIMEOUT_BIT_MASK_V2 = 0x01
SCREEN_MD_REPORT_PROPERTIES2_RESERVED2_MASK_V2 = 0xFE
SCREEN_MD_REPORT_PROPERTIES2_RESERVED2_SHIFT_V2 = 0x01
# Values used for Screen Md Report Legacy command
SCREEN_MD_REPORT_LEGACY_PROPERTIES1_CHAR_PRESENTATION_MASK_V2 = 0x07
SCREEN_MD_REPORT_LEGACY_PROPERTIES1_SCREEN_SETTINGS_MASK_V2 = 0x38
SCREEN_MD_REPORT_LEGACY_PROPERTIES1_SCREEN_SETTINGS_SHIFT_V2 = 0x03
SCREEN_MD_REPORT_LEGACY_PROPERTIES1_RESERVED1_BIT_MASK_V2 = 0x40
SCREEN_MD_REPORT_LEGACY_PROPERTIES1_MORE_DATA_BIT_MASK_V2 = 0x80
SCREEN_MD_REPORT_LEGACY_PROPERTIES2_SCREEN_TIMEOUT_BIT_MASK_V2 = 0x01
SCREEN_MD_REPORT_LEGACY_PROPERTIES2_RESERVED2_MASK_V2 = 0xFE
SCREEN_MD_REPORT_LEGACY_PROPERTIES2_RESERVED2_SHIFT_V2 = 0x01


class ZW_SCREEN_MD_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('numberOfReports', uint8_t),
        ('nodeId', uint8_t),
    ]


class VG_SCREEN_MD_REPORT_VG(ctypes.Structure):
    _fields_ = [
        ('properties1', uint8_t),
        ('characterPosition', uint8_t),
        ('numberOfCharacters', uint8_t),
        ('character1', uint8_t),
    ]


class ZW_SCREEN_MD_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('variantgroup1', VG_SCREEN_MD_REPORT_VG),
    ]


class ZW_SCREEN_MD_GET_V2_FRAME(ZW_SCREEN_MD_GET_FRAME):
    _fields_ = []


class ZW_SCREEN_MD_REPORT_V2_FRAME(ZW_SCREEN_MD_REPORT_FRAME):
    _fields_ = [('properties2', uint8_t)]


class VG_SCREEN_MD_REPORT_LEGACY_V2_VG(ctypes.Structure):
    _fields_ = [
        ('properties1', uint8_t),
        ('characterPosition', uint8_t),
        ('numberOfCharacters', uint8_t),
        ('character1', uint8_t),
    ]


class ZW_SCREEN_MD_REPORT_LEGACY_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('variantgroup1', VG_SCREEN_MD_REPORT_LEGACY_V2_VG),
        ('properties2', uint8_t),
    ]
