COMMAND_CLASS_SECURITY_PANEL_MODE = 0x24

SECURITY_PANEL_MODE_VERSION = 0x01
SECURITY_PANEL_MODE_GET = 0x03
SECURITY_PANEL_MODE_REPORT = 0x04
SECURITY_PANEL_MODE_SET = 0x05
SECURITY_PANEL_MODE_SUPPORTED_GET = 0x01
SECURITY_PANEL_MODE_SUPPORTED_REPORT = 0x02

class ZW_SECURITY_PANEL_MODE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_SECURITY_PANEL_MODE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('mode', uint8_t)]


class ZW_SECURITY_PANEL_MODE_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('mode', uint8_t)]


class ZW_SECURITY_PANEL_MODE_SUPPORTED_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_SECURITY_PANEL_MODE_SUPPORTED_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('supportedModeBitMask1', uint8_t),
        ('supportedModeBitMask2', uint8_t),
    ]
