
COMMAND_CLASS_SECURITY_PANEL_ZONE = 0x2E

SECURITY_PANEL_ZONE_VERSION = 0x01
SECURITY_PANEL_ZONE_NUMBER_SUPPORTED_GET = 0x01
SECURITY_PANEL_ZONE_STATE_GET = 0x05
SECURITY_PANEL_ZONE_STATE_REPORT = 0x06
SECURITY_PANEL_ZONE_SUPPORTED_REPORT = 0x02
SECURITY_PANEL_ZONE_TYPE_GET = 0x03
SECURITY_PANEL_ZONE_TYPE_REPORT = 0x04
# Values used for Security Panel Zone Supported Report command
SECURITY_PANEL_ZONE_SUPPORTED_REPORT_PARAMETERS1_ZONES_SUPPORTED_MASK = 0x7F
SECURITY_PANEL_ZONE_SUPPORTED_REPORT_PARAMETERS1_ZM_BIT_MASK = 0x80


class ZW_SECURITY_PANEL_ZONE_NUMBER_SUPPORTED_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_SECURITY_PANEL_ZONE_STATE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('zoneNumber', uint8_t)]


class ZW_SECURITY_PANEL_ZONE_STATE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('zoneNumber', uint8_t),
        ('zoneState', uint8_t),
    ]


class ZW_SECURITY_PANEL_ZONE_SUPPORTED_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('parameters1', uint8_t)]


class ZW_SECURITY_PANEL_ZONE_TYPE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('zoneNumber', uint8_t)]


class ZW_SECURITY_PANEL_ZONE_TYPE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('zoneNumber', uint8_t),
        ('zoneType', uint8_t),
    ]

