# Sensor Configuration Command Class
# Application
# ==============================
COMMAND_CLASS_SENSOR_CONFIGURATION = 0x9E

SENSOR_CONFIGURATION_VERSION = 0x01
# Sensor Trigger Level Set
SENSOR_TRIGGER_LEVEL_SET = 0x01
# Sensor Trigger Level Get
SENSOR_TRIGGER_LEVEL_GET = 0x02
# Sensor Trigger Level Report
SENSOR_TRIGGER_LEVEL_REPORT = 0x03

# Values used for Sensor Trigger Level Report command
SENSOR_TRIGGER_LEVEL_REPORT_PROPERTIES1_SIZE_MASK = 0x07
SENSOR_TRIGGER_LEVEL_REPORT_PROPERTIES1_SCALE_MASK = 0x18
SENSOR_TRIGGER_LEVEL_REPORT_PROPERTIES1_SCALE_SHIFT = 0x03
SENSOR_TRIGGER_LEVEL_REPORT_PROPERTIES1_PRECISION_MASK = 0xE0
SENSOR_TRIGGER_LEVEL_REPORT_PROPERTIES1_PRECISION_SHIFT = 0x05
# Values used for Sensor Trigger Level Set command
SENSOR_TRIGGER_LEVEL_SET_PROPERTIES1_RESERVED_MASK = 0x3F
SENSOR_TRIGGER_LEVEL_SET_PROPERTIES1_CURRENT_BIT_MASK = 0x40
SENSOR_TRIGGER_LEVEL_SET_PROPERTIES1_DEFAULT_BIT_MASK = 0x80
SENSOR_TRIGGER_LEVEL_SET_PROPERTIES2_SIZE_MASK = 0x07
SENSOR_TRIGGER_LEVEL_SET_PROPERTIES2_SCALE_MASK = 0x18
SENSOR_TRIGGER_LEVEL_SET_PROPERTIES2_SCALE_SHIFT = 0x03
SENSOR_TRIGGER_LEVEL_SET_PROPERTIES2_PRECISION_MASK = 0xE0
SENSOR_TRIGGER_LEVEL_SET_PROPERTIES2_PRECISION_SHIFT = 0x05


class ZW_SENSOR_TRIGGER_LEVEL_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_SENSOR_TRIGGER_LEVEL_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('sensorType', uint8_t),
        ('properties1', uint8_t),
        ('triggerValue1', uint8_t),
    ]


class ZW_SENSOR_TRIGGER_LEVEL_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('sensorType', uint8_t),
        ('properties2', uint8_t),
        ('triggerValue1', uint8_t),
    ]

