# Simple AV Control Command Class
# Application
# ==============================
COMMAND_CLASS_SIMPLE_AV_CONTROL = 0x94

SIMPLE_AV_CONTROL_VERSION = 0x01
# Simple AV Control Set
SIMPLE_AV_CONTROL_SET = 0x01
# Simple AV Control Get
SIMPLE_AV_CONTROL_GET = 0x02
# Simple AV Control Report
SIMPLE_AV_CONTROL_REPORT = 0x03
# Simple AV Control Supported Get
SIMPLE_AV_CONTROL_SUPPORTED_GET = 0x04
# Simple AV Control Supported Report
SIMPLE_AV_CONTROL_SUPPORTED_REPORT = 0x05

# Values used for Simple Av Control Set command
SIMPLE_AV_CONTROL_SET_PROPERTIES1_KEY_ATTRIBUTES_MASK = 0x07
SIMPLE_AV_CONTROL_SET_PROPERTIES1_RESERVED_MASK = 0xF8
SIMPLE_AV_CONTROL_SET_PROPERTIES1_RESERVED_SHIFT = 0x03

SIMPLE_AV_CONTROL_VERSION_V2 = 0x02
SIMPLE_AV_CONTROL_GET_V2 = 0x02
SIMPLE_AV_CONTROL_REPORT_V2 = 0x03
SIMPLE_AV_CONTROL_SET_V2 = 0x01
SIMPLE_AV_CONTROL_SUPPORTED_GET_V2 = 0x04
SIMPLE_AV_CONTROL_SUPPORTED_REPORT_V2 = 0x05
# Values used for Simple Av Control Set command
SIMPLE_AV_CONTROL_SET_PROPERTIES1_KEY_ATTRIBUTES_MASK_V2 = 0x07
SIMPLE_AV_CONTROL_SET_PROPERTIES1_RESERVED_MASK_V2 = 0xF8
SIMPLE_AV_CONTROL_SET_PROPERTIES1_RESERVED_SHIFT_V2 = 0x03

SIMPLE_AV_CONTROL_VERSION_V3 = 0x03
SIMPLE_AV_CONTROL_GET_V3 = 0x02
SIMPLE_AV_CONTROL_REPORT_V3 = 0x03
SIMPLE_AV_CONTROL_SET_V3 = 0x01
SIMPLE_AV_CONTROL_SUPPORTED_GET_V3 = 0x04
SIMPLE_AV_CONTROL_SUPPORTED_REPORT_V3 = 0x05
# Values used for Simple Av Control Set command
SIMPLE_AV_CONTROL_SET_PROPERTIES1_KEY_ATTRIBUTES_MASK_V3 = 0x07
SIMPLE_AV_CONTROL_SET_PROPERTIES1_RESERVED_MASK_V3 = 0xF8
SIMPLE_AV_CONTROL_SET_PROPERTIES1_RESERVED_SHIFT_V3 = 0x03

SIMPLE_AV_CONTROL_VERSION_V4 = 0x04
SIMPLE_AV_CONTROL_GET_V4 = 0x02
SIMPLE_AV_CONTROL_REPORT_V4 = 0x03
SIMPLE_AV_CONTROL_SET_V4 = 0x01
SIMPLE_AV_CONTROL_SUPPORTED_GET_V4 = 0x04
SIMPLE_AV_CONTROL_SUPPORTED_REPORT_V4 = 0x05
# Values used for Simple Av Control Set command
SIMPLE_AV_CONTROL_SET_PROPERTIES1_KEY_ATTRIBUTES_MASK_V4 = 0x07
SIMPLE_AV_CONTROL_SET_PROPERTIES1_RESERVED_MASK_V4 = 0xF8
SIMPLE_AV_CONTROL_SET_PROPERTIES1_RESERVED_SHIFT_V4 = 0x03

class ZW_SIMPLE_AV_CONTROL_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_SIMPLE_AV_CONTROL_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('numberOfReports', uint8_t)]


class VG_SIMPLE_AV_CONTROL_SET_VG(ctypes.Structure):
    _fields_ = [
        ('command1', uint8_t),
        ('command2', uint8_t),
    ]


class ZW_SIMPLE_AV_CONTROL_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('sequenceNumber', uint8_t),
        ('properties1', uint8_t),
        ('reserved21', uint8_t),
        ('reserved22', uint8_t),
        ('variantgroup1', VG_SIMPLE_AV_CONTROL_SET_VG),
    ]


class ZW_SIMPLE_AV_CONTROL_SUPPORTED_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('reportNo', uint8_t)]


class ZW_SIMPLE_AV_CONTROL_SUPPORTED_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('reportNo', uint8_t),
        ('bitMask1', uint8_t),
    ]


class ZW_SIMPLE_AV_CONTROL_GET_V2_FRAME(ZW_SIMPLE_AV_CONTROL_GET_FRAME):
    _fields_ = []


class ZW_SIMPLE_AV_CONTROL_REPORT_V2_FRAME(ZW_SIMPLE_AV_CONTROL_REPORT_FRAME):
    _fields_ = []


class VG_SIMPLE_AV_CONTROL_SET_V2_VG(ctypes.Structure):
    _fields_ = [
        ('command1', uint8_t),
        ('command2', uint8_t),
    ]


class ZW_SIMPLE_AV_CONTROL_SET_V2_FRAME(ZW_SIMPLE_AV_CONTROL_SET_FRAME):
    _fields_ = []


class ZW_SIMPLE_AV_CONTROL_SUPPORTED_GET_V2_FRAME(ZW_SIMPLE_AV_CONTROL_SUPPORTED_GET_FRAME):
    _fields_ = []


class ZW_SIMPLE_AV_CONTROL_SUPPORTED_REPORT_V2_FRAME(ZW_SIMPLE_AV_CONTROL_SUPPORTED_REPORT_FRAME):
    _fields_ = []


class ZW_SIMPLE_AV_CONTROL_GET_V3_FRAME(ZW_SIMPLE_AV_CONTROL_GET_V2_FRAME):
    _fields_ = []


class ZW_SIMPLE_AV_CONTROL_REPORT_V3_FRAME(ZW_SIMPLE_AV_CONTROL_REPORT_V2_FRAME):
    _fields_ = []


class VG_SIMPLE_AV_CONTROL_SET_V3_VG(ctypes.Structure):
    _fields_ = [
        ('command1', uint8_t),
        ('command2', uint8_t),
    ]


class ZW_SIMPLE_AV_CONTROL_SET_V3_FRAME(ZW_SIMPLE_AV_CONTROL_SET_V2_FRAME):
    _fields_ = []


class ZW_SIMPLE_AV_CONTROL_SUPPORTED_GET_V3_FRAME(ZW_SIMPLE_AV_CONTROL_SUPPORTED_GET_V2_FRAME):
    _fields_ = []


class ZW_SIMPLE_AV_CONTROL_SUPPORTED_REPORT_V3_FRAME(ZW_SIMPLE_AV_CONTROL_SUPPORTED_REPORT_V2_FRAME):
    _fields_ = []


class ZW_SIMPLE_AV_CONTROL_GET_V4_FRAME(ZW_SIMPLE_AV_CONTROL_GET_V3_FRAME):
    _fields_ = []


class ZW_SIMPLE_AV_CONTROL_REPORT_V4_FRAME(ZW_SIMPLE_AV_CONTROL_REPORT_V3_FRAME):
    _fields_ = []


class VG_SIMPLE_AV_CONTROL_SET_V4_VG(ctypes.Structure):
    _fields_ = [
        ('command1', uint8_t),
        ('command2', uint8_t),
    ]


class ZW_SIMPLE_AV_CONTROL_SET_V4_FRAME(ZW_SIMPLE_AV_CONTROL_SET_V3_FRAME):
    _fields_ = []


class ZW_SIMPLE_AV_CONTROL_SUPPORTED_GET_V4_FRAME(ZW_SIMPLE_AV_CONTROL_SUPPORTED_GET_V3_FRAME):
    _fields_ = []


class ZW_SIMPLE_AV_CONTROL_SUPPORTED_REPORT_V4_FRAME(ZW_SIMPLE_AV_CONTROL_SUPPORTED_REPORT_V3_FRAME):
    _fields_ = []

