# All Switch Command Class
# Application
# ==============================
COMMAND_CLASS_SWITCH_ALL = 0x27

SWITCH_ALL_VERSION = 0x01
# All Switch Set
SWITCH_ALL_SET = 0x01
# All Switch Get
SWITCH_ALL_GET = 0x02
# All Switch Report
SWITCH_ALL_REPORT = 0x03
# All Switch On
SWITCH_ALL_ON = 0x04
# All Switch Off
SWITCH_ALL_OFF = 0x05

# Values used for Switch All Report command
SWITCH_ALL_REPORT_EXCLUDED_FROM_THE_ALL_ON_ALL_OFF_FUNCTIONALITY = 0x00
SWITCH_ALL_REPORT_EXCLUDED_FROM_THE_ALL_ON_FUNCTIONALITY_BUT_NOT_ALL_OFF = 0x01
SWITCH_ALL_REPORT_EXCLUDED_FROM_THE_ALL_OFF_FUNCTIONALITY_BUT_NOT_ALL_ON = 0x02
SWITCH_ALL_REPORT_INCLUDED_IN_THE_ALL_ON_ALL_OFF_FUNCTIONALITY = 0xFF
# Values used for Switch All Set command
SWITCH_ALL_SET_EXCLUDED_FROM_THE_ALL_ON_ALL_OFF_FUNCTIONALITY = 0x00
SWITCH_ALL_SET_EXCLUDED_FROM_THE_ALL_ON_FUNCTIONALITY_BUT_NOT_ALL_OFF = 0x01
SWITCH_ALL_SET_EXCLUDED_FROM_THE_ALL_OFF_FUNCTIONALITY_BUT_NOT_ALL_ON = 0x02
SWITCH_ALL_SET_INCLUDED_IN_THE_ALL_ON_ALL_OFF_FUNCTIONALITY = 0xFF

class ZW_SWITCH_ALL_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_SWITCH_ALL_OFF_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_SWITCH_ALL_ON_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_SWITCH_ALL_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('mode', uint8_t)]


class ZW_SWITCH_ALL_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('mode', uint8_t)]

