# Multilevel Switch Command Class
# Application
# ==============================
COMMAND_CLASS_SWITCH_MULTILEVEL = 0x26

SWITCH_MULTILEVEL_VERSION = 0x01
# Multilevel Switch Set
SWITCH_MULTILEVEL_SET = 0x01
# Multilevel Switch Get
SWITCH_MULTILEVEL_GET = 0x02
# Multilevel Switch Report
SWITCH_MULTILEVEL_REPORT = 0x03
# Multilevel Switch Start Level Change
SWITCH_MULTILEVEL_START_LEVEL_CHANGE = 0x04
# Multilevel Switch Stop Level Change
SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE = 0x05

# Values used for Switch Multilevel Start Level Change command
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_LEVEL_RESERVED1_MASK = 0x1F
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_LEVEL_IGNORE_START_LEVEL_BIT_MASK = 0x20
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_LEVEL_UP_DOWN_BIT_MASK = 0x40
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_LEVEL_RESERVED2_BIT_MASK = 0x80

SWITCH_MULTILEVEL_VERSION_V2 = 0x02
SWITCH_MULTILEVEL_GET_V2 = 0x02
SWITCH_MULTILEVEL_REPORT_V2 = 0x03
SWITCH_MULTILEVEL_SET_V2 = 0x01
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_V2 = 0x04
SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE_V2 = 0x05
# Values used for Switch Multilevel Start Level Change command
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_RESERVED1_MASK_V2 = 0x1F
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_IGNORE_START_LEVEL_BIT_MASK_V2 = 0x20
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_UP_DOWN_BIT_MASK_V2 = 0x40
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_RESERVED2_BIT_MASK_V2 = 0x80

SWITCH_MULTILEVEL_VERSION_V3 = 0x03
SWITCH_MULTILEVEL_GET_V3 = 0x02
SWITCH_MULTILEVEL_REPORT_V3 = 0x03
SWITCH_MULTILEVEL_SET_V3 = 0x01
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_V3 = 0x04
SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE_V3 = 0x05
# Multilevel Switch Supported Get
SWITCH_MULTILEVEL_SUPPORTED_GET_V3 = 0x06
# Multilevel Switch Supported Report
SWITCH_MULTILEVEL_SUPPORTED_REPORT_V3 = 0x07

# Values used for Switch Multilevel Start Level Change command
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_RESERVED_MASK_V3 = 0x07
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_INC_DEC_MASK_V3 = 0x18
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_INC_DEC_SHIFT_V3 = 0x03
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_INC_DEC_INCREMENT_V3 = 0x00
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_INC_DEC_DECREMENT_V3 = 0x01
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_INC_DEC_RESERVED_V3 = 0x02
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_INC_DEC_NONE_V3 = 0x03
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_IGNORE_START_LEVEL_BIT_MASK_V3 = 0x20
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_UP_DOWN_MASK_V3 = 0xC0
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_UP_DOWN_SHIFT_V3 = 0x06
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_UP_DOWN_UP_V3 = 0x00
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_UP_DOWN_DOWN_V3 = 0x01
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_UP_DOWN_RESERVED_V3 = 0x02
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_UP_DOWN_NONE_V3 = 0x03
# Values used for Switch Multilevel Supported Report command
SWITCH_MULTILEVEL_SUPPORTED_REPORT_PROPERTIES1_PRIMARY_SWITCH_TYPE_MASK_V3 = 0x1F
SWITCH_MULTILEVEL_SUPPORTED_REPORT_PROPERTIES1_RESERVED1_MASK_V3 = 0xE0
SWITCH_MULTILEVEL_SUPPORTED_REPORT_PROPERTIES1_RESERVED1_SHIFT_V3 = 0x05
SWITCH_MULTILEVEL_SUPPORTED_REPORT_PROPERTIES2_SECONDARY_SWITCH_TYPE_MASK_V3 = 0x1F
SWITCH_MULTILEVEL_SUPPORTED_REPORT_PROPERTIES2_RESERVED2_MASK_V3 = 0xE0
SWITCH_MULTILEVEL_SUPPORTED_REPORT_PROPERTIES2_RESERVED2_SHIFT_V3 = 0x05

SWITCH_MULTILEVEL_VERSION_V4 = 0x04
SWITCH_MULTILEVEL_GET_V4 = 0x02
SWITCH_MULTILEVEL_REPORT_V4 = 0x03
SWITCH_MULTILEVEL_SET_V4 = 0x01
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_V4 = 0x04
SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE_V4 = 0x05
SWITCH_MULTILEVEL_SUPPORTED_GET_V4 = 0x06
SWITCH_MULTILEVEL_SUPPORTED_REPORT_V4 = 0x07
# Values used for Switch Multilevel Report command
SWITCH_MULTILEVEL_REPORT_ALREADY_AT_THE_TARGET_VALUE_V4 = 0x00
SWITCH_MULTILEVEL_REPORT_UNKNOWN_DURATION_V4 = 0xFE
SWITCH_MULTILEVEL_REPORT_RESERVED_V4 = 0xFF
# Values used for Switch Multilevel Start Level Change command
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_RESERVED_MASK_V4 = 0x07
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_INC_DEC_MASK_V4 = 0x18
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_INC_DEC_SHIFT_V4 = 0x03
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_INC_DEC_INCREMENT_V4 = 0x00
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_INC_DEC_DECREMENT_V4 = 0x01
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_INC_DEC_RESERVED_V4 = 0x02
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_INC_DEC_NONE_V4 = 0x03
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_IGNORE_START_LEVEL_BIT_MASK_V4 = 0x20
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_UP_DOWN_MASK_V4 = 0xC0
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_PROPERTIES1_UP_DOWN_SHIFT_V4 = 0x06
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_UP_DOWN_UP_V4 = 0x00
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_UP_DOWN_DOWN_V4 = 0x01
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_UP_DOWN_RESERVED_V4 = 0x02
SWITCH_MULTILEVEL_START_LEVEL_CHANGE_UP_DOWN_NONE_V4 = 0x03
# Values used for Switch Multilevel Supported Report command
SWITCH_MULTILEVEL_SUPPORTED_REPORT_PROPERTIES1_PRIMARY_SWITCH_TYPE_MASK_V4 = 0x1F
SWITCH_MULTILEVEL_SUPPORTED_REPORT_PROPERTIES1_RESERVED1_MASK_V4 = 0xE0
SWITCH_MULTILEVEL_SUPPORTED_REPORT_PROPERTIES1_RESERVED1_SHIFT_V4 = 0x05
SWITCH_MULTILEVEL_SUPPORTED_REPORT_PROPERTIES2_SECONDARY_SWITCH_TYPE_MASK_V4 = 0x1F
SWITCH_MULTILEVEL_SUPPORTED_REPORT_PROPERTIES2_RESERVED2_MASK_V4 = 0xE0
SWITCH_MULTILEVEL_SUPPORTED_REPORT_PROPERTIES2_RESERVED2_SHIFT_V4 = 0x05


class ZW_SWITCH_MULTILEVEL_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('value', uint8_t)]


class ZW_SWITCH_MULTILEVEL_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('value', uint8_t)]


class ZW_SWITCH_MULTILEVEL_START_LEVEL_CHANGE_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('level', uint8_t),
        ('startLevel', uint8_t),
    ]


class ZW_SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_GET_V2_FRAME(ZW_SWITCH_MULTILEVEL_GET_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_REPORT_V2_FRAME(ZW_SWITCH_MULTILEVEL_REPORT_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_SET_V2_FRAME(ZW_SWITCH_MULTILEVEL_SET_FRAME):
    _fields_ = [('duration', uint8_t)]


class ZW_SWITCH_MULTILEVEL_START_LEVEL_CHANGE_V2_FRAME(ZW_SWITCH_MULTILEVEL_START_LEVEL_CHANGE_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('dimmingDuration', uint8_t),
    ]


class ZW_SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE_V2_FRAME(ZW_SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_GET_V3_FRAME(ZW_SWITCH_MULTILEVEL_GET_V2_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_REPORT_V3_FRAME(ZW_SWITCH_MULTILEVEL_REPORT_V2_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_SET_V3_FRAME(ZW_SWITCH_MULTILEVEL_SET_V2_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_START_LEVEL_CHANGE_V3_FRAME(ZW_SWITCH_MULTILEVEL_START_LEVEL_CHANGE_V2_FRAME):
    _fields_ = [('stepSize', uint8_t)]


class ZW_SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE_V3_FRAME(ZW_SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE_V2_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_SUPPORTED_GET_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_SUPPORTED_REPORT_V3_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('properties2', uint8_t),
    ]


class ZW_SWITCH_MULTILEVEL_GET_V4_FRAME(ZW_SWITCH_MULTILEVEL_GET_V3_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_REPORT_V4_FRAME(ZW_SWITCH_MULTILEVEL_REPORT_V3_FRAME):
    _fields_ = [
        ('currentValue', uint8_t),
        ('targetValue', uint8_t),
        ('duration', uint8_t),
    ]


class ZW_SWITCH_MULTILEVEL_SET_V4_FRAME(ZW_SWITCH_MULTILEVEL_SET_V3_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_START_LEVEL_CHANGE_V4_FRAME(ZW_SWITCH_MULTILEVEL_START_LEVEL_CHANGE_V3_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE_V4_FRAME(ZW_SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE_V3_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_SUPPORTED_GET_V4_FRAME(ZW_SWITCH_MULTILEVEL_SUPPORTED_GET_V3_FRAME):
    _fields_ = []


class ZW_SWITCH_MULTILEVEL_SUPPORTED_REPORT_V4_FRAME(ZW_SWITCH_MULTILEVEL_SUPPORTED_REPORT_V3_FRAME):
    _fields_ = []
