# Color Switch Command Class
# Application
# ==============================
COMMAND_CLASS_SWITCH_COLOR = 0x33

SWITCH_COLOR_VERSION = 0x01
# Color Switch Supported Get
SWITCH_COLOR_SUPPORTED_GET = 0x01
# Color Switch Supported Report
SWITCH_COLOR_SUPPORTED_REPORT = 0x02
# Color Switch Get
SWITCH_COLOR_GET = 0x03
# Color Switch Report
SWITCH_COLOR_REPORT = 0x04
# Color Switch Set
SWITCH_COLOR_SET = 0x05
# Color Switch Start Level Change
SWITCH_COLOR_START_LEVEL_CHANGE = 0x06
# Color Switch Stop Level Change
SWITCH_COLOR_STOP_LEVEL_CHANGE = 0x07

# Values used for Switch Color Set command
SWITCH_COLOR_SET_PROPERTIES1_COLOR_COMPONENT_COUNT_MASK = 0x1F
SWITCH_COLOR_SET_PROPERTIES1_RESERVED_MASK = 0xE0
SWITCH_COLOR_SET_PROPERTIES1_RESERVED_SHIFT = 0x05
# Values used for Switch Color Start Level Change command
SWITCH_COLOR_START_LEVEL_CHANGE_PROPERTIES1_RES1_MASK = 0x1F
SWITCH_COLOR_START_LEVEL_CHANGE_PROPERTIES1_IGNORE_START_STATE_BIT_MASK = 0x20
SWITCH_COLOR_START_LEVEL_CHANGE_PROPERTIES1_UP_DOWN_BIT_MASK = 0x40
SWITCH_COLOR_START_LEVEL_CHANGE_PROPERTIES1_RES2_BIT_MASK = 0x80

SWITCH_COLOR_VERSION_V2 = 0x02
SWITCH_COLOR_SUPPORTED_GET_V2 = 0x01
SWITCH_COLOR_SUPPORTED_REPORT_V2 = 0x02
SWITCH_COLOR_GET_V2 = 0x03
SWITCH_COLOR_REPORT_V2 = 0x04
SWITCH_COLOR_SET_V2 = 0x05
SWITCH_COLOR_START_LEVEL_CHANGE_V2 = 0x06
SWITCH_COLOR_STOP_LEVEL_CHANGE_V2 = 0x07
# Values used for Switch Color Set command
SWITCH_COLOR_SET_PROPERTIES1_COLOR_COMPONENT_COUNT_MASK_V2 = 0x1F
SWITCH_COLOR_SET_PROPERTIES1_RESERVED_MASK_V2 = 0xE0
SWITCH_COLOR_SET_PROPERTIES1_RESERVED_SHIFT_V2 = 0x05
# Values used for Switch Color Start Level Change command
SWITCH_COLOR_START_LEVEL_CHANGE_PROPERTIES1_RES1_MASK_V2 = 0x1F
SWITCH_COLOR_START_LEVEL_CHANGE_PROPERTIES1_IGNORE_START_STATE_BIT_MASK_V2 = 0x20
SWITCH_COLOR_START_LEVEL_CHANGE_PROPERTIES1_UP_DOWN_BIT_MASK_V2 = 0x40
SWITCH_COLOR_START_LEVEL_CHANGE_PROPERTIES1_RES2_BIT_MASK_V2 = 0x80

SWITCH_COLOR_VERSION_V3 = 0x03
SWITCH_COLOR_SUPPORTED_GET_V3 = 0x01
SWITCH_COLOR_SUPPORTED_REPORT_V3 = 0x02
SWITCH_COLOR_GET_V3 = 0x03
SWITCH_COLOR_REPORT_V3 = 0x04
SWITCH_COLOR_SET_V3 = 0x05
SWITCH_COLOR_START_LEVEL_CHANGE_V3 = 0x06
SWITCH_COLOR_STOP_LEVEL_CHANGE_V3 = 0x07
# Values used for Switch Color Set command
SWITCH_COLOR_SET_PROPERTIES1_COLOR_COMPONENT_COUNT_MASK_V3 = 0x1F
SWITCH_COLOR_SET_PROPERTIES1_RESERVED_MASK_V3 = 0xE0
SWITCH_COLOR_SET_PROPERTIES1_RESERVED_SHIFT_V3 = 0x05
# Values used for Switch Color Start Level Change command
SWITCH_COLOR_START_LEVEL_CHANGE_PROPERTIES1_RES1_MASK_V3 = 0x1F
SWITCH_COLOR_START_LEVEL_CHANGE_PROPERTIES1_IGNORE_START_STATE_BIT_MASK_V3 = 0x20
SWITCH_COLOR_START_LEVEL_CHANGE_PROPERTIES1_UP_DOWN_BIT_MASK_V3 = 0x40
SWITCH_COLOR_START_LEVEL_CHANGE_PROPERTIES1_RES2_BIT_MASK_V3 = 0x80


class ZW_SWITCH_COLOR_SUPPORTED_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_SWITCH_COLOR_SUPPORTED_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('colorComponentMask1', uint8_t),
        ('colorComponentMask2', uint8_t),
    ]


class ZW_SWITCH_COLOR_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('colorComponentId', uint8_t)]


class ZW_SWITCH_COLOR_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('colorComponentId', uint8_t),
        ('value', uint8_t),
    ]


class VG_SWITCH_COLOR_SET_VG(ctypes.Structure):
    _fields_ = [
        ('colorComponentId', uint8_t),
        ('value', uint8_t),
    ]


class ZW_SWITCH_COLOR_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('variantgroup1', VG_SWITCH_COLOR_SET_VG),
    ]


class ZW_SWITCH_COLOR_START_LEVEL_CHANGE_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('colorComponentId', uint8_t),
        ('startLevel', uint8_t),
    ]


class ZW_SWITCH_COLOR_STOP_LEVEL_CHANGE_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('colorComponentId', uint8_t)]


class ZW_SWITCH_COLOR_SUPPORTED_GET_V2_FRAME(ZW_SWITCH_COLOR_SUPPORTED_GET_FRAME):
    _fields_ = []


class ZW_SWITCH_COLOR_SUPPORTED_REPORT_V2_FRAME(ZW_SWITCH_COLOR_SUPPORTED_REPORT_FRAME):
    _fields_ = []


class ZW_SWITCH_COLOR_GET_V2_FRAME(ZW_SWITCH_COLOR_GET_FRAME):
    _fields_ = []


class ZW_SWITCH_COLOR_REPORT_V2_FRAME(ZW_SWITCH_COLOR_REPORT_FRAME):
    _fields_ = []


class VG_SWITCH_COLOR_SET_V2_VG(ctypes.Structure):
    _fields_ = [
        ('colorComponentId', uint8_t),
        ('value', uint8_t),
    ]


class ZW_SWITCH_COLOR_SET_V2_FRAME(ZW_SWITCH_COLOR_SET_FRAME):
    _fields_ = [('duration', uint8_t)]


class ZW_SWITCH_COLOR_START_LEVEL_CHANGE_V2_FRAME(ZW_SWITCH_COLOR_START_LEVEL_CHANGE_FRAME):
    _fields_ = []


class ZW_SWITCH_COLOR_STOP_LEVEL_CHANGE_V2_FRAME(ZW_SWITCH_COLOR_STOP_LEVEL_CHANGE_FRAME):
    _fields_ = []


class ZW_SWITCH_COLOR_SUPPORTED_GET_V3_FRAME(ZW_SWITCH_COLOR_SUPPORTED_GET_V2_FRAME):
    _fields_ = []


class ZW_SWITCH_COLOR_SUPPORTED_REPORT_V3_FRAME(ZW_SWITCH_COLOR_SUPPORTED_REPORT_V2_FRAME):
    _fields_ = []


class ZW_SWITCH_COLOR_GET_V3_FRAME(ZW_SWITCH_COLOR_GET_V2_FRAME):
    _fields_ = []


class ZW_SWITCH_COLOR_REPORT_V3_FRAME(ZW_SWITCH_COLOR_REPORT_V2_FRAME):
    _fields_ = [
        ('currentValue', uint8_t),
        ('targetValue', uint8_t),
        ('duration', uint8_t),
    ]


class VG_SWITCH_COLOR_SET_V3_VG(ctypes.Structure):
    _fields_ = [
        ('colorComponentId', uint8_t),
        ('value', uint8_t),
    ]


class ZW_SWITCH_COLOR_SET_V3_FRAME(ZW_SWITCH_COLOR_SET_V2_FRAME):
    _fields_ = []


class ZW_SWITCH_COLOR_START_LEVEL_CHANGE_V3_FRAME(ZW_SWITCH_COLOR_START_LEVEL_CHANGE_V2_FRAME):
    _fields_ = [('duration', uint8_t)]


class ZW_SWITCH_COLOR_STOP_LEVEL_CHANGE_V3_FRAME(ZW_SWITCH_COLOR_STOP_LEVEL_CHANGE_V2_FRAME):
    _fields_ = []

