# Thermostat Operating State Command Class
# Application
# ==============================
COMMAND_CLASS_THERMOSTAT_OPERATING_STATE = 0x42

THERMOSTAT_OPERATING_STATE_VERSION = 0x01
# Thermostat Operating State Get
THERMOSTAT_OPERATING_STATE_GET = 0x02
# Thermostat Operating State Report
THERMOSTAT_OPERATING_STATE_REPORT = 0x03

# Values used for Thermostat Operating State Report command
THERMOSTAT_OPERATING_STATE_REPORT_LEVEL_OPERATING_STATE_MASK = 0x0F
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_IDLE = 0x00
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_HEATING = 0x01
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_COOLING = 0x02
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_FAN_ONLY = 0x03
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_PENDING_HEAT = 0x04
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_PENDING_COOL = 0x05
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_VENT_ECONOMIZER = 0x06
THERMOSTAT_OPERATING_STATE_REPORT_LEVEL_RESERVED_MASK = 0xF0
THERMOSTAT_OPERATING_STATE_REPORT_LEVEL_RESERVED_SHIFT = 0x04

THERMOSTAT_OPERATING_STATE_VERSION_V2 = 0x02
THERMOSTAT_OPERATING_STATE_GET_V2 = 0x02
THERMOSTAT_OPERATING_STATE_REPORT_V2 = 0x03
# Thermostat Operating State Logging Supported Get
THERMOSTAT_OPERATING_STATE_LOGGING_SUPPORTED_GET_V2 = 0x01
# Thermostat Operating State Logging Supported Report
THERMOSTAT_OPERATING_LOGGING_SUPPORTED_REPORT_V2 = 0x04
# Thermostat Operating State Logging Get
THERMOSTAT_OPERATING_STATE_LOGGING_GET_V2 = 0x05
# Thermostat Operating State Logging Report
THERMOSTAT_OPERATING_STATE_LOGGING_REPORT_V2 = 0x06

# Values used for Thermostat Operating State Report command
THERMOSTAT_OPERATING_STATE_REPORT_PROPERTIES1_OPERATING_STATE_MASK_V2 = 0x0F
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_IDLE_V2 = 0x00
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_HEATING_V2 = 0x01
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_COOLING_V2 = 0x02
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_FAN_ONLY_V2 = 0x03
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_PENDING_HEAT_V2 = 0x04
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_PENDING_COOL_V2 = 0x05
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_VENT_ECONOMIZER_V2 = 0x06
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_AUX_HEATING_V2 = 0x07
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_2ND_STAGE_HEATING_V2 = 0x08
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_2ND_STAGE_COOLING_V2 = 0x09
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_2ND_STAGE_AUX_HEAT_V2 = 0x0A
THERMOSTAT_OPERATING_STATE_REPORT_OPERATING_STATE_3RD_STAGE_AUX_HEAT_V2 = 0x0B
THERMOSTAT_OPERATING_STATE_REPORT_PROPERTIES1_RESERVED_MASK_V2 = 0xF0
THERMOSTAT_OPERATING_STATE_REPORT_PROPERTIES1_RESERVED_SHIFT_V2 = 0x04

class ZW_THERMOSTAT_OPERATING_STATE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_THERMOSTAT_OPERATING_STATE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('level', uint8_t)]


class ZW_THERMOSTAT_OPERATING_STATE_GET_V2_FRAME(ZW_THERMOSTAT_OPERATING_STATE_GET_FRAME):
    _fields_ = []


class ZW_THERMOSTAT_OPERATING_STATE_REPORT_V2_FRAME(ZW_THERMOSTAT_OPERATING_STATE_REPORT_FRAME):
    _fields_ = [('properties1', uint8_t)]


class ZW_THERMOSTAT_OPERATING_STATE_LOGGING_SUPPORTED_GET_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_THERMOSTAT_OPERATING_LOGGING_SUPPORTED_REPORT_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('bitMask1', uint8_t)]


class ZW_THERMOSTAT_OPERATING_STATE_LOGGING_GET_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('bitMask1', uint8_t)]


class VG_THERMOSTAT_OPERATING_STATE_LOGGING_REPORT_V2_VG(ctypes.Structure):
    _fields_ = [
        ('properties1', uint8_t),
        ('usageTodayHours', uint8_t),
        ('usageTodayMinutes', uint8_t),
        ('usageYesterdayHours', uint8_t),
        ('usageYesterdayMinutes', uint8_t),
    ]


class ZW_THERMOSTAT_OPERATING_STATE_LOGGING_REPORT_V2_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('reportsToFollow', uint8_t),
        ('variantgroup1', VG_THERMOSTAT_OPERATING_STATE_LOGGING_REPORT_V2_VG),
    ]
