# Thermostat Setback Command Class
# Application
# ==============================
COMMAND_CLASS_THERMOSTAT_SETBACK = 0x47

THERMOSTAT_SETBACK_VERSION = 0x01
# Thermostat Setback Set
THERMOSTAT_SETBACK_SET = 0x01
# Thermostat Setback Get
THERMOSTAT_SETBACK_GET = 0x02
# Thermostat Setback Report
THERMOSTAT_SETBACK_REPORT = 0x03

# Values used for Thermostat Setback Report command
THERMOSTAT_SETBACK_REPORT_PROPERTIES1_SETBACK_TYPE_MASK = 0x03
THERMOSTAT_SETBACK_REPORT_SETBACK_TYPE_NO_OVERRIDE = 0x00
THERMOSTAT_SETBACK_REPORT_SETBACK_TYPE_TEMPORARY_OVERRIDE = 0x01
THERMOSTAT_SETBACK_REPORT_SETBACK_TYPE_PERMANENT_OVERRIDE = 0x02
THERMOSTAT_SETBACK_REPORT_SETBACK_TYPE_RESERVED = 0x03
THERMOSTAT_SETBACK_REPORT_PROPERTIES1_RESERVED_MASK = 0xFC
THERMOSTAT_SETBACK_REPORT_PROPERTIES1_RESERVED_SHIFT = 0x02
# Values used for Thermostat Setback Set command
THERMOSTAT_SETBACK_SET_PROPERTIES1_SETBACK_TYPE_MASK = 0x03
THERMOSTAT_SETBACK_SET_SETBACK_TYPE_NO_OVERRIDE = 0x00
THERMOSTAT_SETBACK_SET_SETBACK_TYPE_TEMPORARY_OVERRIDE = 0x01
THERMOSTAT_SETBACK_SET_SETBACK_TYPE_PERMANENT_OVERRIDE = 0x02
THERMOSTAT_SETBACK_SET_SETBACK_TYPE_RESERVED = 0x03
THERMOSTAT_SETBACK_SET_PROPERTIES1_RESERVED_MASK = 0xFC
THERMOSTAT_SETBACK_SET_PROPERTIES1_RESERVED_SHIFT = 0x02


class ZW_THERMOSTAT_SETBACK_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_THERMOSTAT_SETBACK_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('setbackState', uint8_t),
    ]


class ZW_THERMOSTAT_SETBACK_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('setbackState', uint8_t),
    ]
