
COMMAND_CLASS_THERMOSTAT_HEATING = 0x38


THERMOSTAT_HEATING_VERSION = 0x01
THERMOSTAT_HEATING_STATUS_REPORT = 0x0D
THERMOSTAT_HEATING_MODE_GET = 0x02
THERMOSTAT_HEATING_MODE_REPORT = 0x03
THERMOSTAT_HEATING_MODE_SET = 0x01
THERMOSTAT_HEATING_RELAY_STATUS_GET = 0x09
THERMOSTAT_HEATING_RELAY_STATUS_REPORT = 0x0A
THERMOSTAT_HEATING_SETPOINT_GET = 0x05
THERMOSTAT_HEATING_SETPOINT_REPORT = 0x06
THERMOSTAT_HEATING_SETPOINT_SET = 0x04
THERMOSTAT_HEATING_STATUS_GET = 0x0C
THERMOSTAT_HEATING_STATUS_SET = 0x0B
THERMOSTAT_HEATING_TIMED_OFF_SET = 0x11
# Values used for Thermostat Heating Status Report command
THERMOSTAT_HEATING_STATUS_REPORT_HEATING = 0x00
THERMOSTAT_HEATING_STATUS_REPORT_COOLING = 0x01
# Values used for Thermostat Heating Mode Report command
THERMOSTAT_HEATING_MODE_REPORT_OFF = 0x00
THERMOSTAT_HEATING_MODE_REPORT_OFF_TIMED = 0x01
THERMOSTAT_HEATING_MODE_REPORT_OFF_3_HOURS = 0x02
THERMOSTAT_HEATING_MODE_REPORT_ANTI_FREEZE = 0x03
THERMOSTAT_HEATING_MODE_REPORT_MANUAL = 0x04
THERMOSTAT_HEATING_MODE_REPORT_TEMPORARY_MANUAL = 0x05
THERMOSTAT_HEATING_MODE_REPORT_AUTOMATIC = 0x06
THERMOSTAT_HEATING_MODE_REPORT_MANUAL_TIMED = 0x07
# Values used for Thermostat Heating Mode Set command
THERMOSTAT_HEATING_MODE_SET_OFF = 0x00
THERMOSTAT_HEATING_MODE_SET_OFF_TIMED = 0x01
THERMOSTAT_HEATING_MODE_SET_OFF_3_HOURS = 0x02
THERMOSTAT_HEATING_MODE_SET_ANTI_FREEZE = 0x03
THERMOSTAT_HEATING_MODE_SET_MANUAL = 0x04
THERMOSTAT_HEATING_MODE_SET_TEMPORARY_MANUAL = 0x05
THERMOSTAT_HEATING_MODE_SET_AUTOMATIC = 0x06
THERMOSTAT_HEATING_MODE_SET_MANUAL_TIMED = 0x07
# Values used for Thermostat Heating Relay Status Report command
THERMOSTAT_HEATING_RELAY_STATUS_REPORT_OFF = 0x00
THERMOSTAT_HEATING_RELAY_STATUS_REPORT_ON = 0x01
# Values used for Thermostat Heating Setpoint Report command
THERMOSTAT_HEATING_SETPOINT_REPORT_PROPERTIES1_SIZE_MASK = 0x07
THERMOSTAT_HEATING_SETPOINT_REPORT_PROPERTIES1_SCALE_MASK = 0x18
THERMOSTAT_HEATING_SETPOINT_REPORT_PROPERTIES1_SCALE_SHIFT = 0x03
THERMOSTAT_HEATING_SETPOINT_REPORT_PROPERTIES1_PRECISION_MASK = 0xE0
THERMOSTAT_HEATING_SETPOINT_REPORT_PROPERTIES1_PRECISION_SHIFT = 0x05
# Values used for Thermostat Heating Setpoint Set command
THERMOSTAT_HEATING_SETPOINT_SET_PROPERTIES1_SIZE_MASK = 0x07
THERMOSTAT_HEATING_SETPOINT_SET_PROPERTIES1_SCALE_MASK = 0x18
THERMOSTAT_HEATING_SETPOINT_SET_PROPERTIES1_SCALE_SHIFT = 0x03
THERMOSTAT_HEATING_SETPOINT_SET_PROPERTIES1_PRECISION_MASK = 0xE0
THERMOSTAT_HEATING_SETPOINT_SET_PROPERTIES1_PRECISION_SHIFT = 0x05
# Values used for Thermostat Heating Status Set command
THERMOSTAT_HEATING_STATUS_SET_HEATING = 0x00
THERMOSTAT_HEATING_STATUS_SET_COOLING = 0x01

class ZW_THERMOSTAT_HEATING_STATUS_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('status', uint8_t)]


class ZW_THERMOSTAT_HEATING_MODE_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_THERMOSTAT_HEATING_MODE_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('mode', uint8_t)]


class ZW_THERMOSTAT_HEATING_MODE_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('mode', uint8_t)]


class ZW_THERMOSTAT_HEATING_RELAY_STATUS_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_THERMOSTAT_HEATING_RELAY_STATUS_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('relayStatus', uint8_t)]


class ZW_THERMOSTAT_HEATING_SETPOINT_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('setpointNr', uint8_t)]


class ZW_THERMOSTAT_HEATING_SETPOINT_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('setpointNr', uint8_t),
        ('properties1', uint8_t),
        ('value1', uint8_t),
    ]


class ZW_THERMOSTAT_HEATING_SETPOINT_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('setpointNr', uint8_t),
        ('properties1', uint8_t),
        ('value1', uint8_t),
    ]


class ZW_THERMOSTAT_HEATING_STATUS_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_THERMOSTAT_HEATING_STATUS_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('status', uint8_t)]


class ZW_THERMOSTAT_HEATING_TIMED_OFF_SET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('minutes', uint8_t),
        ('hours', uint8_t),
    ]
