# Z/IP Command Class
# Network-Protocol
# ==============================
COMMAND_CLASS_ZIP = 0x23

ZIP_VERSION = 0x01
# Z/IP Packet
COMMAND_ZIP_PACKET = 0x02

# Values used for Command Zip Packet command
COMMAND_ZIP_PACKET_PROPERTIES1_RESERVED1_MASK = 0x03
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_OPTION_ERROR_BIT_MASK = 0x04
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_QUEUE_FULL_BIT_MASK = 0x08
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_WAITING_BIT_MASK = 0x10
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_RESPONSE_BIT_MASK = 0x20
COMMAND_ZIP_PACKET_PROPERTIES1_ACK_RESPONSE_BIT_MASK = 0x40
COMMAND_ZIP_PACKET_PROPERTIES1_ACK_REQUEST_BIT_MASK = 0x80
COMMAND_ZIP_PACKET_PROPERTIES2_RESERVED2_MASK = 0x1F
COMMAND_ZIP_PACKET_PROPERTIES2_MORE_INFORMATION_BIT_MASK = 0x20
COMMAND_ZIP_PACKET_PROPERTIES2_Z_WAVE_CMD_INCLUDED_BIT_MASK = 0x40
COMMAND_ZIP_PACKET_PROPERTIES2_HEADER_EXT_INCLUDED_BIT_MASK = 0x80
COMMAND_ZIP_PACKET_PROPERTIES3_SOURCE_END_POINT_MASK = 0x7F
COMMAND_ZIP_PACKET_PROPERTIES3_RESERVED3_BIT_MASK = 0x80
COMMAND_ZIP_PACKET_PROPERTIES4_DESTINATION_END_POINT_MASK = 0x7F
COMMAND_ZIP_PACKET_PROPERTIES4_BIT_ADDRESS_BIT_MASK = 0x80

ZIP_VERSION_V2 = 0x02
COMMAND_ZIP_PACKET_V2 = 0x02
# Values used for Command Zip Packet command
COMMAND_ZIP_PACKET_PROPERTIES1_RESERVED1_MASK_V2 = 0x03
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_OPTION_ERROR_BIT_MASK_V2 = 0x04
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_QUEUE_FULL_BIT_MASK_V2 = 0x08
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_WAITING_BIT_MASK_V2 = 0x10
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_RESPONSE_BIT_MASK_V2 = 0x20
COMMAND_ZIP_PACKET_PROPERTIES1_ACK_RESPONSE_BIT_MASK_V2 = 0x40
COMMAND_ZIP_PACKET_PROPERTIES1_ACK_REQUEST_BIT_MASK_V2 = 0x80
COMMAND_ZIP_PACKET_PROPERTIES2_RESERVED2_MASK_V2 = 0x0F
COMMAND_ZIP_PACKET_PROPERTIES2_SECURE_ORIGIN_BIT_MASK_V2 = 0x10
COMMAND_ZIP_PACKET_PROPERTIES2_MORE_INFORMATION_BIT_MASK_V2 = 0x20
COMMAND_ZIP_PACKET_PROPERTIES2_Z_WAVE_CMD_INCLUDED_BIT_MASK_V2 = 0x40
COMMAND_ZIP_PACKET_PROPERTIES2_HEADER_EXT_INCLUDED_BIT_MASK_V2 = 0x80
COMMAND_ZIP_PACKET_PROPERTIES3_SOURCE_END_POINT_MASK_V2 = 0x7F
COMMAND_ZIP_PACKET_PROPERTIES3_RESERVED3_BIT_MASK_V2 = 0x80
COMMAND_ZIP_PACKET_PROPERTIES4_DESTINATION_END_POINT_MASK_V2 = 0x7F
COMMAND_ZIP_PACKET_PROPERTIES4_BIT_ADDRESS_BIT_MASK_V2 = 0x80

ZIP_VERSION_V3 = 0x03
COMMAND_ZIP_PACKET_V3 = 0x02
# Values used for Command Zip Packet command
COMMAND_ZIP_PACKET_PROPERTIES1_RESERVED1_MASK_V3 = 0x03
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_OPTION_ERROR_BIT_MASK_V3 = 0x04
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_QUEUE_FULL_BIT_MASK_V3 = 0x08
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_WAITING_BIT_MASK_V3 = 0x10
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_RESPONSE_BIT_MASK_V3 = 0x20
COMMAND_ZIP_PACKET_PROPERTIES1_ACK_RESPONSE_BIT_MASK_V3 = 0x40
COMMAND_ZIP_PACKET_PROPERTIES1_ACK_REQUEST_BIT_MASK_V3 = 0x80
COMMAND_ZIP_PACKET_PROPERTIES2_RESERVED2_MASK_V3 = 0x0F
COMMAND_ZIP_PACKET_PROPERTIES2_SECURE_ORIGIN_BIT_MASK_V3 = 0x10
COMMAND_ZIP_PACKET_PROPERTIES2_MORE_INFORMATION_BIT_MASK_V3 = 0x20
COMMAND_ZIP_PACKET_PROPERTIES2_Z_WAVE_CMD_INCLUDED_BIT_MASK_V3 = 0x40
COMMAND_ZIP_PACKET_PROPERTIES2_HEADER_EXT_INCLUDED_BIT_MASK_V3 = 0x80
COMMAND_ZIP_PACKET_PROPERTIES3_SOURCE_END_POINT_MASK_V3 = 0x7F
COMMAND_ZIP_PACKET_PROPERTIES3_RESERVED3_BIT_MASK_V3 = 0x80
COMMAND_ZIP_PACKET_PROPERTIES4_DESTINATION_END_POINT_MASK_V3 = 0x7F
COMMAND_ZIP_PACKET_PROPERTIES4_BIT_ADDRESS_BIT_MASK_V3 = 0x80

ZIP_VERSION_V4 = 0x04
COMMAND_ZIP_PACKET_V4 = 0x02
# Z/IP Keep Alive
COMMAND_ZIP_KEEP_ALIVE_V4 = 0x03


# Values used for Command Zip Packet command
COMMAND_ZIP_PACKET_PROPERTIES1_RESERVED1_MASK_V4 = 0x03
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_OPTION_ERROR_BIT_MASK_V4 = 0x04
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_QUEUE_FULL_BIT_MASK_V4 = 0x08
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_WAITING_BIT_MASK_V4 = 0x10
COMMAND_ZIP_PACKET_PROPERTIES1_NACK_RESPONSE_BIT_MASK_V4 = 0x20
COMMAND_ZIP_PACKET_PROPERTIES1_ACK_RESPONSE_BIT_MASK_V4 = 0x40
COMMAND_ZIP_PACKET_PROPERTIES1_ACK_REQUEST_BIT_MASK_V4 = 0x80
COMMAND_ZIP_PACKET_PROPERTIES2_RESERVED2_MASK_V4 = 0x0F
COMMAND_ZIP_PACKET_PROPERTIES2_SECURE_ORIGIN_BIT_MASK_V4 = 0x10
COMMAND_ZIP_PACKET_PROPERTIES2_MORE_INFORMATION_BIT_MASK_V4 = 0x20
COMMAND_ZIP_PACKET_PROPERTIES2_Z_WAVE_CMD_INCLUDED_BIT_MASK_V4 = 0x40
COMMAND_ZIP_PACKET_PROPERTIES2_HEADER_EXT_INCLUDED_BIT_MASK_V4 = 0x80
COMMAND_ZIP_PACKET_PROPERTIES3_SOURCE_END_POINT_MASK_V4 = 0x7F
COMMAND_ZIP_PACKET_PROPERTIES3_RESERVED3_BIT_MASK_V4 = 0x80
COMMAND_ZIP_PACKET_PROPERTIES4_DESTINATION_END_POINT_MASK_V4 = 0x7F
COMMAND_ZIP_PACKET_PROPERTIES4_BIT_ADDRESS_BIT_MASK_V4 = 0x80
# Values used for Command Zip Keep Alive command
COMMAND_ZIP_KEEP_ALIVE_PROPERTIES1_RESERVED_MASK_V4 = 0x3F
COMMAND_ZIP_KEEP_ALIVE_PROPERTIES1_ACK_RESPONCE_BIT_MASK_V4 = 0x40
COMMAND_ZIP_KEEP_ALIVE_PROPERTIES1_ACK_REQUEST_BIT_MASK_V4 = 0x80

class ZW_COMMAND_ZIP_PACKET_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('properties1', uint8_t),
        ('properties2', uint8_t),
        ('seqNo', uint8_t),
        ('properties3', uint8_t),
        ('properties4', uint8_t),
        ('headerExtension1', uint8_t),
        ('zWaveCommand1', uint8_t),
    ]


class ZW_COMMAND_ZIP_PACKET_V2_FRAME(ZW_COMMAND_ZIP_PACKET_FRAME):
    _fields_ = [('headerLength', uint8_t)]


class ZW_COMMAND_ZIP_PACKET_V3_FRAME(ZW_COMMAND_ZIP_PACKET_V2_FRAME):
    _fields_ = []


class ZW_COMMAND_ZIP_PACKET_V4_FRAME(ZW_COMMAND_ZIP_PACKET_V3_FRAME):
    _fields_ = []


class ZW_COMMAND_ZIP_KEEP_ALIVE_V4_FRAME(ZW_COMMON_FRAME):
    _fields_ = [('properties1', uint8_t)]

