# Z-Wave Plus Info Command Class
# Management
# ==============================
COMMAND_CLASS_ZWAVEPLUS_INFO = 0x5E

ZWAVEPLUS_INFO_VERSION = 0x01
# Z-Wave Plus Info Get
ZWAVEPLUS_INFO_GET = 0x01
# Z-Wave Plus Info Report
ZWAVEPLUS_INFO_REPORT = 0x02

# Values used for Zwaveplus Info Report command
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_CONTROLLER_CENTRAL_STATIC = 0x00
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_CONTROLLER_SUB_STATIC = 0x01
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_CONTROLLER_PORTABLE = 0x02
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_CONTROLLER_PORTABLE_REPORTING = 0x03
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_END_NODE_PORTABLE = 0x04
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_END_NODE_ALWAYS_ON = 0x05
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_END_NODE_SLEEPING_REPORTING = 0x06
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_END_NODE_SLEEPING_LISTENING = 0x07
ZWAVEPLUS_INFO_REPORT_NODE_TYPE_ZWAVEPLUS_NODE = 0x00
ZWAVEPLUS_INFO_REPORT_NODE_TYPE_ZWAVEPLUS_FOR_IP_ROUTER = 0x01
ZWAVEPLUS_INFO_REPORT_NODE_TYPE_ZWAVEPLUS_FOR_IP_GATEWAY = 0x02
ZWAVEPLUS_INFO_REPORT_NODE_TYPE_ZWAVEPLUS_FOR_IP_CLIENT_IP_NODE = 0x03
ZWAVEPLUS_INFO_REPORT_NODE_TYPE_ZWAVEPLUS_FOR_IP_CLIENT_ZWAVE_NODE = 0x04

ZWAVEPLUS_INFO_VERSION_V2 = 0x02
ZWAVEPLUS_INFO_GET_V2 = 0x01
ZWAVEPLUS_INFO_REPORT_V2 = 0x02
# Values used for Zwaveplus Info Report command
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_CONTROLLER_CENTRAL_STATIC_V2 = 0x00
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_CONTROLLER_SUB_STATIC_V2 = 0x01
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_CONTROLLER_PORTABLE_V2 = 0x02
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_CONTROLLER_PORTABLE_REPORTING_V2 = 0x03
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_END_NODE_PORTABLE_V2 = 0x04
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_END_NODE_ALWAYS_ON_V2 = 0x05
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_END_NODE_SLEEPING_REPORTING_V2 = 0x06
ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_END_NODE_SLEEPING_LISTENING_V2 = 0x07
ZWAVEPLUS_INFO_REPORT_NODE_TYPE_ZWAVEPLUS_NODE_V2 = 0x00
ZWAVEPLUS_INFO_REPORT_NODE_TYPE_ZWAVEPLUS_FOR_IP_GATEWAY_V2 = 0x02

class ZW_ZWAVEPLUS_INFO_GET_FRAME(ZW_COMMON_FRAME):
    _fields_ = []


class ZW_ZWAVEPLUS_INFO_REPORT_FRAME(ZW_COMMON_FRAME):
    _fields_ = [
        ('zWaveVersion', uint8_t),
        ('roleType', uint8_t),
        ('nodeType', uint8_t),
    ]


class ZW_ZWAVEPLUS_INFO_GET_V2_FRAME(ZW_ZWAVEPLUS_INFO_GET_FRAME):
    _fields_ = []


class ZW_ZWAVEPLUS_INFO_REPORT_V2_FRAME(ZW_ZWAVEPLUS_INFO_REPORT_FRAME):
    _fields_ = [
        ('installerIconType1', uint8_t),
        ('installerIconType2', uint8_t),
        ('userIconType1', uint8_t),
        ('userIconType2', uint8_t),
    ]

